### ISSUE TITLE
I hit a kind wizard 🤦🏻‍♂️

### ISSUE THREAD

**Issue by kave777** [Electroblob77/Wizardry#103]
Minecraft version: 1.12.2
Wizardry version: 4.1.2 
Environment: Singleplayer

Issue details: I hit a kind wizard by accident and now thew attack me , is it possible to make them friendly again ?

**Comment by Tora-B** [comment]
They'll forget about you if you get far enough away for the chunk to unload.

**Comment by Electroblob77** [comment]
Yes, that part of their AI works the same way as zombie pigmen so if you go far enough away or respawn it will stop being angry at you.
