### ISSUE TITLE
Server crash 4.1.3

### ISSUE THREAD

**Issue by nickjackson-ff** [Electroblob77/Wizardry#104]
Minecraft version: 1.12.2
Wizardry version: 4.1.3
Environment: Server

Crash on SMP server initialization
https://gist.github.com/nickjackson-ff/97bf5350540d6e15d24a53071551aaa4

**Comment by dr3ams** [comment]
Same here ^ Tried with forge 2768(recommended) and 2806(latest) with only Electroblob's enabled.
