### ISSUE TITLE
Question / Request: high level Scroll-of-Identification crafting..?

### ISSUE THREAD

**Issue by Harcagnel** [Electroblob77/Wizardry#109]
Minecraft version: 1.12.2 
Wizardry version: 4.1.4 [latest one in "roguelike adventures and dungeons" pack version 1.21 ]
Environment: Server

Issue details:  The issue is Multi-player, we have 6 players on a private server and as a result we really only have enough Scrolls of Identification for 1 person to progress. As we get to the high level gear we are all still using novice level spells. Would it be possible for make a scroll of identification craft able from extra books/non-Identification scrolls (which we have plenty of because we can share from one chest) some crystals and some high end resources like diamonds, emeralds or something? I don't mind searching for scrolls but as it is we are basically only get them from quest chests because we cleared all the dungeons near us and we are having to travel further and further to have any hope of finding something to progress in this mod. The books are fine because you get a mix but their is never enough scrolls going around and this is our second time playing with your mod. The result is we start with your mod, then abandon It quickly when we run out of identify scrolls. If we had some way to get to the crafting side of the house even if expensive it would give us a path forward when we feel like its dead. Thanks for any consideration.

**Comment by Tora-B** [comment]
You can use spells that aren't identified, and if you cast it successfully, it will identify it. Scrolls of identification are really only necessary when you can't figure out the circumstances required for the spell to work. It's also safer, in that some spells are rather destructive.

Players can work together to identify spells, because as long as one of them knows how to cast a particular spell, they can tell the others, rather than use a scroll of identification.

**Comment by Harcagnel** [comment]
That is good to know. We assumed you had to identify them before you could cast them.

**Comment by Electroblob77** [comment]
Tora-B is correct, that was the intended mechanic. However, I should add that there will be changes to the discovery mechanic coming in the next update which will alter things a bit, so scrolls of identification will be changing a little as a result.
