### ISSUE TITLE
Fire Sigil Burning Caster

### ISSUE THREAD

**Issue by Xen122** [Electroblob77/Wizardry#113]
Minecraft version: 1.12.2 
Wizardry version: 4.1.4 
Environment: Server 

Issue details:  Simple. Placed down a fire sigil, a after a couple days and most likely a server reboot, the fire sigil's decimated me when I tp'd back to my base using /home (Idk if this is relevant) Anyway, the fire sigils didn't recognize the caster and completely fucked me over.  

Other mods involved: I don't know. I am using forgeessentials to do /home though

Link to crash report (if applicable): None

**Comment by Electroblob77** [comment]
It'll almost certainly be the server reboot that did it. Pretty sure I've seen similar behaviour before, I'll see what I can do. Thanks for reporting.

**Comment by Xen122** [comment]
> 
> 
> It'll almost certainly be the server reboot that did it. Pretty sure I've seen similar behavior before, I'll see what I can do. Thanks for reporting.

Anytime, but I'd like to know if there is a proposed fix or anything to prevent it from destroying me

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
