### ISSUE TITLE
error after a player dies

### ISSUE THREAD

**Issue by YOKOGAMA** [Electroblob77/Wizardry#114]
Minecraft version: 1.12.2
Wizardry version: 4.1.4 
Environment: Server 

Issue details: 
If after using the summoning spell, the player dies, the console is written a lot of errors.

![image](https://user-images.githubusercontent.com/40151801/52518801-c3cdb900-2c61-11e9-9545-ac26070dee47.png)

**Comment by Electroblob77** [comment]
Is that the entire log? It only has the first line of the stacktrace, which isn't enough to find the problem. If you have a full crash report (rather than a console log) that would be very useful. Thanks.

**Comment by YOKOGAMA** [comment]
There is no crash, I have only error in console. Here is full log. I summoned the Phoenix and the skeleton. After death player battle with mobs lasted. And then I have error in console.
[latest.log](https://github.com/Electroblob77/Wizardry/files/2850359/latest.log)

**Comment by Electroblob77** [comment]
Must have missed this, sorry. Thanks for the log, that's much more useful. Interesting that it doesn't cause a crash though, perhaps Sponge is catching the error.
