### ISSUE TITLE
Pocket Furnace Smelts Gear

### ISSUE THREAD

**Issue by DarkYuan** [Electroblob77/Wizardry#115]
Version: 4.1.4 - MC 1.12.2
Environment: Singleplayer//Server

Issue details: A pretty big issue with the pocket furnace spell - not a bug per se, but it really shouldn't smelt your (enchanted) iron armor! Found that out with a scroll I didn't know yet.

Other mods involved: N/A

**Comment by Electroblob77** [comment]
Thanks for making the issue. I think the best fix will be to introduce a blacklist feature for which items to smelt, or potentially make it hotbar-only.

**Comment by Electroblob77** [comment]
Pocket furnace no longer smelts armour, tools or weapons, and a blacklist for smelted items has been added, in the 4.2.0 release.
