### ISSUE TITLE
Forcefield Spell Bug

### ISSUE THREAD

**Issue by ghost** [Electroblob77/Wizardry#117]
Minecraft version: 1.12.2 
Wizardry version: 4.1.4
Environment: Singleplayer/LAN game/Server

Issue details: The forcefield spell description states that it should repel mobs and deflect projectiles. 
                     However, it seems to only repel mobs as projectiles pass right through.

Other mods involved: Used in R.A.D. (Roguelike Adventures and Dungeons), but also tested in vanilla Minecraft singleplayer world with a fresh install of the mod.

**Comment by Electroblob77** [comment]
I'll look into this. I'm going to make some improvements to the forcefield spell anyway so I'll see what I can do when I get to that.

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
