### ISSUE TITLE
Chat spam on server

### ISSUE THREAD

**Issue by Beserkerlel** [Electroblob77/Wizardry#120]
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: Server

Feature request: Config option to either stop the naming of mobs spawned by spells or if possible just to keep their names but not send their deaths to chat. Having anymore than 1 player spawning in those mobs spams our servers chat quite quickly and with 10-20 players online talking to each other it can be pretty intrusive to others conversations. Otherwise love the mod running in ATM 3 Remix :)

**Comment by Electroblob77** [comment]
Someone has definitely mentioned this before but I don't seem to have it on the issue tracker, thanks for adding it. This is definitely a bug, it is not intended that summoned creatures send their deaths to the chat.

**Comment by Electroblob77** [comment]
@Beserkerlel I've noticed spirit animals do this in my testing but not other summoned mobs. Is that the case for you or are they all sending chat messages?

**Comment by Beserkerlel** [comment]
[https://puu.sh/D5ngU/bc06275317.png](url)
![image](https://user-images.githubusercontent.com/48270940/54963016-85ecd180-4f3d-11e9-9c13-c38c4e1ed332.png)
 From my testing it seems like anything that's summoned.

**Comment by Electroblob77** [comment]
That's definitely all of them, then. Thanks, I'll see what I can do.

**Comment by Electroblob77** [comment]
I wasn't able to recreate this, I'm wondering if there's another mod that adds it?

**Comment by Beserkerlel** [comment]
Hmm... we've updated several times since then and still get the spam, I'll look around and see if we have any mods that might interact with yours, all the mods remix is pretty huge I wouldn't be surprised, just no clue what it'd be.

**Comment by WesCook** [comment]
CoFH Core has a feature which announces the deaths of named mobs.

https://teamcofh.com/docs/1.12/cofh-core-4/tweaks/#named-mob-death-messages

**Comment by Beserkerlel** [comment]
I've literally been looking for this for months, just changed the setting on the server, will see if it works.

**Comment by Electroblob77** [comment]
@WesCook Nice find! That must be why then, I'll have a look at how CoFH Core implements that feature, I may be able to trick it into thinking summoned mobs aren't named.

**Comment by Electroblob77** [comment]
For now, disable CoFH's named mob death messages feature to prevent this from happening.
