### ISSUE TITLE
[Tweak request] Wizardry Handbook Pauses Game option

### ISSUE THREAD

**Issue by AtomicWaffle14** [Electroblob77/Wizardry#126]
Minecraft version: 1.12.2  
Wizardry version: 4.1.4 
Environment: Singleplayer

The Wizard's Handbook pauses the game in singleplayer, which can be kind of annoying when reading it to pass the time. Can a config option be added to make it pause or not pause the game in singleplayer?

**Comment by Electroblob77** [comment]
A lot of Minecraft's own GUIs pause the game in singleplayer though... I mean, I can add an option pretty easily but that's a default behaviour you're talking about.
For now you could just open to LAN to achieve the same effect.

**Comment by AtomicWaffle14** [comment]
I'd definitely appreciate an option. Most if not all books and guis in vanilla (except the game menu) don't pause the game. Most people don't really notice due to playing on servers I guess.

**Comment by Electroblob77** [comment]
Fair enough, maybe that's changed since I last looked then. It's simple enough to implement, I'll put in the next release.

**Comment by Electroblob77** [comment]
Added in the 4.2.0 release.
