### ISSUE TITLE
Suggestions: some power adjustments to some spells for balance purposes?

### ISSUE THREAD

**Issue by SirAron111** [Electroblob77/Wizardry#127]
Suggestions: some power adjustments to some spells for balance purposes. (It’s nice being able to adjust a general damage factor for all spells but having one for each would be even better.) if that’s not possible it would be a good idea to adjust some values for example silverfish swarm is super op it is a master spell but even if no dmg modifications are made they can solo kill dragons the small hit box makes it hard for mobs other than zombies to hit them. Reducing the number of swarm spawns from 10- 8 to like 4 would be enough for them. Some other spells could need a small bit of tweaking as well. But the silverfish is definitely the hardest to balance one.
And as always. MORE SPELLS XD love the mod

**Comment by Electroblob77** [comment]
Spell JSONs are coming! It's a much-requested feature that I've now pretty much finished implementing. You'll be able to change stats you didn't even know existed...
And of course I'm always adding more spells - last time I checked I was at about 25 so far!

**Comment by SirAron111** [comment]
Mate you are awesome.
