### ISSUE TITLE
change cooldowns?

### ISSUE THREAD

**Issue by martin1112333** [Electroblob77/Wizardry#129]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.7.10 [change as necessary]  
Wizardry version: 4.1.4 [change as necessary]

Is there any way i can increase the cooldown on spells?

**Comment by Electroblob77** [comment]
Not yet, but there will be in the next release - though it will be for 1.12.2 not 1.7.10, sorry.
