### ISSUE TITLE
[Suggestion] ice capsule spell

### ISSUE THREAD

**Issue by Jonson26** [Electroblob77/Wizardry#131]
A spell that creates a protective capsule filled with 2 blocks of air made out of frostwalker-like transparent blastproof glass/ice (it breaks over time and reverts to the original block it replaced). This would allow the player to survive aq massive TNT explosion, catch a breath underwater or give him a few seconds to heal up during combat etc. I think it could fit into the spells category.

**Comment by Electroblob77** [comment]
Interesting, I might consider an ice-shield type spell. Thanks!

**Comment by WinDanesz** [comment]
This spell exists already as an addon spell (Ancient Spellcraft mod)
https://github.com/WinDanesz/AncientSpellcraft/wiki/Cryostasis
Unlikely that the base mod will add it.
