### ISSUE TITLE
[Question] repository for using Wizardry as a Mod dependency

### ISSUE THREAD

**Issue by Dryxen** [Electroblob77/Wizardry#134]
I was curious if it would be possible to list the curseforge maven repository for this project, as jitpack is having issues resolving artifacts due to the gradle build not matching the git repo.

**Comment by Electroblob77** [comment]
I honestly had no idea CurseForge even had the ability to host maven repositories... suffice to say, I haven't set one up!
Could you explain a bit more about the issue you're having with jitpack?

**Comment by Dryxen** [comment]
Heres a log from jitpack https://jitpack.io/com/github/Electroblob77/Wizardry/4.1.4/build.log looks like due to the nameing in the gradle build the local maven repo isnt resolving correctly. I could be very wrong though i'm definitely no expert with gradle or maven.
Thanks for the response been looking for a couple of days trying to find ways to not add Wizardy as a local dependency.
Edit: as you can see at the end of the log its trying to find Electroblobs Wizardry as the version.

Edit:Edit I didn't mean to bother you with jitpack parsing issues though.
if you don't have a repo, i'll continue to look for other ways to manage depenencies for the time being. here's the link with info on curseforges maven if your interested in the future https://authors.curseforge.com/knowledge-base/529-api .

**Comment by Electroblob77** [comment]
Interesting - I've made some edits to build.gradle so it's how you might expect, whether this will help with your problem I don't know. I hadn't heard of jitpack at all before you mentioned it so I can't offer much help on that one I'm afraid, my only other suggestion would be to try building normally using the command line (or your IDE if it supports it). I may look into setting up a maven repository in the future.

**Comment by Dryxen** [comment]
Aye thanks for taking the time to look at it, this can be closed if your satisfied With it, as the question has been answered. On a side note your project builds correctly if clone or fork it this was never a issue =P,the issue was other people trying to build my project if I depended on this and couldn't list it as a external dependency in gradle. 
Edit: I would also like to notify you that thanks to your changes, the latest wizardry changes can now be retrieved with implementation 'com.github.Electroblob77:Wizardry:1.12.2-SNAPSHOT' in peoples gradle.build using jitpack as a repository.
Thanks again =D.

**Comment by itsmeow** [comment]
I was actually just going to make an issue on this. The filename on Curse is set up in possibly the most un-maven-friendly way I've seen xD. Basically, just use the default naming provided by the default buildscript (`modid-major.minor.revis`)
You can even do what I do with my mod, `modid-mcmajor.mcminor.mcrevis-major.minor.revis`, which works very well with Maven and allows for multiple MC versions. For now I have it in my libs folder as a jar for the dependency, but this would be great.

**Comment by itsmeow** [comment]
Mine isn't quite this issue, I'm trying to use the CF api maven and just a regular gradle buildscript to depend on the mod. Problem is Curse maven is not set up super well so if your file is named wrong it doesn't work. Dryxen posted the API link, which is basically the goal here.

**Comment by Electroblob77** [comment]
I've sanitised the jar filename for version 4.2.0, hopefully this will keep Maven happy. Please reopen the issue if it still doesn't work.
