### ISSUE TITLE
Unable to set multiple d imensions

### ISSUE THREAD

**Issue by Vionai** [Electroblob77/Wizardry#136]
12.2.2

Every time I try and add other dimensions, the config resets to default.
Other mods who have multiple dimensions have no issues, whichs means I have the correct syntax, but it's something with this mods config specifically...

**Comment by Electroblob77** [comment]
Please use the template next time, it helps you give me the necessary information first time. Other than this being Minecraft 1.12.2, could you please give the following information:

Wizardry mod version (probably 4.1.4, I'm guessing)
Forge version
Environment i.e. singleplayer, LAN or server - this is particularly important
Did you edit the config file manually using a text editor or using the in-game menu?

Also, if you previously had an older version of wizardry installed, move or delete your wizardry.cfg and launch the game so it generates a new one (you can copy your old settings into it), then try changing the dimensions option again. Updates can result in duplicate options which may cause problems, so it's useful to rule this out.

Thanks.
