### ISSUE TITLE
Iron golem and ice giant (?) summoned by the player could behave as if they were built

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#137]
Little oddity and suggestion to point out for iron golems and ice giant (?) Summons.

Because at the moment when players summon them. They behave like villager spawned golems instead of acting like they were built by the player (the summoner)

Maybe have the summoned iron golem be summoned with the nbt tag "PlayerCreated" be set to one? (Because vanilla has this tag and uses it)

This could also help with the revenge targetting for them, because player made golems don't attack back their creator.

**Comment by Electroblob77** [comment]
Ohhhhhh, that's why people keep saying that! Thank you for pointing that out.

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
