### ISSUE TITLE
Performance issues with EntitySilverfishMinion

### ISSUE THREAD

**Issue by runescapejon** [Electroblob77/Wizardry#138]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.1.4 
Environment: Server - Forge: 1.12.2-14.23.5.2814

Issue details: I am having a bit of performance issues i begin to look into and found this 
![03be13274a474bcece4555cf01bc6a22](https://user-images.githubusercontent.com/10858509/56450240-65245b80-62f2-11e9-87cd-2ba244276406.png)
Is there a way to fix this problem ? thanks
EDIT: for the mean time i had disable it
Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Electroblob77** [comment]
Do you have any other details on how this issue occurred? What were you doing at the time? Does exiting the world and loading it up again fix the problem?

Also, what is that screenshot of? It looks like an IDE code coverage check. It would be useful if you could get a log from when the game is running slowly. Thanks.

**Comment by runescapejon** [comment]
I'm going to close this because i look even deeper and found that on the server someone was abusing this and spawn a crap ton of them and it wouldn't despawn i had to force kill them and i don't have much information either
