### ISSUE TITLE
All Particles "die" out after some constant use of particle effects (including magic)

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#142]
Minecraft version: 1.12.2
Wizardry version: 4.1.4 (latest)
Environment: Client

Issue details:

Some of the comments on curseforge mention this bug and thought I could note it here.

### My overall overview about this bug:
((((
After some continuous use of anything that uses particle effects (including magic itself) seems to put out the particle system and will stay put out until you restart the game.
))))

**Other mods involved:** Unfortunately, this one sort of varies? Because I've had some mod packs where it doesn't put out the particle system and some do. Although, I haven't tried using this mod alone to put out the particle system.

**I wouldn't recommend putting this issue into the 4.2 progress because of how obscure it is (also the fact that it's very difficult to replicate because of how random it is). I'm just posting this here for others to know about this.**

**Comment by Electroblob77** [comment]
Ok, thanks for logging it here. I have made a number of improvements to the particle system for the next update so there's a good chance that will fix it, one for people to test when the time comes.

**Comment by Electroblob77** [comment]
This should be fixed thanks to improvements to the particle system in the 4.2.0 release. Please reopen if the issue persists.
