### ISSUE TITLE
Curse of the Time Out

### ISSUE THREAD

**Issue by McPersson** [Electroblob77/Wizardry#144]
Minecraft version: 1.12.2
Wizardry version: 4.1.4 
Forge: 2836
Environment: LAN game/Server
Java: Version 8 Update 211
Config: Intel Xeon E3-1245V2 (3.5Ghz), GTX 770, 16GB DDR3 at 2133, Windows 10 Pro (with the latest updates), MineCraft on SSD. 
Memory allocated: 5GB;

**Issue details:** Found a very interesting problem. On the server, when a player uses magic, the rest players for some reason fly away **in a Time Out** but not the one who uses magic. I noticed it on the magic "Petrification". On the server there is the SpongeForge Core and the Nucleus plugin. What happens to them, that without them - the result is the same.

Other mods involved: 
![OtherMods](https://user-images.githubusercontent.com/50740709/57927100-d0dbf300-78b5-11e9-83cc-b7c15989a6d6.png)

Logs (According to the logs, unfortunately, you can hardly understand what the problem is:): 
[logs_MC.zip](https://github.com/Electroblob77/Wizardry/files/3191411/logs_MC.zip)

**Comment by McPersson** [comment]
Some more useful information: timeout when the player uses the staff. Scrolls are fine.

How ;(

**Comment by Electroblob77** [comment]
You're right, there's nothing in that log that helps solve the problem. The log seems to indicate a packet-based crash but I assume that's just the timeout. Where did those logs come from, were they from the server, from one of the players that timed out or from the player that cast the spell?

If you have access to the server, here are some things you can try to help narrow down the problem:
- Try to reproduce the problem in a new world
- Try running the server with only sponge and wizardry and see if it still happens
- If it doesn't happen with only sponge and wizardry, try removing mods one-by-one until the problem no longer happens

**Comment by McPersson** [comment]
These were my logs. For some reason, only one player who uses magic is not thrown into the Time-Out. The rest fly away (like me). The experiment was also carried out with the thunderbolt (staff).

I'll try a few more combinations and will report the results later.

**Comment by Electroblob77** [comment]
Ok. Any chance you can get the server log file? And what do you mean by 'fly away'?

**Comment by McPersson** [comment]
Yes of course. I'll do them when I conduct further tests. Fly away (figure of speech), - disconnect from server or Time-Out, something like that.

**Comment by McPersson** [comment]
After long tests, it turned out that everything was to blame: Infinity-0.13.2 (Infinity Item Editor). How it is connected with your mod - I do not know. But now, if anything, just know. Thanks for answers ;')
