### ISSUE TITLE
Handbook is colorized by previous openGL rendering

### ISSUE THREAD

**Issue by Laike-Endaril** [Electroblob77/Wizardry#145]
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: All client-side environments (render)

Issue details:
The openGL color is not being set to white before rendering the handbook background, causing it to use whatever the previous openGL render color was.  Easily noticeable in combination with this sprint/sneak toggle mod: https://minecraft.curseforge.com/projects/auto-sneak-sprint-forge

Other mods involved:
(The sprint/sneak toggle mod above is an example, but the issue could potentially occur with any other mod that alters the openGL color at the right time)

**Comment by Electroblob77** [comment]
Ok, can't say I've noticed this in vanilla but presumably that mod isn't properly resetting the OpenGL state (vanilla isn't consistent with what state it leaves OpenGL in either so it's hard to know what to set and what to leave). It's a a one-line fix so I'll get it done for the next release. Thanks.

**Comment by Laike-Endaril** [comment]
Yep, like you said, it's compat-only.  I had to do a similar fix on one of my own mods for a HUD a while back.

Thanks for the fix!

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
