### ISSUE TITLE
Finding an elemental staff gives the wrong advancement

### ISSUE THREAD

**Issue by Laike-Endaril** [Electroblob77/Wizardry#146]
Minecraft version: 1.12.2, forge stable (14.23.5.2768)
Wizardry version: 4.1.4
Environment: All

Issue details:
Obtaining an elemental wand gives you the "elemental mastery" advancement instead of the "elemental" advancement.  Have not tested to see if the opposite is also true or not (ie. whether using all spells of one element gives you "elemental" instead of "elemental mastery").

1. Create a new world in creative mode
2. Give yourself a staff of shadows

Other mods involved: None (dedicated test)

**Comment by Electroblob77** [comment]
Ah yes, I've noticed this multiple times but never logged it here. Thanks for reminding me!

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
