### ISSUE TITLE
Decreased Mana Cost still stops at the original spell cost despite having enough mana

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#147]
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: All

Issue details: 

When I wear a piece or a full set of elemental wizard robes, the costs of that spell element is decreased. (which works there) However, it doesn't decrease the minimum mana needed to cast that decreased cost spell, even though you clearly have enough mana.

**EX: I'm wearing a full set of Necromancer Robes which gives me 80% decreased cost for all necromancer spells. I'm using a wand which has a necromancer spell (i'm using darkness orb for example) and it decreases the cost of that spell to 2.
Whenever I attempt to cast it at 15/2500 mana, it doesn't let me cast it, despite the spell only costing 2 mana points. I should be able cast that spell until i'm at 1/2500 or 0/2500.**

Other mods involved: N/A

**Comment by Electroblob77** [comment]
Just looked at the code and you're right, it doesn't. I've rewritten most of the wand code for the next update so it will be fixed then. Thanks for reporting.

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
