### ISSUE TITLE
Constantly dead and swapping worlds

### ISSUE THREAD

**Issue by ericc1998** [Electroblob77/Wizardry#149]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.1.4 [change as necessary]
Environment: Singleplayer/LAN game/Server [delete as necessary]
Server
Issue details: [describe what you were doing when the issue occurred, what went wrong, what you expected to happen, etc.] 
I jumped off for the 144 block drop and when I hit the ground my friend teleported and I died, and now I'm stuck in an endless loop going from unable to revive or exit the game while swapping from the Unicorn world back to the normal world. I already had my friend wipe my player data so I wouldn't have been in the server. but it didn't help at all.

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  CXLibraryCore (CXLibrary-1.12.1.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.19.1-release.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  Wizardry Plugin (wizardry-0.10.6.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 6/9/19 3:20 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at codechicken.nei.NEIClientConfig.setSearchExpression(NEIClientConfig.java:366)
	at codechicken.nei.jei.gui.ContainerEventHandler.onGuiMouseEventpre(ContainerEventHandler.java:51)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_625_ContainerEventHandler_onGuiMouseEventpre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at codechicken.nei.NEIClientConfig.setSearchExpression(NEIClientConfig.java:366)
	at codechicken.nei.jei.gui.ContainerEventHandler.onGuiMouseEventpre(ContainerEventHandler.java:51)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_625_ContainerEventHandler_onGuiMouseEventpre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.multiplayer.GuiConnecting
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 997433232 bytes (951 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version           | Source                                        | Signature                                |
	|:------ |:--------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                   | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | advanced-fishing      | 1.2.0             | Advanced-Fishing-Mod-1.12.2.jar               | None                                     |
	| LCHIJA | animalnet             | 1.9.1             | AnimalNet-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | baubles               | 1.5.2             | Baubles-Mod-1.12.2.jar                        | None                                     |
	| LCHIJA | blocklings            | 6.0.0             | Blocklings-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | guideapi              | 1.12-2.1.8-63     | Guide-API-1.12.2.jar                          | None                                     |
	| LCHIJA | bloodmagic            | 1.12.2-2.4.1-103  | Blood-Magic-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | buildcraftlib         | 7.99.14           | BuildCraft-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | buildcraftcore        | 7.99.14           | BuildCraft-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | buildcraftbuilders    | 7.99.14           | BuildCraft-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | buildcraftenergy      | 7.99.14           | BuildCraft-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | buildcraftfactory     | 7.99.14           | BuildCraft-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | buildcraftrobotics    | 7.99.14           | BuildCraft-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | buildcraftsilicon     | 7.99.14           | BuildCraft-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | buildcrafttransport   | 7.99.14           | BuildCraft-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | chickens              | 6.0.4             | chickens-6.0.4.jar                            | None                                     |
	| LCHIJA | codechickenlib        | 3.2.2.353         | CodeChickenLib-1.12.2.jar                     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cucumber              | 1.1.2             | Cucumber-1.12.2-1.1.2.jar                     | None                                     |
	| LCHIJA | cxlibrary             | 1.6.1             | CXLibrary-1.12.1.jar                          | None                                     |
	| LCHIJA | jei                   | 4.15.0.279        | jei_1.12.2-4.15.0.279.jar                     | None                                     |
	| LCHIJA | forestry              | 5.8.0.311         | Forestry-Mod-1.12.2.jar                       | None                                     |
	| LCHIJA | forgelin              | 1.8.2             | Forgelin-1.8.2.jar                            | None                                     |
	| LCHIJA | llibrary              | 1.7.17            | llibrary-1.7.17-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil                | 8.0.0             | fossilsarcheology-8.0.0.jar                   | None                                     |
	| LCHIJA | hatchery              | 2.2.2             | hatchery-1.12.2-2.2.2.jar                     | None                                     |
	| LCHIJA | jeibees               | 0.9.0.5           | JEI-Bees-Mod-1.12.2.jar                       | None                                     |
	| LCHIJA | librarianlib          | 4.19.1            | librarianlib-1.12.2-4.19.1-release.jar        | None                                     |
	| LCHIJA | morefurnaces          | 1.10.5            | More-Furnaces-Mod-1.12.2.jar                  | None                                     |
	| LCHIJA | morechickens          | 3.1.0             | morechickens-1.12.2-3.1.0.jar                 | None                                     |
	| LCHIJA | cfm                   | 6.2.1             | MrCrayfishs-Furniture-Mod-1.12.2.jar          | None                                     |
	| LCHIJA | mysticalagriculture   | 1.7.5             | Mystical-Agriculture-Mod-1.12.2.jar           | None                                     |
	| LCHIJA | nei                   | 2.4.2             | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | omlib                 | 3.1.0-232         | OMLib-1.12.2.jar                              | None                                     |
	| LCHIJA | openmodularturrets    | 3.1.0-335         | OpenModularTurrets-Mod-1.12.2.jar             | None                                     |
	| LCHIJA | pneumaticcraft        | 1.12.2-0.11.0-357 | PneumaticCraft-Mod-1.12.2.jar                 | None                                     |
	| LCHIJA | randomloot            | 1.3               | Random-Loot-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | roguelike             | 1.8.0             | Roguelike-Dungeons-Mod-1.12.2.jar             | None                                     |
	| LCHIJA | flammpfeil.slashblade | mc1.12-r22        | SlashBlade-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | tameableplus          | 0.1.2             | Tameable-Plus-Mod-1.12.2.jar                  | None                                     |
	| LCHIJA | uut                   | 1.0.2             | Toy-Defenders-Mod-1.12.2.jar                  | None                                     |
	| LCHIJA | wizardry              | 0.10.6            | wizardry-0.10.6.jar                           | None                                     |
	| LCHIJA | librarianliblate      | 4.19.1            | librarianlib-1.12.2-4.19.1-release.jar        | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CXLibraryCore (CXLibrary-1.12.1.jar)
  cubex2.cxlibrary.CoreModTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.19.1-release.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
Wizardry Plugin (wizardry-0.10.6.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13544 Compatibility Profile Context 25.20.15011.1004' Renderer: 'AMD Radeon (TM) R7 360 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) R7 360 Series GL version 4.6.13544 Compatibility Profile Context 25.20.15011.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor

**Comment by Electroblob77** [comment]
I think you want the [other wizardry mod](https://github.com/TeamWizardry/Wizardry/issues) (there aren't any unicorns here!)
