### ISSUE TITLE
Lightning hammer crash

### ISSUE THREAD

**Issue by Spikestriker303** [Electroblob77/Wizardry#150]
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: Singleplayer

Issue details: I am playing the Roguelike Adventures and Dungeons mod pack (with a few additions of my own) which has been doing fine for me until now. I had just acquired my master wand and slotted in the Lightning Hammer book I had on me waiting until I could do so. I then wandered outside to see what I could hit with it, found a mob spewing silverfish, and used the spell which I then found out calls down the wrath of Thor (which is awesome by the way). This was when I was kicked back to the main menu with VanillaFix telling me it was a problem with either Lord Craft (which is not and has never been installed that I know of since it isn't in the list) or this (which makes more sense given the circumstances) and that I could join back into the world if I wanted but should probably let this be known. So I tried to join back several times to test things out, like turning the world to peaceful so the mobs weren't there, and each time it let me in for a moment before sending me right back to the main menu and creating a crash report (the latest of which I will put here via paste bin). I then tested it on a new world and the hammer was fine when used on sand with nothing around but crashed the moment I used it on the nearby chicken in the tall grass, so there is that.

Link to crash report: https://pastebin.com/yWPe99Dt

**Comment by Electroblob77** [comment]
>... Lord Craft (which is not and has never been installed that I know of since it isn't in the list)

The crash report begs to differ:
`com.cobbs.lordcraft.Utils.ForgeEvents.playerKnocksBack(ForgeEvents.java:173)`

Either way, what's happened here is that the the method `EntityLivingBase#knockBack` takes an entity argument, but this isn't used in vanilla for anything so I just put null when I wrote the code. However, LordCraft must use it via events and not check for null (which is fair enough, it shouldn't be null really) and that causes the crash. My fault, I'll get it fixed for the next release.

For now, if you're not using LordCraft then check through your mods folder and remove it.

**Comment by Spikestriker303** [comment]
i just checked and it wasn't in the twitch launcher list but it was in the mods folder though i don't remember putting it there, either way i deleted it

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
