### ISSUE TITLE
Game Crashed At Start

### ISSUE THREAD

**Issue by Tahzir213** [Electroblob77/Wizardry#151]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.1.4 [change as necessary]
Environment: Singleplayer/LAN game/Server All
Issue details: [describe what you were doing when the issue occurred, what went wrong, what you expected to happen, etc.]

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): https://pastebin.com/SLKjdtWd

**Comment by Electroblob77** [comment]
It appears newer versions of Forge have changed some methods such that wizardry tries to call a method that is no longer visible. I can't find anything in the forge changelog about it but for now it will work if you use build 2768, the recommended release on the forge download page.

**Comment by Tahzir213** [comment]
still wont work

**Comment by Tahzir213** [comment]
https://pastebin.com/ZLWqaLuP

**Comment by Electroblob77** [comment]
Ok, interesting. All I can suggest at this point is try removing other mods until it works, particularly InventoryTweaks since it's a coremod.

**Comment by Tora-B** [comment]
We actually resolved this over Discord by creating a new profile that uses a separate Game Directory. There must have been some conflict with *something* that was in the default .minecraft directory, but I'm not sure what.

**Comment by Electroblob77** [comment]
Nice, I'll mark this as closed then. It is generally a good idea to run in a separate directory to .minecraft, I personally have one for snapshots, one for modded 1.12, one for modded 1.11, etc.
