### ISSUE TITLE
Game Crashes when firing most of the spells

### ISSUE THREAD

**Issue by ChocolateVegas** [Electroblob77/Wizardry#152]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.10.2
Wizardry version: The latest beta version on 1.10.2 
Environment: Singleplayer

Issue Details: Firing certain spells crashed my game. Force field, Lightning Hammer, Lightning in general, ice wall, etc.

Other mods involved: 
Optifine
Blockbuster
Chisels and Bits
Deco craft
Bauercam 
Architecture craft

Link to crash report (if applicable):

**Comment by Electroblob77** [comment]
Please post your crash report. Thanks.
Also, why are you using a beta version? The latest release for Minecraft 1.10.2 is 2.1.2.

**Comment by ChocolateVegas** [comment]
[crash-2019-07-01_23.03.15-server.txt](https://github.com/Electroblob77/Wizardry/files/3364364/crash-2019-07-01_23.03.15-server.txt)
My bad, sorry!
I had to use the beta version because it's the only one that wouldn't crash on launch.

**Comment by Electroblob77** [comment]
Okay, looks like metamorph is crashing because I wasn't registering my sounds properly in that version (it's very old!). I'm pretty certain that was fixed in 2.1.0, so if you go back to 2.1.2 this crash, at least, will be fixed. If you could post the crash on launch using the latest version, I might be able to help with it.

**Comment by ChocolateVegas** [comment]
I updated to the latest version and this is the crash report I get on launch:

[crash-2019-07-07_10.54.00-client.txt](https://github.com/Electroblob77/Wizardry/files/3365858/crash-2019-07-07_10.54.00-client.txt)

**Comment by Electroblob77** [comment]
You're using a very old version of Forge, update it to the current recommended (or latest) version and it'll fix the issue.
