### ISSUE TITLE
Could you tell me how to config the mob spawning on the end??

### ISSUE THREAD

**Issue by RetroGamerGuy** [Electroblob77/Wizardry#156]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft versions: [if this suggestion only applies to some versions, list them here]

Suggestion details: [describe what you would like to see added to the mod and why]

Other mods involved: [if this suggestion involves integration with other mods, list them here]

**Comment by Electroblob77** [comment]
Which mobs? I assume you mean evil wizards, in which case: if you're using wizardry 4.1.4 for Minecraft 1.12.2, they don't spawn in the end by default but you can add them using the evil wizard dimensions config option.

**Comment by Electroblob77** [comment]
More config options have been added in the 4.2.0 release, these should solve the issue.
