### ISSUE TITLE
Game crashed while crafting magic crystals

### ISSUE THREAD

**Issue by hugonoss** [Electroblob77/Wizardry#159]
Minecraft version: 1.12.2 
Wizardry version: 4.1.4 
Environment: Singleplayer/

Issue details: I picked up a crystal flower and tried to craft a magic crystal, but then the game crashed.

Other mods involved: I have no idea, I was using a lot of mods.

Link to crash report (if applicable): https://paste.dimdev.org/fuyuwubiya.mccrash

**Comment by Electroblob77** [comment]
The crash seems to have happened trying to draw the vanilla recipe book. The only mod mentioned in that stacktrace at all is optifine, so I'm not sure this really has much to do with wizardry. Could you try and reproduce it with the crystal flower again, and see if it happens with any other items?

**Comment by KokSaker** [comment]
https://github.com/Vazkii/Patchouli/issues/126 patchouli issue
