### ISSUE TITLE
Ars Magica 2 Incompatibility?

### ISSUE THREAD

**Issue by Latte-Wolf** [Electroblob77/Wizardry#16]
Minecraft version: 1.7.10
 
Environment: Singleplayer

Issue details: Game crashed, this mod and Ars Magica 2 share an enchantment ID, and I'm honestly not good with mods so I don't think I could fix it myself.

Other mods involved: Ars Magica 2

Report:
The game crashed whilst initializing game
Error: java.lang.IllegalArgumentException: Duplicate enchantment id! class electroblob.wizardry.enchantment.EnchantmentMagicSword and class am2.enchantments.EnchantMagicResist Enchantment ID:100

**Comment by Electroblob77** [comment]
Ars Magica 2... that's a new one, this usually happens with Custom NPCs. Anyway, this is not a bug, it's just an ID conflict. Go into the mod options menu, find Electroblob's Wizardry on the list and click 'configure'. Then click 'configure IDs' and change the enchantment IDs to something other than 100.

**Comment by Electroblob77** [comment]
Alternatively, you can edit wizardry.cfg manually with a text editor.
