### ISSUE TITLE
[please fix] EBWiz Enchantment Books disappear when opening chests

### ISSUE THREAD

**Issue by iamweirdie** [Electroblob77/Wizardry#161]
To Reproduce

Hold an EBWiz Enchantment book, such as Frost ~~Walker~~ Imbuement (walker was mislabel, sorry)
1a [optional]. Put more EBWiz enchantment books in your hotbar.
Right click a chest to open it
Make angry noises as the books suddenly disappear
This bug specifically applies to EBWiz books, I have tried it with vanilla enchantment books and they're just fine.

Server, have not tried single player yet

Minecraft: 1.12.2
Forge: 14.23.5.2838
Mod Pack : edge of twilight https://www.curseforge.com/minecraft/modpacks/edge-of-twilight
Mod Name: Electroblob's Wizardry
Mod Version: 4.1.4

**Comment by iamweirdie** [comment]
alright, i tried single player and the bug didn't happen, so there's likely a config issue with our server pack, i'll double check...

**Comment by Electroblob77** [comment]
Frost walker is not an enchantment from wizardry, it is from vanilla Minecraft. The only enchantments added by wizardry are temporary 'imbuements' which are not supposed to be on enchanted books, however, the only way to remove them from enchanted books is to detect them when you open a chest and delete the books or delete the enchantments from them. See issue #135 and PR #121.

In other words: the intended behaviour is that when you open a chest, any enchanted books with imbuements on them (which shouldn't be obtainable) are deleted, or if they have other enchantments as well, the imbuements are removed and the other enchantments stay.

Please could you explain exactly how your observations differ from this behaviour: are other enchantments incorrectly being deleted as well? And how did you get books with wizardry enchantments on them in the first place? Thanks

**Comment by iamweirdie** [comment]
Tested on SSP with JEI and EBWiz, same bug still occurs. i needed JEI cuz the imbuement books (earlier i mislabeled frost WALKER as opposed to imbuement, sorry), the ones that would disappear, didn't appear in the creative mode.

https://paste.dimdev.org/azigulitaj.md

Deleted enchanted book with illegal enchantments ...?
I know the person who initially got the frost imbuement 3 book got it as a drop, maybe the enchantment book ~~wasn't supposed to exist and~~ was accidentally inside the loot tables.

**Comment by Electroblob77** [comment]
`Deleted enchanted book with illegal enchantments`
That's the message wizardry prints out when the enchantments are removed from those books. In vanilla the only time they appear is in dungeons, so I figured detecting them in a chest would cover it.

To confirm, this is intended behaviour, they're not supposed to be obtainable (hence why they're not in the creative menu) and they won't be much use to you anyway, so don't worry about them. I think it is possible to remove them from loot tables, but it would mean specifying all other enchantments in the enchant_randomly loot function, which depending on your modlist might take a long time!

**Comment by iamweirdie** [comment]
hmm so it was either filter the loot tables or delete them on contact with chests. that makes a lot of sense, thank you!

**Comment by Shibva** [comment]
ehhhhhhhhh, tbh I have seen some other loot tables generate enchantments books that are illegal, so theres must be nothing blocking the enchantment from being pulled into random generation
