### ISSUE TITLE
Worldgen Crash, issue with Dynamic Trees

### ISSUE THREAD

**Issue by Circine** [Electroblob77/Wizardry#165]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.0 [change as necessary]

https://paste.dimdev.org/yopoqixini.sql
When fastworldgen is off, it crashes when trying to generate structures around Dynamic Trees. If I enable fastworldgen, it doesn't crash, but structures generate on the very top of the leaves of the trees.

**Comment by viceroy369** [comment]
Getting the exact same issue

https://paste.dimdev.org/rusacevudu.mccrash

**Comment by Electroblob77** [comment]
Okay that makes sense, I guess I need to add a config list for which blocks count as part of a tree. Until then, dynamic trees is incompatible with the fancy worldgen option so set it to fast, unfortunately you'll have to live with stuff on top of trees for the time being.

**Comment by EightBlade** [comment]
Same issue here!

https://paste.dimdev.org/lilocamoza.mccrash
