### ISSUE TITLE
Player don't take falling damages?

### ISSUE THREAD

**Issue by BlueWither** [Electroblob77/Wizardry#167]
Minecraft version: 1.12.2
Wizardry version: 4.2.0
Environment: Singleplayer

Issue details: When I updated this mod, I noticed that I can't take falling damage.

**Comment by Electroblob77** [comment]
Try turning off replaceVanillaFallDamage in wizardry's config. There may be a conflict with another mod causing the replacement fall damage not to work, if you could post your modlist, it may help me identify any conflicts.
