### ISSUE TITLE
Lots of towers

### ISSUE THREAD

**Issue by BlueWither** [Electroblob77/Wizardry#168]
Minecraft version: 1.12.2 
Wizardry version: 4.2.0 
Environment: Singleplayer

Issue details:Sometimes I see that a lot of wizard towers are standing.
But that doesn't seem to be the case everywhere.
I am using Biomes O' Plenty, and I haven't delete config before update.
Example in Voxelmap. I was continued to find many towers near here.
![example](https://user-images.githubusercontent.com/34153394/63221900-bbd76e80-c1da-11e9-935f-e538c7143a2a.png)

**Comment by BlueWither** [comment]
In super flat
![2019-08-18_19 43 23](https://user-images.githubusercontent.com/34153394/63223510-8722e180-c1f1-11e9-83d0-e786b4625d02.png)

**Comment by Electroblob77** [comment]
You must have updated from a previous version of wizardry, the rarity scale was changed in the latest version to give finer control over the spawn rate. Try deleting your ebwizardry.cfg file and relaunching the game, that will generate a new config file with default settings for the new version.
