### ISSUE TITLE
Wizard Armor pieces breaking

### ISSUE THREAD

**Issue by greenking13** [Electroblob77/Wizardry#17]
Minecraft version: 1.12.2
Wizardry version: 4.1.1
Environment: Server

Issue details: The wizard armor broke. I was fighting a few zombies, and then had my helm break. Then my boots broke a few moments after due to getting hit. From what the handbook says, I would expect the wizard robes to continue being an armor piece, but have an armor rating of 0, not just breaking when it says they are unbreakable.

Other mods involved: Considering it was against a vanilla zombie, I don't really know what mods would interact with the armor. Apologies.

Link to crash report (if applicable): Not applicable.

-Greenking13

**Comment by Electroblob77** [comment]
You are right, that should not happen. Interestingly enough, this happened to me a few times back in my 1.7.10 modpack but no matter what I tried (even in that modpack, with the same mods and so on) I couldn't recreate it. I think it's something to do with how the game handles damage. Did the zombie have an enchanted sword or something, or was it just a regular zombie?

**Comment by greenking13** [comment]
I do believe it was a regular zombie, although I can probably run a test on that in the next few days. I am aware that this issue has occurred for multiple people on the server I play on, so in case I can't test it, I can get one of them to test it instead.

**Comment by Electroblob77** [comment]
I will see if I can reproduce it then, thanks.

**Comment by Ghostrider231** [comment]
I can confirm this is happening, While fighting a bunch of hard hitting mobs (most notably zombies) they've made my wizard robes break. (I've unintentionally reproduced the issue during a play through with the blood moon mod installed, that greatly increases mob spawning which allows me to get hit a lot while the robes are on)
