### ISSUE TITLE
Meteor crashes the game when cast.

### ISSUE THREAD

**Issue by SirAron111** [Electroblob77/Wizardry#172]
Minecraft version: 1.12.2
Wizardry version: 4.2.0
Environment: Singleplayer

Issue details:
Meteor crashes the game when cast.
Currently going through all spells and all scrolls to test them (no altered damages jet just the normal settings) I did turn player block destruction off in the config thought to make I more server friendly.
And this is the First Crash I found maybe more will come (you can ping me on the discord if I should make a separate report for all spells that crash or if I should collect them here)
Hope this helps a little.

Other mods involved:

Link to crash report (if applicable):
https://pastebin.com/0LMCYYNR

**Comment by Electroblob77** [comment]
Ok, I'll have to look into this further. Thanks for reporting.

**Comment by SirAron111** [comment]
I think it has something to do with spells that try to break blocks when the options for players destroying terrain or spells to break blocks is turned off!

**Comment by Electroblob77** [comment]
Just noticed this is a duplicate of #198.
