### ISSUE TITLE
Crash on start up, Error: java.lang.NoSuchMethodError: electroblob.wizardry.spell.Spell.<init>

### ISSUE THREAD

**Issue by Shuisho10** [Electroblob77/Wizardry#174]
Minecraft version: 1.12.2
Wizardry version: 4.1.4 

Issue details: When I updated the mod, i couldn't get it on working because everytime i tried to run it, it just crashes with Error: java.lang.NoSuchMethodError: electroblob.wizardry.spell.Spell<init>

Link to crash report: https://pastebin.com/rUngnhJ2

**Comment by Electroblob77** [comment]
That's because extra spells is not yet compatible with the 4.2.0 release of wizardry. You'll have to wait until meldexun updates it or remove the spell pack for the time being.
