### ISSUE TITLE
NoSuchMethodError in 4.2.0

### ISSUE THREAD

**Issue by kreezxil** [Electroblob77/Wizardry#175]
Issue:  1.12.2 - 4.2.0 crashes dedicated server Forge 1.12.2 build 2838

Notes:
     NoSuchMethodError

crash report:
http://paste.ubuntu.com/p/tt8TqxHKVB/

fml server latest:
http://paste.ubuntu.com/p/KsqScV4JrQ/

I see this is probably the same issue as #174 as I too have Extra Spells installed in World of Dragons.

Is it possible to make your mod detect that Extra Spells is outdated and print a better code to shell? I realize that might be way beyond the scope, but I posit it just in case it is possible.

Feel free to close this, i won't mind.

**Comment by Electroblob77** [comment]
Yes you're right, this is the same thing but for Arcane Essentials. It's normally up to addons to specify the parent mod version in their mcmod.info file, I guess that hasn't really mattered up to this point. I do know FavouriteDragon is already working on updating it so keep an eye on his curseforge page!
