### ISSUE TITLE
Crash when switching to spell (Force Arrow)

### ISSUE THREAD

**Issue by Barbor-1** [Electroblob77/Wizardry#176]
Minecraft version: 1.12.2 
Wizardry version: 4.2.0 
Environment: Singleplayer

Issue details: 
I found new spell and i wanted to try them out so i placed them in my neutral master wand with 2 slot upgrade 2 cooldown upgrade and 2 storage upgrade and i crashed when switching to the Force Arrow spell,it keeps crashing when i try to come back.

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report : 
https://pastebin.com/suKsNRgz
or
https://paste.dimdev.org/irevakodix.mccrash

**Comment by Electroblob77** [comment]
...how is that even possible? Oh well, I'll add a check anyway.
