### ISSUE TITLE
Better Combat Rebirth Compatibility Issue

### ISSUE THREAD

**Issue by TheTrainwreck2010** [Electroblob77/Wizardry#177]
Minecraft version: 1.12.2
Wizardry version: 4.2.0
Environment: Singleplayer/LAN game/Server 

Issue details: After updating Wizardry to 4.2.0, a crash happens anytime a mob is attacked while Better Combat Rebirth is enabled. This happens when using any item as a physical attack including fist and regardless of whether the items are being dual-wielded or not.

Other mods involved: Better Combat Rebirth 1.12.2-1.5.6

https://paste.dimdev.org/qatinoyafa.mccrash

**Comment by Electroblob77** [comment]
Duplicate of #166. This has now been fixed in the 4.2.1 hotfix.
