### ISSUE TITLE
no resurections this time

### ISSUE THREAD

**Issue by lag42** [Electroblob77/Wizardry#178]
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Server

Issue details: i tried to use resurrection to bring another player that was set as my ally back to life, but no matter how much i right clicked around the exact spot where they died they would not come back

the amulet of the immortal is also not working unless you have keepInventory set to true in both singleplayer and multiplayer

i tested this all on the same computer with two instances with separate accounts and a dedicated server all running at once

i have not tried this with separate computers so that might be affecting this

Other mods involved: none, not even jei

EDIT: improved the title by at least 10x, thanks icehawk

**Comment by Electroblob77** [comment]
I tested all the resurrection stuff and the amulet in singleplayer and multiplayer and it worked on my end, so I'm not sure what's happened here. Just to confirm this, could you try it with only wizardry installed - or did you do that already?

**Comment by lag42** [comment]
i tested with only wizardry and forge

**Comment by Electroblob77** [comment]
Just tested it again myself, for whatever reason it's managed to break between when I got it working and the release... what happens for me (with the amulet, I haven't tried multiplayer) is it very briefly resurrects me, then shows the death screen again. Is that the same for you?

**Comment by lag42** [comment]
it didn't even do that for me, the resurrection button just did nothing, it wasn't saving the wand to cast the spell like it should be doing, it was working fine in another instance with quark's totem of holding(which is essentially an entity that acts as a gravestone)

**Comment by Electroblob77** [comment]
Can confirm this is a compatibility issue. It works in my dev environment, and it works with only wizardry and baubles installed. However, in my personal modpack it is broken as I described above, so it must be one or more of the mods I have installed there.
