### ISSUE TITLE
Possession shaders applying for everyone on the server

### ISSUE THREAD

**Issue by lag42** [Electroblob77/Wizardry#179]
Minecraft version: 1.12.2  
Wizardry version: 4.2.1
Environment: Server

Issue details: when someone on a server possesses any entity, everyone gets the shader effect

this effect seems to be exclusive to possession, sixth sense and transience both worked fine

i tested this all on the same computer with two instances with separate accounts and a dedicated server all running at once

i have not tried this with separate computers so that might be affecting this

Other mods involved: none, not even jei

**Comment by Electroblob77** [comment]
If it happens on a localhost it'll happen on any server, there's no real difference code-wise. Does everyone also look like the mob that was possessed (in third-person view), or is it just the shader effect that is wrong?

You can reset shaders by pressing F4, which may help in the meantime.

**Comment by lag42** [comment]
i just tested again to definitively answer this, it's only the shader effect that's going wrong

F4 is a valid workaround though
