### ISSUE TITLE
Possible recipe issue

### ISSUE THREAD

**Issue by brisingraerowing** [Electroblob77/Wizardry#18]
Minecraft version: 1.12.2 
Wizardry version: 4.1.1
Environment: Singleplayer

Issue details: I looked at the crafting recipe for the magic crystals in JEI and noticed two uncrafting recipes for the block of crystal, one giving one magic crystal, and one giving nine of them.

![2018-04-29_01 57 17](https://user-images.githubusercontent.com/250409/39403740-eaa0ea18-4b50-11e8-88e7-65cfd0dff434.png)

**Comment by Electroblob77** [comment]
Ah, that's not right, I noticed this in the recipe book but forgot to fix it. Thanks for reminding me!

**Comment by brisingraerowing** [comment]
NP. This is a very cool mod, and will be going in a progession based magitech modpack I am designing.

**Comment by Echoweaver** [comment]
Oh, ha. I was just going to file this bug. Glad I checked.

I didn't realize there was a 9-crystal recipe at all. The more you know!
