### ISSUE TITLE
casting spell with dispenser

### ISSUE THREAD

**Issue by Varg95** [Electroblob77/Wizardry#182]
Minecraft version: forge-1.12.2-14.23.5.2838  
Wizardry version: ElectroblobsWizardry-4.2.1-MC1
Environment: Singleplayer
Issue details: 
when ever i try to cast a spell with a dispenser my game crashes
Other mods involved: 
/
Link to crash report 
https://pastebin.com/U6SjSGKb

**Comment by Electroblob77** [comment]
Ok, I can see the problem there (dispensers mean the caster is null, thought I'd caught them all but that one slipped through). Does this happen with any other spells or just tornado?
