### ISSUE TITLE
Crash on casting spell (Ice Lance on 7th slot of wand)

### ISSUE THREAD

**Issue by Barbor-1** [Electroblob77/Wizardry#183]
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Singleplayer

Issue details: 
The game crashed when i tried to cast the Ice lance spell, when i cast it without my neutral master wand (2 slot , 2 cooldown and 2 storage upgrade) it doesn't crash (wands had no upgrade). Also i still hear the sound of the projectile breaking when i come back in the game.

Link to crash report: 
https://paste.dimdev.org/ridupozace.mccrash
or
https://pastebin.com/R8EmrWbS

**Comment by Barbor-1** [comment]
I kept playing around and it only crashes because i cast spell with the 7th slot of my master wand.

**Comment by Electroblob77** [comment]
This is similar to your other issue #176... is it the same wand? It may be that the NBT broke somehow with the update.

**Comment by Barbor-1** [comment]
yes same wand maybe because it is also enchanted with unbreaking 3.

**Comment by Barbor-1** [comment]
This bug also happened with another wand on the 6th slot (it had a slot upgrade)
