### ISSUE TITLE
Crash when fighting Wraiths from Obelisk Monster Spawners

### ISSUE THREAD

**Issue by Circine** [Electroblob77/Wizardry#184]
Minecraft version: 1.12.2 
Wizardry version: 4.2.1 
Environment: Singleplayer

https://paste.dimdev.org/dapuquhove.mccrash
Seems to only happen if minionRevengeTargeting=false, hasn't happened since I re-enabled it.

**Comment by Electroblob77** [comment]
This is the same crash as #188 and #185. Interesting that it only happens with minionRevengeTargeting=false, that may explain why I didn't see it when testing. I'll see what I can do.

**Comment by Electroblob77** [comment]
Fixed in 06d02ad
