### ISSUE TITLE
[Sudden server crash]

### ISSUE THREAD

**Issue by KamiSami** [Electroblob77/Wizardry#185]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Server

Issue details: [I was minding my own business and mining in underground till i heard explosion somewhere and suddenly server crashed.]

Other mods involved: [No clue]

Link to crash report (if applicable): [https://pastebin.com/rxEfDxKi] I hope this can help out what actually happened. I was suspecting this mod as it was mentioned in there.

**Comment by KamiSami** [comment]
Same issue seems to happen now and server is unplayable due to this strange bug, as it keeps crashing every time when i log in. If possible, i'd ask a possible quick fix for this?

**Comment by Ghostrider231** [comment]
I have a similar crash with what you are logging here, except i got this by purely messing around in Creative mode with wizard fights.

https://github.com/Electroblob77/Wizardry/issues/188

**Comment by Electroblob77** [comment]
See my comment on #188. Thanks for reporting.
