### ISSUE TITLE
Refilling your wand via crafting with Mana flask empies it

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#189]
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Server

Issue details: 
Refilling your wand with mana flasks via crafting empies them rather then filling up their mana.

Strangely enough, the crafting preview shows the filled wand, but as soon as you craft it. It loses all of its mana.

Filling your wand's mana from the arcane table with magic crystal still work as always.

Other mods involved: None

Link to crash report (if applicable): N/A

**Comment by Electroblob77** [comment]
Is this in the vanilla crafting table? I know there was an issue with modded ones before.

**Comment by kotekoder** [comment]
I have the same problem in inventory grid, tinkers, bibliocraft, and vanilla workbenches.

**Comment by kotekoder** [comment]
It is work when I take crafting result with shift+rigth click

**Comment by Ghostrider231** [comment]
@Electroblob77 yes, i did this through the vanilla 2x2 crafting grid that you have access in your inventory screen.

**Comment by Electroblob77** [comment]
Ok thanks, I'll investigate.

**Comment by Electroblob77** [comment]
Pretty sure this is fixed in 3a788c8
