### ISSUE TITLE
Stone of Transportation hardness rating

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Electroblob77/Wizardry#19]
Minecraft version: 1.12.2
Wizardry version: 4.1.1
Environment: SMP

Issue details: The stone of transportation, despite requiring a pickaxe, has a hardness of 0.  This means that if one accidentally punches a stone, it gets deleted.

**Comment by Electroblob77** [comment]
Hmm, must have missed that. I'll fix it for the next patch, thanks!
