### ISSUE TITLE
Spider swarm spell backfire can destroy bedrock

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#190]
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Server

Issue details: While attempting to the use the unknown spider swarm spell, some of the backfire effects (particularity the earthquake like one) can destroy every block. **And yes, this even includes bedrock.** 

Other mods involved: N/A

Link to crash report (if applicable): N/A

**Comment by Electroblob77** [comment]
Hmm, didn't think of that when I was writing them. I'll get this fixed soon, just be careful for now I guess!
