### ISSUE TITLE
Transcience Amulet wont trigger

### ISSUE THREAD

**Issue by KamiSami** [Electroblob77/Wizardry#192]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Singleplayer

Issue details: So I have died and been critically wounded(?) a lot. (whatever that might be, i assume being on low health? If so that i have been a lot). Even having wand with transcience on it on hand will not trigger the effect when getting beaten to low health, which again, I assume is how it should work? Either i have been VERY unlucky or this truly does not work.

Other mods involved: Just this mods and FTB Library, Utilities and Utilities:Backups, and then JEI and Baubles, nothing else.

Link to crash report (if applicable): None

**Comment by Electroblob77** [comment]
The amulet is supposed to give a 1 in 4 chance of activating the transience effect when your health is 1 heart or less. Of course, if you go from 1.5 hearts or more straight to zero then it can't happen.

I have just tested it myself and can confirm it works. I may increase the threshold or the chance a bit to make it more useful.

**Comment by KamiSami** [comment]
Ah, that might be the reason why it didn't activate for me, plus me being incredebly unlucky when it did go to half a heart and 1 heart. But yeah i think having it activate at higher health than 1 heart would be better, maybe setting config option for it could work? There are mobs for example in my private pack that does a lot of damage so getting to 1 heart is pretty lucky.
