### ISSUE TITLE
Crash: Game crashes when I try to click the in game config button for volume!

### ISSUE THREAD

**Issue by SirAron111** [Electroblob77/Wizardry#193]
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Singleplayer

Issue details:
I wanted to change my volume settings under the music and sound tab in the in game options but it crashed. First I thought it was related to dyn surround or Optifine or something else but simply removing EBWiz fixed it you should look into that.
https://github.com/OreCruncher/DynamicSurroundings/issues/491

Link to crash report (if applicable): 
https://pastebin.com/e4ABiSRJ
https://pastebin.com/hA7YsL0b

**Comment by Electroblob77** [comment]
This is the same as #191. Thanks for the additional info.
