### ISSUE TITLE
Crash while trying unidentified spell

### ISSUE THREAD

**Issue by FinnsRevenge** [Electroblob77/Wizardry#196]
Minecraft version: 1.12.2 
Wizardry version: 4.2.1
Environment: Singleplayer

Issue details: Rightclicked on a mob with an unidentified spell which led to a crash 

Link to crash report (if applicable): https://paste.dimdev.org/tamevikuyo.mccrash

**Comment by Electroblob77** [comment]
Okay that's an interesting one, I think I know what's caused it. Thanks for reporting, will fix for the next patch.
