### ISSUE TITLE
Arcane Workbench does not drop held items when broken

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Electroblob77/Wizardry#20]
Minecraft version: 1.12.2
Wizardry version: 4.1.1
Environment: SSP / SMP

Issue details: If you break an Arcane Workbench with items inside of it, the items are deleted.  In singleplayer, the magic crystal slot drops on the ground, but no other slots do.  In multiplayer, no slots drop.

**Comment by Electroblob77** [comment]
Interesting. The tile entity code is rather old so could do with being looked at. I'll see if I can get this fixed for the next patch, thanks!
