### ISSUE TITLE
[Suggestion] Conjure block spell with sneaking places another block instead of dispelling existing one

### ISSUE THREAD

**Issue by samoja12** [Electroblob77/Wizardry#201]
I have an idea how to make conjure block spell more useful, make it so that if you crouch when casting towards already spawned block instead of dispelling it you cast another block next to it.

**Comment by Electroblob77** [comment]
Thanks for putting this on here, I'll add it for the next update.

**Comment by Electroblob77** [comment]
Added in 5e321cc.
