### ISSUE TITLE
[Suggestion] Greater Telekinesis fix

### ISSUE THREAD

**Issue by Yranic** [Electroblob77/Wizardry#202]
1.12.2

The greater Telekinesis spell right now is not really useful in my opinion. You can throw mobs and blocks around yet if you move your mouse too quickly you often loose the object you are pointing at especially with blocks. Throwing mobs or blocks is also not that powerful but that is acceptable. What I really would want is that once you are affecting a block you won't drop it until you use the spell again not unlike the gravity gun mod. Right now using the spell to try to build or deconstruct something doesn't work because you always select blocks you don't want moved while trying to move the selected one around. Hope you can change or alter this in some way. 
I love this mod and the baubles addition is definitely fitting. 
Some suggestions I have on this are

Ring of Leaves
When equipped this ring uses the vine spell on a block you pass before falling to the death. Shift destroys the vine. 

Runic ring
When equipped and you have a  magic stone circle in your world your are teleported to one of these you with all your items instead of dying. Then you gain a wither effect causing you to die at your chosen spot.

**Comment by Electroblob77** [comment]
Greater telekinesis is supposed to require a bit of skill to use. It wasn't really intended for building. I can try and improve the hit detection a bit though, that may help.

The runic ring idea is interesting, I like it.
