### ISSUE TITLE
Error notification from game.

### ISSUE THREAD

**Issue by Nykiiee** [Electroblob77/Wizardry#204]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.1.4 [change as necessary]
Environment: Multiplayer server

Issue details: Error notification recommending me to send this crashlog to dev on joining server. 

Other mods involved: Roguelike Adventures and Dungeons 1.2.9

Link to crash report (if applicable): https://paste.dimdev.org/abuzukoyal.mccrash

**Comment by AzureDoom** [comment]
You need to update 4.2.1

**Comment by Nykiiee** [comment]
Updated, thank you!
