### ISSUE TITLE
Unknown error that crashes a sole player's minecraft

### ISSUE THREAD

**Issue by ddd800** [Electroblob77/Wizardry#205]
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: Server

Issue details: A crash sometimes happens randomly to players doing different things that crashes them out of minecraft entirely. Seems to happen most often while exploring but players have had it happen to them just sitting at home.

Other mods involved: Only mod I recognize up there that pops up in the logs is yours at this line.
`    at electroblob.wizardry.client.renderer.RenderArcaneLock.onRenderWorldLastEvent(RenderArcaneLock.java:57)`

Link to crash report (if applicable): https://pastebin.com/92HNwPTP

Side bug: at least 5 different spells will cause a client side kick from the server but not a full minecraft or server crash. ( meteor, wither, thunderstorm, Etc..)

**Comment by Electroblob77** [comment]
A CME... that's not good. However, it is only rendering code so I should be able to fix this by making a copy of the list.

The second bug is probably #198.
