### ISSUE TITLE
Crashes upon loading world

### ISSUE THREAD

**Issue by Ferisia** [Electroblob77/Wizardry#206]
Minecraft version: 1.12.2 
Wizardry version: 4.2.1
Environment: Singleplayer/Server

Issue details: When the world loads this happens https://pastebin.com/yRBEiHJW

Other mods involved: Arcane Essentials

**Comment by AzureDoom** [comment]
Arcane Essentials is not updated to support 4.2.x versions of Wizardry yet.

**Comment by Electroblob77** [comment]
It is now!

P.S. Generally speaking, if you know an addon is involved in a crash report please report it to the addon dev first.
