### ISSUE TITLE
[Suggestion] WAWLA support, add descriptions to enchantment books

### ISSUE THREAD

**Issue by WolfBV** [Electroblob77/Wizardry#210]
Minecraft versions: 1.12.2? (idk)

Suggestion details: 
![Screen Shot 2019-08-22 at 7 57 14 PM](https://user-images.githubusercontent.com/47493126/63564456-f6fada00-c519-11e9-925b-99d611f118f0.png)
Add a description to each of the mod's enchantment books.

Other mods involved: WAWLA - What Are We Looking At (https://www.curseforge.com/minecraft/mc-mods/wawla-what-are-we-looking-at) in Misc Features

**Comment by Electroblob77** [comment]
Sure, that's easy enough to do.
