### ISSUE TITLE
Flaming Weapon spell bug

### ISSUE THREAD

**Issue by Barbor-1** [Electroblob77/Wizardry#212]
Minecraft version: 1.12.2 
Wizardry version: 4.2.1
Environment: Singleplayer

Issue details: [describe what you were doing when the issue occurred, what went wrong, what you expected to happen, etc.]
When i cast the flaming weapon spell from my wand, i receive a report by the VanillaFix mod that there is a problem. I also do not see the effect of the spell on my sword and i later realised that even when the enchantment is not visible on the sword and that the spell should have worn off (i'm not good at english i don't know if i write correctly) i still get the effect of the flaming weapon spell on my sword and also that of a similar spell with ice effect ( the zombie hit has both fire and freezing effect).
When i try to add enchantment to the sword it causes a crash.

Other mods involved: VanillaFix for reports and maybe Apotheosis

Link to crash report (if applicable): 
Crash when adding enchants:
https://paste.dimdev.org/gefojagixe.mccrash
for report by VanillaFix when i cast Flaming Weapon:
https://paste.dimdev.org/akozavumen.mccrash

**Comment by Barbor-1** [comment]
My sword also does not have the fire aspect enchantment and my bugged wand from issue 176 and 183 was not used

**Comment by Electroblob77** [comment]
Not sure what's going on there, sorry. Did this happen in a world from a previous version of wizardry?

**Comment by Electroblob77** [comment]
Fixed in 14a624d
