### ISSUE TITLE
Question or maybe Bug: How around new wand tier upgrade

### ISSUE THREAD

**Issue by gdarai** [Electroblob77/Wizardry#213]
Minecraft version: 1.12.2
Wizardry version: 4.1.4 
Environment: Singleplayer

Issue details: I am trying to tier up wand. It is Frost Wand, and I crafted it... I am using it mostly for Magic Missiles for currently for 4-5 minecraft nights. Well I hoped that it will be enough to allow me to level the wand to Apprentice level, but nope. Still same old yellow effect and book stays and wand does not tier up.

Is there some relevant info what I have to do? I was looking around like for an hour or so and only thing I found was the ingame one liner "use the wand to master it"? Sooo.... some ingame info, or progress meter? Or hint somewhere on the web? Can my wand be upgraded or not?

Thank you.

**Comment by Schyler-Lowry** [comment]
Same issue here.

**Comment by gdarai** [comment]
Ok so I cheated in the apprentice wand to skip this issue and I have the same issue with the apprentice one. Now like 20 nights full of killing mobs but the wand will still not accept the apprentice -> advanced upgrade book. I am starting to feel I am forgetting something... or it is a subtle bug.

**Comment by Electroblob77** [comment]
This is not a bug, it's the new wand levelling system. If you keep spamming the same spell, you'll find that your wand levels up very slowly. Instead, try and cast a variety of spells to get it to level up faster. There is some rebalancing needed for this system so stay tuned for that. You can also view wand progression using F3+H to display advanced tooltips.

**Comment by BlueWither** [comment]
So... I can't upgrade wand by book before using many magics?

**Comment by Electroblob77** [comment]
Correct, unless you switch back to the old system using the config option 'Legacy Wand Levelling'.
