### ISSUE TITLE
a crash, apparenty related to pedestals

### ISSUE THREAD

**Issue by aycfes** [Electroblob77/Wizardry#216]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Singleplayer

Issue details: killing wizards that a lightning pedestal spawned
Other mods involved: seemingly none

Link to crash report (if applicable): 
[crash-2019-08-24_13.11.31-server.txt](https://github.com/Electroblob77/Wizardry/files/3537368/crash-2019-08-24_13.11.31-server.txt)

**Comment by Electroblob77** [comment]
Ok I think I know what's happened there. Thanks for reporting, will fix for the next patch.
