### ISSUE TITLE
Crashes/Bugs Spell Crash Collection

### ISSUE THREAD

**Issue by SirAron111** [Electroblob77/Wizardry#217]
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Forge: 14.23.5.2838 (newest version needed by many mods.)
Environment: Singleplayer

Spell Crash Collection/Single player tested with mods (also many spells have no sound related to one of the bugs most likely)

List of Crashes when firing spells. Tested them fired from Wands and from Scrolls!
This is collective post you should work trough and strike trough things you fixed and maybe pin so people can see this before repetitively reporting the same bug many times. I really hope this helps a little. If you need more information just ping me on the discord.

https://pastebin.com/7itchn2K (Flame Ray crashes on simply using it exactly the same crash log happens when using Frost Ray, Life Drain, Lightning Ray, Ray of Purification, Lightning Web, Fire Breath AND Shield/Shadow Ward/Glide / Levitation/Greater Telekinesis EVEN Speed Time Spell (basically all beam type spells and anything that can be held down with 0 spell cool down to apply repetitively) so if you find the error for one it will most likely solve them all together) strangely Flight spell which also needs to be held down doesn’t not crash.    **(Related to the Big sound Bug)**

https://pastebin.com/eFUBEqpx (clairvoyance has a bug with Optifine I think or it’s something else but clairvoyance crashes you when you use it standing on top of the green location block maybe it can’t path to the location if you are already on it or all particles spawn on the same spot unable to know where to draw the path you should block casting the spell if too close to the remembered location)

https://pastebin.com/kPAwcETG (Tornado crashes the game when casting it (and keeps crashing it as long as it exists in the world). I think its related to the sound bug that also happens when you try to open the sound options menu in game stack trace looks the same. So maybe some of your sound accessing or handling files are wrong or incompatible with something? Maybe that’s why every time a special spell using a special sound or the volume options get accessed it crashes) With Tornado especially this basically makes you unable to join the world again as Tornado stays around for a bit and as it immediately crashes again it doesn’t disappear.    **(Related to the Big sound Bug)**

https://pastebin.com/C3vpf6BT (Force field crashed when I was in creative and held the right clock down maybe it tried to spawn a force field in a force field or something like that. Could also be that the force field when expanding outward hit an entity like the passing by goblin or test dummy I use as lab rat to test damage spells on) but the crash looks similar to the one with the beams at the very top. (also when casting spells that stick to the ground like healing aura or some of the sigils in the force field walls this happens https://pastebin.com/va6nRT6u basically nearly the same crash)  **(Related to the Big sound Bug)**  **(Related to revenge target if it hits a summon)**

https://pastebin.com/Rin8WDTm (Frost Wall crash on cast: Here a similar crash to the tornado one does Frost Wall also try to access a sound on creation? If so it’s most likely the same as with tornado).      **(Related to the Big sound Bug)**

https://pastebin.com/ttA8M5Pt (I think I already reported this once but I will still include it in this collection so I can close the old single report file. Meteor crashes the game with this crash log when casting it)   **(Related to the Big sound Bug)**

--Not a crash but a bug: Spectral bow spazes out and repeats the sound of drawing it infinitely as its constantly changing metadata when ticking down the durability.

--Not a crash still a bug: Imbue Weapon, Flaming Weapon and Frozen Weapon don’t get discovered when spell is used weapon gets imbued but the spell on the wand stays as rune language. (Makes you always have a chance of forfeit if you want to use it or also never know what spell it is if not using a scroll of Identification) Also all of them imbue the weapon with the same effect Frostbite.
--Spectral Pathway is also not getting discovered after casting it.

--Combustion Rune ignores block damage settings and still blows up blocks same goes for Mine (on Mine it’s ok I think its purpose is to well mine blocks but it should lob a little bouncy Mine instead of simply blow up the blocks targeted)

--Some Spells that should get affected by Blastradius upgrade don’t get affected like Blizzard or Hailstorm it doesn’t increase I size at all (maybe I got the upgrades intentions wrong)

--Oak/iron to diamond flesh give way to much resistance. It should be 1 resist low duration for oak flesh 1 resistance long duration for iron and 2 resistance long duration for iron (making it 2 for oak 3 for iron and 4 for diamond is to op every resistance lvl gives 20% dmg reduction going over 2 lvls is always broken af)

List of Mods can be found here https://www.curseforge.com/minecraft/modpacks/dimension-zero at the bottom under Midlist. I tested it against all the 209 Mods on the list took a lot of time to run up the pack after every crash good thing I did this on my secondary PC while doing other stuff on my main machine XD.

GZ
SirAron

**Comment by SirAron111** [comment]
Ok After all the remaining tests i did i can nearly pinpoint the cause of the problem, and tell you why so many different mods related to sound or gui pop up in the crash logs.

First of all you are doing something wrong in how you handle Sound settings (writing and loading the volumes set in the options.txt or the in game volume setting) since every time you restart the client even with just EBwiz installed and nothing else the settings reset back to 100% for spell volume. And I think here lays the main problem the other mods dealing with sound and gui etc have with the current EBwiz.

Some examples of mods that try to access these values and crash if they can’t are AutoRegLib (mods by vazkii like quark or psi need that) and OreLib (Dynamic surroundings needs that)

But these moods aren’t at fault they just notice something is wrong and error out on it. And I think if you manage to fix this issue you will fix all sound related crashes and incompatibilities like the many ray type spells or tornado crashing the game.

**Comment by Electroblob77** [comment]
Okay here goes...!

1. Pretty sure this is #198. The sound category adding code isn't actually mine, I borrowed it (with credit) from a post on the forge forums. However, if ARL and OreLib do something similar I may be able to look at those and see what the current code is doing wrong. Those spells are all continuous, the reason flight doesn't do it is because it doesn't use a looped sound.

2. That crash is nothing to do with clairvoyance, you must have right-clicked a transportation stone circle with a wand. I can see what's gone wrong though, will fix for the next patch.

3. Same as 1.

4. Appears to be related to the sound bug (and is present in #199, amongst others). However, these reports have a different stacktrace, and the first part has only a single line pointing to `World#func_72939_s()`, aka `World#updateEntities()`. Hopefully this is the same problem as the others, if not I have no idea what's going on.

5. Same as 1.

6. Same as 4.

7. That's weird, Forge added a hook recently (which I use) with the specific purpose of stopping this from happening. I am able to reproduce it so I'll investigate further.

8. Might be related to #212. I am able to reproduce this so I'll investigate further.

9. Will test and fix.

10. Oops, must have missed that one. Will fix for the next patch.

11. I know, I just didn't get as far as adding support for this in 4.2.0. It's on my to-do list!

12. Well that's what I thought, hence why diamondflesh is resistance IV because that _should_ give 80% damage reduction... right? Unless it gets rounded down all the time? I'll reduce it anyway because of potency modifiers.

Thanks for taking the time to do all this testing, it helps get problems fixed faster.

**Comment by Electroblob77** [comment]
Spectral pathway is being discovered fine for me, I can't reproduce the issue you described. Did the spell itself work normally?

**Comment by SirAron111** [comment]
for me it does the jingle as if i discorvered it but simplay gives me this 
![2019-09-04_17 56 51](https://user-images.githubusercontent.com/39855956/64271424-99b15080-cf3d-11e9-8341-7b11bbad314a.png)
even cast from a wand styll all scramble runes 
![2019-09-04_18 00 58](https://user-images.githubusercontent.com/39855956/64271685-0e848a80-cf3e-11e9-8758-5024084d45e8.png)


https://paste.dimdev.org/atavesolen.mccrash also only the first cast of this spell actually makes a path all seconds just give me this crash
