### ISSUE TITLE
Game fails to initialize

### ISSUE THREAD

**Issue by gian800** [Electroblob77/Wizardry#219]
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Singleplayer

Issue details: I installed this mod and my game started crashing on launch, before loading the main menu. The same crash happens with 4.2.0
Other mods involved: I don't think there are any conflicts with other mods.

Link to crash report: https://pastebin.com/JZJ5hp4t

**Comment by Electroblob77** [comment]
Okay, I can see the problem there. Thanks for reporting, will fix for the next patch.
