### ISSUE TITLE
Crashing when attacking wizards

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Electroblob77/Wizardry#226]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: Singleplayer

Issue details: Attack enemy wizard, game goes kaput.

Link to crash report (if applicable): https://paste.dimdev.org/foyuviyuda.mccrash

https://paste.dimdev.org/yolucusaro.mccrash

**Comment by Electroblob77** [comment]
Duplicate of #198.
