### ISSUE TITLE
Crash on FireBall spell

### ISSUE THREAD

**Issue by ijo42** [Electroblob77/Wizardry#228]
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Server

Issue details: i am trying to kill a mob using a fireball spell and server is downed

Other mods involved: full mods list on hastebin

Link to crash report (if applicable): 
https://hastebin.com/esedoxifal.sql

**Comment by Electroblob77** [comment]
Ugh that method catches me out every damned time! Thanks for reporting, will fix for the next patch.
