### ISSUE TITLE
Get a crash report whenever someone uses transportation spell

### ISSUE THREAD

**Issue by Wiral2** [Electroblob77/Wizardry#229]
Minecraft version: 1.12.2 
Wizardry version: 4.1.1
Environment: Lan Game

Issue details: Whenever someone uses transportation spell I get this crash report :

https://paste.dimdev.org/sujetehevi.mccrash

Currently it's not the biggest deal because the server itself doesn't crash thanks to vanilla fix

**Comment by Electroblob77** [comment]
Please update your wizardry, that's a very old version! In this case the bug is actually still present in the newest version, but you should probably update anyway. I'll fix the bug for the next update.
