### ISSUE TITLE
I get a crash report whenever I use a spell

### ISSUE THREAD

**Issue by Wiral2** [Electroblob77/Wizardry#232]
Minecraft version: 1.12.2 
Wizardry version: 4.1.4 
Environment: Singleplayer/LAN game

Issue details: I recently updated the mod and now whenever I use any spell I get this crash report: https://paste.dimdev.org/izotixoyug.mccrash
I have vanilla fix, so the game itself doesn't crash. But I get bombarded with messages "unknown error has occured"

**Comment by Wiral2** [comment]
Also whenever I hit mobs from lycanitesmobs with the Ice axe, they get extremely weird textures.

**Comment by Electroblob77** [comment]
Probably a duplicate of #198. The second thing may be related to #170, Lycanite's mobs often behaves weirdly anyway.

**Comment by Wiral2** [comment]
Was the problem fixed in the newest update?
