### ISSUE TITLE
Possession change

### ISSUE THREAD

**Issue by KamiSami** [Electroblob77/Wizardry#233]
Minecraft version: 1.12.2

Suggestion details: So I noticed that possession spell is in the game, so i went ahead and tested it and... Results was not entirely what i expected, so i am suggesting a change for it (Unless it is an bug which im not sure of, or if this is intended feature or not) When i possess a mob, i am attacked by mobs and 'I' take damage instead the body i am possessing, as, i think(?) the body you possess should take damage instead the player itself, otherwise the spell does not... Make much sense, unless i am missing something... So far possession just let's you control a mob and you take damage far more easily as mobs dont have armor which seems to count for yourself aswell, i rather not possess a mob which gets killed easily, and that being me basically. So far the only reasons i can see for possession as of current state is stealing their armor or weapons if they have any? (Unsure, has yet to test that, but i believe that is how it works since i got skeleton's bow aswell upon possession). Also a question regarding to possession, is it possible to possess players? If not, is this a feature one can expect in future maybe? If it is too overpowered, maybe making a way that prevents dropping the equipment during possession of player. (Or config for that maybe?)

**Comment by Electroblob77** [comment]
The intended behaviour is this:

When possessing a mob, that creature takes the full incoming damage. However, you _also_ take half of all incoming damage, the idea being that you are somehow 'inside' the mob so you 'feel' whatever it 'feels'. If the mob dies, you immediately get kicked out of possession (you can test this by possessing something and then falling a long way, you should see it die in front of you). If _your health_ (not the mob's health) reaches 1 heart or less, you also get kicked out of possession.

This means that if you're wearing very good armour you will probably take damage more easily when possessing a mob, but in return you gain its abilities - that's the tradeoff. If the mob is wearing armour then you'll get the protection from that too. There's also a chance to fool nearby mobs into thinking you're one of them, iirc.

Possession of players is unlikely to happen for technical reasons, players normally control their own movement so controlling someone else's is likely to break a lot of stuff, not to mention being incredibly tricky to code.

**Comment by KamiSami** [comment]
Ah, i see. I imagined that you wouldn't really normally take damage as player if you transfer your soul and push away the possessed mob's soul away temporarily, since it's not your body that takes damage (Which means you would not be harmed, but the feeling of pain i get yeah) And once you felt enough of pain you would return back to your healthy body again. Anyway, thank you for the answer.

**Comment by Jonson26** [comment]
I think a neat way to incorporate this suggestion, would be to add two higher "tiers" to this spell, the first one making the player take only a quarter of the damage the mob recieves, and the second one damaging the player only when the mob dies. Also, shouldn't mobs think you're just another mob, and not attack you unless provoked? A "suspiciousness meter" would be a nice way of doing this. Then, when the player would leave the mob's body, the other mobs could still be "thinking" that the mob is still posessed and continue attacking.

**Comment by Electroblob77** [comment]
> Also, shouldn't mobs think you're just another mob, and not attack you unless provoked?

This is supposed to happen, yes. I think there's currently a bug affecting this but it should be fixed in the next patch.
