### ISSUE TITLE
Crash when Ice Giant interacts with Phoenix

### ISSUE THREAD

**Issue by JamesATeasdale** [Electroblob77/Wizardry#234]
Minecraft version: 1.12.2 
Wizardry version: 4.1.4
Environment: Singleplayer

I merely spawned an ice giant and a phoenix without issues, but as soon as they tried to attack eachother, the game crashed.

https://paste.dimdev.org/sacelagemo.mccrash

**Comment by JamesATeasdale** [comment]
actually, it looks like i'm having general trouble with anything sound related in this mod

**Comment by Electroblob77** [comment]
Yes, this is a duplicate of #198.
