### ISSUE TITLE
Mobs getting replaced with other mobs?

### ISSUE THREAD

**Issue by Meatshackles** [Electroblob77/Wizardry#237]
Minecraft version: 1.12.2 
Wizardry version: 4.2.2 
Environment: Singleplayer

Issue details: So a bit of backstory, both the Bewitchment mod and Mystic World mod adds owls and so I disabled the mystic world owls but after loading a new world they were still there. At first I thought it was a Mystic world config issue but after testing the mod by itself I confirmed the config works. Then going back I noticed there was no bewitchment owls, only the mystic world owls. I upped the spawn rates for bewitchment owls and set it to spawn in packs of 8, and on a new world I found packs of 8 mystic world owls. Something was causing the bewitchment owl spawns to be replaced with mystic world owls. I thought it might be a incompatibility between the two mods but using just those two mods together had no issues and the bewitchment owls woulds spawn just fine. 
After a lot of testing i've confirmed this issue only happens when I have Electroblob's enabled, as soon as I disable/remove wizardry the bewitchment owls spawn fine and then when I re-add wizardry the spawns are all mystic world owls again. I've had issues open for mystic world and spoke with the bewitchment devs and they've stated their shouldn't be anything in their mods that would cause this. I looked in the wizardry config for anything that might be related but didn't see anything.

Other mods involved: bewitchment, mystic world, possibly other mods that have mobs with the same names

Link to crash report (if applicable): https://paste.ee/p/nPLKI This is the log file, but I looked though it and didn't find anything myself.

**Comment by Electroblob77** [comment]
I have no idea how this could possibly be wizardry, it doesn't interfere with other mods' passive mobs in any way. The only thing I can think of is it may be a registry issue, but how and why that would happen I don't know, since Forge's registry system is supposed to prevent this sort of thing (back in 1.7 this type of issue was common due to duplicate IDs).

I know I have had trouble with the mystic world spawning config options in the past, I tried to disable the deer and they still spawned.

**Comment by Meatshackles** [comment]
I could upload my full instance if you would like to test it but I can definitely say the issue is only present when electroblobs is in the pack.

**Comment by Meatshackles** [comment]
So it doesn't appear to be electroblobs, after further testing it seems like a combination of mods, I still have no clue what the source is. I though it was electroblobs because the issue stopped once it was disabled but once I turned on some other mods it came back, there's like 7 mods in my instance that cause the issue when enabled.
