### ISSUE TITLE
Game crashed when using flame ray.  version 4.2.2 1.12.2 forge 14.23.5.2844

### ISSUE THREAD

**Issue by Sageking10** [Electroblob77/Wizardry#239]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.2 [change as necessary]
Environment: Singleplayer

Issue details: I used flame ray and the game crashed

https://paste.dimdev.org/nidelisifi.mccrash

**Comment by bigenergy** [comment]
+1
I get the same error if I go into the sound settings

**Comment by bigenergy** [comment]
@Electroblob77 pls fix this

**Comment by Electroblob77** [comment]
Duplicate of #238
