### ISSUE TITLE
Crashing when launching game

### ISSUE THREAD

**Issue by bailudayo** [Electroblob77/Wizardry#240]
Minecraft version: 1.12.2
Wizardry version: 4.2.2 [change as necessary]
Environment: Singleplayer

Issue details: I launched the game, then the crash occurred

Link to crash report (if applicable): (https://pastebin.com/GUhtNVcC)

**Comment by Electroblob77** [comment]
I'm not sure what you've posted there, but it's not a crash report. Is there anything in latest.log?
