### ISSUE TITLE
Refilling your wand with mana flasks wipes current spells and upgrades (via vanilla crafting again)

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#242]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.2
Environment: All

Issue details: 

**Refilling your wand with mana flasks (via vanilla 2x2 crafting) clears your wand's upgrades and current spells.**

**So I did mention a specific glitch like this, but this time around it does refill your wand, but clears your wand as if you never put anything on it.**

The spells can be reapplied back, but this might be an issue whenever you are in a tight situation and need to recharge. For Upgrades, those are completely gone, you have to get new ones.

Other mods involved: N/A

Link to crash report (if applicable): N/A

**Comment by Electroblob77** [comment]
That's not good, presumably this was introduced by the fix for #68. Thanks for reporting, I'll see what I can do.
