### ISSUE TITLE
Lost spirit wolf, cant summon new one

### ISSUE THREAD

**Issue by RiscmonIngk** [Electroblob77/Wizardry#243]
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: Singleplayer

I Summoned Spirit wolf, Pushed it into a boat so we could go on an adventure, relogged due to unrelated lag issues, loaded in and boat was gone with wolf, think despawned, later discover I cant summon a new wolf without the other being intentionally dispelled or killed.

its still out there somewhere and I cant make a new one.

I had an idea to disable and reenable the spell in the config but I cant _find_ the config file.

**Comment by RiscmonIngk** [comment]
found the file, it didnt work. im stumped.

**Comment by RiscmonIngk** [comment]
Another potential solution failed "/tp <playername> @e[type=ebwizardry:spirit_wolf]" should have taken me to them as i tested in another world successfully, but all I get is "entity '@e[type=ebwizardry:spirit_wolf]' cannot be found"

This dog both exists and doesnt exist.

**Comment by Electroblob77** [comment]
Please update to the latest version of wizardry (4.2.3), this bug (originally #74) was fixed in version 4.2.0.
