### ISSUE TITLE
Evoker can still sometimes use spells even while being arcane jammed

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#244]
Minecraft version: 1.12.2
Wizardry version: 4.2.3
Environment: All

Issue details: 

**Okay I'm not sure about this one, but I'm going post this anyways.**

**So apparently evokers can now be arcane jammed, which is cool.
However, they can still (sometimes) use spells as if they were not arcane jammed, they wave their arms for a fraction of a second before stopping. (I think this only happens if they get attacked?)**

And yes i've checked if they are still arcane jammed [Particle effects, etc].

**Not a big deal, but something worth pointing out.**

Other mods involved: N/A

Link to crash report (if applicable): N/A

**Comment by Electroblob77** [comment]
This probably has something to do with when forge fires `LivingUpdateEvent`, so there may not be much I can do about it. To clarify, do they just wave their arms or do they actually cast whatever spell they are using?

**Comment by Ghostrider231** [comment]
Taken directly of my message from discord: 

"i may have to tell you here cus i don't have access to my github account atm: the evoker still being able to use spells while arcame jammed, they only need to show their arms for a second (otherwise, they only need to get hit by someone once, and poof spell was casted) their spells have already been casted. (Fang spell casted or vex swarm spell casted). 

Perhaps, you could set their "spellticks" nbt tag to a high value possibly?"
