### ISSUE TITLE
Status effect desync when using forfeits

### ISSUE THREAD

**Issue by PiordaNautor** [Electroblob77/Wizardry#245]
Minecraft version: 1.12.2  
Wizardry version: 4.2.1
Environment: Singleplayer

Issue details: When attempting to figure out an unknown spell (Ward), I gained the Hunger status effect, briefly. However, ever since then the Hunger seems to be permanently "present" (Timer: 0:00, Hunger Bar coloration), but it does not affect the actual value in any way. The glitch is fixable via gaining Hunger again and allowing that (invisible) timer to run out.

**Comment by Electroblob77** [comment]
Sounds like a server/client desync. Thanks for reporting, I'll investigate.
