### ISSUE TITLE
Crash in 4.2.X

### ISSUE THREAD

**Issue by Traincrafter111** [Electroblob77/Wizardry#246]
Minecraft version: 1.12.2 
Wizardry version: 4.2.3
Environment: Singleplayer

Issue details: Hi I have a Modpack of more than 190 mods but In version 4.1.X Wizardy worked fine but when I updated it to any version of 4.2.X (4.2.0-4.2.3) it crash

Link to crash report (if applicable): https://pastebin.com/kAMFS9rm

**Comment by Ghostrider231** [comment]
Did you update extra spells? if not, the update can be found here: https://www.curseforge.com/minecraft/mc-mods/extra-spells-electroblobs-wizardry/files/2700768

**Comment by Traincrafter111** [comment]
It was that thank you a lot!
