### ISSUE TITLE
Trying to open sound settings crashes client

### ISSUE THREAD

**Issue by tobi-polar** [Electroblob77/Wizardry#247]
Minecraft version: 1.12.2 
Wizardry version: 4.2.1
Forge version: 14.23.5.2846
Environment: Singleplayer & playing on Server

Issue details: Trying to open sound settings crashed the client. Trying to open sound settings through the main menu or in game crashed the client.

We tried playing "Which one is it" by disabling all mods and re-enabling them one by one. No dice. I posted to r/feedthebeastcrashes and the advice I was given was to delete my options.txt file, which did fix it, they also said the issue MAY be related to Electro Blobs wizardry. We've since removed your mod and haven't encountered the issue again... Don't know if it was a one off and deleting options.txt was the solution, but multiple people had the issue. It's a custom pack so I'm assuming there was some kind of clash?

For the pack config and modlist: https://www.dropbox.com/s/pchp3vsqam6hnal/Lost%20Lands%20Patent%20Pending%200.4.zip?dl=0

Link to crash report (if applicable): https://paste.ee/p/Kpehk

**Comment by AzureDoom** [comment]
You need to update to 4.2.3, you are two versions behind. This was fixed.

**Comment by Electroblob77** [comment]
Yes, please update to the newest version.
