### ISSUE TITLE
Error-message after Arcane Essentials 0.9.2 update

### ISSUE THREAD

**Issue by Lemopav** [Electroblob77/Wizardry#253]
Minecraft version: 1.12.2
Wizardry version: 4.2.2
Arcane Essentials version: 0.9.2
Environment: Singleplayer/Server

Issue details: After updating Arcane Essentials from version 0.9.1 to 0.9.2 VanillaFix reported a Error. (no Crash)

Other mods involved: VanillaFix

Link to crash report (if applicable): https://paste.dimdev.org/eqesowitem.mccrash

edit: here on a clean minecraft with only VanillaFix and those two mods
https://paste.dimdev.org/ezosejewun.mccrash

**Comment by Electroblob77** [comment]
I've had a dig through and this is definitely a bug in Arcane Essentials. I'll report it to the issue tracker there.
