### ISSUE TITLE
Spellbook 92 is empty

### ISSUE THREAD

**Issue by Martmists-GH** [Electroblob77/Wizardry#256]
Minecraft version: 1.12.2
Wizardry version: 4.2.2
Environment: Server
Modpack: ATM 3 Remix
Other mods involved: None that I'm aware of.

Issue details: I have a wither farm running, and while looking through the spellbooks collected by killing them, I noticed two instances of spell 92 (i.e. Metadata number), which says "Empty Slot". I don't know if a mod other than this one adds the drops to the wither, but somehow spell 92 is selected during loot drops.

**Comment by Electroblob77** [comment]
Spell 92 was firestorm, which was renamed to fire breath as part of the 4.2 update. This means that any world saves from previous versions will assign it a new ID and 92 will effectively be left as a gap. 

I discovered this myself and it led me to make some changes to how spell ID numbers are handled internally so they ignore any gaps (they'll have to be phased out entirely for 1.13 anyway). It sounds like I forgot to make these changes to the loot functions though. I should be able to get that fixed for the next update, thanks for reporting.
