### ISSUE TITLE
Wizard Armor repair issues with Mending and baubles.

### ISSUE THREAD

**Issue by Sidnatum0** [Electroblob77/Wizardry#257]
Minecraft version: 1.12.2
Wizardry version: 4.2.3
Environment: Singleplayer

Issue details: Wizard armor can be enchanted with Mending, but experience orbs don't repair it.
Also, repairing baubles, such as the Amulet of Arcane Defense, repair armor only visually. When moving armor or taking damage, durability points decrease to value that which was before the repair.

**Comment by Electroblob77** [comment]
Interesting, that sounds like a syncing problem with the amulet, but I don't see why that would happen. I'll see if I can reproduce the issue and get it fixed.
