### ISSUE TITLE
Server crash on Activating Evil Wizard Trap

### ISSUE THREAD

**Issue by TheArtcore** [Electroblob77/Wizardry#258]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.2.3
Environment: Server

Issue details: I wandered into some wizard trap after being lured by a chest in the middle of some glyphs and a bunch if evil ice wizard spawned and froze me. When i trie dto escape my vision zoomed in and out and then the server crashes. I think it crashes when trying to send me to a different dimension but I'm not entirely sure as this mod is new to me.

Other mods involved: Not Sure

Link to crash report (if applicable): Here's log of the last error before server crash: https://pastebin.com/kh4c3SgF
And here's the crash report:
https://pastebin.com/ajVF2PRv

**Comment by Electroblob77** [comment]
Thanks for reporting this, I'll see what I can do.

**Comment by Electroblob77** [comment]
Turns out this is actually the same problem as #267, which was just fixed in 03dd76c
