### ISSUE TITLE
Wizard Hat Not Displayed Properly

### ISSUE THREAD

**Issue by PiordaNautor** [Electroblob77/Wizardry#259]
Minecraft version: 1.12.2 
Wizardry version: 4.2.3
Environment: Singleplayer

Issue details: I found a necromancer hat. I put it on. It did not look like a wizard hat.
Other mods involved: Mo'Bends (Possibly but doubted. Thought to be relevant due to it's changing of models, and minor conflict with Googly Eyes (Moves them out of position))
![Not a Wizard Hat](https://user-images.githubusercontent.com/55087535/65380819-a1405b80-dc98-11e9-8a6b-f3d6aecb5a5a.png)

**Comment by SirAron111** [comment]
Mo bends is the cause of this, this also happens with tinkers armor and mo bends and any other mod adding special layered armors. Mo bends alters the way the player model works.

**Comment by Electroblob77** [comment]
It's almost certainly Mo Bends or another armour-altering mod, caused by them not properly supporting 64x64 textures or custom models.
