### ISSUE TITLE
frostbite deletes most of the second layer of a player's skin

### ISSUE THREAD

**Issue by lag42** [Electroblob77/Wizardry#261]
Minecraft version: 1.12.2   
Wizardry version: 4.2.2 
Environment: Singleplayer

Issue details: when a player gets inflicted with frostbite the second layer of that player's skin gets deleted except for the hat, it will stay that way in that until you restart the game even if you create a new world, and it works fine before you get the effect

Other mods involved: no other mods involved, this happens in a clean instance with just wizardry

**Comment by Electroblob77** [comment]
That's odd. Could you post a few screenshots:
1. Before the frostbite effect is applied
2. While the effect is active
3. After the effect ends

Thanks.

**Comment by lag42** [comment]
[here](https://imgur.com/a/7dBTHGI) you go

**Comment by Electroblob77** [comment]
That's really useful, thanks for taking the time to make those. The player skin overlay must somehow be getting removed or overwritten by the frost layer renderer. I'll see if I can recreate this and hopefully get it fixed.
