### ISSUE TITLE
ice giants try to attack you in creative

### ISSUE THREAD

**Issue by BugmanBugman** [Electroblob77/Wizardry#262]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.1.4 [change as necessary]
Environment: Singleplayer/

Issue details: certain summonable mobs such as the frost giant and phoenix attempt to aggro you when on creative

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Ghostrider231** [comment]
Hello I'm not the author.

From the issue you have posted here, it seems that you have posted this on a older version of wizardry.
Try updating to 4.2.3 and see if you still have this problem.

**Comment by Electroblob77** [comment]
Yes, this might well have been fixed by the changes to minion targeting in the 4.2 update.

**Comment by BugmanBugman** [comment]
That was a typo oops, I was already on 4.2.3

**Comment by Electroblob77** [comment]
Sorry just saw this, thanks for confirming the version. I will try and reproduce this myself, it may be an oversight in some of the targeting code.
