### ISSUE TITLE
Makes my Xray mod show grey outlines instead of other colours

### ISSUE THREAD

**Issue by WertL** [Electroblob77/Wizardry#263]
Minecraft version: 1.12.2 
Wizardry version: 4.2.3 
Environment: Singleplayer
Issue details: Usually my X-ray mod outlines blocks in blue or something, but now after putting on your mod, it changes it to grey
Other mods involved: Electroblob's Wizardry, Advanced XRay
Link to crash report (if applicable): 
![2019-09-23_20 21 06](https://user-images.githubusercontent.com/55692397/65418465-d804a600-de3f-11e9-88e6-dc65207f1457.png) With your mod

![2019-09-23_20 23 00](https://user-images.githubusercontent.com/55692397/65418521-f9659200-de3f-11e9-8155-f1adcaedeb4a.png) Without your mod

**Comment by SirAron111** [comment]
This is related to this issue. https://github.com/Electroblob77/Wizardry/issues/208 Also don’t use X rays.
And ye this is a bigger problem as so many mods conflict… especially for mods that need the visual to make them work properly. Imagine having to cut the red or blue wire but you can only see gray ones.

**Comment by WertL** [comment]
> This is related to this issue. #208 Also don’t use X rays.
> And ye this is a bigger problem as so many mods conflict… especially for mods that need the visual to make them work properly. Imagine having to cut the red or blue wire but you can only see gray ones.

Okay :P 
Buts in only for survival
