### ISSUE TITLE
Tome of Arcana & Progression System Not Working.

### ISSUE THREAD

**Issue by Ionix12** [Electroblob77/Wizardry#264]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.2 [change as necessary]
Environment: Server

Issue details: I can't seem to use the Tome of Arcana in the Arcane Workbench. I can place all the necessary components, but upon clicking the checkbox, nothing happens the the Tome is not consumed. On top of this, the "progression bar" is non-existent. It is supposed to be below the mana indicator on the wand. I do not have a progression bar. 
Other mods involved: Botania, Tinker's Construct, Betweenlands.

**Comment by Electroblob77** [comment]
Could you post a screenshot of the wand in the arcane workbench?

**Comment by Ionix12** [comment]
I will do so later today and post it in the GitHub.

**Comment by Seth0067** [comment]
Having the same problem, so here:  
[https://imgur.com/a/rsH7Xzu](url)

Note that the upgrade button works and the table FX play, just nothing happens, the book does not vanish and the wand does not upgrade. Have tried this with a few different books (of same and different tiers) and wands.

This instance is a "Dimension Zero" pack (found on Twitch launcher) using EB 4.2.3

**Comment by Electroblob77** [comment]
That wand does not have sufficient progression to upgrade to the next tier (the progression bar is not filled and the word 'Apprentice' is greyed out). Progression is a new mechanic that was added in wizardry 4.2, see https://github.com/Electroblob77/Wizardry/wiki/Wands#progression

**Comment by Electroblob77** [comment]
Suspected invalid issue

**Comment by TeknoRapture** [comment]
I'm also having this problem.  Wand will not progress, and does not list the progression at all in the UI.  I'm hosting.  I gave the wand to my son and it works for him.

**Comment by TeknoRapture** [comment]
After further testing, this seems to be a display issue.  The Wands ARE gaining progression and will eventually be able to be leveled up, BUT the system is not showing the progress at all.  It's so weird though, I'm hosting a multiplayer game and the display works fine on both of my son's computers, but not mine.

**Comment by WinDanesz** [comment]
Press F3+H
