### ISSUE TITLE
I'm Immortal, nothing hurts me.

### ISSUE THREAD

**Issue by 8w-gremlin** [Electroblob77/Wizardry#266]
I appear to be immortal, nothing hurts me, I can stand in lava, be surrounded by mobs, be at the bottom of the ocean and nothing hurts me. 

I am wearing nothing but the paladin ring, and the immortality amulet, but I am also cursed with undeath. I have no idea why I am immortal, and can not be hurt by anything. 

Not complaining, just thought you should know, and see if you can replicate. 
(ps awesome mod) 

Details below
Minecraft version: 1.12.2
Wizardry version: 4.2.2 
Environment: Singleplayer/LAN game

Issue details: 

Other mods involved: Tek warfare mod pack (lots of mods) 

Link to crash report (if applicable): No Crash

**Comment by Electroblob77** [comment]
Ok, that's very strange. I'll see if I can replicate it.

**Comment by WesCook** [comment]
Do you have Astral Sorcery installed?  They had a known bug with invulnerability.  It was affecting some packs.

https://github.com/HellFirePvP/AstralSorcery/issues/1115

**Comment by LemADEC** [comment]
We had a player reproduce this issue, after using the Curse of undead, which might be unrelated.
It was fixed by reseting the invulnerability flag from their NBT player data.
We do have AstralSorcery, but it already contains above fix and player didn't play with Phoenix.
Any idea how this flag could be set?

**Comment by Electroblob77** [comment]
Useful to know about that workaround, that's clearly what's gone wrong. Wizardry does not touch the invulnerable flag at all though, so that's very confusing.
