### ISSUE TITLE
Strange crash on wizardry and bop interaction

### ISSUE THREAD

**Issue by SirAron111** [Electroblob77/Wizardry#267]
Minecraft version: 1.12.2  
Wizardry version: 4.2.3
Environment: Singleplayer

Issue details: [It just crashed like that on an erroring wizard or spell I think it seems to target something from bop maybe a wizard tries to grow something with a spell or so I attached a crash log.]

Other mods involved: [bioms o plenty aperantly]

Link to crash report (if applicable): https://paste.dimdev.org/awogikemoh.mccrash

**Comment by SirAron111** [comment]
Someone told me on the discord ist an issue with a wizard casting forest of thorns in a bop biome. Or another dimension if he spawns there with natural spawn chance or via the obelisks. So maybe add this option additionfor all spells.

    # Creates a forcefield around the caster which repels creatures and deflects projectiles.
    # Allow for Player.
    B:"ebwizardry:forcefield"=true
    # Allow for Wizards.
    B:"ebwizardry:forcefield"=true


    # Amidst the wood lies a hidden glade,
    # In the glade a wizard performs,
    # Magical arts of an order untold,
    # Deep within the forest of thorns.
    # Allow for Player.
    B:"ebwizardry:forest_of_thorns"=true
    # Allow for Wizards.
    B:"ebwizardry:forest_of_thorns"=false

This could also be used to configure wizards more like only having them use offensive spells or the like if someone so desires or simply to hotfix bugs until complete fixes are found instead of having to disable natural wizard spawning in all ways completely just preventing them from using the erroring spell

**Comment by Electroblob77** [comment]
This is all part of spell JSON files, obviously I know you're unable to use them currently, but when that's fixed you'll be able to prevent just wizards from casting certain spells.

As for the actual crash, I've just had a look and realised what's wrong, so I'll get it fixed for the next update.
