### ISSUE TITLE
Losing wand and spell books when server restarts

### ISSUE THREAD

**Issue by joanros97** [Electroblob77/Wizardry#268]
Hi, I'm using a Sponge 1.12.2 server with mods and plugins. Every time the server restarts, my players lose the wands and spellbooks from their inventory. But if they have the items on a backpack (from the backpack mod) they don't lose it. I'm using the 4.1.4 mod version of Electrobob's Wizardy.

System details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-042stab140.1
	Java Version: 1.8.0_222, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 3912840536 bytes (3731 MB) / 6736052224 bytes (6424 MB) up to 6736052224 bytes (6424 MB)
	JVM Flags: 2 total; -Xms5G -Xmx7G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2825 54 mods loaded, 54 mods active

- Mods:

-Decontable
-Aether legacy
-AnimalBikes
-Backpack mod
-Better Combat
-Biomes O'plenity
-bookworm
-CodeChickenCore
-colytra
-CustomNPC
-dotHackWeapons
-EleccCore
-Electrobob's Wizardy
-guns
-Huds
ICBM classic
-industrialcraft 2
-inventory tweaks
-jei
-Kaizen misc items
llibrary
lostcities
mowzies mobs
nashorn
NotEnoughItems
obfuscate
Optifine
Potion Core
The Betweenlands
Twilight Forest

- Plugins:
Luckyperms
flexible login
keepinventory
Nucleus
MMCrestrict
Nations
project core, portals, worlds
Total economy
Universe guard
worldedit

**Comment by Electroblob77** [comment]
I would ask if anyone used the possession spell, but since you're on 4.1.4 that can't possibly have happened. Firstly, I'd suggest updating to the latest 4.2.3 version of wizardry if possible. Other than that, my first guess would be the keepinventory plugin, try disabling that and see if the issue persists.
