### ISSUE TITLE
ticking world crash on server

### ISSUE THREAD

**Issue by IronworksProductions** [Electroblob77/Wizardry#269]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.3 [change as necessary]
Environment: Server [delete as necessary]

Issue details: null pointer crash relating to ticking world

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): https://gist.github.com/nacjm/d99f29f5eda498e8712d3d30b47b0316

**Comment by Electroblob77** [comment]
I think this is related to #186, but that's rather useful as it gives me a good test case without having to install dynamic trees in my dev environment. Thanks for reporting, I'll see what I can do.

In the meantime, you should be able to work around this by enabling fast worldgen in the config.

**Comment by Electroblob77** [comment]
Fixed in 1a13afb
