### ISSUE TITLE
Item ID issue with Ars Magicka 2 

### ISSUE THREAD

**Issue by Joshuam303** [Electroblob77/Wizardry#270]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.7.10   
Wizardry version: 1.1.4 
Environment: Singleplayer

I keep trying to launch minecraft but get an error saying that electrobob and Ars magicka are taking up the same item id (100)

https://i.imgur.com/f7l50ry.png
https://i.imgur.com/1Rqxlfo.png
https://imgur.com/a/DgN2teP

https://pastebin.com/s8KAzg8t

**Comment by Electroblob77** [comment]
Change the enchantment ID in the config...
