### ISSUE TITLE
[Give a brief, relevant title here]

### ISSUE THREAD

**Issue by Joshuam303** [Electroblob77/Wizardry#271]
Minecraft version: 1.7.10
Wizardry version: 1.1.4
Environment: Singleplayer

Hi! You answered my issue earlier about changing ids but whenever I try change your mod id's for the enchantment it keeps saying either "item id out of bonds" (I tried 1000, 500, 300) or when I go low it clashed again :( from the mod lists what would you recommend I put the 4 id's as? (the 100 ID, 101 ID, 102 ID and 103 ID)

**Comment by Electroblob77** [comment]
Try something like 226, 227, 228, 229, perhaps? The limit is 255, if that helps.
