### ISSUE TITLE
crashes when loading in mods

### ISSUE THREAD

**Issue by blu3wolf17** [Electroblob77/Wizardry#272]
Minecraft version: 1.12.2
Wizardry version: 4.2.2 
Environment: Singleplayer

Issue details: Loading game and crashes when loading in mods.

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): https://pastebin.com/JN1N90Ek

**Comment by Electroblob77** [comment]
Update arcane essentials to the latest version.
