### ISSUE TITLE
SEUS with Wizardy Spells

### ISSUE THREAD

**Issue by serdartpkl** [Electroblob77/Wizardry#273]
Hi!
I've encountered some kind of weird visual experience while i was playing with the wizardy mod. When i try to cast "Fire Breath" spell, the fire itself has no light and it's transparent. It's inverting the true color of the atmosphere. I think it's some kind of setting that SEUS has but it makes it less realistic and really hard to see, especially at night. It seems like it is not a light source. I don't know if i can fix it with changing a setting in SEUS but i am really waiting for a help.

PS: I love your work and i also have some spell/story ideas about the mod. I am an illustrator/designer so i can help you with drawing the GUI/Spells/etc. Keep up the AMAZING work!

Here is a screenshot that can explain the problem better:
![2019-10-04_22 51 00](https://user-images.githubusercontent.com/8151668/66236087-3b24f100-e6fa-11e9-8b69-f458b1a53653.png)

Minecraft version: 1.12.2
Wizardry version: 4.2.2
Environment: Singleplayer
Other mods involved: OptiFine & SEUS

**Comment by Electroblob77** [comment]
That's always a problem with shaders. There are various visual effects in wizardry that don't play too well with shaders, depending on which ones you use (I have been using Sildur's vibrant medium and that tends to work pretty well with them). The fire breath effect is just particles, a bit like the flame on a torch, so you could try looking through the shaderpack files for a list of 'bright' particles (particularly any .properties files). I'm not an expert on shaders so I'm not sure beyond that.
