### ISSUE TITLE
No natural mob generation

### ISSUE THREAD

**Issue by eilamg** [Electroblob77/Wizardry#274]
Minecraft version: 1.12.2
Forge version: 14.23.5.2847
Wizardry version: 4.2.4
Environment: Singleplayer

Latest version of Wizardry seems to remove all natural mob generation (hostile or otherwise) from the game. Villagers still show up and spawners still work, but no mobs appear when flying around the world.

Originally encountered the issue on a heavily modded instance, but issue persisted in a new instance with only JEI, JourneyMap and Wizardy.

**Comment by Electroblob77** [comment]
Ah. Yes, I know exactly what I've done wrong there... this is what happens when you don't test things 🤦‍♀️ This is a pretty major problem so I'm going to get this fixed right now, bear with me!
