### ISSUE TITLE
game keeps crashing

### ISSUE THREAD

**Issue by Joshuam303** [Electroblob77/Wizardry#276]
Minecraft version: 1.12.2
Wizardry version: 4.2.5
Environment: Server

Issue details: Hi! I have been using the 4.1.4 version of your mod but when I downloaded 4.2.5 suddenly it kept crashing my game and server 

not sure which ones might be causing it

https://pastebin.com/9gH8UNKL

**Comment by Electroblob77** [comment]
Update extra spells to the latest version.
