### ISSUE TITLE
mine and slash compat

### ISSUE THREAD

**Issue by Tyrius1** [Electroblob77/Wizardry#277]
Upon further testing, eb spells do in fact do damage based on mine and slash’s damage output system. However it scales your spells to whatever your your mainhand weapon’s physical damage. Which is okay in theory but I would say your spells should only do 25% (configurable) Of weapon damage and then be effected by the unique spell stats in mine and slash. This way building mage gear is more beneficial than just building melee gear and getting the same magic damage benefit.

**Comment by Electroblob77** [comment]
[Mine and Slash Auto Compatibility](https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-auto-compatibility) now has integration with wizardry, I'm guessing that resolves the issue.
