### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by californiaimage** [Electroblob77/Wizardry#28]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 1.12.2
Environment: Singleplayer

Issue details: Crash onload

Other mods involved: None, only mod loaded

Link to crash report (if applicable): 

The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: net.minecraftforge.registries.IForgeRegistry.getValuesCollection()Ljava/util/Collection;

**Comment by Electroblob77** [comment]
Please update your forge to build 2611 or newer.

**Comment by californiaimage** [comment]
Still getting the error on the current version of Forge 14.23.3.2684:

The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: net.minecraftforge.registries.IForgeRegistry.getValuesCollection()Ljava/util/Collection;
