### ISSUE TITLE
if someone use blink spell, everyone will get a screen blink.

### ISSUE THREAD

**Issue by ColaLiao** [Electroblob77/Wizardry#280]
Minecraft version: 1.12.2 
Wizardry version: 4.2.5
Environment: Singleplayer/LAN game

Issue details: 
if someone use blink spell, everyone will get a screen blink.

**Comment by Electroblob77** [comment]
Ok, I'll look into it. Thanks for reporting.

**Comment by focalfury** [comment]
Can confirm this happens in multiplayer games.  Thanks for looking into this.  I love the blink spells but have been banned from using it near my friends.
