### ISSUE TITLE
Forge Initialization Crash

### ISSUE THREAD

**Issue by KxttyKxt** [Electroblob77/Wizardry#282]
Minecraft version: 1.12.2
Wizardry version: 4.2.5
Environment: Initialization

Issue details: Forge Mod Loader crashes right as phase 3 of 7 starts. It happens every time. I gathered from the little I could understand of the crash report. I have run the mod in a 1.12.2 modpack before just fine. I do remember a texture change with the wands that I noticed a few days prior to the crashes.
Other mods involved: No other mods seemed to be mentioned, but my brother did experience this same problem in his own modpack.

Link to crash report: [https://pastebin.com/hs0KLRgS]

**Comment by Tora-B** [comment]
Your copy of Extra Spells is out of date, and incompatible with the latest version of Electroblob's Wizardry.
