### ISSUE TITLE
Version 4.2.5 does not respect the replaceVanillaFallDamage config option.

### ISSUE THREAD

**Issue by gazorpaz** [Electroblob77/Wizardry#284]
Minecraft version: 1.12.2
Wizardry version: 4.2.5
Environment: Singleplayer/Server

Issue details: I have set replaceVanillaFallDamage=false since velocity based calculation breaks Thaumcraft's Cloudstepper ring use (still get damaged). 

After update though no matter if it is true or false damage still happens. Tested on single and server.

For now downgraded to 4.2.3 (latest that I used). Works fine.

**Comment by Electroblob77** [comment]
I don't know how that can possibly be the case, none of that code was changed between 4.2.3 and 4.2.5. However, in 4.2.4 the config file was moved so make sure you're editing `config/ebwizardry/ebwizardry.cfg`, not `config/ebwizardry.cfg`.

**Comment by gazorpaz** [comment]
It really was the config location confusion. Closing.
