### ISSUE TITLE
Roots particles appear white when EB Wizardry is installed

### ISSUE THREAD

**Issue by AstatorDem** [Electroblob77/Wizardry#285]
Minecraft version: 1.12.2 
Wizardry version: 4.2.5
Environment: Singleplayer/LAN game/Server

Issue details: Particles generated by Roots appear white when Wizardry is installed. The issue is only cosmetic, but it seems to affect most particles added by mods.
The quickest way to test this is to grab a Roots Pyre and set any random ritual. When activated, the fire will be white (picture attached):
![Pyre white particles](https://i.imgur.com/YuerR3W.png)

Other mods involved: [Roots](https://www.curseforge.com/minecraft/mc-mods/roots)

**Comment by AstatorDem** [comment]
Related to #208

**Comment by Electroblob77** [comment]
It's probably the same as #208, embers and roots share a core mod after all

**Comment by Electroblob77** [comment]
Should be fixed by PR #319 (released in version 4.2.6). Please reopen if the issue persists.
