### ISSUE TITLE
Vex Swarm Attacks Friendly Wizards

### ISSUE THREAD

**Issue by PiordaNautor** [Electroblob77/Wizardry#286]
Minecraft version: 1.12.2  
Wizardry version: 4.2.5
Environment: Singleplayer

Issue details: When you summon Vexes (I have not tested other Hostile Mob summons), they do not attack Passive Mobs, but they _do_ attack Friendly Wizards.

Other mods involved: Extra Spells (Electroblob's Wizardry) (by meldexum) (Unsure)

**Comment by Electroblob77** [comment]
This is intended behaviour, the same way they attack zombie pigmen even when they aren't angry.
