### ISSUE TITLE
Unable to learn new spells

### ISSUE THREAD

**Issue by Elijah0331** [Electroblob77/Wizardry#287]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.3 
Environment: Singleplayer/Server

I'm encountering what I assume is a bug with this mod, in that I can't seem to learn any new spells. If I use an unknown spellbook on my wand it binds just fine, and I'm able to cast the spell (and it's name in the GUI and my wand is revealed) but I don't get the "You have learned [spell]" message, and if I come back a short time later it's a mystery again - the title on the book and on my wand is back to being unknown runes.

**Comment by Electroblob77** [comment]
That's weird, I saw this once myself a long time ago but it's never happened since and it went away when I restarted the game. Was this on a world from an older version of wizardry? Could you try it on a fresh world and see if the same thing happens?

**Comment by Elijah0331** [comment]
Its on the latest version of ATM 3 Remix running version 4.2.3 of Electroblob's. Tried it on multiple worlds and still get the same result.

**Comment by Elijah0331** [comment]
Ive managed a work around by using Scrolls of Identification for all the spells except for one. The only spell I cant seem to get to work even with the scroll is "Ice Spikes", even after using a scroll of identification on it and it giving the confirmation message in chat that the spell was learned whenever it is cast it does nothing.
