### ISSUE TITLE
About Astral diamond 

### ISSUE THREAD

**Issue by ornleaff** [Electroblob77/Wizardry#290]
Astral diamond can only be obtained by opening the box, but the probability of being tested by me is very slim. Will the author add a new astral diamond access to the next updated version?

**Comment by Electroblob77** [comment]
They are quite rare, but that is kind of the point. I have two on my survival world so far, but am yet to find a wizard selling a master spell so I haven't actually bought anything with them yet. If you want them to be more common you can always edit the loot tables.
