### ISSUE TITLE
Particles stop rendering until game is restarted

### ISSUE THREAD

**Issue by RaindeerGamez** [Electroblob77/Wizardry#293]
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: Singleplayer

Issue details: Usually, if I'm using spells that involve a lot of particles, at some point the particles will stop rendering entirely. It's become almost an inevitable part of my modded game. Lowering my clients particle rendering seems to help keep it from happening for a little while longer, but ultimately the particles will disappear until I restart my game. What I suspect to be possible triggers are rendering chunks by flying over them, casting particle heavy spells, and crossing dimensions.

But sometimes this just happens randomly, and once it happens in-game, the only way to resolve it is to restart the game. But that's temporary fix. To give an idea, it looks like the particles were deleted from the game entirely. Even when mining blocks, the particles are gone.

I've also tried optifine, but it didn't help.

Other mods involved:

**Comment by ColaLiao** [comment]
did you play with ice and fire mod?

**Comment by RaindeerGamez** [comment]
Yeah, I did

**Comment by mxnmnm** [comment]
Update ice and fire to the latest version

**Comment by ColaLiao** [comment]
the problem is from iaf mod,even the newest ver. the problem still exsit

**Comment by mxnmnm** [comment]
hmmmm I thought they finally fixed it lol guess it maybe isn't as bad as it was before so I say you should probably make another issue on their github lol

**Comment by AntiThesis1250** [comment]
Is there a solution??

**Comment by mxnmnm** [comment]
Normally what I do is use fancy block particles and then I just cycle through turning on and off the particles, which usually does the trick. Although, it doesn't work every time it's usually good enough.

**Comment by AntiThesis1250** [comment]
> Normally what I do is use fancy block particles and then I just cycle through turning on and off the particles, which usually does the trick. Although, it doesn't work every time it's usually good enough.

I don't know how to turn off and turn on particles. Can you tell me what to do?

**Comment by AntiThesis1250** [comment]
https://github.com/Electroblob77/Wizardry/issues/626

Here is the question I created ↑

**Comment by mxnmnm** [comment]
By default it is set to none so you'll have to configure it yourself

**Comment by AntiThesis1250** [comment]
> By default it is set to none so you'll have to configure it yourself

Where to modify "None"? Please tell me more details. Thank you very much :)

**Comment by mxnmnm** [comment]
The same way you modify vanilla keybinds
