### ISSUE TITLE
Wizard Hat, Robe, Leggings, Boots will be broken after Item durability become 0 in the Newest version

### ISSUE THREAD

**Issue by ColaLiao** [Electroblob77/Wizardry#294]
Minecraft version: 1.12.2
Wizardry version: 4.2.5
Environment: Singleplayer/LAN game

Wizard Hat, Robe, Leggings, Boots will be broken after Item durability become 0 in the Newest version

**Comment by Electroblob77** [comment]
Okay, various people have said this so I'll look into it, thanks.

**Comment by Electroblob77** [comment]
Can confirm this is happening, it looks like I managed to remove the previous fix for this issue when adding the anti-repairing code. I'll fix this for the next patch.
