### ISSUE TITLE
Sometimes wizard structures not show on Antique Atlas

### ISSUE THREAD

**Issue by ColaLiao** [Electroblob77/Wizardry#296]
Minecraft version: 1.12.2 
Wizardry version: 4.2.5
Environment: Singleplayer/LAN game

Issue details: Sometimes wizard structures not show on Antique Atlas

**Comment by Electroblob77** [comment]
If you're playing on a map with existing structures that were either generated with an old version of wizardry or generated while antique atlas integration was disabled, they won't get marked. To help me reproduce this, could you:
1. Set up an installation with only wizardry and antique atlas.
2. Make sure all antique atlas integration settings are enabled, then generate a new world.
3. Post the world seed and the location of any structures that don't get marked.

**Comment by Electroblob77** [comment]
Probably #323 on second look, will be fixed.
