### ISSUE TITLE
Natural Generation Based Crash.

### ISSUE THREAD

**Issue by ValianceHD** [Electroblob77/Wizardry#298]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.5
Environment: Singleplayer

Issue details: It would seem there is a naturally generating object that is causing a client crash as soon as generated, leaving various areas in player worlds left untouchable. Although the crash log is leading me to believe the issue is caused by some form of dispenser, a mod conflict issue is also not out of the question, for I had many others installed during this particular session.

Link to crash report:
[crash-2019-10-30_04.52.01-server.txt](https://github.com/Electroblob77/Wizardry/files/3787998/crash-2019-10-30_04.52.01-server.txt)

**Comment by Electroblob77** [comment]
This must be jungle temple dispensers, they sometimes generate with scrolls and other dispensable wizardry items in them. I don't know why this is crashing but you should be able to work around it by removing all the items from the loot table `ebwizardry/loot_tables/chests/jungle_dispenser_additions`.
