### ISSUE TITLE
Game Crash with Transportation

### ISSUE THREAD

**Issue by NazzyDragon** [Electroblob77/Wizardry#307]
Minecraft version: 1.12.2
Wizardry version: 4.2.5
Environment: Singleplayer

Issue details: Attempting to set a stone circle as your transportation location after you've already set it to said circle causes a game crash. You can set a different stone circle as your transportation circle normally. Transportation still works normally. It's largely just an issue for people like me who always double/triple check if things are set, as everything still functions.

Other mods involved: Modlist is in the pastebin link if curious.

Link to crash report (if applicable): https://pastebin.com/jQ8CKbZQ

**Comment by Electroblob77** [comment]
Ah yes, I see what I've done. Will fix for the next patch, thanks.
