### ISSUE TITLE
Allow to disable crystal flowers spawning on bonemeal use

### ISSUE THREAD

**Issue by Stormister** [Electroblob77/Wizardry#308]
Suggestion details: For modpack developers, it is normally pretty easy to gate mod progression by disabling Crystal Flowers from spawning. However, as of right now it is impossible to prevent players from spawning them in using bonemeal. As such, there is nothing preventing players from starting Wizardry by using bonemeal until a crystal flower appears. Please add a config option to disable this. Thank you.

**Comment by Stormister** [comment]
As a workaround, I am removing the recipe for crystals from crystal flowers, but it would be nice to keep the flowers useful, at least

**Comment by Electroblob77** [comment]
That makes sense, always happy to add sensible config options. I'll add it for the next update, thanks.
