### ISSUE TITLE
Crash after adding creatures to the immunity list

### ISSUE THREAD

**Issue by belathus** [Electroblob77/Wizardry#31]
Minecraft version: 1.12.2
Wizardry version: 4.1.1
Environment: Server

Issue details: Crash after adding entities to the config for damage immunity. Specifically, I tried adding the Twilight Forest's Snow Queen to the ice immunity list.

Other mods involved: Twilight Forest.

Link to crash report (if applicable): https://gist.github.com/belathus/4dc0471b2d0fe41a7e3393bf73254fd6

Here are two versions of the config file I was using; both caused crashes: https://github.com/belathus/Wanderlust-Renewed/commit/7828cc7eb9e8f897fe4eaa07d7f9c5fe53390c9c

**Comment by Ghostrider231** [comment]
I'm not the author, but I may want to tell you that this can apply to any modded mobs as far as I'm aware of. (So it can be any mod involved or none) [This actually happens in both environments]

I've only used the immunity list once for the ROTD mod and pretty much getting the same crash like you've described there.

**Comment by Electroblob77** [comment]
Thanks @Ghostrider231, that tells me it's definitely a problem with wizardry.

**Comment by Electroblob77** [comment]
Something seems to have gone wrong when looking up entities by name (the entity registry system got changed in 1.12 so that sort of makes sense). I'll look into it, thanks both of you for reporting it.

**Comment by Electroblob77** [comment]
I've just realised this is because the entities haven't been registered at the point when the config is read. It's an easy fix, I'll get it done for the next patch.

**Comment by belathus** [comment]
Sweet. Looking forward to it.

**Comment by Electroblob77** [comment]
Fixed in 00584ad
