### ISSUE TITLE
Lan Server Crash Random ElectroblobsWizardry-4.2.5

### ISSUE THREAD

**Issue by djzombie84** [Electroblob77/Wizardry#310]
Minecraft version: 1.12.2 
ElectroblobsWizardry-4.2.5-MC1.12.2
Environment: LAN game

Server Crash Random

Time: 11/23/19 4:17 AM
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at electroblob.wizardry.client.WizardryClientEventHandler.onClientTickEvent(WizardryClientEventHandler.java:154)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_585_WizardryClientEventHandler_onClientTickEvent_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at electroblob.wizardry.client.WizardryClientEventHandler.onClientTickEvent(WizardryClientEventHandler.java:154)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_585_WizardryClientEventHandler_onClientTickEvent_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DerSchakal'/334, l='MpServer', x=312.46, y=119.00, z=-42.47]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 11 - topography, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (120,135,233), Chunk: (at 8,8,9 in 7,14; contains blocks 112,0,224 to 127,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 9140293 game time, 10406718 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 23 total; [EntityChicken['Huhn'/4876367, l='MpServer', x=-209.49, y=115.00, z=592.05], EntityPlayerSP['DerSchakal'/334, l='MpServer', x=312.46, y=119.00, z=-42.47], EntitySheep['Schaf'/6115333, l='MpServer', x=390.90, y=117.00, z=-69.43], EntityOtherPlayerMP['Minija5'/4928, l='MpServer', x=-216.18, y=115.00, z=629.24], EntityChicken['Huhn'/6103614, l='MpServer', x=279.11, y=126.00, z=-119.11], EntityCreeper['Creeper'/6119985, l='MpServer', x=288.50, y=77.00, z=37.50], EntityCreeper['Creeper'/6119984, l='MpServer', x=291.50, y=77.00, z=36.51], EntityRooster['Hahn'/5554871, l='MpServer', x=322.89, y=127.00, z=-156.49], EntityRooster['Hahn'/6116532, l='MpServer', x=241.43, y=118.00, z=-98.87], EntitySkeleton['Skelett'/5536084, l='MpServer', x=-311.50, y=65.00, z=639.50], EntityCow['Kuh'/6116188, l='MpServer', x=380.72, y=121.00, z=-97.17], EntityBrainyZombie['Angry Zombie'/5554520, l='MpServer', x=307.64, y=66.00, z=-105.30], EntityChicken['Huhn'/5554550, l='MpServer', x=344.57, y=122.00, z=-62.98], EntityChicken['Huhn'/5554551, l='MpServer', x=347.11, y=122.00, z=-63.32], EntityChickensChicken['Obsidianhuhn'/5554556, l='MpServer', x=345.66, y=122.00, z=-63.81], EntityChicken['Huhn'/5554557, l='MpServer', x=347.56, y=122.00, z=-57.83], EntityChicken['Huhn'/5554552, l='MpServer', x=347.31, y=122.00, z=-58.31], EntityChicken['Huhn'/5554553, l='MpServer', x=346.97, y=122.00, z=-58.82], EntityChicken['Huhn'/5554554, l='MpServer', x=347.32, y=122.00, z=-63.90], EntityChicken['Huhn'/5554555, l='MpServer', x=348.17, y=122.00, z=-58.62], EntityXPOrb['Erfahrungskugel'/6086630, l='MpServer', x=321.25, y=120.00, z=-36.63], EntityItem['item.item.coal'/6118825, l='MpServer', x=328.50, y=126.00, z=-81.50], EntityManaBurst['Mana Burst'/6119844, l='MpServer', x=324.95, y=127.07, z=-80.14]]
	Retry entities: 203 total; [EntityChicken['Huhn'/4876367, l='MpServer', x=-209.49, y=115.00, z=592.05], EntityItem['item.item.feather'/5380181, l='MpServer', x=74.84, y=122.00, z=189.44], EntityChicken['Huhn'/4876365, l='MpServer', x=-207.26, y=115.00, z=587.90], EntityCreeper['Creeper'/5544027, l='MpServer', x=-187.50, y=66.00, z=567.50], EntityCreeper['Creeper'/6075465, l='MpServer', x=322.50, y=47.00, z=-108.50], EntitySkeleton['Skelett'/6095940, l='MpServer', x=320.50, y=44.00, z=-110.50], EntityItem['item.item.flint'/5418062, l='MpServer', x=128.45, y=125.00, z=241.07], EntityZombie['Zombie'/6086208, l='MpServer', x=309.50, y=48.00, z=-111.50], EntityItem['item.item.egg'/5482060, l='MpServer', x=90.86, y=122.00, z=174.64], EntityCreeper['Creeper'/5549173, l='MpServer', x=-179.50, y=72.00, z=572.37], EntityItem['item.item.feather'/5501554, l='MpServer', x=173.36, y=120.00, z=287.30], EntityItem['item.item.feather'/5152357, l='MpServer', x=128.41, y=125.00, z=241.45], EntityItem['item.item.feather'/5519461, l='MpServer', x=105.69, y=125.00, z=211.22], EntityItem['item.item.flint'/5514341, l='MpServer', x=174.54, y=120.00, z=286.89], EntityItem['item.item.hatchery.chickenmanure'/5522535, l='MpServer', x=75.76, y=122.00, z=190.01], EntitySheep['Schaf'/4876405, l='MpServer', x=-195.19, y=115.00, z=537.35], EntitySpider['Spinne'/5532693, l='MpServer', x=-186.50, y=64.00, z=562.50], EntityCreeper['Creeper'/5545503, l='MpServer', x=-180.50, y=65.00, z=564.50], EntityItem['item.item.feather'/5523487, l='MpServer', x=159.89, y=123.00, z=192.23], EntityItem['item.item.hatchery.chickenmanure'/5493278, l='MpServer', x=127.75, y=125.00, z=240.82], EntityXPOrb['Erfahrungskugel'/6102547, l='MpServer', x=323.69, y=119.85, z=-41.33], EntityCreeper['Creeper'/5541915, l='MpServer', x=-308.50, y=65.00, z=644.50], EntityItem['item.item.feather'/5390337, l='MpServer', x=-224.24, y=110.00, z=534.64], EntityWitch['Hexe'/6075912, l='MpServer', x=349.50, y=95.00, z=-62.50], EntityCreeper['Creeper'/5551624, l='MpServer', x=-318.50, y=65.00, z=644.50], EntityItem['item.item.flint'/5556744, l='MpServer', x=104.42, y=125.00, z=211.82], EntityItem['item.item.feather'/5457934, l='MpServer', x=112.39, y=124.00, z=179.88], EntityItem['item.item.feather'/5485107, l='MpServer', x=92.88, y=124.00, z=190.05], EntityItem['item.item.coal'/5555765, l='MpServer', x=-214.50, y=111.00, z=615.50], EntityItemFrame['Rahmen'/4860462, l='MpServer', x=-199.03, y=116.50, z=564.50], EntityItemFrame['Rahmen'/4860463, l='MpServer', x=-199.03, y=117.50, z=565.50], EntityBat['Fledermaus'/6064697, l='MpServer', x=276.26, y=25.25, z=-48.35], EntityItemFrame['Rahmen'/4860460, l='MpServer', x=-199.03, y=117.50, z=563.50], EntityBat['Fledermaus'/6064698, l='MpServer', x=346.67, y=43.31, z=-40.19], EntityItemFrame['Rahmen'/4860461, l='MpServer', x=-199.03, y=118.50, z=564.50], EntitySkeleton['Skelett'/5546035, l='MpServer', x=-176.50, y=73.00, z=571.50], EntityButterfly['Wall'/4860474, l='MpServer', x=-215.23, y=124.60, z=572.98], EntityButterfly['Painted Lady'/4860472, l='MpServer', x=-210.89, y=137.20, z=572.30], EntityItem['item.item.hatchery.chickenmanure'/5483040, l='MpServer', x=104.77, y=125.00, z=210.93], EntityButterfly['Marsh Fritillary'/4860476, l='MpServer', x=-215.56, y=124.50, z=571.44], EntityPig['Schinken'/4860464, l='MpServer', x=-199.00, y=115.03, z=569.99], EntityManaBurst['Mana Burst'/5555758, l='MpServer', x=-207.50, y=114.75, z=615.50], EntityCow['Kuh'/5554730, l='MpServer', x=380.72, y=121.00, z=-97.17], EntityCow['Kuh'/4860469, l='MpServer', x=-198.96, y=115.00, z=575.55], EntityItem['item.item.feather'/5449943, l='MpServer', x=105.59, y=125.00, z=209.96], EntityItem['item.item.feather'/5464287, l='MpServer', x=99.22, y=123.00, z=285.66], EntityItem['item.item.hatchery.chickenmanure'/5505220, l='MpServer', x=91.57, y=124.00, z=189.11], EntityButterfly['Marsh Fritillary'/4928216, l='MpServer', x=-235.25, y=126.00, z=607.75], EntityManaBurst['Mana Burst'/6102734, l='MpServer', x=326.63, y=128.01, z=-82.50], EntityItem['item.item.feather'/5074642, l='MpServer', x=113.15, y=124.00, z=179.23], EntitySheep['Schaf'/4927211, l='MpServer', x=-203.33, y=115.00, z=588.89], EntityCow['Kuh'/4927210, l='MpServer', x=-197.90, y=115.00, z=575.45], EntityCow['Kuh'/4927209, l='MpServer', x=-199.51, y=115.00, z=578.80], EntityCow['Kuh'/4927208, l='MpServer', x=-199.85, y=115.00, z=580.26], EntityPig['Schwein'/4859630, l='MpServer', x=-205.08, y=115.00, z=583.88], EntitySheep['Schaf'/4927215, l='MpServer', x=-202.93, y=115.00, z=592.92], EntityBat['Fledermaus'/6094072, l='MpServer', x=331.52, y=46.85, z=-107.60], EntityChicken['Huhn'/4859631, l='MpServer', x=-205.64, y=115.00, z=588.26], EntitySheep['Schaf'/4927214, l='MpServer', x=-202.33, y=115.00, z=589.14], EntityPig['Schwein'/4859628, l='MpServer', x=-213.32, y=115.00, z=577.50], EntityCow['Kuh'/4927213, l='MpServer', x=-203.38, y=115.00, z=586.18], EntityHorse['Pferd'/4927212, l='MpServer', x=-200.40, y=115.00, z=589.27], EntityChicken['Huhn'/4859629, l='MpServer', x=-205.41, y=115.00, z=588.77], EntitySkeleton['Skelett'/5557502, l='MpServer', x=135.50, y=78.00, z=250.50], EntitySheep['Schaf'/4928231, l='MpServer', x=-241.52, y=108.00, z=540.73], EntityCow['Kuh'/4927207, l='MpServer', x=-200.45, y=115.00, z=581.21], EntityItem['item.item.feather'/5490430, l='MpServer', x=-237.97, y=113.00, z=579.82], EntityCow['Kuh'/4927206, l='MpServer', x=-201.38, y=115.00, z=584.29], EntityCow['Kuh'/4927205, l='MpServer', x=-203.52, y=115.00, z=582.45], EntityCow['Kuh'/4927204, l='MpServer', x=-201.11, y=115.00, z=576.84], EntityChicken['Huhn'/4927225, l='MpServer', x=-219.11, y=110.00, z=528.52], EntityButterfly['Speyeria diana'/4927224, l='MpServer', x=-210.92, y=115.02, z=585.15], EntityButterfly['Zitronenfalter'/4927230, l='MpServer', x=-209.70, y=123.50, z=569.13], EntityItem['item.item.feather'/5452517, l='MpServer', x=91.50, y=122.00, z=174.52], EntityPig['Schwein'/4927228, l='MpServer', x=-206.50, y=115.00, z=546.22], EntityPig['Schwein'/4859634, l='MpServer', x=-209.93, y=115.00, z=579.76], EntityPig['Schwein'/4927219, l='MpServer', x=-208.29, y=115.00, z=577.23], EntityChicken['Huhn'/4927218, l='MpServer', x=-204.83, y=115.00, z=591.64], EntityChicken['Huhn'/4859635, l='MpServer', x=-207.64, y=115.00, z=592.14], EntityChicken['Huhn'/4859632, l='MpServer', x=-209.51, y=115.00, z=592.70], EntityPig['Schwein'/4927217, l='MpServer', x=-207.50, y=115.00, z=575.78], EntityZombie['Zombie'/5549294, l='MpServer', x=-190.50, y=67.00, z=565.50], EntityPig['Schwein'/4859633, l='MpServer', x=-205.86, y=115.00, z=584.95], EntitySheep['Schaf'/4927216, l='MpServer', x=-201.46, y=115.00, z=588.07], EntityButterfly['Gatekeeper'/4927223, l='MpServer', x=-210.93, y=124.50, z=571.10], EntityChicken['Huhn'/4859638, l='MpServer', x=-208.95, y=115.00, z=592.59], EntitySheep['Schaf'/4927222, l='MpServer', x=-199.08, y=115.00, z=588.45], EntityRooster['Hahn'/4859636, l='MpServer', x=-205.10, y=115.00, z=590.79], EntitySheep['Schaf'/4927221, l='MpServer', x=-202.97, y=115.00, z=591.84], EntityChicken['Huhn'/4927220, l='MpServer', x=-208.49, y=115.00, z=592.11], EntityChicken['Huhn'/4859637, l='MpServer', x=-205.29, y=115.00, z=591.36], EntityEvilWizard['Wizard'/6089887, l='MpServer', x=325.50, y=45.00, z=-108.50], EntityButterfly['Gelbspanner'/4911232, l='MpServer', x=-220.71, y=124.50, z=571.59], EntityButterfly['Celastrina gozora'/4911233, l='MpServer', x=-205.64, y=117.31, z=548.35], EntityZombie['Zombie'/5553816, l='MpServer', x=-320.50, y=65.00, z=639.50], EntityItem['item.item.feather'/5374083, l='MpServer', x=156.09, y=122.00, z=292.13], EntityEvilWizard['Wizard'/5552270, l='MpServer', x=-309.50, y=65.00, z=637.50], EntitySkeleton['Skelett'/6100614, l='MpServer', x=337.50, y=95.00, z=-53.50], EntityItem['item.item.hatchery.chickenmanure'/5544073, l='MpServer', x=-224.36, y=110.00, z=534.64], EntitySkeleton['Skelett'/5554314, l='MpServer', x=-307.50, y=65.00, z=640.50], EntityItem['item.item.hatchery.chickenmanure'/5385357, l='MpServer', x=156.09, y=122.00, z=293.50], EntitySkeleton['Skelett'/5554315, l='MpServer', x=-308.50, y=65.00, z=639.50], EntitySheep['Schaf'/223, l='MpServer', x=61.28, y=122.00, z=245.29], EntityItem['item.item.feather'/5507764, l='MpServer', x=92.02, y=123.00, z=174.28], EntityChicken['Huhn'/231, l='MpServer', x=75.50, y=122.00, z=190.12], EntityItem['item.item.feather'/5535423, l='MpServer', x=-231.64, y=109.00, z=534.03], EntityItem['item.item.egg'/5527224, l='MpServer', x=91.42, y=124.00, z=189.49], EntitySheep['Schaf'/240, l='MpServer', x=78.58, y=120.00, z=170.23], EntityChicken['Huhn'/4928184, l='MpServer', x=-175.62, y=116.00, z=642.90], EntityItem['item.item.coal'/6101161, l='MpServer', x=328.50, y=126.00, z=-81.50], EntityHorse['Pferd'/4928691, l='MpServer', x=-192.95, y=109.00, z=672.01], EntityItem['item.item.egg'/5538990, l='MpServer', x=-237.62, y=113.00, z=579.39], EntitySheep['Schaf'/5542574, l='MpServer', x=390.90, y=117.00, z=-69.43], EntityRooster['Hahn'/5554863, l='MpServer', x=241.43, y=118.00, z=-98.87], EntitySkeleton['Skelett'/5536084, l='MpServer', x=-311.50, y=65.00, z=639.50], EntityItem['item.item.feather'/5979487, l='MpServer', x=75.01, y=122.00, z=189.99], EntitySheep['Schaf'/4927309, l='MpServer', x=-258.18, y=108.00, z=587.54], EntityItem['item.item.flint'/5534556, l='MpServer', x=-230.74, y=109.00, z=533.57], EntityCreeper['Creeper'/6098257, l='MpServer', x=326.50, y=48.00, z=-105.50], EntityCreeper['Creeper'/6098258, l='MpServer', x=330.50, y=48.00, z=-103.50], EntityBat['Fledermaus'/6099791, l='MpServer', x=328.43, y=45.30, z=-111.51], EntityItem['item.item.hatchery.chickenmanure'/5547843, l='MpServer', x=155.66, y=122.00, z=293.23], EntitySpark['Spark'/4927315, l='MpServer', x=-217.50, y=116.50, z=614.50], EntitySpark['Spark'/4927314, l='MpServer', x=-216.50, y=116.50, z=615.50], EntitySpark['Spark'/4927313, l='MpServer', x=-217.50, y=116.50, z=616.50], EntitySpark['Spark'/4927312, l='MpServer', x=-208.50, y=116.50, z=615.50], EntityZombie['Zombie'/6078279, l='MpServer', x=307.50, y=70.00, z=-104.50], EntitySpark['Spark'/4927317, l='MpServer', x=-218.50, y=116.50, z=615.50], EntitySpark['Spark'/4927316, l='MpServer', x=-212.50, y=116.50, z=611.50], EntityZombie['Zombie'/5551478, l='MpServer', x=-188.50, y=64.00, z=561.50], EntityZombie['Zombie'/5551479, l='MpServer', x=-184.50, y=64.00, z=564.50], EntitySpider['Spinne'/5507442, l='MpServer', x=-182.84, y=65.00, z=564.00], EntityItem['item.item.feather'/5488500, l='MpServer', x=75.88, y=122.00, z=190.78], EntityItem['item.item.feather'/5344630, l='MpServer', x=159.44, y=122.00, z=289.68], EntityItem['item.item.hatchery.chickenmanure'/5483387, l='MpServer', x=-190.57, y=115.00, z=556.62], EntityItem['item.item.feather'/5339519, l='MpServer', x=189.10, y=120.00, z=262.33], EntityItem['item.item.feather'/6101357, l='MpServer', x=75.71, y=122.00, z=189.18], EntityZombie['Zombie'/5543783, l='MpServer', x=-307.50, y=65.00, z=639.50], EntityZombie['Zombie'/5548385, l='MpServer', x=-317.50, y=65.00, z=632.50], EntityItem['item.item.hatchery.chickenmanure'/5515617, l='MpServer', x=-231.30, y=109.00, z=532.97], EntitySkeleton['Skelett'/6100840, l='MpServer', x=321.30, y=120.00, z=-40.44], EntitySkeleton['Skelett'/6100839, l='MpServer', x=321.30, y=120.00, z=-40.60], EntityItem['item.item.feather'/5476718, l='MpServer', x=156.17, y=122.00, z=293.28], EntityItemFrame['Rahmen'/4859656, l='MpServer', x=-209.97, y=117.50, z=563.50], EntityCreeper['Creeper'/6097695, l='MpServer', x=311.50, y=55.00, z=-110.50], EntityButterfly['Kleiner Kohlweißling'/4859657, l='MpServer', x=-205.71, y=124.00, z=575.09], EntityButterfly['Papilio demodocus'/4927247, l='MpServer', x=-235.38, y=126.60, z=605.63], EntityZombie['Zombie'/5557521, l='MpServer', x=130.50, y=94.00, z=199.50], EntityButterfly['Wall'/4859660, l='MpServer', x=-208.86, y=123.00, z=568.64], EntityZombie['Zombie'/4927244, l='MpServer', x=-176.76, y=67.00, z=562.51], EntityItem['item.item.egg'/5444378, l='MpServer', x=156.23, y=122.00, z=292.40], EntityItem['item.item.egg'/5547806, l='MpServer', x=75.49, y=122.00, z=190.29], EntityItemFrame['Rahmen'/4859654, l='MpServer', x=-209.97, y=117.50, z=565.50], EntityItemFrame['Rahmen'/4859655, l='MpServer', x=-209.97, y=118.50, z=564.50], EntityItemFrame['Rahmen'/4859653, l='MpServer', x=-209.97, y=116.50, z=564.50], EntityBat['Fledermaus'/6078739, l='MpServer', x=326.44, y=49.96, z=-45.97], EntityBat['Fledermaus'/6094095, l='MpServer', x=305.15, y=56.12, z=-113.11], EntityItem['item.item.feather'/5513474, l='MpServer', x=188.17, y=120.00, z=263.00], EntitySheep['Schaf'/4927251, l='MpServer', x=-203.93, y=115.00, z=592.45], EntityButterfly['C-Falter'/4927250, l='MpServer', x=-213.38, y=115.59, z=591.62], EntityItem['item.item.hatchery.chickenmanure'/5476105, l='MpServer', x=-237.51, y=113.00, z=580.50], EntityButterfly['Speckled Wood'/4927249, l='MpServer', x=-217.02, y=124.50, z=573.27], EntityOcelot['Poyn'/4927248, l='MpServer', x=-224.69, y=115.00, z=593.49], EntityItem['item.item.feather'/5411599, l='MpServer', x=91.40, y=124.00, z=190.12], EntityItem['item.item.hatchery.chickenmanure'/5479226, l='MpServer', x=100.24, y=123.00, z=286.06], EntitySheep['Schaf'/4927271, l='MpServer', x=-257.46, y=109.00, z=583.24], EntitySpark['Spark'/4927291, l='MpServer', x=-207.50, y=116.50, z=616.50], EntitySpark['Spark'/4927290, l='MpServer', x=-206.50, y=116.50, z=615.50], EntitySpark['Spark'/4927292, l='MpServer', x=-207.50, y=116.50, z=614.50], EntityItem['item.item.feather'/5375790, l='MpServer', x=160.56, y=123.00, z=191.06], EntityChicken['Huhn'/4927286, l='MpServer', x=-237.50, y=113.00, z=573.83], EntityItem['item.item.hatchery.chickenmanure'/5526486, l='MpServer', x=174.93, y=120.00, z=288.43], EntityItem['item.item.feather'/5530065, l='MpServer', x=75.86, y=122.00, z=189.35], EntitySheep['Schaf'/4928479, l='MpServer', x=-227.63, y=109.70, z=624.48], EntityItem['item.item.egg'/5537219, l='MpServer', x=112.66, y=124.00, z=179.57], EntityCreeper['Creeper'/6056389, l='MpServer', x=309.50, y=50.00, z=-110.50], EntityItem['item.item.egg'/5413832, l='MpServer', x=75.48, y=122.00, z=189.24], EntityEvilWizard['Wizard'/5552078, l='MpServer', x=-306.50, y=108.00, z=654.50], EntityItem['item.item.egg'/5531087, l='MpServer', x=-204.75, y=115.00, z=592.43], EntityChickensChicken['Sandhuhn'/4893652, l='MpServer', x=-224.78, y=110.00, z=535.49], EntityChickensChicken['Feuersteinhuhn'/4893653, l='MpServer', x=-231.22, y=109.00, z=533.45], EntityCreeper['Creeper'/5546996, l='MpServer', x=-316.50, y=66.00, z=639.50], EntityCreeper['Creeper'/5546998, l='MpServer', x=-318.50, y=66.00, z=641.50], EntityItem['item.item.flint'/5487607, l='MpServer', x=98.78, y=123.00, z=286.71], EntityItem['item.item.feather'/5526001, l='MpServer', x=-237.20, y=113.00, z=580.47], EntityZombie['Zombie'/5553148, l='MpServer', x=-317.50, y=65.00, z=636.50], EntityZombie['Zombie'/5553147, l='MpServer', x=-311.50, y=65.00, z=637.50], EntityItem['item.item.hatchery.chickenmanure'/5461474, l='MpServer', x=91.45, y=123.00, z=175.58], EntityItem['item.item.coal'/5555589, l='MpServer', x=-210.50, y=111.00, z=615.50], EntityChicken['Huhn'/5555080, l='MpServer', x=271.59, y=124.00, z=-115.83], EntityBat['Fledermaus'/6073216, l='MpServer', x=341.29, y=48.03, z=-55.49], EntityButterfly['Camberwell Beauty'/4927380, l='MpServer', x=-224.78, y=126.24, z=579.94], EntityButterfly['Ringlet'/5233071, l='MpServer', x=-214.77, y=124.00, z=574.69], EntityItem['item.item.feather'/5412784, l='MpServer', x=174.08, y=120.00, z=288.25], EntityItem['item.tile.sand.default'/5552561, l='MpServer', x=-224.53, y=110.00, z=535.13], EntityItem['item.item.feather'/5527992, l='MpServer', x=157.63, y=122.00, z=288.87], EntityItem['item.item.flint'/5384127, l='MpServer', x=104.27, y=125.00, z=210.64], EntityZombie['Zombie'/5551010, l='MpServer', x=-194.50, y=82.00, z=568.50], EntityManaBurst['Mana Burst'/6102442, l='MpServer', x=324.09, y=126.59, z=-80.35], EntityChickensChicken['Schlaues Huhn'/4927409, l='MpServer', x=-205.99, y=115.00, z=589.06], EntityItem['item.item.hatchery.chickenmanure'/5455785, l='MpServer', x=113.80, y=124.00, z=178.92], EntitySheep['Schaf'/4927408, l='MpServer', x=-178.24, y=112.00, z=523.45], EntityItem['item.item.hatchery.chickenmanure'/5532584, l='MpServer', x=-204.75, y=115.00, z=592.47]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2605562472 bytes (2484 MB) / 15813050368 bytes (15080 MB) up to 20774387712 bytes (19812 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx22288m -Xms256m -XX:PermSize=256m -Xms256m

**Comment by Electroblob77** [comment]
Please use gist, pastebin or similar to post crash reports in future. Any details on what you were doing when this happened? Even for crashes that seem 'random', knowing what was happening in-game when it crashed can still be useful, even if you were just walking around. Thanks.

**Comment by djzombie84** [comment]
Where it happened very often,
if anyone visits my island via the draconic evolution portal, or the portal stein of draconic evolution.
Next to the portal is a monster trap with a box for the whole spell books (ElectroblobsWizardry books) which are always picked up by the users.

The rest is always random.

PS: I'll ask again what exactly people are doing and let me know.

This text was translated with Google

**Comment by Electroblob77** [comment]
On closer inspection, this is the same as #304. If you find any more information, please post it in the discussion there. Thanks.
