### ISSUE TITLE
[4.2.5] The sky darkens when i press F1

### ISSUE THREAD

**Issue by Dan4oby** [Electroblob77/Wizardry#313]
Minecraft version: 1.12.2
Wizardry version: 4.2.5
Environment: Singleplayer

Issue details: 
![2019-11-22_20 53 20](https://user-images.githubusercontent.com/37343749/69548027-a1feb200-0fa7-11ea-9c74-e5ae38a335d7.png)
![2019-11-22_20 53 21](https://user-images.githubusercontent.com/37343749/69548063-b2af2800-0fa7-11ea-9bfb-00d0a7bfff4d.png)
P.S the sky is green due to the resource pack, if you turn it off, then when you press F1 it just darkens

Other mods involved: Optifine HD U F4(everything works well without it, 
therefore, the problem is in the conflict between optifine and
 Electroblob's Wizardry)

**Comment by Electroblob77** [comment]
Thanks for posting this here, it's probably related to #208 but I'm not sure so I'll leave it open for now.

**Comment by Electroblob77** [comment]
Should be fixed by PR #319 (released in version 4.2.6). Please reopen if the issue persists.
