### ISSUE TITLE
Unkillable Wizard

### ISSUE THREAD

**Issue by seoyeaji** [Electroblob77/Wizardry#314]
Minecraft version: 1.12.2 
Wizardry version: 4.2.1
Environment: Singleplayer

I'm trying to find some shrines so i can get some new spell book. I killed the two wizards. However one survived. The thing is i can't deal a damage to him and he can't damage me too. I tried everything to kill him. Suffocating, using summon spells, using a sword. But i just can't kill it.

**Comment by Electroblob77** [comment]
That's weird, I wonder if something went wrong with the save? You may just have to kill it with commands unfortunately (but make a backup of the save first just in case). Alternatively, try going into creative mode and breaking the pedestal block beneath the chest, that will unlock the chest.

Also, it might be worth updating to wizardry 4.2.5 - I doubt that will fix it but it's always best to be on the latest version.

**Comment by Electroblob77** [comment]
Suspected arcane essentials bug caused by op casting radiance storm on the wizard in question. Closing for now, please reopen or make a new issue if this problem persists.
