### ISSUE TITLE
thaumcraft particle color compat

### ISSUE THREAD

**Issue by zacharyki102** [Electroblob77/Wizardry#315]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2  
Wizardry version: 4.1.4 
Environment: single player and server and LAN

Issue details: when ebwizardry is run with thaumcraft all of the particle effects from thaumcraft lose their color (defaulting to white) while it isn't game-breaking, thaumcraft provides many stylish decorations that utilize custom particles and having them all be white takes away from the experience.

Other mods involved: thaumcraft (possibly baubles as it assists thaumcraft)

**Comment by Electroblob77** [comment]
This is almost certainly the same as #208. It's a really difficult thing to pin down so bear with me on it, I will get to the bottom of it eventually.
