### ISSUE TITLE
Mod Crash On Start Up (Forge is newer than 2611)

### ISSUE THREAD

**Issue by Spews** [Electroblob77/Wizardry#316]
Minecraft version: 1.12.2
Wizardry version: 4.2.5
Environment: Singleplayer

Issue details: The game just crash on Start Up, I already tried to change my forge version to older ones but i still having this problem.
**forge-14.23.5.2847** This is the minecraft version im using.

Other mods involved: Anyone

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-92-core.jar)
  CreativePatchingLoader (CreativeCore_v1.9.74_mc1.12.2.jar)
  iceandfire (iceandfire-1.8.3.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  OTGCorePlugin (OTG-Core.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  McLib core mod (mclib-1.0.3-1.12.2.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
  AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 12/5/19 3:26 AM
Description: Initializing game

java.lang.NoSuchMethodError: electroblob.wizardry.spell.Spell.<init>(Lelectroblob/wizardry/constants/Tier;ILelectroblob/wizardry/constants/Element;Ljava/lang/String;Lelectroblob/wizardry/constants/SpellType;ILnet/minecraft/item/EnumAction;ZLjava/lang/String;)V
	at meldexun.ExtraSpells.spells.custom.SpellTimeManipulator.<init>(SpellTimeManipulator.java:22)
	at meldexun.ExtraSpells.init.SpellInit.registerSpells(SpellInit.java:60)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_553_SpellInit_registerSpells_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at meldexun.ExtraSpells.spells.custom.SpellTimeManipulator.<init>(SpellTimeManipulator.java:22)
	at meldexun.ExtraSpells.init.SpellInit.registerSpells(SpellInit.java:60)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_553_SpellInit_registerSpells_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2063492640 bytes (1967 MB) / 3811049472 bytes (3634 MB) up to 6524764160 bytes (6222 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7000m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 122 mods loaded, 121 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                            | Signature                                |
	|:----- |:-------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LCH   | mcp                  | 9.42                     | minecraft.jar                                     | None                                     |
	| LCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
	| LCH   | forge                | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
	| LCH   | creativecoredummy    | 1.0.0                    | minecraft.jar                                     | None                                     |
	| LCH   | otgcore              | 1.12.2 - v8.3            | minecraft.jar                                     | None                                     |
	| LCH   | securitycraft        | v1.8.14.1                | [1.12.2] SecurityCraft v1.8.14.1.jar              | None                                     |
	| LCH   | alcatrazcore         | 1.0.4                    | alcatrazcore-1.0.4.jar                            | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCH   | jei                  | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                         | None                                     |
	| LCH   | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| LCH   | ebwizardry           | 4.2.5                    | ElectroblobsWizardry-4.2.5-MC1.12.2.jar           | None                                     |
	| LCH   | arcane_essentials    | 1.0                      | Arcane Essentials-0.9.2.jar                       | None                                     |
	| LCH   | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCH   | astralsorcery        | 1.10.20                  | astralsorcery-1.12.2-1.10.20.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCH   | mantle               | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LCH   | ctm                  | MC1.12.2-1.0.1.30        | CTM-MC1.12.2-1.0.1.30.jar                         | None                                     |
	| LCH   | roots                | 1.12.2-3.0.21            | Roots-1.12.2-3.0.21.jar                           | None                                     |
	| LCH   | mysticalworld        | 1.12.2-1.5.0             | mysticalworld-1.12.2-1.5.0.jar                    | None                                     |
	| LCH   | chisel               | MC1.12.2-1.0.1.44        | Chisel-MC1.12.2-1.0.1.44.jar                      | None                                     |
	| LCH   | tconstruct           | 1.12.2-2.13.0.171        | TConstruct-1.12.2-2.13.0.171.jar                  | None                                     |
	| LCH   | conarm               | 1.2.5.3                  | conarm-1.12.2-1.2.5.3.jar                         | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | mmdlib               | 1.0.0-rc2                | MMDLib-1.12-1.0.0-rc2.36.jar                      | None                                     |
	| LCH   | thaumcraft           | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                  | None                                     |
	| LCH   | basemetals           | 2.5.0-rc2                | BaseMetals-1.12-2.5.0-rc2.332.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | baseminerals         | 2.5.0-rc2                | BaseMinerals-1.12-2.5.0-rc2.69.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | betteradvancements   | 0.1.0.77                 | BetterAdvancements-1.12.2-0.1.0.77.jar            | None                                     |
	| LCH   | forestry             | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                     | None                                     |
	| LCH   | binniecore           | 2.5.1.198                | binnie-mods-1.12.2-2.5.1.198.jar                  | None                                     |
	| LCH   | binniedesign         | 2.5.1.198                | binnie-mods-1.12.2-2.5.1.198.jar                  | None                                     |
	| LCH   | genetics             | 2.5.1.198                | binnie-mods-1.12.2-2.5.1.198.jar                  | None                                     |
	| LCH   | botany               | 2.5.1.198                | binnie-mods-1.12.2-2.5.1.198.jar                  | None                                     |
	| LCH   | extrabees            | 2.5.1.198                | binnie-mods-1.12.2-2.5.1.198.jar                  | None                                     |
	| LCH   | extratrees           | 2.5.1.198                | binnie-mods-1.12.2-2.5.1.198.jar                  | None                                     |
	| LCH   | guideapi             | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                       | None                                     |
	| LCH   | bloodmagic           | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar                   | None                                     |
	| LCH   | bloodarsenal         | 1.12.2-2.2.0-29          | BloodArsenal-1.12.2-2.2.1-29.jar                  | None                                     |
	| LCH   | bloodmoon            | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                      | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | bloodtinker          | 1.0.5                    | bloodtinker-1.0.5.jar                             | None                                     |
	| LCH   | bonsaitrees          | 1.1.3                    | bonsaitrees-1.1.3-b156.jar                        | None                                     |
	| LCH   | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCH   | chiselsandbits       | 14.33                    | chiselsandbits-14.33.jar                          | None                                     |
	| LCH   | clumps               | 3.1.2                    | Clumps-3.1.2.jar                                  | None                                     |
	| LCH   | codechickenlib       | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux         | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cofhcore             | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar            | None                                     |
	| LCH   | cofhworld            | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | colytra              | 1.2.0.4                  | colytra-1.12.2-1.2.0.4.jar                        | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | playerrevive         | 1.0                      | PlayerRevive_v1.2.28_mc1.12.2.jar                 | None                                     |
	| LCH   | creativecore         | 1.9.9                    | CreativeCore_v1.9.74_mc1.12.2.jar                 | None                                     |
	| LCH   | ptrmodellib          | 1.0.4                    | PTRLib-1.0.4.jar                                  | None                                     |
	| LCH   | props                | 2.6.3                    | Decocraft-2.6.3_1.12.2.jar                        | None                                     |
	| LCH   | dynamictrees         | 1.12.2-0.9.6             | DynamicTrees-1.12.2-0.9.6.jar                     | None                                     |
	| LCH   | harvestcraft         | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zf.jar                   | None                                     |
	| LCH   | dynamictreesphc      | 1.12.2-1.4.2             | DynamicTreesPHC-1.12.2-1.4.2.jar                  | None                                     |
	| LCH   | dynamictreesroots    | 0.1.0                    | dynamicTreesRoots-0.1.0.jar                       | None                                     |
	| LCH   | rustic               | 1.1.1                    | rustic-1.1.1.jar                                  | None                                     |
	| LCH   | dynamictreestc       | 1.12.2-1.4.1e            | DynamicTreesTC-1.12.2-1.4.1e.jar                  | None                                     |
	| LCH   | mclib                | 1.0.3                    | mclib-1.0.3-1.12.2.jar                            | None                                     |
	| LCH   | emoticons            | 0.3.2                    | emoticons-0.3.2-1.12.2-dist.jar                   | None                                     |
	| LCH   | golems               | 7.1.8                    | ExtraGolems-1.12-7.1.8.jar                        | None                                     |
	| LCH   | extra_spells         | 1.0.7                    | ExtraSpells-1.12.2-1.0.7.jar                      | None                                     |
	| LCH   | ezstorage            | 2.5.0                    | ezstorage-2.5.0-[1.12.2].jar                      | None                                     |
	| LCH   | openterraingenerator | v8.3                     | OpenTerrainGenerator-1.12.2 - v8.3.jar            | None                                     |
	| LCH   | farfromhome          | 1.0                      | Far_From_Home-1.12.2-3.5.jar                      | None                                     |
	| LCH   | fastfurnace          | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                      | None                                     |
	| LCH   | fastbench            | 1.7.2                    | FastWorkbench-1.12.2-1.7.2.jar                    | None                                     |
	| LCH   | fencejumper          | 1.0.5                    | fencejumper-1.12-1.0.5.jar                        | None                                     |
	| LCH   | harvest              | 1.12-1.2.7-20            | Harvest-1.12-1.2.7-20.jar                         | None                                     |
	| LCH   | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCH   | llibrary             | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire           | 1.8.3                    | iceandfire-1.8.3.jar                              | None                                     |
	| LCH   | infernalmobs         | 1.7.6                    | InfernalMobs-1.12.2.jar                           | None                                     |
	| LCH   | jeibees              | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                      | None                                     |
	| LCH   | journeymap           | 1.12.2-5.5.5             | journeymap-1.12.2-5.5.5.jar                       | None                                     |
	| LCH   | jeresources          | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar           | None                                     |
	| LCH   | keywizard            | 1.12.2-1.7.1             | keywizard-1.12.2-1.7.1.jar                        | None                                     |
	| LCH   | libraryex            | 1.0.12                   | LibraryEx-1.12.2-1.0.12.jar                       | None                                     |
	| LCH   | magicbees            | 1.0                      | MagicBees-1.12.2-3.1.10.jar                       | None                                     |
	| LCH   | malisiscore          | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                      | None                                     |
	| LCH   | malisisdoors         | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| LCH   | golems_metal         | 7.1.5-1                  | MetalGolems-1.12.2-7.1.5-1.jar                    | None                                     |
	| LCH   | testdummy            | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                        | None                                     |
	| LCH   | morpheus             | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                       | None                                     |
	| LCH   | mowziesmobs          | 1.5.4                    | mowziesmobs-1.5.4.jar                             | None                                     |
	| LCH   | netherex             | 2.0.15                   | NetherEx-1.12.2-2.0.15.jar                        | None                                     |
	| LCH   | neid                 | 1.5.4.4                  | NotEnoughIDs-1.5.4.4.jar                          | None                                     |
	| LCH   | orespawn             | 3.3.1                    | OreSpawn-1.12-3.3.1.172.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | desertcraft          | 1.12.2a                  | Pam's DesertCraft 1.12.2b.jar                     | None                                     |
	| LCH   | getalltheseeds       | 1.12a                    | Pam's Get all the Seeds! 1.12a.jar                | None                                     |
	| LCH   | llamamilking         | 1.12.2b                  | Pam's Llama Milking 1.12.2b.jar                   | None                                     |
	| LCH   | sheepmilking         | 1.12.2b                  | Pam's Sheep Milking 1.12.2b.jar                   | None                                     |
	| LCH   | squidmilking         | 1.12.2a                  | Pam's Squid Milking 1.12.2a.jar                   | None                                     |
	| LCH   | pamscookables        | 1.1                      | pamscookables-1.1.jar                             | None                                     |
	| LCH   | pamsimpleharvest     | 2.0.0                    | pamsimpleharvest-2.0.0.jar                        | None                                     |
	| LCH   | patchouli            | 1.0-20                   | Patchouli-1.0-20.jar                              | None                                     |
	| LCH   | potioncore           | 1.8_for_1.12.2           | PotionCore-1.8_for_1.12.2.jar                     | None                                     |
	| LCH   | thermalfoundation    | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | thermalexpansion     | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | redstonearsenal      | 2.6.3                    | RedstoneArsenal-1.12.2-2.6.3.18-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | redstonepaste        | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                    | None                                     |
	| LCH   | redstonerepository   | 1.3.2                    | RedstoneRepository-1.12.2-1.4.0-dev-universal.jar | None                                     |
	| LCH   | t3s4ebw              | 1.0                      | SeedsForWizardry 1.0 For MC Forge 1.12.2.jar      | None                                     |
	| LCH   | spartanweaponry      | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar             | None                                     |
	| LCH   | spartanbm            | 0.3                      | spartanbm-0.3.jar                                 | None                                     |
	| LCH   | spartanfire          | 0.07                     | spartanfire-0.07.jar                              | None                                     |
	| LCH   | spartanshields       | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                   | None                                     |
	| LCH   | storagedrawers       | 1.12.2-5.4.0             | StorageDrawers-1.12.2-5.4.0.jar                   | None                                     |
	| LCH   | tcinventoryscan      | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar        | None                                     |
	| LCH   | thaumicjei           | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                    | None                                     |
	| LCH   | thaumictinkerer      | 1.12.2-5.0-353c71c       | thaumictinkerer-1.12.2-5.0-353c71c.jar            | None                                     |
	| LCH   | tcomplement          | 1.12.2-0.4.2             | TinkersComplement-1.12.2-0.4.2.jar                | None                                     |
	| LCH   | tinkersforging       | 1.1.4                    | tinkersforging-1.1.4.jar                          | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCH   | golems_tcon          | 7.1.5-0                  | TinkersGolemsAddon-1.12-7.1.5-0.jar               | None                                     |
	| LCH   | tinkersjei           | 1.2                      | tinkersjei-1.2.jar                                | None                                     |
	| LCH   | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
	| LCH   | tinymobfarm          | 1.0.5                    | TinyMobFarm-1.12.2-1.0.5.jar                      | None                                     |
	| LCH   | tombstone            | 3.6.2                    | tombstone-3.6.2-1.12.2.jar                        | None                                     |
	| LCH   | travellersbackpack   | 1.0.20.20                | TravellersBackpack-1.12.2-1.0.20.20.jar           | None                                     |
	| LCH   | waystones            | 4.0.72                   | Waystones_1.12.2-4.0.72.jar                       | None                                     |
	| LCH   | immersiveengineering | 0.12-92                  | ImmersiveEngineering-0.12-92.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCH   | mysticallib          | 1.12.2-1.4.0             | mysticallib-1.12.2-1.4.0.jar                      | None                                     |
	| UD    | mclib_core           | 1.0.3                    | minecraft.jar                                     | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-0.12-92-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CreativePatchingLoader (CreativeCore_v1.9.74_mc1.12.2.jar)
  
iceandfire (iceandfire-1.8.3.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
McLib core mod (mclib-1.0.3-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
  c4.colytra.asm.ElytraTransformer
AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
Plugin (NotEnoughIDs-1.5.4.4.jar)
  ru.fewizz.neid.asm.Transformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.41' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)
		- ToolLevelingPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

	Launched Version: forge-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.41, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz

**Comment by Tora-B** [comment]
Your copy of Extra Spells is out of date and not compatible with the latest version of Wizardry.

**Comment by Electroblob77** [comment]
Yep, update extra spells to the latest version and it will fix the issue.
