### ISSUE TITLE
Using the "elements" tag of the "ebwizardry:random_spell" function in the loot table causes a crash when opening the chest.

### ISSUE THREAD

**Issue by belathus** [Electroblob77/Wizardry#32]
Minecraft version: 1.12.2
Wizardry version: 4.1.1
Environment: Singleplayer

### Issue details:
Crash when opening a chest with a modified loot table using the "elements" tag:
```
{"function": "ebwizardry:random_spell", "elements":["necromancy"], "tiers":["basic"]}
```
For reference, I'm using LootTweaker to modify the loot tables. I tested the loot table after restarting the world by using a command:
```
/blockdata ~ ~ ~ {LootTable:"twilightforest:structures/tower_library/tower_library"}
```
Replace the "~ ~ ~" with the coordinates of a chest, of course. Omitting the "elements" tag seems to work fine.

### Other mods involved:
LootTweaker
The script I'm using is here, with the relevant lines commented out: https://github.com/belathus/Wanderlust-Renewed/blob/master/scripts/loot/twilightforest/lich_library.zs

### Link to crash report (if applicable):
https://gist.github.com/belathus/cef1d7228dc2278331693e6f98082d31

**Comment by Electroblob77** [comment]
Well that was very stupid of me, I've managed to write `tiers` instead of `elements` on that line of code. Thanks for reporting this, I'll get it fixed for the next patch.

**Comment by belathus** [comment]
Appreciated. I'm hoping to put ice mage's spells in the snow queen's palace. This'll be fun.
