### ISSUE TITLE
Evil wizard spawning

### ISSUE THREAD

**Issue by emdomanus** [Electroblob77/Wizardry#321]
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: Server

Issue details:

Other mods involved: none

I think there should be an option to limit what dimension evil wizards spawn in because if you go to the end there are just a ton of wizards which i don't really like.

**Comment by Electroblob77** [comment]
Please update wizardry to the latest version (4.2.5), an option was added in 4.2 to do exactly this.
