### ISSUE TITLE
Antique atlas marker names names not displaying properly

### ISSUE THREAD

**Issue by Baryons314** [Electroblob77/Wizardry#323]
Minecraft version: 1.12.2
Wizardry version: 4.2.2
Environment: Singleplayer

Issue details: I added antiqueatlas, and the coloured texture pack for it, after installing ebwizardry. Of course, the already generated structures don't show up as markers, but all of the markers have strange names. Hovering over an obelisk marker, for example shows "intergration.antiqueatlas.ebwizardry:obelisk".
Other mods involved: Antique Atlas
![Capture](https://user-images.githubusercontent.com/58947967/70921452-95a8ca80-2024-11ea-92b5-b89403421e99.PNG)

**Comment by Electroblob77** [comment]
That's weird, the translation keys should be there. Make sure you've updated to the latest version (4.2.5), and can you post your antique atlas version?

**Comment by Baryons314** [comment]
yeah, i'm using 4.2.5. I'm using the latest version of antique atlas too, 4.6.3.

**Comment by Electroblob77** [comment]
It's fine in my dev environment. Perhaps this is caused by new versions of antique atlas?

**Comment by Electroblob77** [comment]
Confirmed, Antique Atlas changed how it handles translation keys internally which caused any characters other than `A-Z`, `a-z` or `.` to render the translation invalid. I'll get this fixed for the next patch.
