### ISSUE TITLE
Make smoke bomb apply blindness to mobs as well

### ISSUE THREAD

**Issue by Jackiecrazy** [Electroblob77/Wizardry#324]
This is a simple compatibility thing with Dynamic Stealth. Since DS adds an in-depth sight system, mobs will still show that they are attacking you on DS's popup HUD, even though they're rendered docile by mind trick and smoke bomb. Applying blindness would stop that, and doesn't break anything.

**Comment by Electroblob77** [comment]
Will do, thanks.
