### ISSUE TITLE
Crash caused by wizard bubble particle

### ISSUE THREAD

**Issue by AlexModGuy** [Electroblob77/Wizardry#325]
Minecraft version: 1.12.2
Wizardry version: 4.2.5
Environment: Singleplayer

Issue details: The wizard trap? thing that spawns hostile wizards when players walk near it has bricked my save by crashing every time I load my world. The crash is due to a particle effect.

Other mods involved: Mc.Eternal Modpack

Link to crash report (if applicable): https://gist.github.com/Alex-the-666/5e3f097918b901a5177957bf3f885857

**Comment by Electroblob77** [comment]
Looks like a problem with the arcane essentials addon, I'll forward it to that issue tracker.

**Comment by Electroblob77** [comment]
Fixed in the latest version of Arcane Essentials
