### ISSUE TITLE
Arcane Workbench Crash

### ISSUE THREAD

**Issue by slidingmike** [Electroblob77/Wizardry#328]
Minecraft version: 1.12.2  
Wizardry version: 4.2.6
Environment: Server 

Issue details: After recently releasing our modpack via the Twitch Client with the new 4.2.6 update, I have a user reporting a fatal error occuring and being kicked from the server after trying to recharge something in an Arcane Workbench.

The user has tested two difference benches in two different areas. Doesn't matter if it's a wand or armor, but clicking the check mark in the lowr right of the gui seems to cause the error. 

Other mods involved: At the time of release, Extra Spells was also updated. 

Link to crash report (if applicable): https://github.com/BreakfastCraft/Spilled-Juice-Modpack/issues/161 has the latest.log attached from when the issue occurs. 

Please let me know if there's any further information I can gather to help investigate. I can work with the user to gather information client side, as well as backend on the server.

**Comment by Electroblob77** [comment]
I think what's happened here is something has gone wrong with the spell data, though I'm not sure what this has to do with the arcane workbench since that crash report refers to a player logging in. Do you have Arcane Essentials installed, by any chance? There is a bug in that addon that can cause issues like this.

**Comment by NiSiSuinegEht** [comment]
It appears that some interaction with Extra Spells is causing the crash.  Removing Arcane Essentials had no effect, but Extra Spells did.

Edit:  We were running Extra Spells v1.1.3, this issue is fixed in 1.1.4 that just came out a couple days ago.

**Comment by slidingmike** [comment]
Appreciate you taking a look Electroblob77. I'll close this issue.
