### ISSUE TITLE
ebwizardry.cfg spellBookDropChance setting does not exist

### ISSUE THREAD

**Issue by mcfensi** [Electroblob77/Wizardry#329]
> # The chance for mobs to drop a spell book when killed. The greater this number, the more often they will drop. Set to 0 to disable spell book drops. Set to 200 for guaranteed drops.
> I:spellBookDropChance=

There were setting options in the previous 4.1.4 version, why is it not in the new version now?I don't want monsters to drop spellbooks in the server

**Comment by Tora-B** [comment]
It's done using loot tables now, which is significantly more customizable and powerful, but also more complex to configure. See https://github.com/Electroblob77/Wizardry/blob/1.12.2/src/main/resources/assets/ebwizardry/loot_tables/entities/mob_additions.json

**Comment by mcfensi** [comment]
Thank you
