### ISSUE TITLE
Wand Upgrade books

### ISSUE THREAD

**Issue by TrueWhtNinja** [Electroblob77/Wizardry#330]
Based on a recently closed issue #264; I made the same mistake thinking that it should be able to upgrade "any" wand.  Can you add more description on the upgrade books to say something along the lines of "will upgrade a sufficiently powerful Novice wand to an Apprentice wand" etc, etc.  I know it is in the Handbook but people are dumb and don't read the in-game manual completely.

**Comment by Electroblob77** [comment]
Good idea, I will update the description.
