### ISSUE TITLE
Server crash when shooting spells into Betweenlands portal

### ISSUE THREAD

**Issue by bigenergy** [Electroblob77/Wizardry#334]
Minecraft version: 1.12.2
Wizardry version: 4.2.7 
Environment: Server (spongeforge-1.12.2-2838-7.1.8)

Issue details: Need to be in the world the betweenlands and activate the rod (with any spell) into the portal betweenlands -  server freezes and crashes

Other mods involved: TheBetweenlands-3.5.4

Link to crash report (if applicable): https://pastebin.com/DtJPM1zM and https://pastebin.com/pu6fcXyh

**Comment by Electroblob77** [comment]
Not entirely sure what's going on there, wizardry isn't directly mentioned in the stacktrace. I'll have to try this myself at some point and figure out what's going wrong.
