### ISSUE TITLE
about fireballs bug

### ISSUE THREAD

**Issue by Hokorizero** [Electroblob77/Wizardry#335]
Minecraft version: 1.12.2 
Wizardry version: 4.2.7 
Environment: Singleplayer

Issue details: ![20200106112748.png](https://i.loli.net/2020/01/06/jRhLJe4lVq1DQnv.png)
![20200106112600.png](https://i.loli.net/2020/01/06/keo64h8d9PAcWaj.png)
look at this two pictures.I can't unlock the schedule of thuamcraft
because the fireballs' texture was changed

Other mods involved: thaumcraft

**Comment by Electroblob77** [comment]
Thanks, various people have pointed this out. I will add the parrying behaviour to the custom fireballs, which should fix the problem. In the meantime, you can temporarily disable the `replaceVanillaFireballs` option in the config to allow you to use vanilla fireballs.
