### ISSUE TITLE
Time Stop + Relogging = Invincibility on multiplayer

### ISSUE THREAD

**Issue by CammiePone** [Electroblob77/Wizardry#336]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.7
Environment: Server

Issue details: So apparently if you stop time locally with Peculiar Pocketwatch and Slow Time on a player, and then that player logs out and logs back in when the effect is over, they become unable to break blocks and are unable to take damage until someone casts Slow Time again. We were able to repeat it several times and it's so weird.

Other mods involved: Baubles

**Comment by Electroblob77** [comment]
Okay, I think I know what's going on there. I'll see what I can do, thanks.
