### ISSUE TITLE
Make Magic Protection protect against vanilla magic damage

### ISSUE THREAD

**Issue by CammiePone** [Electroblob77/Wizardry#337]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.7
Environment: Singleplayer/Server

Issue details: Magic Protection doesn't protect against vanilla magic damage. Tested it by throwing splash potions of harming 2 at my feet, and it didn't make a difference with no armour or armour with Magic Protection 4.

**Comment by Jonson26** [comment]
You could argue, that potion damage is not inherently magic damage per se. I'd rather like to think of it as of various poisons and acids, that are being thrown around in vials. Though such a mechanic would provide the player with an opportunity to somewhat counter witch attacks.

**Comment by CammiePone** [comment]
> 
> 
> You could argue, that potion damage is not inherently magic damage per se. I'd rather like to think of it as of various poisons and acids, that are being thrown around in vials. Though such a mechanic would provide the player with an opportunity to somewhat counter witch attacks.

The potion of harming is one of the few ways magic damage is possible, and it's the main damage dealer that Witches use. The other ways to deal magic damage are Dragon Fireballs and Evoker Fangs. It's magic damage that doesn't get reduced by Magic Resistance.

**Comment by Electroblob77** [comment]
I believe this is intended behaviour. I might change it though, potentially that may make more sense.
