### ISSUE TITLE
Crash during the first loading phase when Baubles is installed

### ISSUE THREAD

**Issue by BassTheFish** [Electroblob77/Wizardry#346]
Minecraft version: 1.12.2
Wizardry version: 4.2.7 
Environment: N/A. The intent is for a private server, but the game won't launch at all.

Issue details: I was gonna test the mod out in single player, so I booted the game up and it refused to get past the first loading phase. It only happens with Baubles installed, but I discovered it gets further in the loading process if B:baublesIntegration is set to false.

Other mods involved: It's a small modpack with maybe 50 mods in it, but the only thing that causes it to crash is including Baubles ver1.5.2.

Here's links to the crash reports:

[(Integration off)crash-2020-01-25_22.06.51-client.txt](https://github.com/Electroblob77/Wizardry/files/4113128/Integration.off.crash-2020-01-25_22.06.51-client.txt)
[(Integration on)crash-2020-01-25_22.01.10-client.txt](https://github.com/Electroblob77/Wizardry/files/4113129/Integration.on.crash-2020-01-25_22.01.10-client.txt)

**Comment by BassTheFish** [comment]
I don't know how to add tags, sadly, but It should have the Compatability and Crash tags on it

**Comment by Electroblob77** [comment]
`at com.oblivioussp.spartanweaponry.item.ItemQuiverBase.getBaubleType(ItemQuiverBase.java:269)`
`at electroblob.wizardry.integration.baubles.WizardryBaublesIntegration.init`
This is clearly happening to any mod that adds bauble items. Looking at the reports, it would appear that certain bauble types (body and charm in this case) somehow don't exist.
Obviously it's going to get further if you disable wizardry's baubles features (which is what that option does), but presumably that's what made it crash with spartan weaponry instead.
You'd be better off reporting this to the Baubles issue tracker, though I'm not sure how active it is nowadays. Also try launching with just Baubles and check all the slots exist in your inventory.
