### ISSUE TITLE
Server crash after using a spell.

### ISSUE THREAD

**Issue by BlueYoshi68** [Electroblob77/Wizardry#347]
Minecraft version: 1.12.2
Wizardry version: 4.2.7
Environment: Server

Mods involved: Arcane addons, Extra Spells. Latest version

Issue details: Server crashed after using the Lighting Vortex spell. Server won't start back up now.

Link to crash report (if applicable): https://pastebin.com/pnYtBijd

**Comment by Electroblob77** [comment]
That spell is from arcane essentials, please report it to their issue tracker instead. In this case, it's already been reported https://github.com/FavouriteDragon/Arcane-Essentials/issues/12.
