### ISSUE TITLE
Crash while using many spells after each other.

### ISSUE THREAD

**Issue by QboiDev** [Electroblob77/Wizardry#348]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.7 [change as necessary]
Environment: Singleplayer

Issue details: Using many spells after each other. After using "Slow Time" (Skeleton was invincible, because other bug #336). 

Other mods involved: CoFH Core 4.6.3.27

Link to crash report: https://paste.dimdev.org/fanicorake.mccrash

Sorry, for my bad English.

**Comment by Electroblob77** [comment]
Hopefully this is just a side-effect of #336. I should get that fixed soon, and then see if this issue persists. Thanks for reporting.

**Comment by Electroblob77** [comment]
Assuming the above is true, this should now be fixed since #336 is fixed. Please reopen if the issue persists in the latest version.
