### ISSUE TITLE
Request: command to spawn wizards who want to protect blocks.

### ISSUE THREAD

**Issue by belathus** [Electroblob77/Wizardry#35]
I'm considering making custom wizard towers using Recurrent Complex. It'll be fine for the evil wizards, but I can't think of a way to make normal wizards protective of their new home.

I did see that they have a list of blocks they protect in their NBT tag, but since it is a data-packed tag, I can't think of any way to apply a list of protected blocks using a script/command block. I'm thinking I might need a custom spawn command specifically for this.

Thanks!

**Comment by Electroblob77** [comment]
You make a good point... I'm just not sure how that would be done. It might be better for wizardry to interact with recurrent complex in some way. When I get to cross-mod integration I'll install recurrent complex and see what I can figure out.

**Comment by Electroblob77** [comment]
For the next release, I've changed the data format in the tag to be a list of X, Y, Z compound tags instead of a list of packed long tags. Hopefully they can then be interacted with via scripts.

**Comment by Electroblob77** [comment]
The above change has been implemented in the 4.2.0 release.
