### ISSUE TITLE
Vanilla fix alerts me of an error.

### ISSUE THREAD

**Issue by soupcant95** [Electroblob77/Wizardry#350]
Minecraft version: 1.12.2
Wizardry version: 4.2.8
Environment: Singleplayer

Issue details: Nothing went wrong. I just loaded my singleplayer mod and a vanillafix popup alerted me of an error. I just wanted to send this to you all so you can find bugs :) 

Other mods involved: Wizardry

Link to crash report: https://paste.dimdev.org/fipilexiye.mccrash

**Comment by Electroblob77** [comment]
Duplicate of #253. This is a bug in the arcane essentials addon.
