### ISSUE TITLE
Fireballs problem

### ISSUE THREAD

**Issue by SoyJetixXD** [Electroblob77/Wizardry#351]
Minecraft version: 1.12.2 
Wizardry version: 4.2.8 
Environment: Server (SpongeForge)

Issue details: Hi, I am playing with my friends on a Mod server with 45 mods. As we saw that the fireballs were different from the originals, we decided to remove them thanks to the configuration of the mod, but the problem comes after deactivating that option, every time a blaze or a dispenser will throw Fireballs an error comes out. We tried to verify it alone, and we removed all the mods, but we realized that the problem does not come from any of the mods and it is on the server, because it works great alone.It is solved when one goes out and re-enters the server, but when we go to the nether we cannot leave and enter every so often.
That error causes the FPS to drop.

![2020-02-04_18 40 22](https://user-images.githubusercontent.com/60457424/73797613-90434300-477e-11ea-9646-8c59aa433ca8.png)
![2020-02-04_18 41 26](https://user-images.githubusercontent.com/60457424/73797615-920d0680-477e-11ea-993c-b0e77ea3ccd2.png)
![2020-02-04_18 47 38](https://user-images.githubusercontent.com/60457424/73797854-1cee0100-477f-11ea-8afa-bbaf58b87eb7.png)
![2020-02-04_18 52 29](https://user-images.githubusercontent.com/60457424/73798016-8d951d80-477f-11ea-86ad-9796ecb8473d.png)

**Comment by Electroblob77** [comment]
That's a lot of particles you've got there! That must be why the FPS is dropping. It may be because of the addition of fireball parrying in 4.2.8, I'll have to have a look at that. In the meantime, you should be able to disable blazes and dispensers shooting the custom fireballs in the config.

**Comment by SoyJetixXD** [comment]
Hi, Your mod is my server's favorite, most of the members asked to place it, I only found that little bug, but the problem only begins by deactivating the fireballs to place the normal ones, meanwhile we will activate that option until we find a solution.
Thank you for reading.

**Comment by bigenergy** [comment]
@Electroblob77 can you fix this or enter an option in the config to turn it off?

**Comment by Electroblob77** [comment]
Okay, I think I know what's going on here. That config option is currently only server-side, but it should be synchronised. I will change this, but in the meantime you should be able to work around it by making sure all players have disabled that option in their configs too.
