### ISSUE TITLE
Metadata on custom wizard trade currency items?

### ISSUE THREAD

**Issue by Not-February** [Electroblob77/Wizardry#353]
**Minecraft versions:** Any, though I am currently using 1.12.2
**Wizardry version:** 4.2.8

**Question details:** In the config field for adding new items to things wizards might ask for in trades(i.e. gold and emeralds by default), I can't help but notice that there doesn't seem to be a documented way to use items that are differentiated only by metadata.

For example, a coin item from a theoretical given mod might have different variants baked into the same item; let's call it "examplemod:coin". It has copper, silver, and gold variants, which are all registered in that same item - the silver and gold coins are differentiated by adding metadata to the base copper coin(examplemod:coin:1 for silver and examplemod:coin:2 for gold in this case).

Without being able to specify the metadata in the config, it would be impossible to use any coin other than copper in this scenario - in the same way that it would be impossible to add charcoal specifically to this trade list and not coal, because charcoal is a metadata variant of coal.

Is there a way to specify metadata in this config field that just isn't immediately obvious, or is it actually impossible?

If it's _not_ currently possible, I'd like to request a way to differentiate metadata in this config field - and possibly any other fields where items might be blacklisted/whitelisted from certain functionality as necessary.

**Comment by Electroblob77** [comment]
I don't think it is possible, it's a bit of an oversight on my part so thanks for pointing it out. I will get this added to all the item options for the next update.
