### ISSUE TITLE
Font of Mana not working

### ISSUE THREAD

**Issue by EpicOverKill567** [Electroblob77/Wizardry#355]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.2.8 
Environment: LAN game/Server

Issue details: When I use font of mana I dont seem to have any decrease to cooldown times. I am using it with a wand of healing and even with font of mana 2 my cooldowns are the same.

Other mods involved: I am using Arcane Essentials as well as roguelike adventures and dungeons modpack

**Comment by Electroblob77** [comment]
Right... I'll test it, I don't see why this wouldn't work since it definitely worked the last time I checked, and it's unlikely that any mods would interfere with it.

**Comment by Andri92** [comment]
I'm seeing this in MCEternal v1.3.5.3 too.

**Comment by Electroblob77** [comment]
Recently got reported again as #477, will be fixed next update. Check that issue for further updates.
