### ISSUE TITLE
Another Modded problem...

### ISSUE THREAD

**Issue by TEM187** [Electroblob77/Wizardry#358]
I keep getting this crash whenever a Necromancer tries casting a spell at me. All other evil-wizards are fine. Any way to fix this. Would love to use this mod, or remove another if need be to get it working out. God Bless. 

Crash report: 
[crash-2020-02-10_20.42.27-server.txt](https://github.com/Electroblob77/Wizardry/files/4184041/crash-2020-02-10_20.42.27-server.txt)

**Comment by TEM187** [comment]
Nevermind. Upon closer inspection, it seems Arcane Essentials is the culprit. Carry one being awesome.

**Comment by Electroblob77** [comment]
Yeah, that's arcane essentials. And thanks!
