### ISSUE TITLE
Wizardry Guide Book

### ISSUE THREAD

**Issue by JacksonWhite502** [Electroblob77/Wizardry#36]
Minecraft version: 1.12.2   
Wizardry version: 4.1.1 
Environment: Server

Issue details: Me and my friend started a modded survival server and we added the mod and in the beginning we could open the book fine but after a while every time we try and open it, it crashes our game.

Other mods involved: Rouge like Dungeons, Bookshelf, AbyssalCraft,Hunter Dimension, Industrial Craft and Buildcraft

Link to crash report: https://pastebin.com/9sY7YZh9

**Comment by Electroblob77** [comment]
Could you tell me what your keybindings are for the next/previous spell keys?

**Comment by JacksonWhite502** [comment]
Mouse5 and Mouse4

**Comment by Electroblob77** [comment]
Ok so they're not keyboard keys, that makes sense. The wizard handbook GUI uses `org.lwjgl.input.Keyboard` to look up the key names but obviously that doesn't work for mouse buttons (I'm not sure my mouse even _has_ a button 4 and 5), so it crashes. I'll get that fixed for the next update.
