### ISSUE TITLE
Game crashes if legion skeletons are killed using Forest of Thorns while Cofh Core is installed.

### ISSUE THREAD

**Issue by AdamEternal** [Electroblob77/Wizardry#362]
Minecraft version: 1.12.2
Wizardry version: 4.2.8
Environment: Singleplayer

Issue details: While Cofh Core was installed, with no other mods aside from Redstone Flux 2.1.0 (required for Cofh Core, but did not on its own cause this crash) and Electroblob's Wizardry, if a skeleton summoned with Summon Skeleton Legion died to thorns created with Forest of Thorns, the game would crash.

Other mods involved: Cofh Core 4.6.3

Link to crash report: https://pastebin.com/raw/qv5fkWRp

**Comment by Electroblob77** [comment]
Ok, I'll look into it, thanks.
