### ISSUE TITLE
Spanish handbook translation crashes the game

### ISSUE THREAD

**Issue by SoyJetixXD** [Electroblob77/Wizardry#365]
Minecraft version: 1.12.2  
Wizardry version: 4.2.9 
Environment: Opening The Launcher

Issue details: Hello, We see each other again, I have installed the latest version of the Mod, I added it to my Modpack (where I deleted everything from the config folder.)
But the problem is when starting the Minecraft Launcher, the Vanilla Fix mod helped me.
Postscript: Do not modify anything of the mod.

Other mods involved: Vanilla Fix, and 51 another mods.

Link to crash report : https://paste.dimdev.org/cajuhitixe.mccrash
![CRASH REPORT](https://user-images.githubusercontent.com/60457424/75125449-2e8e3e80-5683-11ea-914d-27fcfd87f090.png)

**Comment by Electroblob77** [comment]
Apologies, this is an error introduced by the spanish handbook translations added in 4.2.9. Should be fixed soon.
