### ISSUE TITLE
Which Class?

### ISSUE THREAD

**Issue by Master-Henry2006** [Electroblob77/Wizardry#367]
Minecraft version: 1.12.2 
Wizardry version: 4.2.5

Question details: Which class are the magic wands? Classes like classTool.
Thanks

**Comment by Tora-B** [comment]
Did you look here?: https://github.com/Electroblob77/Wizardry/blob/1.12.2/src/main/java/electroblob/wizardry/item/ItemWand.java

**Comment by Electroblob77** [comment]
Do you mean Java class? If not, what do you mean?

**Comment by Master-Henry2006** [comment]
I mean the type of class. Like a pickaxe has the class ClassTool and a bow ClassBow.

**Comment by Electroblob77** [comment]
Wands use the `ItemWand` class, which extends `Item`. They are not tools, bows, swords or anything else.

**Comment by Master-Henry2006** [comment]
Hi Electroblob,
I looked for the class itemwand, because I am editing a config file and I
need this class. Thanks for your help. I hope I wasn't too annoying. Sorry
for my bad English, and I hope it wasn't too unintelligible.
Thanks for your help again.
