### ISSUE TITLE
Ice Spikes spell crash

### ISSUE THREAD

**Issue by DeliciousTea** [Electroblob77/Wizardry#371]
Minecraft version: 1.12.2
Wizardry version: 4.2.9
Environment: Server

Issue details: Player of mine used the Ice Spikes spell, I'm not sure what other specifics may have happened, but the server crashed and threw up this error, then would crash any time he loaded the chunk.

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable):  https://hastebin.com/xocojizewe.http

**Comment by Electroblob77** [comment]
~~The link you posted has nothing in it...~~

Edit: okay now it does, that was weird. I'll have a look at it.
