### ISSUE TITLE
[1.12.2] Runestone obelisks seem to only spawn on top of the nether bedrock roof

### ISSUE THREAD

**Issue by bshawvt** [Electroblob77/Wizardry#372]
They seem to spawn just fine in the overworld, however once I enter the nether I can't find them anywhere except above the bedrock roof. 
I've set them to the highest chance to spawn to confirm and was unable to locate them anywhere except on the roof.

**Comment by Electroblob77** [comment]
Ah... yeah I think I might know why that is, it's looking for somewhere it can see the sky. I'll see what I can do, thanks.
