### ISSUE TITLE
Minecraft Launcher crashes bc of EBW mod.

### ISSUE THREAD

**Issue by prohitman** [Electroblob77/Wizardry#374]
Minecraft version: 1.12.2
Wizardry version: 4.2.9
Environment: Client, maybe.

Issue details: so my friend and I wanted to make a modded server with forge version : 14.23.5.2838, but, for some reason, whenever my friend adds this mod, the minecraft launcher crashes. Even if he singled out this mod.

Other mods involved: Lots, but the problem persists even with out any mod except this one.

Link to crash report https://pastebin.com/u5guPg66

**Comment by Electroblob77** [comment]
Duplicate of #365.

**Comment by Electroblob77** [comment]
Duplicate of #365.
