### ISSUE TITLE
About possession spells bugs and some suggestions

### ISSUE THREAD

**Issue by Hokorizero** [Electroblob77/Wizardry#376]
Minecraft version: 1.12.2
Wizardry version: 4.2.9 
Environment: Server

when i used the possession spells,I found two bugs.Look at this two gifs.
![bugs1](https://s1.ax1x.com/2020/03/12/8VcRoj.gif)
![bugs2](https://s1.ax1x.com/2020/03/12/8ZS9i9.gif)

suggestion：Can you add the prohibited or enabled features of the accessory.Like the Peculiar Pocketwatch,I don't want my players to use it in the server

**Comment by Electroblob77** [comment]
One thing per issue next time please!

Bug 1: That's very weird, I will see if I can reproduce it.  
Bug 2: Easy enough to fix, I should just be able to stop players picking up items while possessing.

Suggestion: That's on my list of things to add, it may or may not make it into the next patch but it will get done. Thanks.
