### ISSUE TITLE
Integration for the Antique Atlas is crashing the game

### ISSUE THREAD

**Issue by Tegamin** [Electroblob77/Wizardry#378]
Every time I move my view to the place where wizard tower exsits on the atlas(or opening the atlas with the wizard tower exsits on sight) , the game will crash. It's fine when I only view the small map on the top right.
Here is the crash report , would you please help me figure out the problem? I really love your mod!
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2020-03-17 16:20:55 CST
Description: Rendering screen

java.util.IllegalFormatConversionException: d != java.lang.String
    at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source)
    at java.util.Formatter$FormatSpecifier.printInteger(Unknown Source)
    at java.util.Formatter$FormatSpecifier.print(Unknown Source)
    at java.util.Formatter.format(Unknown Source)
    at java.util.Formatter.format(Unknown Source)
    at java.lang.String.format(Unknown Source)
    at hunternif.mc.atlas.util.Log.lambda$log$0(Log.java:16)
    at org.apache.logging.log4j.util.LambdaUtil.getMessage(LambdaUtil.java:91)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1982)
    at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1845)
    at org.apache.logging.log4j.spi.AbstractLogger.log(AbstractLogger.java:1649)
    at hunternif.mc.atlas.util.Log.log(Log.java:16)
    at hunternif.mc.atlas.util.Log.warn(Log.java:28)
    at hunternif.mc.atlas.client.gui.GuiAtlas.renderMarker(GuiAtlas.java:875)
    at hunternif.mc.atlas.client.gui.GuiAtlas.drawScreen(GuiAtlas.java:739)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Screen render details --
  Screen name: hunternif.mc.atlas.client.gui.GuiAtlas
  Mouse location: Scaled: (285, 207). Absolute: (571, 313)
  Screen size: Scaled: (625, 364). Absolute: (1250, 727). Scale factor of 2

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Tegami'/69, l='MpServer', x=-2011.37, y=83.00, z=1789.75]]
  Chunk stats: MultiplayerChunkCache: 169, 169
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (80,64,248), Chunk: (at 0,4,8 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 5172135 game time, 6487519 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 97 total; [EntityVillager['村民'/112645, l='MpServer', x=-1998.69, y=70.00, z=1750.08], EntityCreeper['爬行者'/115719, l='MpServer', x=-2056.50, y=39.00, z=1858.50], EntityVillager['村民'/112646, l='MpServer', x=-1985.50, y=69.00, z=1745.57], EntityCreeper['爬行者'/115721, l='MpServer', x=-2054.50, y=39.00, z=1859.50], EntityCreeper['爬行者'/115720, l='MpServer', x=-2057.24, y=39.00, z=1862.76], EntitySheep['羊'/112651, l='MpServer', x=-1990.41, y=69.00, z=1743.31], EntitySheep['羊'/112653, l='MpServer', x=-1995.37, y=72.00, z=1740.79], EntitySheep['羊'/112652, l='MpServer', x=-2001.17, y=74.00, z=1740.70], EntitySheep['羊'/112654, l='MpServer', x=-1989.10, y=72.00, z=1747.41], EntitySpider['蜘蛛'/115740, l='MpServer', x=-2089.50, y=18.00, z=1760.50], EntityBat['蝙蝠'/115744, l='MpServer', x=-2080.07, y=28.42, z=1783.68], EntitySpider['蜘蛛'/115249, l='MpServer', x=-2051.50, y=14.00, z=1770.50], EntitySheep['羊'/114759, l='MpServer', x=-1984.67, y=73.00, z=1852.75], EntitySheep['羊'/114758, l='MpServer', x=-2020.50, y=64.00, z=1841.75], EntitySheep['羊'/114761, l='MpServer', x=-1987.50, y=73.00, z=1853.50], EntitySheep['羊'/114760, l='MpServer', x=-1987.50, y=73.00, z=1854.50], EntityPlayerSP['Tegami'/69, l='MpServer', x=-2011.37, y=83.00, z=1789.75], EntityVillager['村民'/113265, l='MpServer', x=-2002.67, y=66.00, z=1751.50], EntityVillager['村民'/113264, l='MpServer', x=-2003.55, y=70.00, z=1749.28], EntityVillager['村民'/113266, l='MpServer', x=-1998.49, y=67.00, z=1754.58], EntityZombieVillager['僵尸村民'/115834, l='MpServer', x=-2012.49, y=58.00, z=1780.06], EntityCreeper['爬行者'/114859, l='MpServer', x=-2033.50, y=40.00, z=1745.50], EntitySkeleton['骷髅'/114351, l='MpServer', x=-2090.50, y=17.00, z=1726.50], EntityCreeper['爬行者'/115394, l='MpServer', x=-2060.50, y=24.00, z=1755.50], EntitySheep['羊'/111823, l='MpServer', x=-1962.55, y=69.00, z=1784.24], EntitySheep['羊'/111822, l='MpServer', x=-1972.20, y=68.00, z=1772.49], EntitySheep['羊'/111825, l='MpServer', x=-1955.83, y=69.00, z=1783.19], EntitySheep['羊'/111824, l='MpServer', x=-1960.68, y=68.00, z=1767.77], EntityVillager['村民'/111826, l='MpServer', x=-1978.50, y=69.00, z=1740.50], EntityVillager['村民'/113367, l='MpServer', x=-2011.38, y=69.94, z=1742.73], EntityVillager['村民'/113369, l='MpServer', x=-2018.41, y=64.00, z=1761.49], EntityVillager['村民'/113368, l='MpServer', x=-1994.38, y=68.00, z=1777.26], EntityVillager['村民'/113370, l='MpServer', x=-2016.58, y=64.00, z=1754.65], EntitySheep['羊'/114911, l='MpServer', x=-1989.50, y=73.00, z=1857.50], EntitySheep['羊'/114912, l='MpServer', x=-1997.50, y=70.00, z=1860.50], EntitySheep['羊'/114915, l='MpServer', x=-2005.04, y=63.00, z=1864.52], EntityVillager['村民'/113381, l='MpServer', x=-2014.49, y=82.00, z=1789.70], EntitySheep['羊'/114919, l='MpServer', x=-2003.50, y=64.00, z=1860.50], EntitySheep['羊'/114921, l='MpServer', x=-2000.52, y=68.00, z=1862.32], EntitySheep['羊'/114920, l='MpServer', x=-2000.50, y=68.00, z=1859.50], EntityZombie['僵尸'/115434, l='MpServer', x=-2018.51, y=59.20, z=1782.03], EntitySheep['羊'/110837, l='MpServer', x=-1940.50, y=64.00, z=1815.50], EntitySheep['羊'/110839, l='MpServer', x=-1940.50, y=64.00, z=1811.50], EntitySheep['羊'/110838, l='MpServer', x=-1942.50, y=64.00, z=1814.50], EntitySheep['羊'/110840, l='MpServer', x=-1941.50, y=64.00, z=1811.50], EntityItemLoot['item.tile.dirt.default'/115974, l='MpServer', x=-2011.13, y=80.94, z=1783.41], EntitySheep['羊'/111885, l='MpServer', x=-1968.76, y=69.00, z=1799.64], EntitySheep['羊'/111887, l='MpServer', x=-1966.50, y=69.00, z=1821.50], EntitySheep['羊'/111886, l='MpServer', x=-1973.31, y=69.00, z=1809.81], EntitySheep['羊'/111888, l='MpServer', x=-1965.50, y=69.00, z=1821.50], EntitySheep['羊'/111391, l='MpServer', x=-1949.50, y=65.00, z=1746.50], EntitySheep['羊'/111390, l='MpServer', x=-1958.43, y=66.00, z=1739.77], EntitySheep['羊'/111393, l='MpServer', x=-1956.50, y=65.00, z=1740.50], EntitySheep['羊'/111392, l='MpServer', x=-1953.80, y=65.00, z=1744.84], EntityChicken['鸡'/111395, l='MpServer', x=-1957.50, y=70.00, z=1719.83], EntityChicken['鸡'/111394, l='MpServer', x=-1956.50, y=68.00, z=1726.50], EntityChicken['鸡'/111397, l='MpServer', x=-1958.50, y=68.00, z=1725.50], EntityChicken['鸡'/111396, l='MpServer', x=-1950.84, y=69.00, z=1723.50], EntityDonkey['驴'/111399, l='MpServer', x=-1952.52, y=65.00, z=1741.18], EntityDonkey['驴'/111398, l='MpServer', x=-1953.83, y=65.00, z=1743.67], EntityZombie['僵尸'/115515, l='MpServer', x=-2084.50, y=14.00, z=1777.50], EntityBat['蝙蝠'/115541, l='MpServer', x=-2080.00, y=26.44, z=1764.19], EntityBat['蝙蝠'/116056, l='MpServer', x=-2034.40, y=18.75, z=1773.31], EntityEvilWizard['巫师'/115041, l='MpServer', x=-2085.50, y=18.00, z=1779.50], EntityZombie['僵尸'/115040, l='MpServer', x=-2089.47, y=18.00, z=1786.29], EntitySheep['羊'/114029, l='MpServer', x=-2080.50, y=67.00, z=1714.50], EntitySheep['羊'/114028, l='MpServer', x=-2077.50, y=65.00, z=1712.50], EntitySheep['羊'/114030, l='MpServer', x=-2079.50, y=67.00, z=1714.50], EntityZombie['僵尸'/116091, l='MpServer', x=-2062.50, y=40.00, z=1847.50], EntityZombie['僵尸'/116090, l='MpServer', x=-2064.50, y=40.00, z=1848.50], EntityVillager['村民'/113535, l='MpServer', x=-2011.55, y=72.00, z=1734.50], EntityVillager['村民'/113534, l='MpServer', x=-2012.50, y=72.00, z=1737.67], EntityVillager['村民'/113042, l='MpServer', x=-2007.52, y=83.00, z=1786.56], EntityCreeper['爬行者'/116116, l='MpServer', x=-2059.50, y=40.00, z=1848.50], EntitySheep['羊'/113565, l='MpServer', x=-2024.95, y=64.00, z=1773.48], EntitySheep['羊'/113567, l='MpServer', x=-2021.71, y=64.00, z=1777.49], EntitySheep['羊'/113566, l='MpServer', x=-2037.26, y=63.00, z=1771.61], EntitySheep['羊'/113568, l='MpServer', x=-2024.37, y=64.00, z=1768.56], EntitySheep['羊'/113571, l='MpServer', x=-2036.50, y=64.00, z=1822.50], EntitySheep['羊'/113573, l='MpServer', x=-2043.21, y=64.00, z=1817.79], EntitySheep['羊'/113572, l='MpServer', x=-2037.50, y=64.00, z=1823.50], EntitySheep['羊'/113574, l='MpServer', x=-2037.50, y=64.00, z=1825.50], EntityEnderman['末影人'/116155, l='MpServer', x=-2088.50, y=31.00, z=1747.50], EntityCreeper['爬行者'/116156, l='MpServer', x=-2086.50, y=31.00, z=1743.50], EntitySkeleton['骷髅'/115165, l='MpServer', x=-2043.50, y=58.00, z=1864.50], EntityBat['蝙蝠'/115683, l='MpServer', x=-1935.77, y=21.58, z=1720.28], EntityPig['猪'/114153, l='MpServer', x=-2088.50, y=63.00, z=1712.50], EntityItemLoot['item.tile.mushroom'/113643, l='MpServer', x=-2038.11, y=58.00, z=1747.41], EntityPig['猪'/114155, l='MpServer', x=-2088.75, y=56.00, z=1715.48], EntityPig['猪'/114154, l='MpServer', x=-2089.50, y=64.00, z=1711.50], EntityZombieVillager['僵尸村民'/116202, l='MpServer', x=-2018.50, y=59.79, z=1782.61], EntitySheep['羊'/114159, l='MpServer', x=-2086.74, y=64.00, z=1762.64], EntitySkeleton['骷髅'/115182, l='MpServer', x=-2002.50, y=14.00, z=1735.50], EntitySheep['羊'/113659, l='MpServer', x=-2064.50, y=72.00, z=1742.50], EntitySheep['羊'/113658, l='MpServer', x=-2064.50, y=74.00, z=1741.50], EntitySheep['羊'/113661, l='MpServer', x=-2069.27, y=71.00, z=1743.48], EntitySheep['羊'/113660, l='MpServer', x=-2063.50, y=71.00, z=1745.50]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_66, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1313146560 bytes (1252 MB) / 3507486720 bytes (3345 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 5 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xms128M -Xmx4096M
  IntCache: cache: 2, tcache: 1, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2814 58 mods loaded, 58 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                          | Version         | Source                                          | Signature                                |
       |:------ |:--------------------------- |:--------------- |:----------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                   | 1.12.2          | minecraft.jar                                   | None                                     |
       | LCHIJA | mcp                         | 9.42            | minecraft.jar                                   | None                                     |
       | LCHIJA | FML                         | 8.0.99.99       | forge-1.12.2-14.23.5.2814.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                       | 14.23.5.2814    | forge-1.12.2-14.23.5.2814.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | aether_legacy               | 1.4.4           | aether_legacy-1.12.2-v1.4.4.jar                 | None                                     |
       | LCHIJA | aether_legacy_addon         | 1.12.2-v1.2.3   | aether_continuation-1.12.2-v1.2.3.jar           | None                                     |
       | LCHIJA | antiqueatlas                | 4.5.1           | antiqueatlas-1.12.2-4.5.1.jar                   | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHIJA | antiqueatlasoverlay         | 1.2             | antiqueatlas-1.12.2-4.5.1.jar                   | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHIJA | anvilpatch                  | 1.0.0           | anvilpatch-1.0.0.jar                            | None                                     |
       | LCHIJA | baubles                     | 1.5.2           | Baubles-1.12-1.5.2.jar                          | None                                     |
       | LCHIJA | atum                        | 2.0.16          | Atum-1.12.2-2.0.16.jar                          | None                                     |
       | LCHIJA | betterthanmending           | 1.1.2           | BetterThanMending-1.1.2.jar                     | None                                     |
       | LCHIJA | biomesoplenty               | 7.0.1.2441      | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar   | None                                     |
       | LCHIJA | bookshelf                   | 2.3.585         | Bookshelf-1.12.2-2.3.585.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | champions                   | 1.12.2-1.0.11.3 | champions-1.12.2-1.0.11.3.jar                   | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | chiselsandbits              | 14.33           | chiselsandbits-14.33.jar                        | None                                     |
       | LCHIJA | toughasnails                | 3.1.0.139       | ToughAsNails-1.12.2-3.1.0.139-universal.jar     | None                                     |
       | LCHIJA | comforts                    | 1.4.1.2         | comforts-1.12.2-1.4.1.2.jar                     | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | crafttweaker                | 4.1.20          | CraftTweaker2-1.12-4.1.20.jar                   | None                                     |
       | LCHIJA | ctgui                       | 1.0.0           | CraftTweaker2-1.12-4.1.20.jar                   | None                                     |
       | LCHIJA | jei                         | 4.15.0.268      | jei_1.12.2-4.15.0.268.jar                       | None                                     |
       | LCHIJA | crafttweakerjei             | 2.0.3           | CraftTweaker2-1.12-4.1.20.jar                   | None                                     |
       | LCHIJA | disenchanter                | 1.6             | disenchanter-[1.12]1.6.jar                      | None                                     |
       | LCHIJA | dldungeonsjbg               | 1.13.1          | DoomlikeDungeons-1.13.1-MC1.12.2.jar            | None                                     |
       | LCHIJA | durabilityviewer            | 1.4             | DurabilityViewer-1.12-forge14.21.1.2387-1.4.jar | None                                     |
       | LCHIJA | dynamiclights               | 1.4.9           | DynamicLights-1.12.2.jar                        | None                                     |
       | LCHIJA | dynamiclights_onfire        | 1.0.7           | DynamicLights-1.12.2.jar                        | None                                     |
       | LCHIJA | dynamiclights_creepers      | 1.0.6           | DynamicLights-1.12.2.jar                        | None                                     |
       | LCHIJA | dynamiclights_dropitems     | 1.1.0           | DynamicLights-1.12.2.jar                        | None                                     |
       | LCHIJA | dynamiclights_entityclasses | 1.0.1           | DynamicLights-1.12.2.jar                        | None                                     |
       | LCHIJA | dynamiclights_mobequipment  | 1.1.0           | DynamicLights-1.12.2.jar                        | None                                     |
       | LCHIJA | dynamiclights_flamearrows   | 1.0.1           | DynamicLights-1.12.2.jar                        | None                                     |
       | LCHIJA | dynamiclights_floodlights   | 1.0.3           | DynamicLights-1.12.2.jar                        | None                                     |
       | LCHIJA | dynamiclights_otherplayers  | 1.0.9           | DynamicLights-1.12.2.jar                        | None                                     |
       | LCHIJA | dynamiclights_theplayer     | 1.1.3           | DynamicLights-1.12.2.jar                        | None                                     |
       | LCHIJA | ebwizardry                  | 4.2.9           | ElectroblobsWizardry-4.2.9-MC1.12.2.jar         | None                                     |
       | LCHIJA | eplus                       | 5.0.176         | EnchantingPlus-1.12.2-5.0.176.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | enchdesc                    | 1.1.15          | EnchantmentDescriptions-1.12.2-1.1.15.jar       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | erebus                      | 1.0.31          | Erebus-1.0.31.jar                               | None                                     |
       | LCHIJA | giacomos_bookshelf          | 1.2             | GiacomosBookshelf-1.12.2-1.2.jar                | None                                     |
       | LCHIJA | jeresources                 | 0.8.5.27        | JustEnoughResources-1.12.2-0.8.5.27.jar         | None                                     |
       | LCHIJA | libraryex                   | 1.0.12          | LibraryEx-1.12.2-1.0.12.jar                     | None                                     |
       | LCHIJA | livingenchantment           | 3.1.9           | living_enchantment-3.1.9.jar                    | None                                     |
       | LCHIJA | lostcities                  | 2.0.21          | lostcities-1.12-2.0.21.jar                      | None                                     |
       | LCHIJA | naturescompass              | 1.5.1           | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
       | LCHIJA | netherex                    | 2.0.15          | NetherEx-1.12.2-2.0.15.jar                      | None                                     |
       | LCHIJA | potioncore                  | 1.6_for_1.12.2  | PotionCore-1.6_for_1.12.2.jar                   | None                                     |
       | LCHIJA | realdrops                   | 1.2.14          | RealisticItemDrops-1.2.14.jar                   | None                                     |
       | LCHIJA | roguelike                   | 1.8.0           | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
       | LCHIJA | saltmod                     | 1.12.6.2        | SaltyMod-1.12.2-1.12.6.2.jar                    | None                                     |
       | LCHIJA | twilightforest              | 3.10.1013       | twilightforest-1.12.2-3.10.1013-universal.jar   | None                                     |
       | LCHIJA | tfspellpack                 | 1.0             | TFSpellPack-1.0-MC1.12.2.jar                    | None                                     |
       | LCHIJA | tombstone                   | 3.5.2           | tombstone-3.5.2-1.12.jar                        | None                                     |
       | LCHIJA | torohealthmod               | 1.12.2-11       | torohealth-1.12.2-11.jar                        | None                                     |
       | LCHIJA | trashslot                   | 8.4.10          | TrashSlot_1.12.2-8.4.10.jar                     | None                                     |
       | LCHIJA | vanillafix                  | 1.0.10-SNAPSHOT | VanillaFix-1.0.10-99.jar                        | None                                     |
       | LCHIJA | wards                       | 1.3.1           | wards-1.3.1.jar                                 | None                                     |
       | LCHIJA | thebetweenlands             | 3.5.7           | TheBetweenlands-3.5.7-universal.jar             | 38067d6878811efb38b6a045521cfd80b9b60b38 |
  Loaded coremods (and transformers): TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.7-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      DLFMLCorePlugin (DynamicLights-1.12.2.jar)
                                        atomicstryker.dynamiclights.common.DLTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.35' Renderer: 'GeForce GTX 750/PCIe/SSE2'
  Suspected Mods: Antique Atlas (antiqueatlas), Antique Atlas Overlay (antiqueatlasoverlay)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2814
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 750/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.35, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by Electroblob77** [comment]
Try updating antique atlas to the latest version. Antique atlas 4.6 changed the way the marker names were processed, it may be that it's not backwards-compatible.

Edit: I have managed to recreate this with Antique Atlas 4.5.1. Looking more closely at the change I had to make for Antique Atlas 4.6 (see issue #323), I don't think it could have caused this. Still worth updating Antique Atlas anyway though.

**Comment by Tegamin** [comment]
> Try updating antique atlas to the latest version. Antique atlas 4.6 changed the way the marker names were processed, it may be that it's not backwards-compatible.
> 
> Edit: I have managed to recreate this with Antique Atlas 4.5.1. Looking more closely at the change I had to make for Antique Atlas 4.6 (see issue #323), I don't think it could have caused this. Still worth updating Antique Atlas anyway though.

Problem solved! Thx!

**Comment by Electroblob77** [comment]
Cool, I'll specify that the mod requires Antique Atlas 4.6 or newer for the next update.
