### ISSUE TITLE
CTD NullPointerException: Ticking entity EntityMagicSlime

### ISSUE THREAD

**Issue by muddykat-tech** [Electroblob77/Wizardry#379]
Minecraft version: 1.12.2
Wizardry version: ~~4.2.9~~ 4.2.10
Environment: Singleplayer

Issue details: ~~I was in the inventory looking for things to test, beforehand I had spawned in two wizards one evil one good, one of them killed the other. nothing happened for a while~~
the abyssalcraft cow, when killed turns itself into a demon cow. If its death is caused by the slime spell, the game will crash to desktop.

Other mods involved: abyssalcraft

Link to crash report (if applicable): https://pastebin.com/84ARMcTi

**Comment by Electroblob77** [comment]
Okay, I'll see what I can do, thanks
