### ISSUE TITLE
Arcane Lock can not be undone (or cast)

### ISSUE THREAD

**Issue by Tegamin** [Electroblob77/Wizardry#380]
**Thank you for sparing time to read this!**
Arcane lock on my chest can not be undone with the spell. I have tried restarting my game , switching from different dimensions and other things I could just do. But they didn't work. Even when I try the arcane lock in another new world with creative mode on , the problem sometimes pops up as well (as well as unable to lock the chest or other containers).
Is this another _double-click_ bug like the previous one (I've come up with this idea cuz when I am trying using the scroll under creative mode, hoping to find out the problem, I can use the spell and open the chest at the same time with a single _right-click_) or something else that is messing up the spell's mechanism? Could you please help me with this? Thx!

**Comment by Tegamin** [comment]
Well , after further testing on the spell , it's most likely to be the _double-click_ bug like the previous one.
The testing goes like this: Hold two wands in hands and the wand with Arcane Lock is in the right hand. With a single click, both wands cast their spells at the same time (still fail to undone the lock though). However, if you hold two wands without the Arcane Lock active, a single click won't cast both spells, which probably means the Arcane Lock is the one with the bug similar to the previous one.
Perhaps that's what the bug should be, can you fix it like what you did last time? (or maybe not since I'm not 100% sure about this)

**Comment by Electroblob77** [comment]
The previous one? Not sure I remember it, would you mind linking the issue here? It sounds like arcane lock is not returning the correct action result when clicking on a block.

**Comment by Tegamin** [comment]
> The previous one? Not sure I remember it, would you mind linking the issue here? It sounds like arcane lock is not returning the correct action result when clicking on a block.

I actually saw a sentence saying Fixing a double-click bug on a certain spell in one of your changelogs for a certain mod version , but I can't remember that clearly. And it didn't seem to be referring to any issue page on Github. Perhaps I'm wrong since I didn't pay much attention to it. On top of that, I'm not even sure whether the bug here is similar to that one.

**Comment by Electroblob77** [comment]
Okay, well I have an idea of what might be happening so I'll see what I can do, thanks for reporting.

**Comment by Electroblob77** [comment]
Was the same as #580, now fixed.
