### ISSUE TITLE
Mending enchantment should not be valid for mana-based items

### ISSUE THREAD

**Issue by DaRcCrysys** [Electroblob77/Wizardry#383]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  1.12.2
Wizardry version: 4.2.10 [change as necessary] 4.2.9-MC1-1.12.2
Environment: Singleplayer/LAN game/Server [delete as necessary] Server

Issue details: [describe what you were doing when the issue occurred, what went wrong, what you expected to happen, etc.]

I have been enjoying the Storm Mage armor set but, I take a lot of damage sometimes so I decided to add Mending (the base Minecraft Enchant) instead of using up all my Magic Crystals.  Mending is shown as a valid enchant to use (pressing U when hovering any armor item).  However, no amount of dropped XP seems to be repairing the armor.

Other mods involved: [only list mods that are relevant to the problem] As far as I can tell no mother mods are causing any sort of issue.

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.] No crash occurring

**Comment by Electroblob77** [comment]
Intended behaviour. Mending will not work on items that recharge with mana in wizardry 4.2+. I will see if there is a way to prevent the enchantment from even being applied.
