### ISSUE TITLE
3rd Wizard Not spawing.  Stuck in forcefield.

### ISSUE THREAD

**Issue by Bohika** [Electroblob77/Wizardry#390]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.10 [change as necessary]
Environment: Singleplayer/LAN game/Server [delete as necessary]

Issue details: Well I'm stuck in the force-field.   No third wizard.
Other mods involved: Playing R.A.D

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Electroblob77** [comment]
Are you sure there's no third wizard? Maybe it spawned underground or something? Other than that I don't know, it should detect if the wizard is dead and remove the containment field so something is making it think that wizard still exists somewhere. Have you tried relogging?

**Comment by Bohika** [comment]
I could not find him.   So I packed all my gear and killed myself.   That worked.
