### ISSUE TITLE
Java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by omerbadawy11** [Electroblob77/Wizardry#393]
Issue details: I can't connect to my server but I can make a singleplayer game just fine

Other mods involved: https://paste.dimdev.org/vocetubeyu.coffeescript Modlist including spongeforge on the server

Link to crash report (if applicable): 
![image](https://user-images.githubusercontent.com/16752592/77832646-846a7080-7172-11ea-9d56-5069f89d96d9.png)

**Comment by Electroblob77** [comment]
Appears to be a duplicate of #384. Have you removed any spell packs?
