### ISSUE TITLE
Client crash from Grapple spell

### ISSUE THREAD

**Issue by CritLoren** [Electroblob77/Wizardry#394]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.10 [change as necessary]
Environment: Singleplayer/LAN game/Server [delete as necessary]

Issue details: Any time the Grapple spell is used (on the player by hostile mobs at least, i don't have the spell book yet) there is a client crash. Curiously, servers don't crash.

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): https://pastebin.com/M6BhjQdn

**Comment by Electroblob77** [comment]
Ah yes, I can see what's happened there, that's my fault for not null checking. Thanks for reporting.
