### ISSUE TITLE
replace vanilla fireball config will not change on server

### ISSUE THREAD

**Issue by hello1234658901** [Electroblob77/Wizardry#395]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.10 [change as necessary]
Environment: Server

Changing the replace vanilla fireball setting in config to off does not change the fireballs. The fireballs conflict with thaumcraft and will not allow me to complete one of the quests. Any way to disable the setting for a whole server?

Other mods involved: Thaumcraft

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Electroblob77** [comment]
Ah, I see what I missed there! For now, you'll have to make sure all players have this option turned off in their own configs as well.
