### ISSUE TITLE
Possession Shaders apply to all players

### ISSUE THREAD

**Issue by ErenBlack** [Electroblob77/Wizardry#397]
Minecraft version: 1.12.2
Wizardry version: 4.2.10 
Environment: Server

# Issue details: 

Issue #179 is still back, where the possession spell shaders were applied to all players instead of just the one using possession

Other mods involved: N/A

**Comment by Electroblob77** [comment]
Ah yes, just found the place I missed when I thought I'd fixed this. I'll get it fixed for the next patch.
