### ISSUE TITLE
Please remove

### ISSUE THREAD

**Issue by kdseitz1** [Electroblob77/Wizardry#401]
Whoopsie, wrong forum.

**Comment by Electroblob77** [comment]
What on earth is Flourish and Botts? Transfiguration? The bookstore? Are you playing a modpack?

Whatever they are, I'm glad you've solved the issue!

**Comment by kdseitz1** [comment]
> What on earth is Flourish and Botts? Transfiguration? The bookstore? Are you playing a modpack?
> 
> Whatever they are, I'm glad you've solved the issue!

Oh my god I am a big dummy. I've posted this to completely the wrong forum lol. This was meant for the "Witchcraft and Wizardry" Harry Potter map fml.

**Comment by Electroblob77** [comment]
Hehe no worries, I figured that's what had happened!
