### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by mxnmnm** [Electroblob77/Wizardry#402]
Minecraft version: 1.12.2
Wizardry version: 4.2.10 
Environment: Singleplayer

Issue details: I killed an ice wraith and I got a fatal error

Other mods involved: holoinventory

Link to crash report (if applicable): https://gist.github.com/mxnmnm/fd03d594e9c1401e5995b54c936ea332

**Comment by mxnmnm** [comment]
https://github.com/dries007/HoloInventory/issues/40

**Comment by Electroblob77** [comment]
An entity with a null UUID... that's a new one on me, but easy enough to fix I guess. Thanks for reporting.
