### ISSUE TITLE
crash when open handbook in chinese environment

### ISSUE THREAD

**Issue by TUsama** [Electroblob77/Wizardry#404]
Minecraft version: 1.12.2
Wizardry version: 4.2.10

Issue details: 
I had test the crash, when the handbook text file saved as UTF-8 code, this issue appeared. when it saved as GBK code, it can be open correctly, 

the crash report is here:  https://paste.ubuntu.com/p/M6y2fpfprB/

it seems that you can use git hook to convert its code automatically, just remember to transfer your file code to the right code.

**Comment by Electroblob77** [comment]
Interesting. I wonder if PR #400 fixes this? If the change you're describing fixes it then that's easy enough to do, thanks.

**Comment by Electroblob77** [comment]
Should be fixed in 153ea74

**Comment by alan67160** [comment]
@Electroblob77 The issues is happening again at Traditional Chinese(zh_tw.lang)
