### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by SerotoninJC** [Electroblob77/Wizardry#407]
Minecraft version: 1.12.2 
Wizardry version: 4.2.11 
Environment: Singleplayer

Issue details: Crash on loading mods

Other mods involved: Not sure

Link to crash report (if applicable): https://pastebin.com/Xu1RfC5q

Similar to #342 but has "com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 16 column 6 path $.images.workbench.caption" on top of that

**Comment by SerotoninJC** [comment]
fixed by updating to newest version of forge

**Comment by Electroblob77** [comment]
That crash report _is_ with the newest version of forge... are you sure it's fixed? And what is your language setting?
