### ISSUE TITLE
crashing when open handbook

### ISSUE THREAD

**Issue by wei0915** [Electroblob77/Wizardry#408]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.10 / 4.2.11 [change as necessary]
Environment: Singleplayer/LAN game/Server [delete as necessary]

Issue details: the game still crashed when opened the handbook in chinese environment.

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): https://paste.ubuntu.com/p/pgrYqQZjmq/

**Comment by Electroblob77** [comment]
Duplicate of #406. (You've written exactly the same thing, word for word!)
