### ISSUE TITLE
[1.12.2] Unlocalised death message

### ISSUE THREAD

**Issue by Morpheus1101** [Electroblob77/Wizardry#41]
Minecraft version: 1.12.2 
Wizardry version: 4.1.1
Environment: SMP
Forge: *.2702

In this instance im presuming a wizard died or a zombie or something and the msg said: death.attack.indirectWizardyMagic

**Comment by Electroblob77** [comment]
Ok thanks for reporting, I'll get that fixed for the next patch.

**Comment by Morpheus1101** [comment]
Addendum to this, now its live on the server, this msg is spammed quite a bit
![javaw_2018-06-01_22-54-55](https://user-images.githubusercontent.com/10524952/40841754-e363753c-65ee-11e8-9d87-1630d949e5a2.png)

**Comment by Electroblob77** [comment]
I can actually see a second issue there, it shouldn't print out a death message when a minion dies because that happens quite often, as can be seen here! I think it's doing that because the minions technically have custom names.
