### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by YaroslavChetskiy** [Electroblob77/Wizardry#410]
Hello again!  And now I have a question.  Server administrators don't want to update the mod because they are afraid that they will have to delete all objects and the console will not be able to withstand it.  Tell me, is it true? Thanks a lot.

**Comment by Electroblob77** [comment]
I am unaware of any significant issues when updating the mod. What do you mean by 'delete all objects'? Which version of wizardry are you on currently, and which version are you planning to update to?
