### ISSUE TITLE
crash, ticking entity fighting evil wizard. (zammle spell)

### ISSUE THREAD

**Issue by sa13103** [Electroblob77/Wizardry#411]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.2.11
Environment: Singleplayer

crash when fighting altar spawned evil purple wizard. when wizard casts a spell it causes a {java.lang.NullPointerException: Ticking entity} it appears to be the spell (Zammle)

[crash-2020-04-16_12.51.04-server.txt](https://github.com/Electroblob77/Wizardry/files/4489472/crash-2020-04-16_12.51.04-server.txt)

**Comment by Electroblob77** [comment]
Zammle is from the Arcane Essentials addon. I've forwarded this issue to their issue tracker.
