### ISSUE TITLE
Add config option for restricting elemental wands to spells of their element

### ISSUE THREAD

**Issue by BigDaleAHA** [Electroblob77/Wizardry#414]
Hi. I had thought about a good idea when playing with my friends. We were wondering if it is possible for some future additions on the config file. We thought about the idea that maybe a config command can be added to enable/disable that different wands can only use spells of the same element(e.g. fire wands can only use fire spells). 

I think this would greatly increase how much fun it is in servers where people might have this sense of "class" system when this is enabled

Thank you very much!!!!

**Comment by Electroblob77** [comment]
This has been discussed before, I'm certainly considering it as it has potential for minigames or adventure servers as well. Thanks for posting.

**Comment by Electroblob77** [comment]
Now available as an addon called Wizardry Fates: https://www.curseforge.com/minecraft/mc-mods/wizardry-fates
