### ISSUE TITLE
Throwable entities hit their caster when aimed at another entity at close range

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#42]
Minecraft version: 1.12.2
Wizardry version: 4.1.1
Environment: Both

I'm not talking about Wither Skull, Fireball Spells, or Detonate cause those spells you CAN hurt yourself with. (Explosive Radius from those spells are expected to hurt anything, so that's normal)

**Issue details:** 

But,

These spells below that you're normally unable to hurt yourself with. (But they do, by glitching out and immediately hitting and hurting you before you even see the projectile)

**When using certain spells like (there could be more then I know):**

----

Fire bomb
Lightning Disk
Spark bomb
Poison bomb
Darkness Orb
Fire Bolt
Ice Charge

----

When casting these spells, it may randomly instead immediately hit the caster and can actually hurt them instead of shooting projectiles like it's supposed to be. **This issue is possible to both Wizards and Players.**

Certain spells like Firebomb and Firebolt (which you're not supposed to hurt yourself with) may end up hitting their own caster and setting them on fire instead of actually shooting out to their target like it's suppose to be.
 
**Reproducing is quite random, but it's plausible:**
### # 1
(Make sure you're in survival otherwise you can't tell if the projectile decides to glitch out or not)
1. Get a Wand or a scroll with one of the specified spells. **(I'd suggest using a wand for this as you may have to repeat this bug multiple times)** 
2. Use one of specified spells than could potentially glitch out and hit/hurt you instead.
3. Proceed to cast one of specified spells (Firebomb and Firebolt are usually best)
4. Keep casting in random directions. (This one may require a little of messing around)
5. If you did get hurt then the firebomb/firebolt projectile glitched out and damaged you and set you on fire instead. (If not, you may need to repeat to step 2)

### # 2
(Creative mode only with wizard spawn eggs and Firebolt/Firebomb Spellbooks)
1. Get the Wizard Spawn eggs and get the spells for them.
2. Spawn the Wizards and right click them with the firebomb/firebolt spell in hand.
3. Spawn a Hostile Mob. (I'll go for spiders/skeletons/husks/zombies)
4. This one also may require a little of messing around. (So you may need to repeat to step 2 or 3)
5. One of the Wizards will get hurt by his own projectiles when using firebomb/firebolt for trying to target a Hostile Mob.

**Note**: Vanilla Snowballs/eggs also do this, but doesn't hurt the thrower. For eggs, it just spawns a baby chicken right in your face instead.

**Comment by Electroblob77** [comment]
Ugh, I thought I'd fixed that. As you noticed, the vanilla throwables also do this but because they don't cause damage it doesn't matter so much, so I expect it's a problem in the vanilla code. I'll see what I can do.

**Comment by Ghostrider231** [comment]
Okay, what I said about this happening in survival seems to occur in creative mode as well. So it's pretty much in both modes. Something I like to point out.
I've used poison bomb and I've got hit by my spell, but the poison only happens for like a fraction of a second.

**Something I forgot to mention about vanilla throwables**: I don't know if Ender Pearls are affected by the hit yourself bug. Like the Snowballs and eggs.

**Comment by Tora-B** [comment]
This is probably [vanilla Minecraft bug MC-88491](https://bugs.mojang.com/browse/MC-88491).

**Comment by Electroblob77** [comment]
Yes I saw that bug when investigating this issue in 1.11.2, clearly it still hasn't been fixed. I can still fix this in wizardry though, I'll just have to sync the thrower myself.

**Comment by Electroblob77** [comment]
I have now managed to recreate this bug, but in order to do so I have to shoot one of the above named spells _at an entity_ from within a certain range (specifically, the distance the projectile flies in 2 ticks). The fix is to synchronise the thrower field, which will increase network traffic but unfortunately it's necessary.
