### ISSUE TITLE
Forest of Thorns

### ISSUE THREAD

**Issue by Gloxinega** [Electroblob77/Wizardry#420]
Minecraft version: 1.12.2 
Wizardry version: 4.2.11 

Question details: HI, it's nothing all that important to be honest. I was testing all of the spells the mod has to offer and i CANNOT figure out what Forest of Thorns does. Mobs don't take damage when they come in contact with the thorns as i assumed. It doesn't give me any noticeable buffs and i just can't seem to find a use for it. 
When i checked the spell description on the wiki, it just contained a poem/lore of sorts, which is fun and i know what you were going for, but you probably should've added an actual description below it.

**Comment by Electroblob77** [comment]
I've heard someone else reporting this, what should happen is the thorns should trap mobs like cobwebs do and then keep damaging them while trapped. I'll have to test it myself, it was working last time I checked. Thanks for reporting.

**Comment by Electroblob77** [comment]
Forgot to close this, it was fixed in wizardry 4.3.
