### ISSUE TITLE
Request - Spell Catalog

### ISSUE THREAD

**Issue by Random-Scientist** [Electroblob77/Wizardry#424]
The Spell Catalog is an in game self updating 'catalog' for all spells a player has unlocked. There is one spell per page, and each page contains all of the info from the wand HUD as well as the lore tag of the spell book. The spell catalog would be crafted by combining a book and quill (not a normal book) with a magic crystal in the crafting grid

I think it would be really helpful to a player looking to find his best spells, quickly

**Comment by Electroblob77** [comment]
A feature similar to this is coming in wizardry 4.3, there's a sneak peek on Discord if you're interested!
