### ISSUE TITLE
Quality tools compatibility

### ISSUE THREAD

**Issue by Another-human51** [Electroblob77/Wizardry#425]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Singleplayer/LAN game

The potioncore.magicDamage property only affects some spells while the projectileDamage affect others and the support ones like healing cant be modified at all 
EDIT:
looks like someone already reported it

**Comment by Electroblob77** [comment]
Yes, this is a duplicate of #396.
