### ISSUE TITLE
Slow time blacks out game

### ISSUE THREAD

**Issue by sokisoko** [Electroblob77/Wizardry#426]
Minecraft version: 1.12.2 
Wizardry version: 4.2.11
Environment: Server 

Issue details: I cast the spell slow time and it completely blacked out minecraft. I could still move around and punch around blindly, and other people around me told me that I did indeed slow time. The peculiar pocketwatch also still results in me going completely blind but it instead freezes time. 
I opened the menu and could click around for the buttons but I also couldn't see it, or any other guis.

Other mods involved: I have the twilight forest spellpack and ancient spellcraft installed too

**Comment by sokisoko** [comment]
OH WAIT NEVERMIND I made a friend test out the spell and it appeared normally for them. It turns out my screen blacked out because I had fast render on false alarm im so sorry

**Comment by Electroblob77** [comment]
Oh ok no worries, glad you got it fixed. I think what's probably happened is Optifine's fast render is incompatible with the shader used by slow time. There's a config option to turn wizardry's custom shaders off if you'd rather use fast render.
