### ISSUE TITLE
Two hands crash

### ISSUE THREAD

**Issue by bigenergy** [Electroblob77/Wizardry#428]
Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Server 

Issue details: Take two wands of the mage in both hands, right-click and get the client crash
The player can not join into the server after this crash.

Link to crash report (if applicable): https://pastebin.com/md6Z8118

**Comment by Electroblob77** [comment]
Okay, I'll look into it, thanks.

**Comment by AuuTTo** [comment]
I just encountered this as well. i haven't been able to log back into our server for about two days now. Im playing mc eternal lite and have had much fun. please fix.

**Comment by Electroblob77** [comment]
I have tested this and it can only happen if you select the previous spell on a newly-crafted wand while holding any other wand in your offhand (this is such an obscure corner-case that it's taken nearly a year for anyone to notice!). It is not triggered by right-clicking.

To avoid the crash for now, make sure you _always put a new wand in the arcane workbench and press the apply button before trying to use it_ (you need not actually bind any spells to it). To fix a world that has already crashed, you'll have to get the server owner to edit the player.dat file for your player, find wherever it says `selectedSpell: -1` and change it to `selectedSpell: 0`.

I will fix this for the upcoming 4.3 update, but it will be a while before that gets released.
