### ISSUE TITLE
Certain Spells evilwizards use in twilight crashing server

### ISSUE THREAD

**Issue by TheMightyMcGrew** [Electroblob77/Wizardry#429]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.11 [change as necessary]
Environment:Server [delete as necessary]

Issue details: Traveling in twilight in survival. Come across evil wizards (now whitelisted in config to spawn in this dimension) wizard targets players with spells, at first I thought it was just Ray type spells, but further inspection of crashreports shows the most recent is CycloneShield. Also these crashes are restricted to targeting players, in spectator/creative evil wizards targeting good wizards can and will elicit the crashes as well. I have provided 3 pastebin links

Other mods involved: Dont know which spells are from which mod but arcaneessetials, ebwizardy, ebwizardy twilight addon, and twilight forest are the relevant mods included.

Links to crash reports
https://pastebin.com/3jF8G82Z
https://pastebin.com/cFck1Dd9
https://pastebin.com/uwTNTGV2

**Comment by Ghostrider231** [comment]
Hello, I'm not the author.

The crash logs you sent seem to be coming from Arcane Essentials.

Also just from looking at the log you seem to be using an older version of Arcane Essentials (0.9.2), maybe update to the latest version of arcane essentials? (1.0.0 v6 alpha)

If the problem persists, report the issue to the Arcane Essentials author.

**Comment by Electroblob77** [comment]
Yeah this looks like it's an issue with arcane essentials. The latest version is a beta but it's still more stable than 0.9.2, it may well fix the issue.
