### ISSUE TITLE
spell do not disapear (light and petrified ) sometimes

### ISSUE THREAD

**Issue by DeggTheBeast** [Electroblob77/Wizardry#430]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.11 [change as necessary]
Environment: Singleplayer/LAN game/Server [delete as necessary]

Issue details: [describe what you were doing when the issue occurred, what went wrong, what you expected to happen, etc.]

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Electroblob77** [comment]
I'm going to need more information than that, please fill out the blanks above to explain what your issue is and how it happened.
