### ISSUE TITLE
Crashes with BSL-Shaders 1.12.2

### ISSUE THREAD

**Issue by rolandborder** [Electroblob77/Wizardry#433]
First of all, i have some crashes with BSL-Shaders when i cast some spells, actually projectiles ones, and most problematic spell is Darkness orb.
Second problem is graphics issues with BSL-Shaders, as i understand this problems are on my side, so i would be greatfull if you will help me with this issues. I think, my shaders config is really bad - i have some white glow when i cast most most of spells with projectiles or laser.

Sorry for my bad english its not my native language.

**Comment by Electroblob77** [comment]
Please use the issue template, it's there to help you provide the right information for me to help you.

Please post your wizardry version, your crash report, and screenshots of the graphical issues you are seeing. Thanks.
