### ISSUE TITLE
Arcane Work Bench Cosmetic Issue

### ISSUE THREAD

**Issue by lunarmaximum** [Electroblob77/Wizardry#434]
Minecraft version: 1.12.2 
Wizardry version: 4.2.11 
Environment: Server

Issue details: This is a minor issue, but I noticed that sometimes I still see the wand or special effects on the arcane workbench even after my friend was finished using it. When I right click the table, it goes away

Thanks!

**Comment by Electroblob77** [comment]
Ah yes, this is a very old bug which I never got round to fixing, because of course I never notice it in singleplayer testing. I did find a fix while working on new features recently so it will be fixed in 4.3. Thanks!

**Comment by lunarmaximum** [comment]
Thanks for the update, I appreciate it!
