### ISSUE TITLE
Purifying Elixir does not remove Curse of Undeath

### ISSUE THREAD

**Issue by TherminatorX** [Electroblob77/Wizardry#435]
Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Singleplayer/Server

Issue details: Testing out undiscovered master tier spells on a server, got hit with Curse of Undeath repeatedly, used multiple Purifying Elixirs I had gotten from chests and none worked. Turned out to be the Resurrection spell. Tested in a creative singleplayer instance by giving myself a master wand and a Res. book, then setting to survival mode and misfiring to get cursed. Again, spawning in more elixirs did not cure me.
Is it just a low chance to remove curses?

Other mods involved: None hopefully, though TF Spell Pack and Arcane Essentials are installed.

**Comment by Electroblob77** [comment]
No, it should work every time. Does it have to be a misfire effect or does purifying elixir not work if you are cursed by a wizard either? And does the remove curse spell work in either situation?

**Comment by TherminatorX** [comment]
Remove Curse works with both the misfire and getting cursed by a bad bearded boi.

Elixir works with neither situation.

**Comment by Electroblob77** [comment]
Thanks, that narrows down the problem. I'll see what I can do.

**Comment by kaojinn** [comment]
I was wondering if this bug has has an update that squashed it yet.  I'm currently playing an MC Eternal pack, and was hit with Curse of Undeath by a wizard.  I've consumed 2 of the remove curse potions, and I'm still stuck with the curse.  Is there a workaround available to remove the curse, like a console command the admin could enter?

**Comment by TherminatorX** [comment]
As above, the Remove Curse spell does work as a workaround if you can get the spellbook for it.
