### ISSUE TITLE
[Radiance Storm] Causes immortality of affected entities

### ISSUE THREAD

**Issue by Icewalker221** [Electroblob77/Wizardry#437]
Minecraft version: 1.12.2 
Wizardry version: 4.2.11 (-MC1.12.2.jar)
Environment: Open LAN & Server (Occurs between both. Untested in Single player)

Issue details: I've noticed that there's a chance (it's RNG and not guranteed) that using the spell [Radiance Storm] will cause effected Mobs and Players to become effectively immortal where no method of causing them damage will apply. (Hunger, lava, weapons, spells.etc Nothing will harm them anymore.) Using the command /kill will remove the effect from players and they can be hurt normally after respawning but, we have no method like /butcher for NPCs.
The immortals are capable of harming other players/mobs and vice versa. (Two immortal entities cannot harm each other.)

For full and proper reference the spell casting focus I was utilizing.
[Master Healing Sword] From Arcane Essentials.   Upgrades will be in (these)
 (3x Wand Duration) - (3x Wand Attunement) - (3x Wand Blast)
Wearing: [Ring of Interdiction] and [Ring of The Paladin]

I've noticed there's an immortality bug already present on the issue tracker and I'm going to link that one to this one on suspicion that these may be related. 
#314 

Other mods involved: Abyssal Craft / Arcane Essentials
1. (Using a [Holy Sword] as a Spellcasting Wand) (AE)
2. First noted immortality was on a Depths Ghoul. (Abyssal Craft) (Noting this for reference purposes, unlikely to be part of the bug.)

Link to crash report -- N/A Does not cause crashes or warnings.

**Comment by Ghostrider231** [comment]
This is an Arcane Essentials bug, and I'm having this problem too, even in the latest version. 
(This can apply to just about any mob, I tried a villager and it happened on the first radiance storm spell cast)

You can hurt and kill the immortal entity if you are in creative mode.
OR you can use the **/kill @e[type=modidname:yourmobnameidhere]** command.
**EX:** /kill @e[type=ebwizardry:evil_wizard]

You may want to send this report to the Arcane Essentials bug report github instead: https://github.com/FavouriteDragon/Arcane-Essentials/issues
