### ISSUE TITLE
[TickingEntity] AOE spells cause ticking entity errors

### ISSUE THREAD

**Issue by Icewalker221** [Electroblob77/Wizardry#438]
Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Open LAN / Server

Issue details: We're a bit confused with this one. Spells such as [Lightning Vortex], [Whirlpool], and [Whirlwind], which when used send moving AOE attacks or even in the case where they don't move there's a chance that the Server will crash. The [Sploosh] spell also can cause a ticking entity error. I'm hoping this isn't a mod confliction but, I do not perceive any of the other mods having an interaction which would matter other than Astral Sorcery due to it's perk tree but, I've doubts about it being related. The crash does not happen 100% of the time but, it happens very frequently.

The origin doesn't matter. Dispensers, Players, and Angry Wizards that use these spells all have the chance of causing this crash when it's cast.

I apologize for not being able to provide more details. I haven't gone and tested every spell to see if they'll crash the game.

Other mods involved: Arcane Essentials 0.9.2 / (Possible) Astralsorcery-1.12.2-1.10.23.jar

Link to crash report -  https://pastebin.com/pxyf5mmG

**Comment by Ghostrider231** [comment]
With the crash log you've provided, it seems to be directing them to Arcane essentials.

You seem to be using an older version of arcane essential (0.9.2), maybe update to the latest version? (1.0.0 v6 alpha)

Even then, I also get a crash similar to this, but with different spells.

You may want to send this report to the Arcane Essentials bug report github instead: https://github.com/FavouriteDragon/Arcane-Essentials/issues

**Comment by Electroblob77** [comment]
_Whirlwind_ is a wizardry spell, I very much doubt it causes this crash since it only uses vanilla particles. The other spells are all from arcane essentials, and I'm pretty sure this bug was fixed in the latest alpha/beta version.
