### ISSUE TITLE
crash when open handbook in traditional chinese environment

### ISSUE THREAD

**Issue by alan67160** [Electroblob77/Wizardry#440]
Minecraft version: 1.12.2
Wizardry version: 4.2.11

Issue details: same as issues #404 but this time is Traditional Chinese(zh_tw.lang)

Link to crash report: [https://paste.ubuntu.com/p/FYjmKXrd8w/](https://paste.ubuntu.com/p/FYjmKXrd8w/)

**Comment by Electroblob77** [comment]
Okay that's presumably the encoding again. I will fix this for the upcoming 4.3 update but that may be a while yet. In the meantime you should be able to fix this by copying the `zh_tw.lang` file into an empty resource pack and changing the encoding to GBK.

**Comment by alan67160** [comment]
but in this time GBK can't fix this because GBK is not supporting Traditional Chinese, GBK only work for Simplified Chinese

**Comment by alan67160** [comment]
I have tried big5 and UTF-8 and it also not working

**Comment by alan67160** [comment]
@Electroblob77

**Comment by TUsama** [comment]
我也测试了一下，发现gbk、gb18030，gb2312都无法支持繁体中文的显示。。我感觉这个问题只能通过blob改书的代码，使书籍能够支持更多编码，才能解决这个问题。而且似乎在10版本以前是没有书籍崩溃问题的。

**Comment by oachan** [comment]
v4.2.10
+ Added Taiwanese translations, courtesy of chesterccj305
This update caused the crash.

So we only can play in version before v4.2.9.  Orz

**Comment by alan67160** [comment]
@oachan but before v4.2.9 don't have Traditional Chinese translate :(

**Comment by alan67160** [comment]
[traditional-chinese-translate-crash-fix.zip](https://github.com/Electroblob77/Wizardry/files/4688479/traditional-chinese-translate-crash-fix.zip)

**Comment by alan67160** [comment]
@Electroblob77

**Comment by Electroblob77** [comment]
@alan67160 Sorry, this issue got lost somehow... thanks for making that fix, I will add it to the next update. For now, you can use a custom resource pack to override the broken translation files with the fixed versions, or replace the ones in the jar directly.
