### ISSUE TITLE
Ghasts Immune to Deflected Projectiles

### ISSUE THREAD

**Issue by Bulldogg6404** [Electroblob77/Wizardry#443]
**Minecraft version:** 1.12.2
**Wizardry version:** 4.2.11
**Environment:** Singleplayer

**Issue details:** Ghast fireballs are replaced by Wizardry fireballs, which despite being able to deflect and explode on contact with the ghast that fired them, they do no damage to the ghast and seemingly makes them immune to Return to Sender. I experimented in a creative world a bit and spent a good twenty minutes deflecting fireballs at ghasts in a variety of ways while attempting to target random locations on the ghast's body. In almost every instance where I succeeded in hitting the ghast, the projectile did nothing except make an explosion particle and sound effect. There does seem to be a small vulnerable hitbox on the underside of the ghast, but even then, it does very little (if any) damage anyway. 

After going into the Wizardry configs, disabling the vanilla fireball replace setting, and summoning a new ghast, the very next fireball I deflected hit the ghast cleanly and killed it outright. 

To be fair, I suspect replacing their fireballs is either the intended behavior or not a fixable bug, but if it's possible to give ghasts special treatment so their fireballs are not replaced or so that ghasts are damaged by the wizardry fireball spell, it would solve this issue and save myself and others time and concern trying to kill ghasts this way.

**Other mods involved:** I have other mods installed, but I can't say for certain any of them are relevant to the problem

**Crash report:** No crash occurred, n/a

**Comment by Electroblob77** [comment]
Weird, I remember testing it for that exact reason. I'm going to add more granularity to that config option anyway, but if it's not hitting the ghast then that's a bug that should be fixed.
