### ISSUE TITLE
Evil Wizard Crashes Game

### ISSUE THREAD

**Issue by Nocturnus13** [Electroblob77/Wizardry#444]
Minecraft version: 1.12.2  
Wizardry version: 4.2.11
Environment: Singleplayer

Issue details: I had set up a few wizards and evil wizards to battle when one of the evil wizards fired off a spell that crshed the game before i could register what it was this has happened a couple of other times in different worlds.

Other mods involved:
Wizardry
ancient spellcraft (possible)
Arcane essentials (possible)
Tf spell pack (possible)
Extra Spells (possible)

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]
https://pastebin.com/neqEfdjj

**Comment by Electroblob77** [comment]
Update arcane essentials to the latest alpha/beta version
