### ISSUE TITLE
Slowness III on Snare spell

### ISSUE THREAD

**Issue by lukebemish** [Electroblob77/Wizardry#446]
Minecraft version: 1.12.2 
Wizardry version: 4.2.11
Environment: Singleplayer

Issue details: If a player walks through their own snare, they are not slowed down or damaged, as would be expected. However, the "Slowness III" effect is shown, though it appears to have no effect, and continues to show once the timer has reached 0. So, if watched in the inventory, it will say "Slowness III: 0:04", then 0:03, 0:02, 0:01, 0:00, 0:00...; the "Slowness III 0:00" never disappears.

Other mods involved: None. Tested in fresh installation with only VanillaFix.

**Comment by lukebemish** [comment]
One other thing to note; this could be due to some sort of desync issue. I suspect this because though the potion symbol is shown on screen, no effects are applied and attempting to clear effects with the command line does nothing to change it, telling me that there are no effects to clear.

Additionally, the effect visuals appear to be gone when I leave the world and enter again, so it is likely a desync; maybe a check against whether an entity is the caster somehow fails on the client? I'll think about if there are any other good spells to test this.

**Comment by Electroblob77** [comment]
Can confirm this is happening for me too, it appears I'm only setting the owner of the snare on the server side 🤦‍♂️. It's an easy fix, I'll get it done for the next release. Thanks for reporting.
