### ISSUE TITLE
Adding wand upgrade

### ISSUE THREAD

**Issue by edotenseilove** [Electroblob77/Wizardry#447]
I have an idea of adding an upgrade that would allow user to upgrade spells so (range, duration etc) with each **kill with a spell on wand** that has the upgrade. Also i would suggest making a config option where we could set if it would be possible to add this upgrade on a wand that has got a spell upgrading upgrade (if it is stackable with other spell upgrades) or values such as maximum bonus provided and so

**Comment by WinDanesz** [comment]
Not sure what this meant, sorry. Happy to discuss suggestions in the discord server in more details.
