### ISSUE TITLE
Crash on book open

### ISSUE THREAD

**Issue by 1gn153n515** [Electroblob77/Wizardry#45]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.1.1 [change as necessary]  
Environment: Singleplayer

Issue details: Wanted to open book and game crashed

[crash-2018-05-31_21.23.25-client.txt](https://github.com/Electroblob77/Wizardry/files/2059759/crash-2018-05-31_21.23.25-client.txt)

**Comment by ejektaflex** [comment]
Same thing here, same versions. 

[VanillaFix crash dump](https://paste.dimdev.org/ovagiraret.txt)

**Comment by Electroblob77** [comment]
Just looked at the code and I can't see how this can possibly happen, but I will attempt to reproduce it. Does this happen every time you try to open the handbook or just sometimes?

**Comment by 1gn153n515** [comment]
It happened twice while I was playing will go and try again to see if it still crashes and give a new crash report

**Comment by 1gn153n515** [comment]
Crashed again in a new world. 
I just gave myself the book to test.

[crash-2018-06-02_13.42.21-client.txt](https://github.com/Electroblob77/Wizardry/files/2064951/crash-2018-06-02_13.42.21-client.txt)

**Comment by Circine** [comment]
It's No Recipe Book causing it.

**Comment by Electroblob77** [comment]
@Circine that's very helpful, the crash is definitely recipe-related

**Comment by adishpan** [comment]
I have the same error, but (for possibly unrelated reasons) the crash quits the launcher, too, so I can't get a log. It may not be No Recipe Book, however, because I don't have that mod.

**Comment by Apotrox** [comment]
[crash-2018-07-01_17.40.40-client.txt](https://github.com/Electroblob77/Wizardry/files/2152916/crash-2018-07-01_17.40.40-client.txt)

Here another crash report ^^

**Comment by Electroblob77** [comment]
@Apotrox That's not the same bug, it's actually a duplicate of #36, which was fixed in wizardry 4.1.2. I can see you're using version 4.1.1 so please update your wizardry to 4.1.2 and it will fix your problem. (In future, please check you have the most up-to-date version before posting here!)

**Comment by Electroblob77** [comment]
This may have been fixed by the handbook rewrite, it's a very old issue anyway. Please reopen if the problem persists.

**Comment by axin0452** [comment]
@Electroblob77 I also encountered the same problem
[crash-2020-04-12_01.34.38-client.txt](https://github.com/Electroblob77/Wizardry/files/4465087/crash-2020-04-12_01.34.38-client.txt)
