### ISSUE TITLE
Can't use arcane workbench on my server

### ISSUE THREAD

**Issue by Kapparow** [Electroblob77/Wizardry#450]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Server [delete as necessary]

Issue details: When i tried to use arcane workbench on my server, i can open it and i can put wand. But when i click apply button effect and sound appears but nothing else happens. It doesn't upgrade wand, it doesn't apply any spell to wand but in singleplayer i can do that.

**Comment by Ghostrider231** [comment]
Hello, I'm not the author.

**Did you had any spell books or upgrades in the arcane workbench menu when you clicked apply on your wand?**

Otherwise if you are only putting the wand in the arcane workbench, I'm assuming from what you're describing here is intentional.

**Comment by Kapparow** [comment]
Hello, thank you for your reply.
Answer is yes. and there is an screnshot
![image](https://user-images.githubusercontent.com/25988411/83127478-df710300-a0e2-11ea-9084-f0bc75b82b31.png)

**Comment by Electroblob77** [comment]
Does this happen for all spells? Are any spells disabled in the config?

**Comment by Kapparow** [comment]
yes it happens for all spells. No all spells active. I can't upgrade my wand too

**Comment by Ghostrider231** [comment]
Do you have have any other mods installed?

Or perhaps check your (which is going to be on your server installation) **latest.log** to see if it's spewing any errors related to wizardry.

**Comment by Electroblob77** [comment]
Yes, a log would be useful
