### ISSUE TITLE
Custom Trade Currency Items cause Bugged Trades

### ISSUE THREAD

**Issue by Squidman13** [Electroblob77/Wizardry#451]
Minecraft version: 1.12.2 
Wizardry version: 4.2.11 
Environment: Singleplayer & Server 

When adding custom items to be used as currency for trades, I have noticed that some wizard trades have their first slot show up empty, making it impossible to make the trade. I think this is happening because an item with a high value ends up matched with a low level trade. When I removed all items with values over 6, all the trades seem fine. I made sure to check for typos and all of the items I defined in the config were showing up in some trades, but some low level trades were still missing the first slot item.

**Comment by Electroblob77** [comment]
That figures, sounds like I need to limit the number of currency items to a minimum of 1

**Comment by Electroblob77** [comment]
Forgot to close this, was fixed in wizardry 4.3.
