### ISSUE TITLE
Hungarian Translations

### ISSUE THREAD

**Issue by Bombadil-tr** [Electroblob77/Wizardry#452]
Greetings! I'll just drop these in here.
[hu_hu_unzip_this.zip](https://github.com/Electroblob77/Wizardry/files/4711094/hu_hu_unzip_this.zip)

**Comment by Blueberryy** [comment]
You can fork this repository then upload your file and make pull request to this repository from your fork.

**Comment by Electroblob77** [comment]
Got the translations via discord pm, they'll be included in the next release!
