### ISSUE TITLE
Empowering Presence spell has no sound

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#454]
Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Client

Issue details: Casting the empowering presence spell doesn't play the spell casting sound.

Other mods involved: N/A

Link to crash report (if applicable): N/A

**Comment by Electroblob77** [comment]
Huh, so it doesn't. I must have missed this during the sound overhaul for 4.2... thanks for reporting!
