### ISSUE TITLE
Wand going to -30267 when giving them mana

### ISSUE THREAD

**Issue by ryanl127** [Electroblob77/Wizardry#455]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.11 [change as necessary]
Environment: Server 

Issue details: when adding mana to my master necromancy wand and Master wand (at separate times) they both glitched and lost all spells on them and had -30267 mana on them making them useless both were done in the cyclic crafting table.

Other mods involved: it happend with the cyclic mod in the rougelike adventures and dungeons.
(mod pack in twitch)

**Comment by Electroblob77** [comment]
This was fixed a _long_ time ago, see issue #68. Are you sure the wizardry version you posted is correct? I know RAD was using a backdated version, not sure if that's still the case. If this is definitely happening on the latest version, cyclic must be doing something very strange.
