### ISSUE TITLE
Elivinia's Everburning Lantern Not Working

### ISSUE THREAD

**Issue by Darkoath2001** [Electroblob77/Wizardry#458]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.11 [change as necessary]
Environment: Server

Issue details: Conjured light doesn't last longer than the scripted time, 30s.

**Comment by Electroblob77** [comment]
It definitely works in my test environment. How are you equipping the lantern, and is baubles installed?
