### ISSUE TITLE
Freeze spell no longer freezes liquids

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#460]
Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: All

**Issue details:**

**Using the freeze spell on the water no longer turns it into ice.
This also applies to lava as well where it no longer turns it into obsidian/cobblestone.**

https://github.com/Electroblob77/Wizardry/blob/27d53b4e93f65303277da4c525d3feef9afff77c/src/main/java/electroblob/wizardry/spell/Freeze.java#L62-L76

Other mods involved: N/A

**Comment by Electroblob77** [comment]
I have also noticed this, it also applies to ice age. I'm looking into it, thanks for reporting.
