### ISSUE TITLE
Evil wizard crash

### ISSUE THREAD

**Issue by foldaren** [Electroblob77/Wizardry#462]
Game crashes when I assume the wizard casts a specific spell. Here is the crash report

[crash-2020-06-13_13.05.57-server.txt](https://github.com/Electroblob77/Wizardry/files/4775074/crash-2020-06-13_13.05.57-server.txt)

**Comment by Ghostrider231** [comment]
Your crash log is logging arcane essentials.

You also seem to be using an older version of arcane essentials (0.9.2). Perhaps update to the latest version of arcane essentials (1.0.0). If the issue still persists in the latest version, consider reporting to the arcane essentials' issue tracker.
