### ISSUE TITLE
Uh, oh, entity tick loop crash here

### ISSUE THREAD

**Issue by LUEZIS** [Electroblob77/Wizardry#463]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.11 [change as necessary]
Environment: Singleplayer/LAN game/Server [delete as necessary]

Issue details: [describe what you were doing when the issue occurred, what went wrong, what you expected to happen, etc.]

- I was sorting items in my own taking from Millenaire NPC's house, nothing so special.

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

- https://pastebin.com/k49sR7yS

**Comment by Ghostrider231** [comment]
The crash log mentions arcane essentials.

You also seem to be using an older version of arcane essentials (0.9.2). Perhaps update to the latest version of arcane essentials (1.0.0). If the issue still persists in the latest version, consider reporting to the arcane essentials' issue tracker.

**Comment by Electroblob77** [comment]
Yep, this is the same as #466, it's an old bug in arcane essentials that was fixed in the newest beta version.
