### ISSUE TITLE
Possible incompatibility with summons

### ISSUE THREAD

**Issue by wootaboot** [Electroblob77/Wizardry#465]
Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Server/Single

Issue details: When casting summon zombie/skeleton/wither skeley, the summon is hostile towards everything always. was expecting it to only be hostile towards things that are hostile towards me.

Other mods involved: rough mobs 2, zombie awareness(probably the problem)

**Comment by Electroblob77** [comment]
They should be hostile to mobs, any wizards, other players who aren't allied to you (and aren't on the same team), and mobs summoned by other non-allied players or wizards. You can set players for your summoned creatures to ignore, see https://github.com/Electroblob77/Wizardry/wiki/Ally-Designation-System. However, if they are attacking pigs, for example, then that's a bug.

**Comment by wootaboot** [comment]
The summon is attacking me the summoner, it has something to do with zombie awareness, found a bug report on it but that mod is not active. but you should be aware of the issue.

**Comment by Electroblob77** [comment]
Okay, I expect zombie awareness is overwriting the AI of the mobs you mentioned above. Does it have a blacklist option? It's unlikely I can get around this from my end.
