### ISSUE TITLE
Ticking Entity crash on server, when casting on non-Vanilla mobs.

### ISSUE THREAD

**Issue by Hakovu** [Electroblob77/Wizardry#467]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.2.11 
Environment: Server

Issue details: On various occations, when casting spells on mobs that are not Vanilla, it goes into a crash with a Ticking Entity problem.
This is both with direct target spells, AOE, and Summons attacking targets. 

Other mods involved: Bewitchment, Ice and Fire, Abyssalcraft
[crash-2020-06-27_15.48.02-server.txt](https://github.com/Electroblob77/Wizardry/files/4840630/crash-2020-06-27_15.48.02-server.txt)

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Electroblob77** [comment]
This appears to be an issue with Bewitchment, have you reported it to their issue tracker?

**Comment by Electroblob77** [comment]
Confirmed as an issue in Bewitchment, see https://github.com/Um-Mitternacht/Bewitchment/issues/598.
