### ISSUE TITLE
[How to cast spells for Weapons?]

### ISSUE THREAD

**Issue by Neoowiz** [Electroblob77/Wizardry#468]
version: 1.12.2   
Question details: [Greetings, I wonder if it is possible to cast your spells into weapons. As an example of JJ skills, 
* https://www.curseforge.com/minecraft/mc-mods/jj-skill * |The mod is specific and damp, I would like to know some functions or ideas on this subject. I saw similar in Arcane Essentials addon]
Other mods involved: [Spartan Weaponry-Metallurgy 4 reforged]

**Comment by Electroblob77** [comment]
No, weapons need special support to cast spells. Arcane essentials has special swords that are programmed to be able to cast spells.
