### ISSUE TITLE
Are the attributes that affect wizard armor and wands able to be applied to other equipment?

### ISSUE THREAD

**Issue by puncrafter** [Electroblob77/Wizardry#470]
Minecraft version: 1.12.2  
Wizardry version: 4.2.8 

I'm making a modpack using this mod, and I am trying to make the twilight forest trophies increase spell potency or decrease spell cost when worn. Is there a way to apply the attributes that make the wands and robes improve your spellcasting to something that isn't those wands or robes by using commands? 

For example, could I make wearing the Naga Scale Trophy give the player +50% Earth Spell Potency, or a -50% Earth Spell Cost?

**Comment by Electroblob77** [comment]
Not with commands, but it would certainly be possible with an addon (the spell modifiers don't use the vanilla attribute system).
