### ISSUE TITLE
Condenser stacks dont work as suggested

### ISSUE THREAD

**Issue by TheMightyMcGrew** [Electroblob77/Wizardry#472]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.2.11
Environment: Server 
Issue details: Stacked condenser upgrades dont not work as suggested, 1 or 3 is not different, they regen mana at the same speed

Other mods involved: Durability viewer to watch both durabilities progress at the same time (not involved in the problem but relevant i felt)

**Comment by Electroblob77** [comment]
The durability always ticks up at the same speed, but with 1 upgrade it should increase by 1 each time, with 2 it should increase by 2 and so on. I have tested this and can confirm it works as intended on my end.
