### ISSUE TITLE
[Thaumcraft Fire Projectile Bug]

### ISSUE THREAD

**Issue by spiderking23** [Electroblob77/Wizardry#473]
Minecraft version: 1.12.2 
Wizardry version: 4.2.11 
Environment: Singleplayer
Issue details: In order to progress in Auromancy, for Thaumcraft, which this mod shares the bauble compat with, one needs to be hit with a "Fiery Projectile" IE a Fire Charge from a Dispenser or Blaze. For some reason, this does not work due to the changes to the firecharge and blazes attacks. 

Other mods involved: Thaumcraft

**Comment by spiderking23** [comment]
I just noticed in the config the ability to change the blazes projectile, but i don't know if this will work. I'll test it later.

**Comment by Electroblob77** [comment]
See #443. The config option is supposed to address this, but there is possibly a problem with it.
