### ISSUE TITLE
Cascading worldgen lag on first time server start.

### ISSUE THREAD

**Issue by xVVitch** [Electroblob77/Wizardry#476]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.11 [change as necessary]
Environment: Server [delete as necessary]

Issue details: Started my server and was watching the console and saw this pop up:

Server thread/WARN [FML]: Electroblob's Wizardry loaded a new chunk [2, 7] in dimension 0 (overworld) while populating chunk [1, 7], causing cascading worldgen lag.

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by xVVitch** [comment]
oops i forgot to change the title, sorry!

**Comment by Char022** [comment]
I've gotten this error too - It really doesn't seem to actually cause lag for me. I'm pretty sure what it's essentially saying is "Hey, they're making a wizard tower here, but they also loaded another chunk. This could cause lag."
However, seeing as it's only one additional chunk, I don't see this causing much lag. For me, it's just happened any time an Electroblob's structure generated, and it hasn't caused lag spikes yet.

It's probably in there in case a mod loads a few hundred extra chunks at once, not one, as that would certainly cause lag.

**Comment by Electroblob77** [comment]
@Char022 I've only just seen your comment sorry, it's quite an old issue and I don't often check this far down. What you've said there is correct, a small amount of cascading worldgen is not a big deal - however, I made some changes in the 4.3 release that should have eliminated it entirely. Could you confirm the version of wizardry _you_ were using when you got that log message?

**Comment by Char022** [comment]
@Electroblob77 I was using 4.2 when I got the log messages. After switching to 4.3, these logs no longer show up.

**Comment by Electroblob77** [comment]
Great, I'll mark this as fixed then!
