### ISSUE TITLE
Font of Mana is not working.

### ISSUE THREAD

**Issue by Tegamin** [Electroblob77/Wizardry#477]
Bug: Font of Mana doesn't work. 

Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Singleplayer

Hello! I've always been having fun with your mod but recently I come across a problem. The Font of Mana is not shortening the cool down time of any spell as expected no matter the level of the effect. 
Could you have a check on it?

**Comment by Electroblob77** [comment]
I can check it, last time I tried it was working
