### ISSUE TITLE
Crash when open handbook

### ISSUE THREAD

**Issue by yajiedesign** [Electroblob77/Wizardry#487]
Minecraft version: 1.12.2 
Wizardry version: 4.2.11
Environment: Server

Issue details: Crash when open handbook ,my language is chinese.It look like handbook_zh_cn.json endcode error.i I am change handbook_zh_cn.json to ansi encode,it work fine.

Other mods involved: 

Link to crash report (if applicable): [latest.log](https://github.com/Electroblob77/Wizardry/files/5050511/latest.log)

**Comment by TUsama** [comment]
建议先看看站内搬运贴，我们已经解决了，下版本该问题已被修复。
https://www.mcbbs.net/forum.php?mod=viewthread&tid=894070&page=1#pid15117644
