### ISSUE TITLE
Growth aura causes Timeout and server crash

### ISSUE THREAD

**Issue by Hakovu** [Electroblob77/Wizardry#488]
Minecraft version: 1.12.2  
Wizardry version: 4.2.11 
Environment: Server

Issue details: Cast Growth Aura, while wearing the augmenting Bauble. It was used on Bewitchment crops, on Rustic fertile soil.

Other mods involved: Bewitchment, Rustic
[crash-2020-08-11_16.12.29-server.txt](https://github.com/Electroblob77/Wizardry/files/5057465/crash-2020-08-11_16.12.29-server.txt)

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Electroblob77** [comment]
Okay, I'll take a look. Thanks for reporting.
