### ISSUE TITLE
Crash when opening Spells tab

### ISSUE THREAD

**Issue by Sepinula** [Electroblob77/Wizardry#490]
Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Singleplayer/LAN game/Test Server

Issue details: [so i created a new spell and everything and i'm not sure what i did wrong sadly but whenever i add the spell to the mod and i go on the spells tab of the mod it crashes me, i did try to remove all files from my spell i opened it once again and it said the spell was missing (The one i created) so that means my spell was added but when i went to the creative tab and tried to open the spells tab it was working again is there something i should be changing on the creative tabs part of the mod so i won't crash hoping you could help me thanks.]

Link to crash report (if applicable): https://pastebin.com/XdaKZzfa

Also do you have a discord server or something where i could join?

**Comment by Sepinula** [comment]
Nevermind about the discord server i found it

**Comment by Sepinula** [comment]
I talked to a support on your server and he helped me a lot :D his name is Dan(WinDanesz)

**Comment by Electroblob77** [comment]
Oh cool, yeah Dan is helpful like that, he knows the code pretty well. Glad you sorted it out, can't wait to see what spells you make!
