### ISSUE TITLE
[Give a brief, relevant title here]

### ISSUE THREAD

**Issue by subzerofox** [Electroblob77/Wizardry#492]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.11 [change as necessary]
Environment: Singleplayer

Issue details: Wizard in tower cast a spell when hostile, game crashed.

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report: https://pastebin.com/6Pentt0u

**Comment by Electroblob77** [comment]
This is a bug in the arcane essentials spell pack. Try updating to the latest beta of arcane essentials, that might fix it.

**Comment by subzerofox** [comment]
Thanks for the response, I'll give it a try.
