### ISSUE TITLE
Plans for 1.15.2?

### ISSUE THREAD

**Issue by willwh** [Electroblob77/Wizardry#496]
Minecraft version: 1.15.2 
Wizardry version: TBD :) 

Hello @Electroblob77  :) Awesome work on this mod, it's great :+1: - do you have plans to start a port for 1.15.2? I would love to help get Wizardry ready for 1.15.2!

**Comment by TUsama** [comment]
nope, you can join the discord and see the reason.

**Comment by willwh** [comment]
Understood, thank you!
