### ISSUE TITLE
Mine little pony crash with Wizardry

### ISSUE THREAD

**Issue by omnislash772** [Electroblob77/Wizardry#497]
Minecraft version: 1.12.2
Wizardry version: 4.2.11 
Environment: Singleplayer 

Issue details: Pressing the skins button in the Mine little pony mod on the main menu causes Wizardry to null pointer and freeze client

Other mods involved: Mine Little Pony/HDskins, Liteloader

Link to crash report (if applicable): https://pastebin.com/yQjwnk9K

**Comment by Electroblob77** [comment]
Hmm okay, I don't know why I'm even using the client player there when there's a perfectly good one in the event... I've rewritten the on-player render effects for 4.3 anyway so I'll just double check that I haven't done the same thing again, should be fixed in the next release.
