### ISSUE TITLE
Ticking Entity Causing Server Crashes (Reoccurring Problem)

### ISSUE THREAD

**Issue by SageofSouls001** [Electroblob77/Wizardry#498]
Minecraft Launcher: GDLauncher
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2854
Electroblob's Wizardry Version: 4.2.11
Environment: Server

Issue Details: Basically, my friend who was on my server was running around and an Evil Wizard became a ticking entity. This is not the first time this has happened.

Other Mods Involved: Arcane Essentials (version 0.9.2)

Crash Report: https://pastebin.com/2gkFX1L2

Other Notes: I have read that this was a common issue when Electroblob's Wizardry interacted with Bewitchment, and I do actually have Bewitchment, but nowhere in the error portion of the crash log did it say anything about Bewitchment, so I don't think that's the problem. According to the crash log, the only other mod listed in the error was Arcane Essentials, but that's an addon mod to Electroblob's Wizardry to my understanding. The only fix I've been able to do for this is to just delete the associated chunk's .mca file and let it regenerate, but that's not really a solution to the problem as a whole, only how to get rid of that instance of the ticking entity.

Full List of Mods (for if needed): https://pastebin.com/dKbpQBkF

**Comment by Electroblob77** [comment]
This is a bug in arcane essentials (same as #429, #463, #466, #492, and probably others). It was fixed in the latest _beta_ version of arcane essentials so try updating to that.

**Comment by SageofSouls001** [comment]
Forgive me for reopening this. I wasn't sure if it'd be more appropriate to open a new thread or reopen this one, given that I'm still having the same issue, but now with other mods. If you would prefer me to open a new thread whenever this problem occurs again but with different mods being the cause, please let me know and I'll do so in the future.

(Unchanged) Minecraft Launcher: GDLauncher
(Unchanged) Minecraft Version: 1.12.2
(Unchanged) Forge Version: 14.23.5.2854
(Unchanged) Electroblob's Wizardry Version: 4.2.11
(Unchanged) Environment: Server

Issue Details: Same as before, but this time it's just a regular Minecraft Zombie being ticked.

Other Mods Involved: Epic Siege Mod (version 13.167) and Foam Fix (version 0.10.10) both appear to be mentioned in the crash log.

Crash Report: https://pastebin.com/VbC6hLK8

Other Notes: I did update Arcane Essentials to version 1.0.0-alpha-6, but this crash report does not appear to mention Arcane Essentials. However, that doesn't mean that I can confirm that the update has eliminated Arcane Essentials from ever having this problem in the future.

Full List of Mods (for if needed): https://pastebin.com/mN5MLLqh
(Note: This is an updated mod list from before. There have been some additions since the last time this error was reported. However, Elecrtoblob's Wizardry, itself, has not changed versions since the last report. The update comes from having Arcane Essentials and The Twilight Forest receiving updates and a few mods being added.)
