### ISSUE TITLE
Ticking Entity Again (Different Responsible Mod)

### ISSUE THREAD

**Issue by SageofSouls001** [Electroblob77/Wizardry#499]
I had wanted to keep using my previous thread for this issue, since it was the same issue, but with a different responsible mod(s), but I guess once the thread's closed, it doesn't get looked at anymore. I'm sorry for the repost.

(Unchanged) Minecraft Launcher: GDLauncher
(Unchanged) Minecraft Version: 1.12.2
(Unchanged) Forge Version: 14.23.5.2854
(Unchanged) Electroblob's Wizardry Version: 4.2.11
(Unchanged) Environment: Server

Issue Details: Same as before, but this time it's just a regular Minecraft Zombie being ticked.

Other Mods Involved: Epic Siege Mod (version 13.167) and Foam Fix (version 0.10.10) both appear to be mentioned in the crash log.

Crash Report: https://pastebin.com/VbC6hLK8

Other Notes: I did update Arcane Essentials to version 1.0.0-alpha-6, but this crash report does not appear to mention Arcane Essentials. However, that doesn't mean that I can confirm that the update has eliminated Arcane Essentials from ever having this problem in the future.

Full List of Mods (for if needed): https://pastebin.com/mN5MLLqh
(Note: This is an updated mod list from before. There have been some additions since the last time this error was reported. However, Elecrtoblob's Wizardry, itself, has not changed versions since the last report. The update comes from having Arcane Essentials and The Twilight Forest receiving updates and a few mods being added.)

**Comment by Electroblob77** [comment]
This is not the same kind of crash at all, Minecraft has run out of memory (it just happens to have run out while an entity was being ticked). How much RAM have you allocated to your installation?

Not entirely sure why you're reporting this here since wizardry isn't even mentioned in the stacktrace.

**Comment by SageofSouls001** [comment]
Probably because A. I'm an idiot who didn't read the log correctly and B. I made an assumption that it was a Wizardry thing again. -.-

I apologize. You can close this, since it has nothing to do with Wizardry.

As for the memory thing, I have 10 GB dedicated to the server, which I thought would be enough. I'll continue to look into it. Sorry for bothering you.

**Comment by Electroblob77** [comment]
That's ok, hope you find a fix for it! 10GB should be more than enough RAM, unless the server has loads of worlds running at once, I suspect you may have a mod hogging memory somewhere...
