### ISSUE TITLE
Throwable entites still hit their caster at point blank range

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#50]
Minecraft version: 1.12.2
Wizardry version: 4.1.2
Environment: Both

Issue details: 
This bug behaves differently for mobs and players apart. Although the patch did fix most of the spells except for **Darkness orb**.

**Players** can hurt themselves at point blank range when using the darkness orb spell at a target. If I cast it against a wall, it won't hurt me,

It won't matter where your angle is, so as long you're in point blank range of your target. So you can be looking up towards your target.

**Wizards** seems to be somewhat similar, except firebomb can also (sorta?) hurt them at point blank range.

**Note: I've tested without any other mods involved, so the same issue still applies.**

Reproducing is shown in the videos. You only need to cast Darkness Orb to reproduce the issue more effectively. 

----------------------------

**Videos of the issue** (sounds included):

**Players:**

https://www.youtube.com/watch?v=kpBKFfdg66Y

---------------------------

**Wizards:**
Notice, Slimes in vanilla ONLY attack the player and always.

https://www.youtube.com/watch?v=gLgTT7FFKVg

**Comment by Ghostrider231** [comment]
The Wizards video is still taking it's time processing, so it may take a while.

update: oh wait nvm, it's up now.

**Comment by Electroblob77** [comment]
I'll have to look into this properly then, thought I'd fixed it in 4.1.2.
