### ISSUE TITLE
Ticking Entity when cast necromancy spell Zam or Zamle

### ISSUE THREAD

**Issue by OttoOttoman** [Electroblob77/Wizardry#500]
Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Server, have not tested on singleplayer

Issue details: When a dark wizard used the spells zam or zamble my server crashed from entity ticking. Once I turned off zam and zamble in config the crash stopped.

Other mods involved: Ice & Fire, Arcane Essentials, Minecraft Comes Alive

Link to crash report (if applicable): https://pastebin.com/rexrd1sZ

**Comment by TUsama** [comment]
It's a bug from Arcane Essentials(maybe)

**Comment by Electroblob77** [comment]
Yes, this is a bug in arcane essentials. Try updating it to the latest _beta_ version, I think it got fixed in that patch.
