### ISSUE TITLE
Additional Configs

### ISSUE THREAD

**Issue by Naigaru** [Electroblob77/Wizardry#501]
Minecraft versions: 1.12.2

Suggestion details: Could we get an option in the config to enable and disable the custom item tooltips that the mod introduces? This includes the spell potency, current spell, mana and progression tags. Also an option to enable / disable the spell gui, as well as the icon (this isn't as important tho as it is possible to hide this by causing it to render off screen).

**Comment by Electroblob77** [comment]
Yes, that should be easy enough to do for the tooltips. I've actually already added an option to hide the spell HUD in my dev branch so that should cover the entire thing including the icon.

**Comment by Electroblob77** [comment]
This feature has been added in 4.3, closing.
