### ISSUE TITLE
Probability of "Ancient compass"

### ISSUE THREAD

**Issue by Horus8823** [Electroblob77/Wizardry#502]
Minecraft version: 1.12.2
Wizardry version: 4.2.11
Environment: Singleplayer
Issue details: I verified one thousand shrine's chests, but there are not "Ancient compass". I think about loot table be not writen about "Ancient compass".
P.S. I verified about "Ancient compass" only, I don't verified other artifact.
I attach world data that I verified.

Other mods involved: none

Digression: your mod is very great, intresting, and charming!
 I wish you continued success and health.
[Verification.zip](https://github.com/Electroblob77/Wizardry/files/5284098/Verification.zip)
![2020-09-26_01 23 34](https://user-images.githubusercontent.com/71891659/94293467-41f6e480-ff99-11ea-90f6-7f925ff44c98.png)

**Comment by WinDanesz** [comment]
Its a known issue that the loot table doesn't include it, so I hope you didnt literally open 1000 chests to find that out

**Comment by Electroblob77** [comment]
I appreciate the effort, thanks! I've fixed it in my dev branch so the fix will be in the next release.

**Comment by Horus8823** [comment]
Sorry! I forgot check known issue;;
Thank you for everyone's Polite correspondence!

**Comment by Electroblob77** [comment]
This has now been fixed in the 4.3 release.
