### ISSUE TITLE
My launcher won't launch. Please help.

### ISSUE THREAD

**Issue by Caperised** [Electroblob77/Wizardry#507]
Minecraft version: 1.12.2   
Wizardry version: 4.2.11

I have the latest version of forge (1.12.2-forge-14.23.5.2854) and I am just trying to load the Wizardry with no other mods. I am using macOs version 10.13.6.

When I try and launch the game it says 'Exit Code: 0'
Please tell me what to send to help you understand what went wrong. Sorry I don't know much about computer stuff.

**Comment by Electroblob77** [comment]
I'll need a crash report and/or a log file. Crash reports can be found in `.minecraft/crash-reports` (if you're using the default `.minecraft` folder, if not then substitute the directory you're running the game in), and the most recent log file can be found at `.minecraft/logs/latest.log`.

**Comment by Caperised** [comment]
Oh it's fine I know the problem now. Thanks.
