### ISSUE TITLE
No Mobs spawning

### ISSUE THREAD

**Issue by Nerdskillz** [Electroblob77/Wizardry#508]
Minecraft version: 1.12.2 
Wizardry version: 4.2.11
Environment: Singleplayer/LAN game

Issue details: When having electroblobs wizardry installed, no mobs spawn. Neither vanilla nor modded mobs.

Other mods involved: There were a few world gen mods, (traverse, biomes o plenty) but even after removing those the issue persisted.

**Comment by Electroblob77** [comment]
There was a problem like this in version 4.2.5 but it was fixed in 4.2.6, are you sure you're using 4.2.11?

**Comment by WinDanesz** [comment]
Closing inac
