### ISSUE TITLE
Ticking entity crash, probably related to this mod, crash report in the details

### ISSUE THREAD

**Issue by KenshinSpirit** [Electroblob77/Wizardry#514]
Minecraft version: 1.12.2
Wizardry version: 4.2.11 [change as necessary]
Environment: Singleplayer

Issue details: I was mining underground for diamonds, when suddenly, while mining coal, the game crashed cause of a ticking entity, later revealed to be an evil wizard in the crash report. I don't know if it is strictly related to this mod, as I have a few. I can provide a list if necessary.

Other mods involved: Unknown

Link to crash report (if applicable): https://pastebin.com/RG8jPH8G

**Comment by Falcion** [comment]
**A similar situation: server and client crash almost at the same moment.**

**Both client and server Minecraft version:** 1.12.2.
**Both client and server Wizardry version:** 4.2.11.
A similar situation, but with the server and the client at the same time: the evil wizard does not even have to interact with the player (attack, summon creatures, etc.), but throws it out as the server side (the error is indicated as _TickEntity_ and points to Electroblob's Wizardry and entity with ID: _ebwizardry: evil_wizard_) and from the client side:

[Crash report from server](https://hastebin.com/wegedagoci.rb)

[Crash report from user](https://hastebin.com/guhanayepa.rb)
[Another crash report from user](https://hastebin.com/jerinevivu.rb)

**Comment by Electroblob77** [comment]
These are a variety of different crashes all related to the Arcane Essentials spell pack. I believe they were all fixed in the latest _beta_ version.
