### ISSUE TITLE
Cooldown for scrolls

### ISSUE THREAD

**Issue by ghost** [Electroblob77/Wizardry#515]
Minecraft versions: 1.12.2

Suggestion details: Scrolls are really spammy with a whole stack or when on creative because there is no cooldown after using them. Scroll of Charge for example gives you pretty amusing results for really fast travel. Having an item cooldown similar to ender pearls would be nice.

**Comment by Electroblob77** [comment]
Funny you should say that, I've already added this feature to the upcoming library update (4.3) so you'll see it in the mod very soon!

**Comment by Electroblob77** [comment]
This feature has now been added, closing.
