### ISSUE TITLE
Player animations conflict with the Betweenlands' rendering system

### ISSUE THREAD

**Issue by Airisii** [Electroblob77/Wizardry#518]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3 [change as necessary]
Environment: Singleplayer

Issue details: Making a new world 

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): https://pastebin.com/5NRBdVAe

**Comment by Electroblob77** [comment]
Wizardry's player animations seem to be conflicting with the betweenlands' rendering system. I'll see if there's something I can do on my end to fix it, but for now you can avoid the crash by turning player animations off in the config.
