### ISSUE TITLE
Wizard mob ticking entity crash

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#519]
Minecraft version: 1.12.2
Wizardry version: 4.3
Environment: All

Issue details: When trying out the new update, and with every new update I always do the wizard mob horde test (wizards vs evil wizards)

### How I did it:

1. Be in creative mode
2. Have both the wizard and evil wizard eggs (Easier and faster then finding wizards)
3. Spawn both as many as possible (make sure they can see each other)
4. Watch them fight

**From the crash logs, it seems to be mentioning spellray related spells.**
**UPDATE:** Just did it with a newly generated config, and it still happens.

Other mods involved: N/A

**Link to crash report (if applicable):**  https://pastebin.com/JMPUqtmC
I also had another crash where it mentions about the freeze spell itself: https://pastebin.com/r8B69U6v

**Comment by Electroblob77** [comment]
Okay, I think those two reports are different crashes but one may be a result of the other. I'll see what I can do.

**Comment by Ghostrider231** [comment]
Just wanted to update. So apparently with the crash regarding the freeze spell itself, I managed to get one with a BOP plant instead of an air block: https://pastebin.com/A4c0NJ35
Comparing this crash to the air one, I seem to be getting the same crash index? (Instead of Blocksnow, I get BlockBOPPlant)

**Comment by Electroblob77** [comment]
I've just seen the problem, and it's really stupid 🤦‍♀️

https://github.com/Electroblob77/Wizardry/blob/378e19a6148064fc812e87357e05fb378f84469e/src/main/java/electroblob/wizardry/util/BlockUtils.java#L413-L427

I'm checking if the block above the targeted block is replaceable, but I'm checking it on the targeted block type, which is obviously not the same block as the position I'm checking. Easy fix, will be in the next patch.
