### ISSUE TITLE
Wizards (not evil) no longer sound like villagers

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#52]
Minecraft version: 1.12.2
Wizardry version: 4.1.2
Environment: Client

Issue details: 
Wizards **(not evil cause they use witch sounds)** no longer use villager sounds whenever they get hurt, killed, or make idle noises.

A suggestion, you could even give wizards (and evil) their own sound events (they can still use vanilla sounds), rather then sharing sound events from vanilla. So that resource pack makers are allowed to change them without affecting vanilla ones.

### **Vanilla sound events borrowed:**
**(Used by Evil Wizard at a lower pitch)**
entity.witch.ambient
entity.witch.hurt
entity.witch.death

**(Used by Wizard. Well, they used to)**
entity.villager.ambient
entity.villager.hurt
entity.villager.death

### **Wizardry's new sound events:**
wizard.ambient **(uses entity.villager.ambient sounds)**
wizard.hurt **(uses entity.villager.hurt sounds)**
wizard.death **(uses entity.villager.death sounds)**

wizardevil.ambient **(uses entity.witch.ambient sounds at pitch 0.7)**
wizardevil.hurt **(uses entity.witch.hurt sounds at pitch 0.7)**
wizardevil.death **(uses entity.witch.death sounds at pitch 0.7)**

**Example for Borrowing Vanilla Sounds:**

  "wizardevil.hurt": {
    "sounds": [
      {
        "type": "event",
        "name": "minecraft:entity.witch.hurt",
        "pitch": 0.7
      }
    ]
  }

**Comment by Electroblob77** [comment]
Yeah that's definitely a good idea, I'll get it done for the next update.

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
