### ISSUE TITLE
Imbuement Altar bug

### ISSUE THREAD

**Issue by Hokorizero** [Electroblob77/Wizardry#520]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3 [change as necessary]
Environment: Singleplayer

Issue details: Please look at the GIF. If I place 4 receptacles on each side of the altar, the item on will drop out, the dusts in the receptacles and the item on the altar will disappear
Other mods involved: none

![altar_bug (1)](https://user-images.githubusercontent.com/50108932/97067690-9f3d8000-15af-11eb-966a-3620936f0aa8.gif)

**Comment by Electroblob77** [comment]
Can confirm this is a bug, will be fixed ASAP.
