### ISSUE TITLE
Dynamic trees issue

### ISSUE THREAD

**Issue by DaniilGa** [Electroblob77/Wizardry#522]
Minecraft version: 1.12.2 
Wizardry version: 4.3 
Environment: Singleplayer

Issue details: Minecraft crashes if electroblobs wizardry version 4.3 is installed. There were no such errors before.

Other mods involved: dynamic trees

**Comment by Electroblob77** [comment]
Crash report please.

**Comment by DaniilGa** [comment]
[crash-2020-10-25_18.56.54-client.txt](https://github.com/Electroblob77/Wizardry/files/5434859/crash-2020-10-25_18.56.54-client.txt)

**Comment by DaniilGa** [comment]
[Uploading crash-2020-10-25_19.00.49-client.txt…]()

**Comment by DaniilGa** [comment]
[crash-2020-10-25_19.00.49-client.txt](https://github.com/Electroblob77/Wizardry/files/5434870/crash-2020-10-25_19.00.49-client.txt)

**Comment by Electroblob77** [comment]
Ah right, so that's what that crash is... okay, in that case this is the same crash as #517, so please post any further info there. Thanks for helping track it down.

**Comment by DaniilGa** [comment]
Thank you very much. By the way, I am very glad that there are such awesome mods as this mod.
