### ISSUE TITLE
Crash when using a spell with shaders on

### ISSUE THREAD

**Issue by nickiminaj22** [Electroblob77/Wizardry#524]
https://pastebin.pl/view/a29072f4
Whenever I have a shader on it causes a crash when you try to use a spell.

**Comment by Electroblob77** [comment]
This is nothing to do with shaders. Wizardry's player animation system is conflicting with MoBends' animation system. The two systems are not compatible, please either disable wizardry's player animations in the config or uninstall MoBends. I may make it auto-disable itself if MoBends is installed to prevent this from happening.
