### ISSUE TITLE
lock on world startup - NO dynamic trees installed

### ISSUE THREAD

**Issue by seefourdnd** [Electroblob77/Wizardry#525]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3 [change as necessary]
Environment: Singleplayer/LAN game/Server [delete as necessary]

Issue details: Game world locks up on start. 

"The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Rendering entity in world
Exit Code: -1"

Other mods involved: [Optifine seems to be the kicker, without optifine the world runs.  Previous version of Wizardry works with all installed mods listed in crash report.]

Link to crash report - https://pastebin.pl/view/b0cdf32f

I am only posting this because it seems you've pinned the crash down to dynamic trees, maybe this is a different crash, I am not sure!

**Comment by Electroblob77** [comment]
This seems to be the same crash as #518. Do you have betweenlands installed?

**Comment by seefourdnd** [comment]
no inbetween lands, also I tried what you suggested on cursed forge(disabling custom shaders for Wizardry) - same crash.

**Comment by Electroblob77** [comment]
Thanks for the reply. I didn't think disabling the shaders would work, but it was worth a try. That is interesting that you don't have the betweenlands, maybe it's not to blame for the other issue either? Or perhaps another mod is also conflicting (maybe Optifine, as you say)? I'll leave both issues open for now, time to do some digging...

**Comment by seefourdnd** [comment]
yes, it is kind of strange eh?  I can tell you that the new Wizardry runs fine with my mod setup if I disable optifine

I wish you the best of luck because this seems like an amazing update, and I cannot wait to play it :)

**Comment by Electroblob77** [comment]
Okay great. This is the same crash so I'm going to assume that optifine is also doing whatever the betweenlands does to cause this crash. More importantly, the fix should be the same!
