### ISSUE TITLE
Model Baking crash on startup

### ISSUE THREAD

**Issue by brisingraerowing** [Electroblob77/Wizardry#531]
Minecraft version: 1.12.2
Wizardry version: 4.3
Environment: Singleplayer

Issue details: Crash on startup

Other mods involved: Unknown. I'm doing more testing.

Link to crash report (if applicable): [Crash Log](https://gist.github.com/BrisingrAerowing/31fa655b5ed1e2ec55acf251f4eddad0)

**Comment by Electroblob77** [comment]
Duplicate of #517.
