### ISSUE TITLE
Casting Spells crashes other nearby players

### ISSUE THREAD

**Issue by Char022** [Electroblob77/Wizardry#533]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.3 
Environment: Server

Issue details: Any time a player casts a spell, other players in that area get a light blue colored screen and crash within seconds.

Other mods involved: While we are playing on a modpack I made, this issue never once happened until we updated to 4.3, and as that was the only change we made, I don't think the other mods caused it. If I need to, I can paste the modpack mod list in a reply

Link to crash report (if applicable): MultiMC hasn't generated a crash report yet which is weird, but I'll continue testing it and try to get one.

**Comment by Char022** [comment]
We have also specifically tested:
Greater telekinesis (Used on player)
Lightning Bolt (Within sight of player, not sure if it is necessary to be looking at it however)
Mind Trick (Used on player)
Light (Within render distance, not line of sight)
Curse of Soulbinding (Used on player, lots of crashes)
Summon Zombie (Within render distance, not line of sight)

We've agreed to stop casting spells near each other but we have yet to find a spell that doesn't cause a crash, with the exception of a scroll of conjure bow.

**Comment by alphaNumeric01** [comment]
Can confirm. Invigorating presence and Summon Wither Skeleton caused my friend to crash as well.

**Comment by Electroblob77** [comment]
Okay thanks, but I will need a crash report to solve this. You can usually find them in your game directory, not sure how MultiMC does it but one way or another it will use `.minecraft` or a folder exactly like it.

**Comment by Char022** [comment]
![image](https://user-images.githubusercontent.com/41021864/97731716-dfb76500-1aab-11eb-83c3-47ae32f2756a.png)
Here's the server output
And I found the crash reports the crash reports

https://gist.github.com/Char022/59039b202a7221fcfbbd3a2c475e0734
Hope this helps!

**Comment by Char022** [comment]
Also, let me know if you need me to test anything else on the server. I should be able to get more crash reports if it helps.

**Comment by Char022** [comment]
Upon futher testing, going into 3rd person view via F5 while maintaining a greater telekinesis spells also crashes the game. The reports are here:
https://gist.github.com/Char022/54f2c7bad5bfbb4df42de2f5ab4a4c1e

**Comment by Electroblob77** [comment]
Thanks for getting those, they're both the same crash so I should be able to fix both at once.

In the meantime, since this is due to the player animation system you should be able to avoid the issue by disabling spellcasting animations in the config. _Make sure all players do this as it's a client-side setting._
