### ISSUE TITLE
Reskillable addon CompatSkills prevents Recharging mana and applying spells to wands

### ISSUE THREAD

**Issue by luna6667** [Electroblob77/Wizardry#534]
Minecraft version: 1.12.2
Wizardry version: 4.3 
Environment: Singleplayer/Server 

Issue details: Unable to recharge mana/Apply spells to wands with the CompatSkills addon for Reskillable, even with level restrictions not applied. The animation plays, but nothing actually happens.  Previous version of Wizardry works. 

Other mods involved: Reskillable with Compatskills addon. 

Link to crash report (if applicable): N/A

**Comment by Electroblob77** [comment]
That is probably because the addon is not yet updated to work with wizardry 4.3.

**Comment by MagmaSlime123** [comment]
Reskillable & its addon is dead.

**Comment by Electroblob77** [comment]
Assumed external bug.
