### ISSUE TITLE
My game crashes when starting my mod Pack

### ISSUE THREAD

**Issue by PfeiNi230327** [Electroblob77/Wizardry#535]
Minecraft version: 1.12.2
Wizardry version: 4.3
Environment: Singleplayer

Issue details: I started my game and it crashed when using electroblobs wizardry
Other mods involved: 

Link to crash report
[crash-2020-10-30_15.06.04-client.txt](https://github.com/Electroblob77/Wizardry/files/5465620/crash-2020-10-30_15.06.04-client.txt)

**Comment by brisingraerowing** [comment]
Duplicate of #517
