### ISSUE TITLE
crash upon world load

### ISSUE THREAD

**Issue by rwja16** [Electroblob77/Wizardry#538]
Minecraft version: 1.12.2 
Wizardry version: 4.3 
Environment: Singleplayer

Issue details: I updated the mod to 4.3 on my personal modpack, now my game crashes every time I try to load a world, and VanillaFix points Wizardry as the mod that is causing the crashes. 
Maybe the same as #525 ?

Other mods involved: Not sure, maybe OptiFine? (big modpack, consider checking the modlist at the crash report)

Link to crash report: [pastebin](https://pastebin.com/DLxG0qUL)

**Comment by Electroblob77** [comment]
Yes, this is the same as #525 and #518.
