### ISSUE TITLE
[Suggestion]More player models support

### ISSUE THREAD

**Issue by B-Wither** [Electroblob77/Wizardry#539]
Minecraft versions: [if this suggestion only applies to some versions, list them here]
1.12.2

Suggestion details: [describe what you would like to see added to the mod and why]
I think it would be even more appealing if the magical animations were applied to the models added in More player models.
For example, Quark's emotes are supported, so you may want to use that technology.

Other mods involved: [if this suggestion involves integration with other mods, list them here]
[More Player Models](https://www.curseforge.com/minecraft/mc-mods/more-player-models)
[Quark](https://www.curseforge.com/minecraft/mc-mods/quark)

**Comment by Electroblob77** [comment]
I believe this was made possible by the fix in 4.3.2, see issue #551.

**Comment by B-Wither** [comment]
Thank you!

**Comment by B-Wither** [comment]
It seems that custom animation is not accepted with MPM, although I didn't change its config.
