### ISSUE TITLE
Crash when using spell (From vadudosinka)

### ISSUE THREAD

**Issue by Vadimaldo** [Electroblob77/Wizardry#54]
Minecraft version: 1.12.2   
Wizardry version: 4.1.2   
Environment: Singleplayer

Issue details: Just use "Trap spell" on Slime

Other mods involved: ActullyAdditions
                                    AlternateFlux
                                    AntiqueAtlas
                                    AP2
                                    AstralSorcery
                                    Baubles
                                    BiblioCraft
                                    Bonfires
                                    ChikenChunks
                                    ElectroblobsWizardy
                                    Embers
                                    ExtraCells
                                    HorsePower
                                    IceAndFire
                                    Immersive Ingineering (petroleum)
                                    JEI
                                    JER
                                    MegaLoot
                                    NuclearCraft
                                    OpenGlider
                                    OptiFine
                                    Prefab
                                    Roots
                                    SimpleRPG
                                    StorageDrawlers
                                    TConstract (TinkerToolLeveling)
                                    Thaumcraft
                                    ThermalExpansion (Dynamics, Foundation)
                                     TTRF
                                     xRay
                                     +Libraries for mods

Link to crash report (if applicable): 
[crash-2018-06-17_11.26.03-client.txt](https://github.com/Electroblob77/Wizardry/files/2109044/crash-2018-06-17_11.26.03-client.txt)

**Comment by Electroblob77** [comment]
This is actually the same issue as #15, it's caused by Optifine.
