### ISSUE TITLE
Electroblob's Wizardry: Twilight Forest Spell Pack latest version mod incompatible with Electroblob's Wizardry newly updated latest main mod.

### ISSUE THREAD

**Issue by MattLikesGaming** [Electroblob77/Wizardry#545]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.3.1
Environment: Starting up server

Issue details: I was trying to start up the game with the updated mod and I keep receiving this message even though I have the latest version for both of them. I have the latest version 4.3.1 but says it requires version 4.3 for Electroblob's Wizardry main mod.

Other mods involved: Electroblob's Wizardry: Twilight Forest Spell Pack 1.0.2

Link to crash report (if applicable): https://pastebin.com/wVKjGBj2
![Capture](https://user-images.githubusercontent.com/39849197/98334859-b2414e80-1fb8-11eb-95f3-8726315053de.PNG)

**Comment by Electroblob77** [comment]
This is working as intended. TF spell pack is not yet updated to work with wizardry 4.3, please be patient!

**Comment by MattLikesGaming** [comment]
Will do thank you for telling me on whats going on
