### ISSUE TITLE
minecraft Crash electroblob/wizardry/client/renderer/RenderMagicArrow

### ISSUE THREAD

**Issue by Phan7om012** [Electroblob77/Wizardry#546]
Minecraft version: 1.12.2   
Wizardry version: 4.3.1 
Environment: Singleplayer

Issue details: Crashing after loading minecraft here is the link for a crash report

Link to crash report : [crash-2020-11-06_11.52.56-client.txt](https://github.com/Electroblob77/Wizardry/files/5501124/crash-2020-11-06_11.52.56-client.txt)

**Comment by Electroblob77** [comment]
Okay... this looks like the kind of error that happens when the dedicated server tries to load a client class, except you're not on a dedicated server! Try redownloading the newest version of wizardry (currently 4.3.1).

**Comment by Phan7om012** [comment]
I redownloaded as you said and it didin't work, the same crash appears as before

**Comment by Electroblob77** [comment]
Okay, I'll look into it then, thanks.

**Comment by Sawors** [comment]
I had the same issue, apparently this is ExtraSpells spell pack that causes this incompatibility. I tested it with a clean profile with and without the pack and it crashed like that with the pack

Hope it could help :D

**Comment by Phan7om012** [comment]
Pal it was very helpfull ! Thanks to you I was able to indetify the problem by myself, it was outdated extraspells mod that was causing the crash, All I had to do was to update the extraspells mod and thats its, everething is working now

**Comment by Electroblob77** [comment]
Assuming this is resolved.
