### ISSUE TITLE
JSON syntax error in translations

### ISSUE THREAD

**Issue by wong012** [Electroblob77/Wizardry#552]
Minecraft version: 1.12.2 
Wizardry version: 4.3.1 
Environment: Singleplayer

Issue details: It malfunctions when starting the game

Link to crash report (if applicable):  
[crash-2020-11-12_00.49.26-client.txt](https://github.com/Electroblob77/Wizardry/files/5525562/crash-2020-11-12_00.49.26-client.txt)

**Comment by Electroblob77** [comment]
Seems to be the same as #561, it's an issue with the translations. What is your language set to?

**Comment by TUsama** [comment]
They seem are all using Traditional Chinese as their current language. In the https://github.com/Electroblob77/Wizardry/blob/14e481a71dd91462ce3a137737e6c66b672e371c/src/main/resources/assets/ebwizardry/texts/handbook_zh_tw.json#L249 , you can see the wrong syntax error that causes this crash, Github has marked it out already:
![image](https://user-images.githubusercontent.com/21279092/101562714-e0281180-3a02-11eb-922b-272eff2598f7.png)

**Comment by Electroblob77** [comment]
Oh nice. I assume PR #568 fixes this?

**Comment by TUsama** [comment]
> Oh nice. I assume PR #568 fixes this?

hopefully yes, at least in the past mod version, the old version zh_tw.json didn't throw an error.

**Comment by Electroblob77** [comment]
Great, thanks!
