### ISSUE TITLE
loading crash

### ISSUE THREAD

**Issue by theirryb** [Electroblob77/Wizardry#553]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.1 [change as necessary]
Environment: Singleplayer]

Issue details: launching minecraft with the mod on it
Other mods involved:

Link to crash report (if applicable): 
[crash-2020-11-12_23.40.46-client.txt](https://github.com/Electroblob77/Wizardry/files/5535033/crash-2020-11-12_23.40.46-client.txt)

**Comment by WinDanesz** [comment]
Arcane Essentials incompatibility issue with Wizardry 4.3. Remove the mod till its updated to support the library update (4.3).
