### ISSUE TITLE
Weather change forfeit is not disabled when invoke weather is disabled

### ISSUE THREAD

**Issue by ShiroBlank** [Electroblob77/Wizardry#554]
Minecraft version: 1.12.2
Wizardry version: 4.2.11 

Question details: Is it possible to disable the creation of a thunderstorm apon spell backfire for multiplayer so people cannot spam weather effects?

**Comment by Electroblob77** [comment]
Hmm, it isn't but it should be! I think this is an oversight on my part, thanks for reporting.
