### ISSUE TITLE
Evil Wizzards are the only Mob that spawns!

### ISSUE THREAD

**Issue by 1998jacob** [Electroblob77/Wizardry#558]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.10 
Environment: Server 

Issue details: The only Hostile mob spawning are evil wizards. Everything seemed normal, until the sun went down, and a gaggle of angry wizards just, opened my door, walked in my house, and destroyed EVERYTHING. Flying around, I could not find a single non wizard hostile mob. I deleted the map twice. I tried different versions of the mod. I'm running a custom pack. I ran a pack with 318 mods, this being one, and it worked fine tho. This pack has 219 mods. Messing with the config did not help, 

[ebwizardry.txt](https://github.com/Electroblob77/Wizardry/files/5565147/ebwizardry.txt)

Other mods involved: [only list mods that are relevant to the problem]
![93b5a21c495aff25beb700cae16bc738a1e3f1445315cdba5c232ffd914b658f](https://user-images.githubusercontent.com/74703204/99636415-04e32780-2a09-11eb-9c59-5e17d272b4bb.png)

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Electroblob77** [comment]
I don't recall this ever being an issue. Is it just that world or does it happen when you create a new world?

Several things to try:
1. Update to the latest version of wizardry (currently 4.3.1). If you can't use 4.3.x for whatever reason, update to 4.2.11.
2. Try removing the overworld (0) from the list of hostile mob spawn dimensions in the config.
3. Make a copy of the world, remove all mods except wizardry, see if the issue persists.

I will not be releasing any more fixes for wizardry 4.2.x, so to fix it I'll need to know if this happens for you in 4.3 or not (it doesn't in my installation).
