### ISSUE TITLE
Some Console Spam when casted spells

### ISSUE THREAD

**Issue by avescarelo** [Electroblob77/Wizardry#56]
Minecraft version: 1.12.2
Wizardry version: 4.1.2 
SpongeForge version: 1.12.2-2705-7.1.0-BETA-3203
Environment: Server

Issue details: When i put spell in my inventory in creative mode, and take - i have a console spam

> [15:03:35] [Server thread/INFO] [ebwizardry]: A mod has called ItemScroll#getItemStackDisplayName from the server side. Using thedeprecated server-side translation methods as a fallback.

Link to error log: https://gist.github.com/pingvikin/a1de64425659e6093eb01ea292cdab06

**Comment by Electroblob77** [comment]
I should probably remove that warning, it doesn't really make sense any more. Thanks for pointing it out.

**Comment by Electroblob77** [comment]
This is getting annoying for people, it should have been fixed ages ago! Marking as high priority.
