### ISSUE TITLE
Invalid JSON syntax in handbook translation file

### ISSUE THREAD

**Issue by 404nill** [Electroblob77/Wizardry#561]
This is a very troublesome question.Because I have no problem in another archive and can run normally
[crash-2020-11-24_14.26.14-client.txt](https://github.com/Electroblob77/Wizardry/files/5587876/crash-2020-11-24_14.26.14-client.txt)

**Comment by WinDanesz** [comment]
What is your minecraft client's language? The error indicates a syntax error in the translation file. Switch back your client to English to resolve the crash until someone fixes the translation. **It won't be fixed unless you let us know the client language**

**Comment by Electroblob77** [comment]
Yep, language settings don't show up in the crash report, I need it to fix the issue.

**Comment by Electroblob77** [comment]
Assuming this is the same as #552.
