### ISSUE TITLE
Purifying Elixir still doesn't work...

### ISSUE THREAD

**Issue by shaye1444** [Electroblob77/Wizardry#562]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.1 [change as necessary]
Environment: Singleplayer/LAN game/Server [delete as necessary]

Issue details: I have curse of undeath. I've used many purifying elixirs they still don't work.

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Electroblob77** [comment]
Working as intended in my installation. Of course, it won't put you out immediately if you're on fire.

**Comment by shaye1444** [comment]
The issue is that it is not cleansing the curse at all.

**Comment by Electroblob77** [comment]
Okay, could you check the following:
1. Does the remove curse spell work?
2. If you drink an elixir and then restart the world / relog, does the effect go away?
3. Does it make a difference if you have any other potion effects?
4. Do you have any potion-related mods installed?

**Comment by WinDanesz** [comment]
Old version issue. Reopen if still present in 4.3.4+
