### ISSUE TITLE
Game crashes every time I sleep while it's raining.

### ISSUE THREAD

**Issue by centhusiastx2** [Electroblob77/Wizardry#569]
Minecraft version: 1.12.2 
Wizardry version: 4.3.1
Environment: Singleplayer

Issue details: [I tried sleeping in a bed three times while it's raining, but then I always encounter a crash]

Link to crash report (if applicable): 
[crash-2020-12-09_18.35.27-client.txt](https://github.com/Electroblob77/Wizardry/files/5669343/crash-2020-12-09_18.35.27-client.txt)

**Comment by brisingraerowing** [comment]
That's a compatability issue between Mo' Bends and Ido. EB Wizardry has no fault here.

**Comment by Electroblob77** [comment]
> That's a compatability issue between Mo' Bends and Ido. EB Wizardry has no fault here.

That's kind of true, except that wizardry is now supposed to disable its animations automatically if mobends is installed. What's really weird is that nothing from wizardry is mentioned in that crash report at all.

@centhusiastx2 Try disabling player animations in wizardry's config file and see if the crash still happens.

**Comment by Electroblob77** [comment]
I've looked again and it's definitely nothing to do with wizardry, closing.
