### ISSUE TITLE
Flight gives other players around wings - occurs for all effects rendered on caster [SMP]

### ISSUE THREAD

**Issue by zEpiixz** [Electroblob77/Wizardry#57]
Minecraft version: 1.12.2 
Wizardry version: 4.1.2 
Environment: Server 
Issue details: When a Person my Server uses the flight spell. He doesnt show wings but instead other players in the area get the wings. The user can fly and only sees the wings on him but others on them. The other people cant fly witht he wings just glichting through them.

**Comment by Electroblob77** [comment]
Ok, thought I'd fixed that. I'll have to check it out again, thanks for reporting it.

**Comment by zEpiixz** [comment]
Oh and same for Shield spell thanks.

**Comment by Electroblob77** [comment]
Yeah it'll be the same for all the effects that get rendered on the player, so shadow ward probably does it too.

**Comment by Electroblob77** [comment]
That's not how closing issues works! I'll close it when it's fixed.

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
