### ISSUE TITLE
Antique Atlas Compatibility Issue

### ISSUE THREAD

**Issue by Sj348** [Electroblob77/Wizardry#570]
Minecraft version: 1.12.2 
Wizardry version: 4.3.1
Environment: Singleplayer
Issue details: When attempting to create antique atlas, no markers displayed for any of  the Electroblob's structures known to be in the area mapped.
Other mods involved: Antique Atlas (by Hunternif)

**Comment by Electroblob77** [comment]
What Antique Atlas version are you using? I have 4.6.3 and it works fine.
