### ISSUE TITLE
ebwizardry.cfg questions

### ISSUE THREAD

**Issue by Hokorizero** [Electroblob77/Wizardry#572]
Minecraft version: 1.12.2 
Wizardry version: 4.3.1 & 4.2.11

Question details: In Obviously,the previous ebwizardry.cfg can read language files.I think it is a fun feature.
Why not continue to use this feature？
![Snipaste_2020-12-12_11-30-59](https://user-images.githubusercontent.com/50108932/101971745-6e7edc00-3c2b-11eb-9eff-d99cb4577fc6.png)
![Snipaste_2020-12-12_11-31-12](https://user-images.githubusercontent.com/50108932/101971747-72126300-3c2b-11eb-8211-7270cbf3880e.png)

**Comment by Electroblob77** [comment]
Yes, it was useful, but it meant that whenever the language was changed all the config settings would reset... sadly. That's why I removed it. I guess that's why the in-game config menu exists, I'd encourage everyone to use that whenever they can.

**Comment by Hokorizero** [comment]
well,that is so pity....
