### ISSUE TITLE
Overlay Issue in the Wizard Handbook

### ISSUE THREAD

**Issue by fandomaniac** [Electroblob77/Wizardry#58]
Minecraft version: 1.12.2 
Wizardry version: 4.1.2
Environment: SMP Server

Overlay issue on page 47 of the Wizard Handbook (see screen capture below).

![wizard-handbook](https://user-images.githubusercontent.com/37810246/42730623-13352086-87c7-11e8-8fdf-43539c7cc274.jpg)

**Comment by Electroblob77** [comment]
This is because of Sphax's extra-wide font causing the text to spill over onto another page. However, it should automatically move the crafting recipes to the next free double-page, so something's obviously wrong with the code that does that. Thanks for reporting it.

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
