### ISSUE TITLE
Bugs with the Mine spell and Arcane Lock

### ISSUE THREAD

**Issue by Shibva** [Electroblob77/Wizardry#580]
The mine spell. refuses to work and break blocks And I cant undo the Arcane Lock when casting it again 

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.1 [change as necessary]
Environment: Singleplayer

If issue is unable to be reporduced, let me know, it should be the same mods as I have listed in the other issue I posted in (https://github.com/Electroblob77/Wizardry/issues/578)

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Shibva** [comment]
Oh. and on another note, the Imbumnet alter is unharvistable, idk if this is intentonal or not But if you can make one and then place it, it would be like doing the same with bedrock

not sure about this though

**Comment by Shibva** [comment]
https://user-images.githubusercontent.com/38770780/102697116-3fef9b00-4201-11eb-97ef-9caf3ee77d4f.mp4

**Comment by Electroblob77** [comment]
Okay, so just to clarify, arcane lock works on some blocks (enchantment table) but triggers twice on others (chest, wizardry bookshelf)?

For the mine spell, please could you double-check that `playerBlockDamage` is not disabled in the config? Also, are you in any kind of protected region?

The imbuement altar is supposed to be unbreakable, that is intentional. I will try out the other two things.

**Comment by Shibva** [comment]
oh I have that turned off

I have it off so the spells that do blast damage dont hurt

if thats the case, can you add a config option that makes it so where only the mine spell can work and the others are diasbled, that way people can use the Mine spell and not have to worry about the other spells causing unessisary grief when used

**Comment by Electroblob77** [comment]
I can do that, yes. I believe it was suggested to me that the block damage settings should be more granular, this would be part of that.

**Comment by Shibva** [comment]
👍

**Comment by Shibva** [comment]
My bad, hit the wrong button
