### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by MergingFob06913** [Electroblob77/Wizardry#581]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.3.1 
Environment: Multiplayer (server)

Issue details: The issue doenst really have to do with the main mod. I am using the toy boxx on the technic launcher and we did add some more mods to it. The mods we added were JEI, NEI, Inventory tweaks, warp book, flan's, soul shard, and enchangting plus. The modpack itself is working great but we really want to add the add ons to gain more spells because we are really loving this mod. However when I press play to start the game from the technic launcher, it disappears like normal but then sends me back to the main launcher. So mc wont start at all and then when I take out that mod add on it works just fine. Not sure if another mod is conflicting or what, 
Other mods involved: Not sure, I can post the mod list if needed. 

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]
 No crash report was available

**Comment by WinDanesz** [comment]
Without the actual console output (there must have been something related to this), nothing can be done.

**Comment by MergingFob06913** [comment]
What do you mean by that? There must be something I can post or maybe video to show what I'm doing.

**Comment by Electroblob77** [comment]
Go into the folder where your game is installed (the one with `saves`, `resourcepacks` and so on inside). If you don't know where it is, launch the game, go to the resource packs menu and click _open resource pack folder_ and then navigate up one level. You should see a `crash_reports` folder, go in there and find the most recent .txt file. Post the contents of that file into gist or pastebin and put a link here.

**Comment by MergingFob06913** [comment]
https://pastebin.com/vziWd9Du
Here is the link. For reference I added the Ancient spell addon and that worked fine but when I added the arcane essentials it crashed and here is the report. I did use the 0.9.2 version for the 4.3version I am using

**Comment by WinDanesz** [comment]
ArcaneEssentials does not support the library version, it crashes with 4.3+. You have to wait till the mod is updated or remove it from your pack.
