### ISSUE TITLE
Acacia Lectern

### ISSUE THREAD

**Issue by Hyrulekoopa** [Electroblob77/Wizardry#587]
Minecraft version: 1.12.2 
Wizardry version: 4.3.1 
Environment: LAN game

Issue details: So I wanted to play with my friend and you know we did a lot of things but for some unknown reason an acacia lectern crashed our game and now it's not letting us join because when we do join the game it immediately crashes. So we tried to modify the jar and it did not work it corrupted the world but we had backups so it was all fine. So here is the crash report.

![image0](https://user-images.githubusercontent.com/76500965/102944236-33c93f00-4488-11eb-8da4-098b5cbe70e4.jpg)

**Comment by SettingDust** [comment]
crash-report file plz

**Comment by Electroblob77** [comment]
Well that's weird. It says the `facing` property doesn't exist, but you can quite clearly see that it does just from what's written there. An actual crash report file might help shed some light on it, click 'view crash report' to open it.
