### ISSUE TITLE
language set to other except en_us cause start up crash 

### ISSUE THREAD

**Issue by 27tj** [Electroblob77/Wizardry#589]
Minecraft version: 1.12.2 
Wizardry version: 4.3.1
Environment: Singleplayer

Issue details:  setting language to other and quit minecraft cause forge crash on start up next time open minecraft ,( I use zh_tw (繁體中文 (台灣)) for my language settings)
Link to crash report (if applicable): https://drive.google.com/file/d/1_ceZOIttzUqTD2MPkWF4sARYT7NC_Ti5/view?usp=sharing

**Comment by Electroblob77** [comment]
Duplicate of #552. This only happens with zh_tw, it's just an error in that file.
