### ISSUE TITLE
Crash while playing with biomesoplenty

### ISSUE THREAD

**Issue by TheQKnight** [Electroblob77/Wizardry#594]
Minecraft version: 1.12.2
Wizardry version: 4.3.2
Environment: Singleplayer

Issue details:

This crash happened while just running around the world. I have a few other mods installed, but it seems like biomesoplenty and wizardry is at fault here.

Other mods involved: Biomes o Plenty

Link to crash report: Pastebin does not work for me, so I attached it as a separate file.
[crash-2021-01-04_01.22.59-server.txt](https://github.com/Electroblob77/Wizardry/files/5763977/crash-2021-01-04_01.22.59-server.txt)

**Comment by TheQKnight** [comment]
After further investigation it seems to happen when a wizard shoots a mob but the projectile hits a blade of BOP grass.

**Comment by Rover656** [comment]
Can confirm this issue, took my entire dedicated server out.

**Comment by mxnmnm** [comment]
Seems to happen with version 4.3 and beyond but it seems fine for older versions

**Comment by Rover656** [comment]
Appears to occur on this [line](https://github.com/Electroblob77/Wizardry/blob/3b4ce6860661c99b2450b6d6dcc0746e20f9f50d/src/main/java/electroblob/wizardry/util/BlockUtils.java#L422) when calling isReplaceable. In both my crash and the OP's, it seems that the target block at pos.up() is an air block. A possible fix would be checking that this block is not air before checking isReplaceable?

**Comment by Electroblob77** [comment]
Seems to be similar to #519, but that got fixed in 4.3... hmmm....
