### ISSUE TITLE
[Crash with everlasting abilities and potion core]

### ISSUE THREAD

**Issue by PercyJames** [Electroblob77/Wizardry#595]
Minecraft version: 1.12.2 
Wizardry version: 4.3.1 
Environment: Singleplayer

Issue details: when i click the ability bottle my game crashes. 

Other mods involved: Everlasting Abilities, EverlastingAbilities-PotionCore, Cyclops Core.

Link to crash report (if applicable): https://pastebin.com/jCd2uCeU

**Comment by Electroblob77** [comment]
Fixed in 4.3.2

**Comment by PercyJames** [comment]
thanks
