### ISSUE TITLE
Add some configurable items in the configuration file

### ISSUE THREAD

**Issue by YKDZ** [Electroblob77/Wizardry#596]
1.12.2

hi , I want to be able to configure the cooldown and damage of each spell in the config file . This can make the mod better used in the server . Some spells do too much damage now . Thanks . I love this mod 👍 : )

**Comment by WinDanesz** [comment]
Already possible https://github.com/Electroblob77/Wizardry/wiki/Spell-Properties#modifying-spell-properties
