### ISSUE TITLE
Maybe give spell books a Damage

### ISSUE THREAD

**Issue by YKDZ** [Electroblob77/Wizardry#597]
1.12.2

I think the spell book can be used indefinitely may affect the balance of the server . Maybe you can add a Damage to the spell book . It should be possible adjust and switch in the config file . 👍

**Comment by WinDanesz** [comment]
I'd suggest to join our discord community to discuss ideas like this. https://discord.gg/eYM3ag4YgN

**Comment by Electroblob77** [comment]
See #309 for discussion of this.
