### ISSUE TITLE
electroblob.wizardry.spell.SpellRay. Causing Crash on start up.

### ISSUE THREAD

**Issue by AncientDrako** [Electroblob77/Wizardry#598]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.22.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  OTGCorePlugin (OTG-Core.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  MixinLoader (water-erosion-1.12.2-forge-1.1.1-beta1-full.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  Wizardry Plugin (wizardry-0.11.1.jar)
  FarseekCoreMod (Farseek-1.12-2.5.1.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 1/9/21 11:22 AM
Description: Initializing game

java.lang.NoSuchMethodError: electroblob.wizardry.spell.SpellRay.<init>(Ljava/lang/String;Ljava/lang/String;ZLnet/minecraft/item/EnumAction;)V
	at com.favouritedragon.arcaneessentials.common.spell.SpellRay.<init>(SpellRay.java:25)
	at com.favouritedragon.arcaneessentials.common.spell.ice.BlizzardBeam.<init>(BlizzardBeam.java:29)
	at com.favouritedragon.arcaneessentials.RegisterHandler.register(RegisterHandler.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_303_RegisterHandler_register_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.favouritedragon.arcaneessentials.common.spell.SpellRay.<init>(SpellRay.java:25)
	at com.favouritedragon.arcaneessentials.common.spell.ice.BlizzardBeam.<init>(BlizzardBeam.java:29)
	at com.favouritedragon.arcaneessentials.RegisterHandler.register(RegisterHandler.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_303_RegisterHandler_register_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2617387848 bytes (2496 MB) / 3846701056 bytes (3668 MB) up to 18175492096 bytes (17333 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx19500m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 127 mods loaded, 127 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                 | Source                                                | Signature                                |
	|:----- |:------------------------ |:----------------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                | 1.12.2                  | minecraft.jar                                         | None                                     |
	| LCH   | mcp                      | 9.42                    | minecraft.jar                                         | None                                     |
	| LCH   | FML                      | 8.0.99.99               | forge-1.12.2-14.23.5.2854.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                    | 14.23.5.2854            | forge-1.12.2-14.23.5.2854.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | otgcore                  | 1.12.2-v9.3             | minecraft.jar                                         | None                                     |
	| LCH   | codechickenlib           | 3.2.3.358               | CodeChickenLib-1.12.2-3.2.3.358-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | ancientwarfare           | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar                   | None                                     |
	| LCH   | ancientwarfarestructure  | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar                   | None                                     |
	| LCH   | ancientwarfarevehicle    | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar                   | None                                     |
	| LCH   | ancientwarfarenpc        | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar                   | None                                     |
	| LCH   | ancientwarfareautomation | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar                   | None                                     |
	| LCH   | animalnet                | v1.12.2 b3              | animalnet-v1.12.2 b3.jar                              | None                                     |
	| LCH   | baubles                  | 1.5.2                   | Baubles-1.12-1.5.2.jar                                | None                                     |
	| LCH   | jei                      | 4.16.1.301              | jei_1.12.2-4.16.1.301.jar                             | None                                     |
	| LCH   | botania                  | r1.10-363               | Botania r1.10-363.jar                                 | None                                     |
	| LCH   | craftstudioapi           | 1.0.0                   | CraftStudio-1.0.0.93-mc1.12-alpha.jar                 | None                                     |
	| LCH   | openterraingenerator     | v9.3                    | OpenTerrainGenerator-1.12.2-v9.3.jar                  | None                                     |
	| LCH   | harvestcraft             | 1.12.2zb                | Pam's HarvestCraft 1.12.2zg.jar                       | None                                     |
	| LCH   | animania                 | 2.0.2.26                | animania-1.12.2-base-2.0.2.26.jar                     | None                                     |
	| LCH   | appleskin                | 1.0.14                  | AppleSkin-mc1.12-1.0.14.jar                           | None                                     |
	| LCH   | ebwizardry               | 4.3.2                   | ElectroblobsWizardry-4.3.2-MC1.12.2.jar               | None                                     |
	| LCH   | arcane_essentials        | 1.0                     | Arcane Essentials-0.9.2.jar                           | None                                     |
	| LCH   | architecturecraft        | @VERSION@               | architecturecraft-1.12-3.98.jar                       | None                                     |
	| LCH   | betterbuilderswands      | 0.11.1                  | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar       | None                                     |
	| LCH   | bettercaves              | 1.12.2                  | bettercaves-1.12.2-2.0.4.jar                          | None                                     |
	| LCH   | bettermineshafts         | 1.12.2-2.1.1            | BetterMineshaftsForge-1.12.2-2.1.1.jar                | None                                     |
	| LCH   | blockdrops               | 1.4.0                   | blockdrops-1.12.2-1.4.0.jar                           | None                                     |
	| LCH   | buildersbag              | 1.12.2                  | buildersbag-1.12.2-1.4.1.24.jar                       | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCH   | ctm                      | MC1.12.2-1.0.2.31       | CTM-MC1.12.2-1.0.2.31.jar                             | None                                     |
	| LCH   | mysticalworld            | 1.12.2-1.9.2            | mysticalworld-1.12.2-1.9.2.jar                        | None                                     |
	| LCH   | chisel                   | MC1.12.2-1.0.2.45       | Chisel-MC1.12.2-1.0.2.45.jar                          | None                                     |
	| LCH   | conquest                 | 3.0.2                   | ConquestReforged-3.0.2-mc1.12.2.jar                   | None                                     |
	| LCH   | blockpalette             | 1.5.0                   | ConquestReforged-3.0.2-mc1.12.2.jar                   | None                                     |
	| LCH   | connect                  | 1.0.3-mc1.12.2-SNAPSHOT | ConquestReforged-3.0.2-mc1.12.2.jar                   | None                                     |
	| LCH   | customnpcs               | 1.12                    | CustomNPCs_1.12.2-(05Jul20).jar                       | None                                     |
	| LCH   | dragonmounts             | 1.12.2-1.6.3            | DragonMounts2-1.12.2-1.6.3.jar                        | None                                     |
	| LCH   | dat                      | 1.0                     | dragonsattacktektopians-1.12.2-1.0.jar                | None                                     |
	| LCH   | dregora                  | 1.0                     | Dregora-1.12.2-v1.66.2.jar                            | None                                     |
	| LCH   | enderore                 | 1.12.2-v1.1             | Ender Ore-1.12.2-v1.1.jar                             | None                                     |
	| LCH   | endercrop                | 1.12.2-1.6.0            | endercrop-1.12.2-1.6.0.jar                            | None                                     |
	| LCH   | enderzoo                 | 1.12.1-1.4.0.49         | EnderZoo-1.12.1-1.4.0.49.jar                          | None                                     |
	| LCH   | mantle                   | 1.12-1.3.3.55           | Mantle-1.12-1.3.3.55.jar                              | None                                     |
	| LCH   | tinkersextras            | 1.12.2-1.1.0            | TinkersExtras-1.12.2-1.1.0.jar                        | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | tconstruct               | 1.12.2-2.13.0.183       | TConstruct-1.12.2-2.13.0.183.jar                      | None                                     |
	| LCH   | veinminer                | 0.38.2                  | VeinMiner-1.12-0.38.2.647+b31535a.jar                 | None                                     |
	| LCH   | mmdlib                   | 1.0.0-rc2               | MMDLib-1.12-1.0.0-rc2.36.jar                          | None                                     |
	| LCH   | endmetals                | 1.2.0-rc2               | EndMetals-1.12-1.2.0-rc2.67.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | endportrec               | 1.0                     | endportrec_1.12-1.0.jar                               | None                                     |
	| LCH   | golems                   | 7.1.9                   | ExtraGolems-1.12-7.1.9.jar                            | None                                     |
	| LCH   | farseek                  | 2.5.1                   | Farseek-1.12-2.5.1.jar                                | None                                     |
	| LCH   | fenceoverhaul            | 1.3.4                   | FenceOverhaul-1.3.4.jar                               | None                                     |
	| LCH   | forgelin                 | 1.8.4                   | Forgelin-1.8.4.jar                                    | None                                     |
	| LCH   | hammerx                  | ${version}              | hammerx-1.12-1.1.4.jar                                | None                                     |
	| LCH   | hopperducts              | 1.5                     | hopperducts-mc1.12-1.5.jar                            | None                                     |
	| LCH   | llibrary                 | 1.7.20                  | llibrary-1.7.20-1.12.2.jar                            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire               | 1.9.1                   | iceandfire-1.9.1-1.12.2.jar                           | None                                     |
	| LCH   | lunatriuscore            | 1.2.0.42                | LunatriusCore-1.12.2-1.2.0.42-universal.jar           | None                                     |
	| LCH   | ingameinfoxml            | 2.8.2.94                | InGameInfoXML-1.12.2-2.8.2.94-universal.jar           | None                                     |
	| LCH   | sereneseasons            | 1.2.18                  | SereneSeasons-1.12.2-1.2.18-universal.jar             | None                                     |
	| LCH   | igisereneseasons         | 1.0.0.1                 | igisereneseasons-1.0.0.1.jar                          | None                                     |
	| LCH   | igi|sereneseasons        | 1.0                     | IGISereneSeasons.jar                                  | None                                     |
	| LCH   | jaffa                    | 7.63.1                  | JAFFA-7.63.1.jar                                      | None                                     |
	| LCH   | jeiintegration           | 1.6.0                   | jeiintegration_1.12.2-1.6.0.jar                       | None                                     |
	| LCH   | jeivillagers             | 1.0                     | jeivillagers-1.12-1.0.2.jar                           | None                                     |
	| LCH   | journeymap               | 1.12.2-5.7.1            | journeymap-1.12.2-5.7.1.jar                           | None                                     |
	| LCH   | jehc                     | 1.7.2                   | just-enough-harvestcraft-1.12.2-1.7.2.jar             | None                                     |
	| LCH   | jeid                     | 1.0.3-55                | JustEnoughIDs-1.0.3-55.jar                            | None                                     |
	| LCH   | jeresources              | 0.9.2.60                | JustEnoughResources-1.12.2-0.9.2.60.jar               | None                                     |
	| LCH   | keywizard                | 1.12.2-1.7.3            | keywizard-1.12.2-1.7.3.jar                            | None                                     |
	| LCH   | librarianlib             | 4.22                    | librarianlib-1.12.2-4.22.jar                          | None                                     |
	| LCH   | lootbagmod               | 1.5.1                   | lootbagmod-1.12.2-1.5.1.jar                           | None                                     |
	| LCH   | placebo                  | 1.6.0                   | Placebo-1.12.2-1.6.0.jar                              | None                                     |
	| LCH   | magicalmap               | 3.3.2                   | Magical Map-1.12.2-3.3.2.jar                          | None                                     |
	| LCH   | magicalsculpture         | 0.99                    | magicalsculpture-1.0.0.jar                            | None                                     |
	| LCH   | mana_wizardry            | 0.3                     | Mana Wizardry-0.3.jar                                 | None                                     |
	| LCH   | mca                      | 6.1.0                   | MCA-1.12.2-6.1.0-universal.jar                        | None                                     |
	| LCH   | mcwbridges               | 1.0.4                   | mcw-bridges-1.0.4-mc1.12.2.jar                        | None                                     |
	| LCH   | mcwdoors                 | 1.0                     | mcw-doors-1.0.0-mc1.12.2.jar                          | None                                     |
	| LCH   | mcwfurnitures            | 1.0.1                   | mcw-furniture-1.0.1-mc1.12.2beta.jar                  | None                                     |
	| LCH   | mcwroofs                 | 1.0.2                   | mcw-roofs-1.0.2-mc1.12.2.jar                          | None                                     |
	| LCH   | mcwwindows               | 1.0                     | mcw-windows-1.0.0-mc1.12.2.jar                        | None                                     |
	| LCH   | metallurgy               | 1.2.3                   | Metallurgy-4-Reforged-1.2.3.jar                       | None                                     |
	| LCH   | mousetweaks              | 2.10                    | MouseTweaks-2.10-mc1.12.2.jar                         | None                                     |
	| LCH   | naturalnetherportals     | 1.2.0                   | naturalnetherportals-1.2.0-mc1.12.x.jar               | None                                     |
	| LCH   | nethermetals             | 1.2.0-rc2               | NetherMetals-1.12-1.2.0-rc2.76.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | notenoughroofs           | 0.8.0.1                 | notenoughroofs-1.12.2-0.8.0.1.jar                     | None                                     |
	| LCH   | nps                      | 2.1                     | nps_1.12-2.1.jar                                      | None                                     |
	| LCH   | oreexcavation            | 1.4.150                 | OreExcavation-1.4.150.jar                             | None                                     |
	| LCH   | orespawn                 | 3.3.1                   | OreSpawn-1.12-3.3.1.179.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | clayspawn                | 1.12a                   | Pam's ClaySpawn 1.12a.jar                             | None                                     |
	| LCH   | desertcraft              | 1.12.2b                 | Pam's DesertCraft 1.12.2c.jar                         | None                                     |
	| LCH   | patchouli                | 1.0-23.6                | Patchouli-1.0-23.6.jar                                | None                                     |
	| LCH   | roguelike                | 2.2.0                   | RoguelikeDungeonsFnarEdition-1.12.2-2.2.0.jar         | None                                     |
	| LCH   | t3s4ebw                  | 1.0                     | SeedsForWizardry 1.0 For MC Forge 1.12.2.jar          | None                                     |
	| LCH   | oeshapeselector          | 1.0                     | shapeselector-1.12.2b4.jar                            | None                                     |
	| LCH   | similsaxtranstructors    | 1.12-1.0.21             | SimilsaxTranstructors-1.12-1.0.22.jar                 | None                                     |
	| LCH   | smallernp                | 1.1                     | smallernp_1.12-1.1.jar                                | None                                     |
	| LCH   | streams                  | 0.4.9                   | Streams-1.12-0.4.9.jar                                | None                                     |
	| LCH   | tektopia                 | 1.1.0                   | tektopia-1.1.0.jar                                    | None                                     |
	| LCH   | tthcc                    | 1.3                     | Tektopia-Harvestcraft-Compat-1.3.jar                  | None                                     |
	| LCH   | tektopiainformation      | 1.4.0                   | TektopiaInformation-1.12.2-1.1.0-1.4.0.jar            | None                                     |
	| LCH   | tinkersjei               | 1.2                     | tinkersjei-1.2.jar                                    | None                                     |
	| LCH   | veinminermodsupport      | 0.38.2                  | VeinMiner-1.12-0.38.2.647+b31535a.jar                 | None                                     |
	| LCH   | villagenames             | 4.1.2                   | VillageNames-1.12.2-4.1.2.jar                         | None                                     |
	| LCH   | water-erosion            | 1.1.1-beta1             | water-erosion-1.12.2-forge-1.1.1-beta1-full.jar       | None                                     |
	| LCH   | waystones                | 4.1.0                   | Waystones_1.12.2-4.1.0.jar                            | None                                     |
	| LCH   | weeeflowers              | 1.12.2b                 | Weee! Flowers 1.12.2b.jar                             | None                                     |
	| LCH   | window_dressings         | 1.0.0                   | WindowDressings_1.2.1.jar                             | None                                     |
	| LCH   | wizardry                 | 0.11.1                  | wizardry-0.11.1.jar                                   | None                                     |
	| LCH   | wizardrygolems           | 1.0.1                   | WizardryGolems-1.0.1.jar                              | None                                     |
	| LCH   | worldedit                | 6.1.10                  | worldedit-forge-mc1.12.2-6.1.10-dist.jar              | None                                     |
	| LCH   | worldeditcuife3          | 3.0.8                   | WorldEdit-CUI-FE3-1.12.2-3.0.8.jar                    | None                                     |
	| LCH   | zettaigrimoires          | 1.4.5                   | ZettaiGrimoires+1.4.5.jar                             | None                                     |
	| LCH   | zettaimagic              | 1.3.4                   | ZettaiMagic+1.3.4.jar                                 | None                                     |
	| LCH   | lemonlib                 | 1.3.0                   | lemonlib-1.12.2-1.3.0.jar                             | None                                     |
	| LCH   | arcaneworld              | 0.0.11                  | arcaneworld-1.12.2-0.0.11.jar                         | None                                     |
	| LCH   | densemetals              | 2.0.0                   | DenseMetals-1.12.2-2.0.0.30.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | drplibrary               | 1.12.2-0.1.3-SNAPSHOT   | drplibrary-1.12.2-0.1.3-SNAPSHOT-20190129.034240.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCH   | drpcmblueprints          | 1.12.2-1.2.3            | drpcmblueprints-1.12.2-1.2.3.jar                      | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCH   | drpcmmaarg               | 1.12.2-0.10.0-SNAPSHOT  | drpcmmaarg-1.12.2-0.10.0-SNAPSHOT-20181116.074036.jar | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCH   | drpcmguis                | 1.12.2-0.0.2-SNAPSHOT   | drpcmguis-1.12.2-0.0.1-SNAPSHOT-20181125.120253.jar   | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCH   | drpcore                  | 1.12.2-0.4.7            | drpcore-1.12.2-0.4.8.jar                              | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCH   | drpcmlocks               | 1.12.2-1.0.1            | drpcmlocks-1.12.2-1.0.0-SNAPSHOT-20181126.111203.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCH   | drpmedieval              | 1.12.2-0.3.6            | drpmedieval-1.12.2-0.3.6.jar                          | None                                     |
	| LCH   | structurize              | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar               | None                                     |
	| LCH   | librarianliblate         | 4.22                    | librarianlib-1.12.2-4.22.jar                          | None                                     |
	| LCH   | mysticallib              | 1.12.2-1.9.0            | mysticallib-1.12.2-1.9.0.jar                          | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.22.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  org.dimdev.jeid.JEIDTransformer
MixinLoader (water-erosion-1.12.2-forge-1.1.1-beta1-full.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Wizardry Plugin (wizardry-0.11.1.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
FarseekCoreMod (Farseek-1.12-2.5.1.jar)
  farseek.core.FarseekClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Patchouli open book context: n/a
	Launched Version: forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	
	
	
	Any help would be amazing. I've just recently started having this issue. So I've tried backdating my mods and it still pops up so I'm not really sure where to go after this. I'm really really wanting this in my mod lineup and would hate to have to remove it if I don't need to..

**Comment by WinDanesz** [comment]
The addon mod Arcane Essentials is not compatible with Electroblob's Wizardry 4.3+ as the author haven't updated the addon yet. Remove that mod or downgrade wizardry below 4.3. Please close this issue.

**Comment by AncientDrako** [comment]
> The addon mod Arcane Essentials is not compatible with Electroblob's Wizardry 4.3+ as the author haven't updated the addon yet. Remove that mod or downgrade wizardry below 4.3. Please close this issue.

Thank's man I'm gonna go try that and I'll get back to you.
