### ISSUE TITLE
Spell usage on lan world in survival mode causing massive 2-7k ping spikes even with good bandwidth. 

### ISSUE THREAD

**Issue by Syalucard** [Electroblob77/Wizardry#599]
Minecraft version: 1.12.2 
Wizardry version: 4.3.2 
Environment: LAN game

Issue details: So, little bit of skippable story if you need. My lil bro and I are doing pvp, using the mod for spell combat and stuff. Testing out spells in creative mode are no problem as it doesn't lag us out. However when both of us go into survival mode, when one of us uses even a simple spell such as magic missile or frizz, the person that casted the spell lags out the entire world despite having good connection to our wifi, and the laptops which are decently strong are sitting side by side. If one of us goes into creative mode and that person is using spells, it doesn't lag out the other person and the caster, but if one person is in survival mode and the other is in creative and that specific person in survival casts a spell, it lags out the world. Noone else was using the wifi at the time and lowering the particle limit doesn't help with it, we keep getting 2k to 7k ping spikes with a single cast from an enemy or a player and lags us out of the world completely. 

Other mods involved: It does it with the base electroblob's spells and our other modded ones, Ancient Spellcraft, the Twlight forest pack, Arcane Essentials, and the Extra spells mod. 

Link to crash report (if applicable): No crash report, just a connection loss that says either Disconnected, or Timed out.

**Comment by WinDanesz** [comment]
Arcane Essentials with wizardry 4.3.2? Wonder how did you even manage to load the game. That addon is incompatible since the library upgrade. Try removing it

**Comment by Syalucard** [comment]
Oh, related to that, We used the 0.9.1 version of AE with it and vanillafix but the spells wouldn't load anyways as it would keep detecting a problem with it, but unrelated to the problem. It, somewhat helped at first but it stopped working after a novice spell cast and the other computer went up to 1600-3200 ms for a good few seconds. My main laptop is at 0-2 ms, so it might be the other laptop, I'm not sure right now. Sometimes it went up to 8000+ ms but didn't time out. 
![image](https://user-images.githubusercontent.com/77219931/104123287-35f02200-52ff-11eb-9715-70cb82045a44.png)

**Comment by WinDanesz** [comment]
Not sure if I understand... so did you remove arcane essentials and try to reproduce the error without it? Did that solve the issue or not?

**Comment by WinDanesz** [comment]
This mod might help with identifying the source too
https://www.curseforge.com/minecraft/mc-mods/laggoggles

**Comment by Electroblob77** [comment]
Yep, lag goggles will reveal where the problem is
