### ISSUE TITLE
earthquake kills players without a message

### ISSUE THREAD

**Issue by LemADEC** [Electroblob77/Wizardry#60]
Minecraft version: 1.12.2
Wizardry version: 4.1.2
Environment: Server

Issue details:
Player A stand on the ground with low health
Player B stand on the same level and user an earthquake spell
Player A dies
Expected: chat message explaining player B kill player A
Observed: no chat message

**Comment by Electroblob77** [comment]
Hmm, that's odd. At the very least, it ought to say 'Player A was killed by magic'... I'll have to look into it, thanks for reporting.

**Comment by Electroblob77** [comment]
Should be fixed in the 4.2.0 release.
