### ISSUE TITLE
Server crash when being attacked by remnants

### ISSUE THREAD

**Issue by faeldray** [Electroblob77/Wizardry#600]
Minecraft version: 1.12.2
Wizardry version: 4.3.2
Environment: Server

Issue details: While playing in a self-hosted server, I got too close to an obelisk and some remnants spawned. When they attacked me with another player close by, the server crashed. It continues to crash if the remnants stick around and both me and the other player log on and are in close proximity. If I log in by myself and kill the remnants, there's no more crashes.

Other mods involved: None AFAIK

Link to crash report (if applicable): https://pastebin.com/A7R8phBj

Additional info: I'm no dev but judging from the crash report, this seems very similar to a crash I've also experienced with Fish's Undead Rising. Apparently it's caused by there being no target for a mob's attack but it attacks anyways. (Ref: https://github.com/FuGu0416/Fishs_Undead_Rising/issues/63)

**Comment by Electroblob77** [comment]
Huh, not sure why that would happen (it shouldn't even get that far with no target) but it's easily fixed, thanks for reporting.
