### ISSUE TITLE
Wand Cooldown Upgrade Scrolls + Warlock Gear = "Bricked" wands

### ISSUE THREAD

**Issue by Oreo365** [Electroblob77/Wizardry#603]
I was experimenting with combining Wand Cooldown Upgrade Scrolls with the Warlock Gear when i seemingly "Bricked" my wands.
After casting the spell "Lightning Arrow", the Cooldown Bar was permanently stuck as "Empty" (As in devoid of all colour and grey). the wand had lots of Mana left so that was not the issue. Unequipping the Warlock armour did not fix the wand. I repeated the same process with a new wand but without the Warlock gear and everything was fine. I then equipped the Warlock gear and cast a spell, "Bricking" the wand that had just previously worked fine.

See attached screenshot for a picture of the "Permanently Empty" cooldown bar. I hope i am just making a silly mistake but in the off-chance this is an actual bug i thought best to report it.

![2021-01-17_23 38 51](https://user-images.githubusercontent.com/77593406/104859468-7f52f980-591d-11eb-860b-ef50ac40e068.png)

**Comment by GapHusky** [comment]
I also got this bug when experimenting with the warlock armor any wand with a cooldown upgrade will be bugged while wearing it.  After using a wand with a cool down upgrade and warlock armor that given slot will never work again even if you replace the spell. Edit: (This bug also happens when wearing warlock armor using Font of Mana and the Ring of Gathering Storm.)

**Comment by Electroblob77** [comment]
Can confirm. This seems to be related to how wand data is handled, I first saw it when using font of mana but forgot to go back and look at it. Will get this fixed asap.

Edit: Ideally I'll make it fix the broken wands, can't promise that but it should be possible. If not, you can un-break them by editing the NBT for the wand and setting the cooldowns back to 0.
