### ISSUE TITLE
(Ancient Spellcraft) Random crash unable to get back on serever

### ISSUE THREAD

**Issue by EmrysPendragon67** [Electroblob77/Wizardry#604]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.3.1 (I think) (Whatever the latest Roguelike Adventures and Dungeons modpack uses)
Environment: Singleplayer

Issue details: I was fighting some evil wizards and I had just killed them all and was going to the chest when the game crashed. I don't know why and I am now unable to get back on the server.

Other mods involved: Ancient Spellcaft by Dan.

Link to crash report (if applicable): I don't know if this is right sorry.
https://gist.github.com/EmrysPendragon67/c6bf2738e761b9b4ac2604c7487e5b0c#file-crash-2021-01-18_15-16-05-server

**Comment by Electroblob77** [comment]
Looks like a bug with ancient spellcraft
