### ISSUE TITLE
Seal of Protection Removed/Missing/Errored Out in version update

### ISSUE THREAD

**Issue by hadenkw** [Electroblob77/Wizardry#607]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.3.2-4.3.3
Environment: Server

Issue details: When updating from 4.3.2 to 4.3.3 the Seal of Protection was removed from the server somehow. Seals in inventories/chests were removed and is now unavailable via /give or creative mode.

Other mods involved: 

Link to crash report (if applicable):

**Comment by WinDanesz** [comment]
the seal was replaced with 3 other, new armor upgrade items as part of the introduction of the armor classes

**Comment by hadenkw** [comment]
Will there be any update to the wiki to reflect this? Most of those pages haven't been recently updated and still show the Seal as the sole means of upgrades.
Similarly, has the in-game book been updated with this info?

**Comment by Electroblob77** [comment]
The book will be updated shortly. Otherwise, this is intended behaviour, the seals would be useless now anyway. I don't have time to update the wiki constantly, sorry.

**Comment by MagmaSlime123** [comment]
No point in the wiki if it's not being updated.
