### ISSUE TITLE
armour upgrades casing exception on server (using the super hostile modpack)

### ISSUE THREAD

**Issue by bluejello42** [Electroblob77/Wizardry#608]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.3.3 
Environment:  Server 

Issue details: When I try to upgrade my armour on my server it throws the exception linked in pastebin (this is not a crash), it works as expected in single player and lan worlds.  This issue also happens on another server with this modpack and to other players.

Other mods involved: https://www.curseforge.com/minecraft/modpacks/super-hostile-modpack/relations/dependencies 

Link to crash report https://pastebin.com/tZmEWVAP

I will try to find the problem mod later today.

**Comment by bluejello42** [comment]
testing with just electroblobs runs into the same issue.

**Comment by Electroblob77** [comment]
Great, it's another one of those random methods that's client-side only for no reason whatsoever. Thanks for reporting, will fix.

**Comment by 3omar13** [comment]
Having the same issue where I cant craft anything 12.2 dedicated server
But Im on version 4.3.4, I just made sure right now to make sure Im not crazy and somehow was running 4.3.3, I do not have compat skills either so I am at a loss for what is wrong

**Comment by 3omar13** [comment]
works fine in single player, but on my server I cannot craft anything in the arcane workbench
