### ISSUE TITLE
Crashing while using handbook

### ISSUE THREAD

**Issue by Worest0** [Electroblob77/Wizardry#610]
Minecraft version: 1.12.2 
Wizardry version: 4.3.3 
Environment: Singleplayer/LAN game

Issue details:

When I tried to open the handbook(in Hungarian language, I dont know it is matter, didn't try another language) it is crashed.
Not all the time, just sometimes.
Then I tried go back to the world, but I could not do it, because crash happened again.

Other mods involved: I'm using the Twilight Forest Pack, and the Extra Spells mod too.

Link to crash report (if applicable): https://pastebin.com/97E7xEGp

**Comment by Electroblob77** [comment]
Yeah that's a translation error. Try changing your language for now, I'll fix the translation file for the next update.

**Comment by Worest0** [comment]
> Yeah that's a translation error. Try changing your language for now, I'll fix the translation file for the next update.

Okey, I'll change the language, thank you for the answer.
