### ISSUE TITLE
Armor Upgrades not working

### ISSUE THREAD

**Issue by BluGX** [Electroblob77/Wizardry#612]
Minecraft version: 1.12.2  
Wizardry version: 4.3.3
Environment: Server 

Issue details: We have collected items for our wizard armors to upgrade into one of 3 types (Battle Mage, Sage, Warlock). Battle mage to be exact but, the upgrade did not happen.
Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by hadenkw** [comment]
Having the same issue with the Thread for Sage gear on our server. Also 1.12.2/4.3.3

**Comment by Electroblob77** [comment]
Do either of you have CompatSkills installed? The current version was causing problems with the arcane workbench.
Edit: may be related to #608, the above info would still be useful though

**Comment by Electroblob77** [comment]
Assuming this is the same as #608, now fixed in 4.3.4. Please reopen this issue if you still experience this problem.
