### ISSUE TITLE
"generated\.......... .json" file spam in server root folder

### ISSUE THREAD

**Issue by NLBlacky** [Electroblob77/Wizardry#615]
**Minecraft version:** 1.12.2 
**Wizardry version:** 4.3.3
**Environment:** Server

**Issue details:** 
After updating my server from `Roguelike Adventures and Dungeons` `v1.41` to version `v1.42` which updated `Electroblobs Wizardry` from version `v4.3.1` to `v4.3.3`, I've been getting 301x a file called something like `generated\.......... .json` in the root folder of the server instance. Everytime I try to delete the files, they re-appear after each server restart. 

**Other mods involved:**
Not sure which mods are involved, since only `ebwizardry` is mentioned in all the files I've opened. The modpack versions are listed above. If needed, you can check their server files for a list of mods per version.

**Relevant information:**
Part of the list + shows the amount of files:
![image](https://user-images.githubusercontent.com/42154364/106354266-bc8d9300-62f0-11eb-9052-f7f7c6c5cdf5.png)

Contents of one of the files, all look very similar:
![image](https://user-images.githubusercontent.com/42154364/106354270-c1eadd80-62f0-11eb-9c89-0bada1a6f256.png)

Difference between the 2 config files:
![image](https://user-images.githubusercontent.com/42154364/106354272-c7e0be80-62f0-11eb-87bf-a72a22a0df5a.png)

**Comment by Electroblob77** [comment]
Haha it seems I managed to leave my item model generator in... oops 😅 I'll get it fixed, thanks for reporting.

**Comment by Neptainium** [comment]
> Haha it seems I managed to leave my item model generator in... oops 😅 I'll get it fixed, thanks for reporting.

Any idea on when this will be patched? was just getting ready to make the same post myself.

**Comment by Electroblob77** [comment]
Imminently, just need to fix a few other issues and then I'll release a patch.
