### ISSUE TITLE
Don't know how to use gradle to add your modules to the code

### ISSUE THREAD

**Issue by AntiThesis1250** [Electroblob77/Wizardry#616]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.3 [change as necessary]

Question details: I'm new. I don't know how to use gradle to add your modules to the code.

Other mods involved: Just a moment. I'll post my gradlebuild below

**Comment by AntiThesis1250** [comment]
![Uploading can't  download.png…]()

**Comment by AntiThesis1250** [comment]
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not resolve electroblobs-wizardry:ElectroblobsWizardry:4.3.3.
  Required by:
      project :
   > Could not resolve electroblobs-wizardry:ElectroblobsWizardry:4.3.3.
      > Could not get resource 'https://minecraft.curseforge.com/api/maven/electroblobs-wizardry/ElectroblobsWizardry/4.3.3/ElectroblobsWizardry-4.3.3.pom'.
         > Could not GET 'https://minecraft.curseforge.com/api/maven/electroblobs-wizardry/ElectroblobsWizardry/4.3.3/ElectroblobsWizardry-4.3.3.pom'.
            > Connect to minecraft.curseforge.com:443 [minecraft.curseforge.com/104.19.147.132, minecraft.curseforge.com/104.19.146.132] failed: Connection timed out: connect

**Comment by AntiThesis1250** [comment]
```
buildscript {
    repositories {
        jcenter()
        maven { url = "https://files.minecraftforge.net/maven" }

    }
    dependencies {

        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'
//Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.

repositories {
    maven {
        name 'Curseforge Maven'
        url 'https://minecraft.curseforge.com/api/maven/'
    }

}
version = "1.0"
group = "com.yourname.modid" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "modid"

sourceCompatibility = targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    version = "1.12.2-14.23.5.2836"
    runDir = "run"

    // the mappings can be changed at any time, and must be in the following format.
    // snapshot_YYYYMMDD   snapshot are built nightly.
    // stable_#            stables are built at the discretion of the MCP team.
    // Use non-default mappings at your own risk. they may not always work.
    // simply re-run your setup task after changing the mappings to update your workspace.
    mappings = "snapshot_20171003"
    // makeObfSourceJar = false // an Srg named sources jar is made by default. uncomment this to disable.
}

dependencies {
    // you may put jars on which you depend on in ./libs
    // or you may define them like so..
    //compile "some.group:artifact:version:classifier"
    //compile "some.group:artifact:version"

    // real examples
    compile "electroblobs-wizardry:ElectroblobsWizardry:4.3.3:MC1.12.2"

    // the 'provided' configuration is for optional dependencies that exist at compile-time but might not at runtime.
    //provided 'com.mod-buildcraft:buildcraft:6.0.8:dev'

    // the deobf configurations:  'deobfCompile' and 'deobfProvided' are the same as the normal compile and provided,
    // except that these dependencies get remapped to your current MCP mappings
    //deobfCompile 'com.mod-buildcraft:buildcraft:6.0.8:dev'
    //deobfProvided 'com.mod-buildcraft:buildcraft:6.0.8:dev'

    // for more info...
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html

}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'

        // replace version and mcversion
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }

    // copy everything else except the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

```

**Comment by AntiThesis1250** [comment]
I can't download it with Google browser 
'https://minecraft.curseforge.com/api/maven/electroblobs-wizardry/ElectroblobsWizardry/4.3.3/ElectroblobsWizardry-4.3.3.pom'

**Comment by AntiThesis1250** [comment]
![Uploading QQ截图20210131151936.jpg…]()

**Comment by AntiThesis1250** [comment]
>

**Comment by Electroblob77** [comment]
1. I don't think this matters but try moving the `repositories` block to after the `compileJava` block
2. You should be using `deobfCompile`, not `compile`
3. Try `https://minecraft.curseforge.com/api/maven/deobf` instead of `https://minecraft.curseforge.com/api/maven`

There was some discussion about this a while back (see #436) and that last change worked for them, your mileage may vary.

Also, if you are using IntelliJ IDEA, make sure you run `gradlew setupDecompWorkspace`, restart IDEA, and refresh the Gradle project again. This often seems to fix problems with Gradle not refreshing properly so it's worth doing whenever you change anything in `build.gradle`.
