### ISSUE TITLE
charged Astral diamond, grand magic crystal, remnant

### ISSUE THREAD

**Issue by wowxiz** [Electroblob77/Wizardry#617]
Minecraft version: 1.12.2
Wizardry version: 4.3.1 
Question details: charged astral diamond: how do i obtain/craft this?
                            grand magic crystal: i read that is only found in dungeons, is that correct? if yes what type of dungeon, the 
                            vanilla ones?
                            Remnant: where can i found then? or how do i spawn(without the egg spawner)?

Other mods involved: R.A.D

**Comment by Electroblob77** [comment]
Charged astral diamonds are part of the Ancient Spellcraft addon, they are obtained using one of the addon's spells.
Grand magic crystals are found in both vanilla and wizardry structures.
Remnants are found around obelisk stuctures.

**Comment by wowxiz** [comment]
obelisk is the mage tower?

**Comment by WolfBV** [comment]
> obelisk is the mage tower?

https://github.com/Electroblob77/Wizardry/wiki/Obelisk
