### ISSUE TITLE
Wizard Armor Upgrades Not Working On A Server

### ISSUE THREAD

**Issue by GoldenMaster8** [Electroblob77/Wizardry#618]
Minecraft version: 1.12.2 
Wizardry version: 4.3.3 
Environment: Server 

Issue details: I was on my server trying to upgrade my armor to warlock, but when i clicked the upgrade button it played the sound like i was upgrading the armor, but nothing happened and no items were consumed.  I went on a singleplayer world and upgrading worked as intended, and I even tried restarting the server but it didn't help.

**Comment by Electroblob77** [comment]
Duplicate of #608
