### ISSUE TITLE
Curse of soulbinding never ends

### ISSUE THREAD

**Issue by Nocruz** [Electroblob77/Wizardry#619]
Minecraft version: 1.12.2 
Wizardry version: 4.3.3
Environment: Server

Issue details: When a player applies Curse of Soulbinding on another player, the effect remains even if the curse is removed. The victim won't see the effect next to the inventory, but its still there. Even after drinking the Purifying Elixr, using the Remove Curse spell, or even dying won't remove the curse

Other mods involved: Meldexun's Extra Spells may be involved.

**Comment by Electroblob77** [comment]
> the effect remains even if the curse is removed.

What _exactly_ do you mean by this? Does the victim still take damage when the player that used the curse does? I need to establish whether the potion effect is there but is somehow not displaying, or whether the potion effect is completely gone but the damage still happens anyway.

If you do `/effect @p clear`, does it fix the problem or does it tell you the victim has no potion effects?

**Comment by Nocruz** [comment]
The potion effect is gone, but the damage still happens. /effect does not work because the game considers there's no curse affecting the player right now

**Comment by Electroblob77** [comment]
Thanks for answering that. I can confirm this is a problem, it is caused by some data not being removed when the potion effect is removed. I will fix this for the next patch.

In the meantime, you should be able to get rid of the damage if the player that _cast_ the curse dies.

**Comment by Nocruz** [comment]
The other major problem is that dying doesnt remove the effect either

**Comment by ManfredRichthofen** [comment]
Same issue for me now neither the caster or the receiver can die yet lose all hearts and cant cast or interact with anything.
