### ISSUE TITLE
The hyperlink bug in CHS translation after remove the space which is around the hyperlink 

### ISSUE THREAD

**Issue by TUsama** [Electroblob77/Wizardry#620]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.4 [change as necessary]

Issue details: 

after https://github.com/Electroblob77/Wizardry/issues/527, you remove all the space around the hyperlink. Now it causes a new bug, see the pic below:

![image](https://user-images.githubusercontent.com/21279092/106705015-11e6de80-6628-11eb-9c47-a5a67d72c954.png)

code in repository: 

https://github.com/Electroblob77/Wizardry/blob/32340191de0c338e0f375b5b919fed98cf6f04f0/src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json#L730

In short, the hyperlink symbol "@" make the whole paragraph become a hyperlink, but it should just turn two words into a hyperlink.

This pic shows the text normally after add space at the around of the hyperlink.
![image](https://user-images.githubusercontent.com/21279092/106704371-fa5b2600-6626-11eb-9c2c-94c8393fc572.png)

corresponding code:

`						"想要在旅途中为你的 @wands 魔杖@ 充能？没问题！ @mana 魔力@ 现在可以被装入瓶内了。将八颗魔力水晶放入玻璃瓶中，魔法瓶的制作就这样简简单单。当你想使用它时，将它与你的魔杖合成一下，它将会为你的魔杖恢复一些魔力。",
`

I don't know if this issue can be fixed, considering https://github.com/Electroblob77/Wizardry/issues/527, we can add space back so that avoid this issue, but still hope you can take a look at it. thanks!

**Comment by Electroblob77** [comment]
This must be a problem with the code, hyperlinks are not supposed to need spaces around them in order to work correctly. I will take a look.

**Comment by TUsama** [comment]
Thanks for your time!

**Comment by Electroblob77** [comment]
Workaround: add newline characters (`\n`) manually, see #636. Leaving this open because I'd like to fix the underlying problem.
