### ISSUE TITLE
Minecraft wont start because GUI of the Handbook

### ISSUE THREAD

**Issue by LordMietz** [Electroblob77/Wizardry#622]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.4 [change as necessary]
Environment: Singleplayer

Issue details: Startet the game, before it even startet it crashed

Other mods involved: 98 mods, but they dont interfere with others, because it works at my friends pc

Link to crash report (if applicable): https://pastebin.com/676Kusmj

My Minecraft outputs this
![crash-picture](https://user-images.githubusercontent.com/78601498/107039575-602de600-67be-11eb-8f63-45e6bf00994c.png)

**Comment by Electroblob77** [comment]
What is your language set to?

**Comment by LordMietz** [comment]
my language is set to english

Am So., 7. Feb. 2021 um 14:47 Uhr schrieb Electroblob <
notifications@github.com>:

**Comment by Electroblob77** [comment]
Something is causing languages not to load properly. This cannot possibly be a problem with wizardry, nothing on the line of code where the crash happened should be null in a working installation.

**Comment by LordMietz** [comment]
and how do i fix it?
thanks for helping so far

**Comment by LordMietz** [comment]
just a note:
i tried and download other versions of the mod this includes: 4.3.4 - 4.2.9
No version worked tho

**Comment by WinDanesz** [comment]
Closing old ticket. Reopen if the issue is still present
