### ISSUE TITLE
Ethereal Crystalweave issue

### ISSUE THREAD

**Issue by ClockyVaudeville** [Electroblob77/Wizardry#623]
Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Server

Issue details: Basically Ethereal Crystalweave isn't working the way I expect it to. JEI says I can use it to change my wizard robes into warlock robes, regardless of what element they're for, fair enough. So I made some base wizard robes and turned them into Earth Wizard robes, but then when I tried to use the Ethereal Crystalweave to turn them into Earth Warlock robes it doesn't work. I thought they had to be charged so I charged them, then tried again, still nothing. Then I thought maybe the workbench didn't like that I'd enchanted them, so I used some of the unenchanted Lightning Wizard robes I have, and that didn't work either. So now I'm confused as to how the Crystalweave is supposed to work. 

Other mods involved: Not sure if there's any issues with the other mods, my game is playing stable, isn't crashing or anything so not sure.

Link to crash report (if applicable): Not applicable

**Comment by Electroblob77** [comment]
This is working fine for me (in singleplayer). Tried with unenchanted earth mage robes in both survival and creative, with and without crystals in the workbench.

Are you _sure_ that both the server and all clients are using wizardry 4.3.4? This was a bug in previous versions (see #608) but was fixed in 4.3.4. It would also be worth trying to apply the upgrade, then checking the server log for any error messages.

**Comment by ClockyVaudeville** [comment]
I checked, both client and serverside had the most recent version of the mod

**Comment by Electroblob77** [comment]
Weird. Is there anything in the server log?

**Comment by ClockyVaudeville** [comment]
Not that we saw, it just wasn't working. I don't have the logs anymore tho to be absolutely certain, but I recall the server owner saying there was nothing on the logs that was iff

**Comment by Skinnybones2002** [comment]
I am having the same issue but with all upgrade items, none of them work no matter which armor I attempt to use it on, I am running a server using the RAD lite modpack and I just checked and the mod is in 4.3.3, I am unable to update the mod itself without the server blocking me from joining, I use aternos to run servers.

**Comment by Electroblob77** [comment]
@Skinnybones2002 As I said above, there was a similar bug in 4.3.3 that was supposed to be fixed in 4.3.4, so it's likely you are experiencing the original bug. If you are unable to update the mod, that's not my problem, sorry.

**Comment by IzWush** [comment]
Hi 😄
How I can craft the Ethereal Crystalweave ? 😄
To upgrade my stuff
