### ISSUE TITLE
#Damage modifier in command doesn't work | {damage}

### ISSUE THREAD

**Issue by LANCECHEN117** [Electroblob77/Wizardry#627]
DAMAGE MODIFIER in casting command:   /cast spell {} OR    /cast spell x y z direction {}     DOESNT WORK

Minecraft version: 1.12.2 FORGE 8554
Wizardry version: 4.3.4 / previous version as well
Environment: Singleplayer/LAN game/Server both

Issue details: [describe what you were doing when the issue occurred, what went wrong, what you expected to happen, etc.]

Other mods involved: I only installed EBW for test 

By the way, one small suggestion : could you integrate this two form of cast command into one ?

THANKS ALOT!

**Comment by Electroblob77** [comment]
That's because it's not `damage`, it's `potency`. Apologies if you found that on the wiki or something, it may be out-of-date.

> By the way, one small suggestion : could you integrate this two form of cast command into one ?

How would this work, exactly? They do different things.

**Comment by LANCECHEN117** [comment]
> > By the way, one small suggestion : could you integrate this two form of cast command into one ?
> 
> How would this work, exactly? They do different things.

Hi blob, just like you can have /cast spell [@p,@a,@s] [position where cast happend] [direction] [modifier]

**Comment by LANCECHEN117** [comment]
/cast spell @p can be casted from defined position x,y,z and have it's direction lol

**Comment by Electroblob77** [comment]
Right, so if I understand correctly, you would like to be able to cast a spell at a position, but as a player? Seems a bit of a niche use case to me, and it would require significant rewriting of a lot of the spell code.
