### ISSUE TITLE
Sponge Forge server 1.12.2 crash after updating Electroblob's Wizardry

### ISSUE THREAD

**Issue by DarkStar0790** [Electroblob77/Wizardry#630]
Minecraft version: 1.12.2
Wizardry version: 4.3.4
Environment: Server

Issue details: I recently update the Electroblob's Wizardry from 4.3.1 to 4.3.4 and now my server crash randomly when someone enter to the server. sometime happen sometime dont with the same players. its random.

Link to crash report (if applicable): https://gist.github.com/DarkStar0790/c1c84f9818d9eee543cc023e1e40948e

**Comment by Electroblob77** [comment]
No wizardry mentioned in the stacktrace in that crash report. I'm pretty sure wizardry doesn't touch `PlayerChunkMap` either. If you downgrade wizardry to 4.3.1 again, does the crash stop happening?

**Comment by DarkStar0790** [comment]
Yeah its little weird, but so far the crash didnt happen again. For some weird reason.  Anyways I will keep you in tocuh and i will reopen this if happen again and also i will add my notes for more details.
