### ISSUE TITLE
Crash with some spells

### ISSUE THREAD

**Issue by eudalia** [Electroblob77/Wizardry#632]
Minecraft version: 1.12.2
Wizardry version: 4.3.4
Environment: Singleplayer

Issue details: Charge, Ice Shard and Thunderbolt spells give me a crash, when i had ice shard in my glove, my game would crash after loading

Other mods involved: I discovered Thunderbolt and it crashed, then reproduced the crash with it and the other spells with a summoned zombie from chocolate quest

Link to crash report (if applicable): https://pastebin.com/1SpYi1bP

**Comment by Electroblob77** [comment]
Gloves are part of the Zettai Magic addon. Could you temporarily remove that addon and try to reproduce the issue again?
