### ISSUE TITLE
LAG with space suits from extraplanets mod

### ISSUE THREAD

**Issue by theismarius** [Electroblob77/Wizardry#633]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.4 [change as necessary]
Environment: Singleplayer and LAN game

Issue details: When wizardry mod is added with extraplanets mod, when equiped extra planets space suit armor game starts laggin. Alredy opened an incident. (https://github.com/MJRLegends/ExtraPlanets/issues/631).

Other mods involved: extraplanets mod

Link to crash report (if applicable): No crash report, but adding .nps files. one with wizardry mod and other without it.
[wizardry.zip](https://github.com/Electroblob77/Wizardry/files/6032295/wizardry.zip)
[nowizardry.zip](https://github.com/Electroblob77/Wizardry/files/6032296/nowizardry.zip)

**Comment by Electroblob77** [comment]
This is the same kind of issue as #648. It's a bug in extra planets, they should not be creating new armour models every tick.

As with the other issue, I will add a safeguard against this but it's a good idea for the extra planets dev to fix this on their end. I've added a comment over on the other issue explaining the problem.
