### ISSUE TITLE
could not place the Receptacle on the Imbuement Altar

### ISSUE THREAD

**Issue by mlies** [Electroblob77/Wizardry#637]
Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Singleplayer and Server 

Issue details:  the Receptacle cannot place to the each side of imbuement altar
[https://media.giphy.com/media/5RtVXfHHqfeo2Wjf1L/giphy.gif](url)

**Comment by Electroblob77** [comment]
I assume you worked this out, but for anyone else reading this issue, you need to hold shift when placing them.
