### ISSUE TITLE
Where do I find the items used to make warlock, sage and battlemage armour in survival?

### ISSUE THREAD

**Issue by InsanePig** [Electroblob77/Wizardry#638]
Minecraft version: 1.12.2   
Wizardry version: 4.3.4 

Issue details: Hi there, I've been having a blast with the mod on a multiplayer server and I'm at the point where I want to get some sage armour, yet I haven't been able to find even one of the items I need to make it. I've been exploring the overworld looking for shrines and not found any resplendent thread and looted almost all of the end cities within a couple thousand blocks of the main island. I'm not sure if they're just super rare or if I'm doing something wrong, so I figured I'd ask about it on here.

**Comment by KnightCa** [comment]
I found the thread in dungeon chests. They are very rare to get.

**Comment by Electroblob77** [comment]
This is correct, they are rare loot from chests.
