### ISSUE TITLE
Hi so today i got a Bottom less pervisons charm and i cant bind it to my wand idk why if i could get some help that would be awsome

### ISSUE THREAD

**Issue by Jasmin2277** [Electroblob77/Wizardry#639]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.4 [change as necessary]

Question details: [explain your question here]

Other mods involved: [if this question involves other mods, list them here]

**Comment by MagmaSlime123** [comment]
Bottomless Pervisons is a charm. Not a Wand Upgrade.

If you have Baubles installed, put it in its respective Charm slot within the Baubles GUI (B by default). If done correctly, Restore Hunger should trigger when needed.

If Baubles isn't installed, keep the Charm on your hotbar.
