### ISSUE TITLE
Mod crashes Minecraft whilst initializing game

### ISSUE THREAD

**Issue by OCTAVIAN5085** [Electroblob77/Wizardry#640]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.3.4

Issue details: Whenever I try to Start Minecraft, it alwase crashes when it is initializing. When I look at the crash report, it says this mod is responsible

Other mods involved: No other mods.

Link to crash report: 
https://github.com/Electroblob77/Wizardry/files/6138051/crash-2021-03-14_20.18.05-client.txt

**Comment by WinDanesz** [comment]
update the arcane essentials mod to the latest version. known incompatibility, about the 100th issue with the same problem
