### ISSUE TITLE
Unable to work mod with minecraft forge.

### ISSUE THREAD

**Issue by NotAPotter** [Electroblob77/Wizardry#641]
Minecraft version: 1.16.2 [I think.]  
Wizardry version: 4.3.4 
Environment: Singleplayer

You'll have to forgive me, I'm very new to modding, from what I could gather from guides i needed to download minecraft forge and that seemed to get some mods i wanted to use to work, but this mod and one other related to it,  had an error message come up when started, saying it was for an 'earlier' version of forge. Naturally, i went and downloaded an earlier version of forge and tried again, but got the same message. So i kept going earlier and earlier until i hit 1.13, where i was told it and baubles were not valid mods.

What am I doing wrong?

**Comment by Naigaru** [comment]
This mod is for 1.12.2 as the highest compatible minecraft version right now, anything above will not work. (Notice how the file is called "Electroblob's Wizardry - 4.3.4 - MC 1.12.2" <---)
So try forge 14.23.5.2854 and make sure all your mods are compatible with 1.12.2 as well and you should be fine (on curseforge you can click files then in the dropdown menu specify which minecraft version you want to download the mod for)

**Comment by NotAPotter** [comment]
Well, that presents problems for other mods i want to use, but at least wizarding works. Thank you for your help.
