### ISSUE TITLE
electroblob's wizardry mod does not work on RLcraft modpack

### ISSUE THREAD

**Issue by moji497** [Electroblob77/Wizardry#642]
Minecraft version: 1.12.2 
Wizardry version: 4.3.4 

Question details: Hi , So today i start playing "RLcraft" and i added to it "Electroblob's wizardry" mod , the mod is working fine so i got some crystals and i crafted a wand and when i tried to charge it up with crystals it was not working and even i tried the novice magic missle spell , the wand stays empty , please help me and thanks you for reading my issue

Other mods involved: [Electroblob's wizardry, RLcraft modspack]

**Comment by WinDanesz** [comment]
Might be the compatskills mod - if RLcraft has it. Compatskills totally breaks the arcane workbench gui button

**Comment by draconique700** [comment]
@WinDanesz Thank you very much, your comment helps me solve the problem.

**Comment by YejiYeah** [comment]
> @WinDanesz Thank you very much, your comment helps me solve the problem.

What did you do to fix it?

**Comment by WinDanesz** [comment]
Disable the Wozardry integration in compatskills config and/or in the reskillable config, or remove compatskills

**Comment by jvthales** [comment]
Thank you so much!
