### ISSUE TITLE
[Give a brief, relevant title here]The Glide Sound doesn't stop

### ISSUE THREAD

**Issue by TheLuckyOne69** [Electroblob77/Wizardry#646]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.3.4
Environment: Singleplayer

Issue details: [When using the glide spell, the whooshing sound plays and when you land it doesn't stop for around 10-30 seconds.]

Other mods involved: [None]

Link to crash report (if applicable): [N/A]

**Comment by Electroblob77** [comment]
Okay, it's supposed to stop when you stop casting the spell. Thanks for reporting, I'll take a look.
