### ISSUE TITLE
No Such Method Error when initializing

### ISSUE THREAD

**Issue by Rknuts18** [Electroblob77/Wizardry#647]
I was encountering a crash bug when encountering an evil wizard and found the answer was to update the mod. Unfortunately, when I try to launch Minecraft it crashes on initialization and gives me this error

The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: electroblob.wizardry.spell.SpellRay.<init>(Ljava/lang/String;Ljava/lang/String;ZLnet/minecraft/item/EnumAction;)V
Exit Code: -1

Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Singleplayer/LAN game/Server

**Comment by Rknuts18** [comment]
Found the answer

**Comment by Rknuts18** [comment]
I updated Arcane Essentials and it's still throwing the error what did I do wrong?

**Comment by Rknuts18** [comment]
My brain is smooth and polished like a cue ball. I was using the wrong version still

**Comment by pyroAvatar91** [comment]
I am having this same error with my personal modpack and I have the most updated version of Arcane Essentials added as well. Here's my crash log: https://pastebin.com/buCS1eFi

Can someone check it out and let me know what's wrong and how to fix it? Thanks!
