### ISSUE TITLE
Can't look at certain spells in the wiki.

### ISSUE THREAD

**Issue by SterIing** [Electroblob77/Wizardry#65]
Part of the wiki looks like its requesting admin access just to read, can you fix this for the novice tier spells? Thank you!

**Comment by Electroblob77** [comment]
The answer is that those pages don't exist yet! Normally those links would be red, but for some reason that doesn't happen if they're in a table.

In case you were wondering why it says that message: if I click a redlink (red or not), github automatically directs me to create a new page with that title, but this happens even if you don't have edit permission... except you can't create the page, so it displays that (rather confusing) message instead.
