### ISSUE TITLE
Shadow Ward [advanced spell] causes huge lag issue and spams the console with errors

### ISSUE THREAD

**Issue by minh-dong** [Electroblob77/Wizardry#650]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Server

Issue details: My friend and I were playing on MC Eternal modpack. Friend has the Shadow Ward spell equipped and he told me to hit him. So I did with a TiC sword and generate a huge lag on the server along with the console being spammed. Not only that, the log file generated like 200MB under a minute.

Other mods involved: mods from MC Eternal 1.4.3.1

Link to crash report (if applicable): https://drive.google.com/file/d/1i_mrZcxzA4JTEcYRloli5P4QSX0UYa7k/view?usp=sharing
_Uploaded to drive since the file is way too large for me to open it and copy/paste it + it crashes my browser attempting to do so_

**Comment by WinDanesz** [comment]
Hello
1) Shadow Ward is a spell of Ancient Spellcraft, so it doesn't belong to this issue tracker, but to AS's.
2) You are using an outdated version of AS, this issue is already fixed in the latest release. Either update your pack if the latest version contains the last AS release or update AS manually.

**Comment by minh-dong** [comment]
Oh, didn't know it was related to AS. A mod from MC Eternal told me to report that issue here. I might as well report it to the mod pack developer then to use the updated mod.

Thanks!
