### ISSUE TITLE
Arcane workbench not working in modpack

### ISSUE THREAD

**Issue by GenWarfield** [Electroblob77/Wizardry#652]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Server

Issue details: 
I'am currently using the R.A.D pack (lite) modpack (server edition) and it seems that upgrading the wizard armor sets doesn't work properly. The animation plays but neither the upgrade material nor does the wizard armor get upgraded (such as using resplendent thread, etc), they also do not get consumed.

I suspect it may be caused by quality tools mod but am not sure. Would appreciate some help in tracing the issue as I'm not sure how to blacklist the armor or isolate the issue.

Further testing has shown that electrobob wizardry armor don't provide any mana reduction effects whatsoever either. 

-----------------------------------------------------
Issue is not present in single player, the arcane workbench functions normally and wizard armor is upgraded normally as well as upgrade material being consumed.
-----------------------------------------------------

Other mods involved: R.A.D (lite) modpack, potentially caused by Quality tools or an error with the server world file.. 

Link to crash report (if applicable): no crash, just absence of functionality.

**Comment by MagmaSlime123** [comment]
I'd recommend asking the R.A.D developers. If they use CompatSkills,
then disable its compat. with Wizardry. Read #609 for more info.

**Comment by Electroblob77** [comment]
Sounds a lot like that issue to me. Please reopen this issue if it turns out not to be.
