### ISSUE TITLE
Ancient Compass Does not Work

### ISSUE THREAD

**Issue by Sharpeims** [Electroblob77/Wizardry#657]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.4 [change as necessary]
Environment: Singleplayer/LAN game/Server [delete as necessary]

Issue details: Ancient Compass does not work

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Electroblob77** [comment]
You need to equip it by placing it in your Baubles charm slot if you have Baubles installed, or on your hotbar if not. Once you have done so, you should be able to click on multiple stone circles while the compass is equipped and then when you select transportation on your wand, you should see icons appear in the direction of each stone circle you clicked. Cast the spell while looking at one of those icons to teleport there.

If this isn't working for you, please let me know which step you're having trouble with. Thanks.
