### ISSUE TITLE
Freeze texture does not show up on layers

### ISSUE THREAD

**Issue by WesternSpace** [Electroblob77/Wizardry#659]
Minecraft version: 1.12.2 
Wizardry version: 4.3.4
Environment: LAN game

Issue details: I was playing with the mod on a lan world when I noticed a bug with the Frostbite effect. The freeze texture shows up on the player itself but not on the layers.
![Screenshot (271)](https://user-images.githubusercontent.com/80211714/118410136-f5f9cc80-b65b-11eb-8bf7-9cd1c2ad2e09.png)

Other mods involved: None

Link to crash report (if applicable): None

**Comment by Electroblob77** [comment]
There is nothing I can do about this, unfortunately. The freeze texture is itself a layer and the layer system doesn't allow layers to be applied to other layers. It kind of makes sense though, it freezes your body but not your clothes... I guess?
