### ISSUE TITLE
Sage armor cannot be repaired with Mending Enchantment

### ISSUE THREAD

**Issue by KnightCa** [Electroblob77/Wizardry#662]
Minecraft version: 1.12.2
Wizardry version: 4.3.4
Environment: Singleplayer

Issue details: Sage armor can be enchanted with Mending, but experience orbs don't repair it. Didn't test this with the normal wizard robes.

**Comment by Electroblob77** [comment]
Intended behaviour. Wizard robes must be recharged with crystals, they cannot be repaired via normal means. I should probably prevent that enchantment being applied though.
