### ISSUE TITLE
Problems with Possession

### ISSUE THREAD

**Issue by r-uthel** [Electroblob77/Wizardry#666]
Minecraft version: [1.12.2]
Wizardry version: [4.3.4]
Environment: [Singleplayer]

Issue details: So, I was using my wand, as usual. When I tried using Possession, it worked. But, the game, instead of running like how it was running all of the time, started lagging incredibly.. I usually have about 60-100 FPS, but it jumped to about three. However, it doesn't crash and I can press the Left Shift to exit it and it all returns to normal. I have no idea what's causing it, and here I am. Posting about my problem.

Other mods involved: Alright, since I don't know if the mods are causing it (they prob are), I'm going to list them all;
- Ancient Spellcraft [1.1.3]
- ExtraSpells [1.2.0]
- Optifine [1.12.2 HD U G5]
- Twilightforest [3.11.1021 - Universal]
- ZettaiMagic+ [1.4.2]
- Seeds For Wizardry [1.0]
- TFSpellPack [1.1.0]

Link to crash report: None

**Comment by Electroblob77** [comment]
What mob did you possess, or does it happen for any mob?

The quickest way to get to the bottom of this would be to install LagGoggles (https://www.curseforge.com/minecraft/mc-mods/laggoggles). Once you've done that, cast possession again and then open up the LagGoggles interface. Run the profiler for a few seconds then analyse the results and post a screenshot here. It should tell me which bit of the code is causing the lag.

**Comment by r-uthel** [comment]
When I was about to go screenshot, I casted possession and the
problem seems to have fixed itself. Maybe it was something temporary or a
problem with/about my laptop. Have a good day, thanks for answering.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Electroblob77** [comment]
Okay, I'll close this for now then. If it happens again, feel free to reopen this issue.
