### ISSUE TITLE
Unable to craft magical crystals from flowers

### ISSUE THREAD

**Issue by TranquilStar** [Electroblob77/Wizardry#667]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 

Wizardry version: 4.3.4
Environment: Server

Issue details: Unable to craft magical crystals from crystal flowers

Other mods involved:
![mods](https://user-images.githubusercontent.com/76603402/120833894-53cd5600-c530-11eb-943f-1fd3db0eaa56.png)

**Comment by TranquilStar** [comment]
I checked and no it wasnt witchery resurrected

**Comment by WinDanesz** [comment]
I'd suggest joining the discord server to have a quicker way to discuss, you can find the link in the mod's CurseForge page.
Otherwise, what does JEI show for the Crystal Flower? No recipes at all?

**Comment by Electroblob77** [comment]
Very strange, since that recipe is entirely handled by the vanilla system and wizardry only provides the JSON file for it. What crafting interface are you using, the vanilla workbench, the 2x2 grid or a modded crafting table?
