### ISSUE TITLE
ForceField speel dosen't work anymore

### ISSUE THREAD

**Issue by Zaureon** [Electroblob77/Wizardry#668]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.4 [change as necessary]
Environment: Singleplayer/LAN game/Server [delete as necessary]

Issue details: The ForceField spell dosen't work anymore, when you try to use it the shield will be there, but you can't be in, like it isn't yours

Other mods involved: I don't think that another mod is influencing that issue

**Comment by Electroblob77** [comment]
Did this happen straight after you cast the spell, or did it stop working after you quit and log back in?

**Comment by Zaureon** [comment]
Doesn't matter how you cast the spell, it won't work anyway

**Comment by WinDanesz** [comment]
Is this immediate, or after re-logging to the game?
