### ISSUE TITLE
Pigmented Planks Crash

### ISSUE THREAD

**Issue by DragonCatGaming** [Electroblob77/Wizardry#67]
g.

Minecraft version: 1.12.2
Wizardry version: 4.1.2
 Environment: Server 

Issue details: pigmented wisdom wood planks caused crashes in 2 out of the 3 players on a private server, happened whenever the unafflicted player held it in his hand, the other players opened a chest with it, picked it up, or whenever it was dropped on the ground.

Other mods involved: a large number of mods involved. possible conflicts. the mods list includes: Biblocraft, biomes a plenty, block armor, chest transporter, chisel, chiselsandbits, connected textures, custommobspawner, tinkers construct, mo creatures, twlight forest, and quark mod. latest version of all mods of time of this report installed

Link to crash report (if applicable): 
[crash-2018-08-15_20.44.42-client.txt](https://github.com/Electroblob77/Wizardry/files/2292365/crash-2018-08-15_20.44.42-client.txt)

**Comment by Electroblob77** [comment]
I think you want the other wizardry mod! Have a link: https://github.com/TeamWizardry/Wizardry/issues

**Comment by DragonCatGaming** [comment]
... i feel dumb now :P
