### ISSUE TITLE
How to increase the number of improvements in one wand?

### ISSUE THREAD

**Issue by Sfgod** [Electroblob77/Wizardry#670]
Please read the [guide for contributing]) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.4 [change as necessary]

Question details: [explain your question here]

Other mods involved: [if this question involves other mods, list them here]

**Comment by MagmaSlime123** [comment]
Wand Upgrades. Put them in the upper right slot of the Arcane Workbench, a Wand in the center slot, then hit Apply.
Wands can only a certain amount of upgrades. Upgrades and everything related to them can be configured.

**Comment by Electroblob77** [comment]
I think they mean how can they change the maximum number of upgrades that can be applied to a wand. This is currently not possible but has been requested a lot, it might get added in future but I don't know.
