### ISSUE TITLE
Question for wizardry fate add  - sub-discipline potency configs 

### ISSUE THREAD

**Issue by lunarmaximum** [Electroblob77/Wizardry#674]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.4 
Wizardry Fate Version 2.0.0.

Question details: I had originally asked on discord but my message got deleted... not sure why? I just wanted help. 
Does the potency reduction on the wizardry fate configs work for buffs like empowering presence? I was trying to reduce potency on sub-disciplines by 60% in order to not have any advantage on elemental wands.

**Comment by WinDanesz** [comment]
This is the issue tracker of the base mod, not for my unofficial addon. I'd suggest joining the discord if you have questions about my addons https://discord.gg/QExbJntsdR
