### ISSUE TITLE
Silverfish Swarm and Spider Swarm is not working correctly

### ISSUE THREAD

**Issue by ghost** [Electroblob77/Wizardry#678]
Forge Version: 14.23.5.2854 
Minecraft version: 1.12.2
Wizardry version: 4.3.4 
Environment: Singleplayer

Issue details: After using the spell, the silverfish began to attack me (I checked whether they attack the mobs that I hit and also checked whether they attack the mobs that damage me and they just continued to attack me) and the same thing happened with the spiders

Other mods involved: None

Link to crash report (if applicable): None

**Comment by WinDanesz** [comment]
Refer to my reply of #679
