### ISSUE TITLE
radiant totem does not working correctly

### ISSUE THREAD

**Issue by ghost** [Electroblob77/Wizardry#679]
Forge Version: 14.23.5.2854
Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Singleplayer

Issue details: the radiant totem is attacking me (I summoned him and he starts attacking me) it makes no difference which mode you are in

Other mods involved: None

Link to crash report (if applicable): None

**Comment by Electroblob77** [comment]
Did you re-log after casting it, or does it do that immediately?

Is it actually damaging you or just showing the beam of light?

**Comment by ghost** [comment]
> Did you re-log after casting it, or does it do that immediately?
> 
> Is it actually damaging you or just showing the beam of light?

I rebooted the game after that and yes it does damage in the form of damage

**Comment by ghost** [comment]
The problem disappeared after that, but I think that if I close this report, then the problem will not be solved

**Comment by Electroblob77** [comment]
> I rebooted the game after that and yes it does damage in the form of damage

Right, I assumed that was the case but was worth checking.

> The problem disappeared after that, but I think that if I close this report, then the problem will not be solved

Yeah don't close the issue, leave it with me and I'll see what I can find out.

**Comment by WinDanesz** [comment]
Are you playing with a MC account purchased on minecraft.net or a cracked one? Because this owner (UUID) resetting is a known symptom of cracked clients. Reopen the issue if this was a legit account so that we can further look into the issue. (Don't expect a fix for cracked accounts)
