### ISSUE TITLE
Mana Flasks not working in Tinkers Construct crafting stations

### ISSUE THREAD

**Issue by whitepik101** [Electroblob77/Wizardry#68]
Minecraft version: 1.12.2  
Wizardry version: 4.1.2
Environment: Singleplayer

Issue details: When crafting a mana flask with a wand or any of the wizard clothing using a TC crafting station, the mana value turns into an extremely low negative number that differs depending on what item is used, this does not happen in a regular crafting table

Other mods involved: Tinkers Construct

Link to crash report (if applicable): No crash

A screenshot of the issue:
![2018-08-17_20 28 54](https://user-images.githubusercontent.com/13441106/44285737-70545280-a25e-11e8-8242-3a73f397af2e.png)

**Comment by Electroblob77** [comment]
This will happen with any modded crafting table that does not extend the vanilla one. I'll have to figure out a way of handling such crafting tables without knowing what they are at compile-time. Wizardry certainly isn't only mod that has repair recipes like this, I'll see if I can find out how other mods do it.

For the record, I think the value you're seeing is the minimum integer value (-32767) plus whatever durability the item should have.
