### ISSUE TITLE
Hyeleth's Amulet does not consume scroll on activation.

### ISSUE THREAD

**Issue by jazoobio** [Electroblob77/Wizardry#680]
Minecraft version: 1.12.2
Wizardry version: 4.3.4
Environment: Server

Issue details: When the Hyeleth's Amulet activates the shield spell via a spell scroll, the scroll is not consumed and thus the effect can be used endlessly without cost.

Other mods involved: None

Link to crash report (if applicable): None

**Comment by Electroblob77** [comment]
Huh, interesting. I don't think it's supposed to work with scrolls so I'll just disable that entirely.
