### ISSUE TITLE
[Multicraft smp crashes when casting spells]

### ISSUE THREAD

**Issue by darkri2000** [Electroblob77/Wizardry#681]
Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Server [

Issue details: [Every time i try to use a wand or cast a spell the server crashes and kicks me off]

Other mods involved: Ancientspellcraft 1.1.3
                                    Arte magicum 1.0.0
                                    Baubles 1.12-1.5.2
                                    Electroblob's wizardry 4.3.4
                                    Iceandfire 1.9.1 - 1.12.2
                                    Kaishi's weaposn reborn v2018.01
                                    twilightforest 1.12.2-3.11.1021
                                    Xaeros Minimap 21.8.2
                                    Xaeros World Map 1.13.5
                                    Zettai Magic 1.4.2
Link to crash report : ---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_21.8.2_Forge_1.12.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.13.5_Forge_1.12.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 6/23/21 11:32 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at electroblob.wizardry.spell.Spell.isEnabled(Spell.java:904)
	at electroblob.wizardry.WizardryEventHandler.onSpellCastPreEvent(WizardryEventHandler.java:130)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_58_WizardryEventHandler_onSpellCastPreEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at electroblob.wizardry.item.ItemWand.canCast(ItemWand.java:453)
	at electroblob.wizardry.item.ItemWand.func_77659_a(ItemWand.java:377)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.optifine.override.PlayerControllerOF.func_187101_a(PlayerControllerOF.java:80)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at electroblob.wizardry.spell.Spell.isEnabled(Spell.java:904)
	at electroblob.wizardry.WizardryEventHandler.onSpellCastPreEvent(WizardryEventHandler.java:130)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_58_WizardryEventHandler_onSpellCastPreEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at electroblob.wizardry.item.ItemWand.canCast(ItemWand.java:453)
	at electroblob.wizardry.item.ItemWand.func_77659_a(ItemWand.java:377)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.optifine.override.PlayerControllerOF.func_187101_a(PlayerControllerOF.java:80)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['CasuallyNoob'/748, l='MpServer', x=98.75, y=87.00, z=30.47]]
	Chunk stats: MultiplayerChunkCache: 433, 433
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (152,64,256), Chunk: (at 8,4,0 in 9,16; contains blocks 144,0,256 to 159,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 24448 game time, 24448 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 86 total; [EntityPlayerSP['CasuallyNoob'/748, l='MpServer', x=98.75, y=87.00, z=30.47], EntityCreeper['Creeper'/1152, l='MpServer', x=107.50, y=59.00, z=11.50], EntityChicken['Gallina'/898, l='MpServer', x=124.20, y=77.00, z=-6.50], EntityChicken['Gallina'/899, l='MpServer', x=112.88, y=85.00, z=3.45], EntityChicken['Gallina'/900, l='MpServer', x=121.06, y=80.00, z=-0.95], EntityChicken['Gallina'/906, l='MpServer', x=132.00, y=78.00, z=1.50], EntityBat['Murciélago'/910, l='MpServer', x=175.84, y=13.85, z=39.50], EntityBat['Murciélago'/1188, l='MpServer', x=77.18, y=22.96, z=45.21], EntityBat['Murciélago'/1191, l='MpServer', x=69.54, y=43.35, z=3.30], EntitySkeleton['Esqueleto'/811, l='MpServer', x=23.50, y=27.00, z=-35.75], EntitySkeleton['Esqueleto'/812, l='MpServer', x=24.52, y=27.00, z=-34.70], EntityBat['Murciélago'/813, l='MpServer', x=25.36, y=51.01, z=-40.32], EntityCreeper['Creeper'/814, l='MpServer', x=31.83, y=44.00, z=-13.47], EntityBat['Murciélago'/815, l='MpServer', x=37.49, y=31.11, z=7.56], EntityZombie['Zombi'/816, l='MpServer', x=30.75, y=46.00, z=6.46], EntityZombie['Zombi'/818, l='MpServer', x=27.51, y=26.03, z=21.70], EntityCreeper['Creeper'/819, l='MpServer', x=30.50, y=46.00, z=20.50], EntitySkeleton['Esqueleto'/825, l='MpServer', x=45.50, y=29.00, z=-6.50], EntityChicken['Gallina'/827, l='MpServer', x=49.17, y=98.00, z=51.50], EntityChicken['Gallina'/828, l='MpServer', x=41.63, y=96.00, z=47.47], EntityChicken['Gallina'/829, l='MpServer', x=44.49, y=99.00, z=45.79], EntitySkeleton['Esqueleto'/830, l='MpServer', x=37.73, y=17.00, z=71.50], EntitySkeleton['Esqueleto'/831, l='MpServer', x=37.82, y=16.00, z=67.79], EntityItem['item.item.seeds'/833, l='MpServer', x=41.94, y=63.00, z=90.88], EntityCreeper['Creeper'/1090, l='MpServer', x=40.50, y=16.00, z=68.50], EntitySkeleton['Esqueleto'/1220, l='MpServer', x=29.50, y=29.00, z=8.50], EntityZombie['Zombi'/965, l='MpServer', x=172.50, y=19.00, z=18.50], EntityZombie['Zombi'/843, l='MpServer', x=54.50, y=21.00, z=-18.75], EntitySkeleton['Esqueleto'/971, l='MpServer', x=72.50, y=25.00, z=-17.50], EntityZombie['Zombi'/844, l='MpServer', x=56.50, y=21.00, z=-20.17], EntitySkeleton['Esqueleto'/845, l='MpServer', x=49.50, y=39.00, z=-22.50], EntityChicken['Gallina'/846, l='MpServer', x=50.41, y=86.00, z=-31.17], EntityChicken['Gallina'/847, l='MpServer', x=58.16, y=89.00, z=-17.50], EntityChicken['Gallina'/848, l='MpServer', x=62.11, y=92.00, z=-22.62], EntityChicken['Gallina'/849, l='MpServer', x=51.50, y=88.00, z=-27.50], EntityZombie['Zombi'/978, l='MpServer', x=164.50, y=18.00, z=-7.50], EntityZombie['Zombi'/979, l='MpServer', x=158.75, y=19.00, z=0.46], EntityZombie['Zombi'/852, l='MpServer', x=48.50, y=54.00, z=11.50], EntitySkeleton['Esqueleto'/853, l='MpServer', x=60.50, y=54.00, z=28.50], EntityZombie['Zombi'/981, l='MpServer', x=168.50, y=18.00, z=-7.50], EntitySkeleton['Esqueleto'/854, l='MpServer', x=58.30, y=54.00, z=21.43], EntityChicken['Gallina'/855, l='MpServer', x=48.44, y=101.00, z=47.50], EntityCreeper['Creeper'/856, l='MpServer', x=61.50, y=26.00, z=70.16], EntitySkeleton['Esqueleto'/857, l='MpServer', x=49.26, y=16.00, z=77.46], EntityBat['Murciélago'/858, l='MpServer', x=43.67, y=19.82, z=72.93], EntityCreeper['Creeper'/859, l='MpServer', x=74.50, y=17.00, z=-33.50], EntityZombie['Zombi'/860, l='MpServer', x=73.20, y=17.00, z=-23.48], EntityZombie['Zombi'/861, l='MpServer', x=69.50, y=16.00, z=-19.50], EntitySkeleton['Esqueleto'/862, l='MpServer', x=64.50, y=29.00, z=-29.50], EntityCreeper['Creeper'/863, l='MpServer', x=64.50, y=29.00, z=-29.50], EntityBat['Murciélago'/864, l='MpServer', x=70.69, y=42.93, z=-14.63], EntityBat['Murciélago'/865, l='MpServer', x=67.49, y=40.79, z=-15.47], EntityBat['Murciélago'/866, l='MpServer', x=65.57, y=57.10, z=11.32], EntityBat['Murciélago'/994, l='MpServer', x=32.50, y=42.51, z=14.45], EntityZombie['Zombi'/867, l='MpServer', x=76.76, y=62.00, z=9.52], EntityChicken['Gallina'/868, l='MpServer', x=68.57, y=101.00, z=15.50], EntityBat['Murciélago'/870, l='MpServer', x=64.40, y=26.02, z=69.02], EntityVillager['Aldeano'/742, l='MpServer', x=151.43, y=66.00, z=100.53], EntityCreeper['Creeper'/871, l='MpServer', x=74.17, y=23.00, z=54.50], EntityVillager['Aldeano'/743, l='MpServer', x=144.43, y=66.00, z=98.30], EntityCreeper['Creeper'/872, l='MpServer', x=67.99, y=26.00, z=55.46], EntityVillager['Aldeano'/744, l='MpServer', x=160.49, y=72.00, z=107.33], EntityVillager['Aldeano'/745, l='MpServer', x=167.81, y=68.00, z=104.91], EntityBat['Murciélago'/874, l='MpServer', x=75.75, y=25.10, z=48.75], EntityVillager['Aldeano'/746, l='MpServer', x=167.30, y=68.00, z=105.70], EntityVillager['Aldeano'/747, l='MpServer', x=163.48, y=67.94, z=105.69], EntityBat['Murciélago'/1004, l='MpServer', x=175.17, y=22.23, z=-33.50], EntityChicken['Gallina'/749, l='MpServer', x=101.47, y=86.00, z=26.41], EntityCreeper['Creeper'/877, l='MpServer', x=88.50, y=32.00, z=-6.50], EntityCreeper['Creeper'/878, l='MpServer', x=86.50, y=32.00, z=-7.50], EntityZombie['Zombi'/879, l='MpServer', x=85.50, y=37.00, z=4.50], EntitySkeleton['Esqueleto'/880, l='MpServer', x=83.50, y=62.00, z=9.50], EntityChicken['Gallina'/881, l='MpServer', x=72.44, y=98.00, z=20.16], EntityChicken['Gallina'/882, l='MpServer', x=83.28, y=92.00, z=7.77], EntityEnderman['Enderman'/883, l='MpServer', x=94.50, y=18.00, z=18.50], EntityChicken['Gallina'/885, l='MpServer', x=87.12, y=90.00, z=24.60], EntityBat['Murciélago'/1141, l='MpServer', x=49.09, y=53.02, z=14.85], EntityChicken['Gallina'/886, l='MpServer', x=73.49, y=90.00, z=49.95], EntityChicken['Gallina'/887, l='MpServer', x=92.30, y=86.00, z=34.84], EntityChicken['Gallina'/888, l='MpServer', x=109.50, y=83.00, z=-18.38], EntityChicken['Gallina'/889, l='MpServer', x=104.97, y=82.00, z=-12.62], EntityChicken['Gallina'/890, l='MpServer', x=93.76, y=84.00, z=-9.52], EntityChicken['Gallina'/891, l='MpServer', x=103.31, y=84.42, z=10.63], EntityChicken['Gallina'/892, l='MpServer', x=105.39, y=77.00, z=58.11], EntityCreeper['Creeper'/1150, l='MpServer', x=108.53, y=59.00, z=12.07], EntityCreeper['Creeper'/1151, l='MpServer', x=107.50, y=59.00, z=11.50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1377896240 bytes (1314 MB) / 4160749568 bytes (3968 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version       | Source                                             | Signature                                |
	|:------ |:------------------- |:------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2        | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                 | 9.42          | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                 | 8.0.99.99     | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2855  | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core   | 1.12.2-1.0    | minecraft.jar                                      | None                                     |
	| LCHIJA | xaeroworldmap_core  | 1.12.2-1.0    | minecraft.jar                                      | None                                     |
	| LCHIJA | damageindicatorsmod | 1.0           | [1.12.2]DamageIndicatorsMod-3.5.1.jar              | None                                     |
	| LCHIJA | baubles             | 1.5.2         | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA | jei                 | 4.16.1.301    | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| LCHIJA | ebwizardry          | 4.3.4         | ElectroblobsWizardry-4.3.4-MC1.12.2.jar            | None                                     |
	| LCHIJA | ancientspellcraft   | 1.1.3         | ancientspellcraft-1.1.3.jar                        | None                                     |
	| LCHIJA | arte_magicum        | 1.0.0         | ArteMagicum+1.0.0.jar                              | None                                     |
	| LCHIJA | ichunutil           | 7.2.1         | iChunUtil-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | backtools           | 7.0.1         | BackTools-1.12.2-7.0.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | craftstudioapi      | 1.0.0         | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | customnpcs          | 1.12          | CustomNPCs_1.12.2-(05Jul20).jar                    | None                                     |
	| LCHIJA | orelib              | 3.6.0.1       | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround           | 3.6.1.0       | DynamicSurroundings-1.12.2-3.6.1.0.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | forgelin            | 1.8.2         | Forgelin-1.8.2.jar                                 | None                                     |
	| LCHIJA | fpsreducer          | mc1.12.2-1.18 | FpsReducer-mc1.12.2-1.18.jar                       | None                                     |
	| LCHIJA | llibrary            | 1.7.20        | llibrary-1.7.20-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire          | 1.9.1         | iceandfire-1.9.1-1.12.2.jar                        | None                                     |
	| LCHIJA | kaishiweapons       | v2018.01      | Kaishi's+Weapons+REBORN+v2018.01+[1.12.2].jar      | None                                     |
	| LCHIJA | lunatriuscore       | 1.2.0.42      | LunatriusCore-1.12.2-1.2.0.42-universal.jar        | None                                     |
	| LCHIJA | moreplayermodels    | 1.12.2        | MorePlayerModels_1.12.2-(05Dec19).jar              | None                                     |
	| LCHIJA | spartanshields      | 1.5.4         | SpartanShields-1.12.2-1.5.4.jar                    | None                                     |
	| LCHIJA | twilightforest      | 3.11.1021     | twilightforest-1.12.2-3.11.1021-universal.jar      | None                                     |
	| LCHIJA | worldedit           | 6.1.10        | worldedit-forge-mc1.12.2-6.1.10-dist.jar           | None                                     |
	| LCHIJA | xaerominimap        | 21.8.2        | Xaeros_Minimap_21.8.2_Forge_1.12.jar               | None                                     |
	| LCHIJA | xaeroworldmap       | 1.13.5        | XaerosWorldMap_1.13.5_Forge_1.12.jar               | None                                     |
	| LCHIJA | zettaimagic         | 1.4.2         | ZettaiMagic+1.4.2.jar                              | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
XaeroMinimapPlugin (Xaeros_Minimap_21.8.2_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
XaeroWorldMapPlugin (XaerosWorldMap_1.13.5_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 465.89' Renderer: 'NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 465.89, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 465.89
	OpenGlRenderer: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8]

**Comment by WinDanesz** [comment]
The crash log is a bit generic, can you reproduce the error without the Ebwiz addons?

**Comment by Electroblob77** [comment]
`Server brand: vanilla`

...have you even installed the mod on the server? Normally for a modded server this should say `fml; forge` or similar.

The crash report you gave is a _client_ crash report. You said the server crashed so please post the _server_ crash report (and please use gist or pastebin this time).

This crash report is caused by the spell properties files failing to load, but due to what I said above I can't be sure if that's the real issue. If you have been editing the spell properties files then it would be a good idea to try removing your custom ones.

**Comment by darkri2000** [comment]
I'm sorry to bother you but i have no idea on what is going on actually xD....It's my first server and i just follow what everyone told me. Copy the forge (custom.jar) into multicraft by firezilla and then put the mods into the mods folder and relaunch a new world. Its weird because all those mods in single player work perfectly even with ancient spellcraft, arte magicum and zettai magic but when i put them in the server, i don't know why, it kicks me off the server and that's the only crash report i got.
Im sorry im stupid i'm trying my best ;-;

**Comment by Electroblob77** [comment]
Don't worry, we're here to help! (Sorry if I came across angry, that's not how I meant it 🙂)

To be honest I'm not familiar with multicraft, I assume it's similar to other hosting services but I don't know. If you have Discord you may find it helpful to join the wizardry discord server (https://discord.gg/hs8yJP2) and see if there's someone in there with experience running modded servers who would be willing to help you out.

What I can help with is how to find the server crash report. If you go onto filezilla, next to your mods folder should be one called `crash-reports`, the crash report should be in there.

> Im sorry im stupid i'm trying my best ;-;

You're not stupid, just inexperienced. There's a big difference!
