### ISSUE TITLE
Server crashes when summoning mage.

### ISSUE THREAD

**Issue by darkri2000** [Electroblob77/Wizardry#682]
Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Server

Issue details: Hey, it's me again. I managed to run everything and the game works, until it tries to summon a mage (it seems from what i read from the console).

List of mods being used: https://imgur.com/JeZI72P

Link to crash report (if applicable): https://pastebin.com/UzKgzK02
Link to console when the game crashed: https://pastebin.com/b9NKxbxW

**Comment by WinDanesz** [comment]
Arte Magicum mod issue amd not EBWiz. Report to the mod's author
