### ISSUE TITLE
Crash in modded server

### ISSUE THREAD

**Issue by felipeleite5w** [Electroblob77/Wizardry#683]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting. You may also find the [troubleshooting page](https://github.com/Electroblob77/Wizardry/wiki/Troubleshooting) helpful.

Minecraft version: 1.7.10 
Wizardry version: Electroblob's+Wizardry+-+1.1.5+-+MC+1.7.10.jar
Environment: Multiplayer

Issue details: server crash suddenly

Link to crash report (if applicable): https://gist.github.com/felipeleite5w/aae62b2d518249de7a7210675d4ac7c8

**Comment by Electroblob77** [comment]
1.7.10 is no longer in active development, sorry.

Looks like a chunk was unloaded with a spark bomb in it, then reloaded when the player that shot it was no longer online, so you could try using an external program to delete all spark bombs in the world save file, then launch the server again.

**Comment by felipeleite5w** [comment]
so, you cant fix it @Electroblob77 ?

**Comment by Electroblob77** [comment]
I won't be releasing any new patches for 1.7.10, no. You can try the temporary fix I suggested above, or if you know how to code in Java then you can edit the mod yourself and fix it that way.
