### ISSUE TITLE
Son Can't Play With Mod Until Updated to Work With Minecraft Version > 1.12.2

### ISSUE THREAD

**Issue by hsonpalbiz** [Electroblob77/Wizardry#686]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft versions: 1.12.2

Suggestion details: One key reason we got Minecraft for my son on his 10th birthday was so he could play your mod, Wizardry.  I set up a hand-me-down Lenovo laptop with Ubuntu, bought and installed Minecraft Java, created a Minecraft installation with 1.12.2 to use the mod and found that all versions of Minecraft 1.12.2 and below crash on this computer.  The bug is a cross-platform Minecraft bug and is listed here: https://bugs.mojang.com/browse/MCL-9735.  I'm a former software engineer and all the listed workarounds in that bug and duplicate bugs did not work for us.  Is there a timeline for supporting later versions of Minecraft?

Other mods involved: [if this suggestion involves integration with other mods, list them here]

**Comment by WinDanesz** [comment]
> Is there a timeline for supporting later versions of Minecraft?

Sadly, no. Maybe one day.

**Comment by WinDanesz** [comment]
If this issue is Ubuntu-specific, I'd suggest using a different distro (or Windows). Doesn't seem to be Wizardry-specific anyways.
