### ISSUE TITLE
Latest version of TFspell pack corrupts my server world 

### ISSUE THREAD

**Issue by lunarmaximum** [Electroblob77/Wizardry#687]
Minecraft version: 1.12.2   
Wizardry version: 4.3.4 
Twilight Forest Spell Pack - 1.1.0 - MC 1.12.2

Question details: When I updated electroblob base mod, my world was fine, but after updating my TFspellpack addon for the latest version, the entire world got corrupted - I am not sure if this was expected but wanted to ask. 

Other mods involved: Twilight Forest - MC 1.12.2 - 3.11.1021

**Comment by WinDanesz** [comment]
Not expected and you're the first one to report this. If the issue is still present, reopen with a crash log/more details.
