### ISSUE TITLE
Antique Atlas's markers doesn't show up unless I quit and re enter the server

### ISSUE THREAD

**Issue by DacherK** [Electroblob77/Wizardry#689]
Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Server 

Issue details: [Basically, when I explore, I tend to keep the Atlas at hand, because, since I'm flying with mounts, the map spots more stuff than me with my bare eye (I'm looking for shrines, obelisks and magic stuff). The problem is that recently, the map has started to stop showing markers as I explore, that will instead appear if I log out and then re log in into the server! What can I do?]

Other mods involved: [I don't think there are, but I'm plying a modified version of the RLCraft, I also have most of the Electroblob's addons (twilight forest, extra spells, etc)]

**Comment by WinDanesz** [comment]
Sounds like it's caused server lag, reopen the issue if still present.
