### ISSUE TITLE
Summons Attack All of My friends! Can't stop it no matter what I do, turn off pvp and everything still doesn't work.

### ISSUE THREAD

**Issue by ellagent** [Electroblob77/Wizardry#695]
So I use nitrado for my server which has all preset mods from MC Eternal and it uses Minecraft V 1.12 with Electroblob's wizardry.
 I use any summon spells and the summons attack my friends that are in the server and I can't stop it even when making them in my team or setting them as ally. I can't find anything to help and I'm getting very very very frustrated, please help!

**Comment by WinDanesz** [comment]
You have to ally them, check the ingame wizard's handbook about the allying system.
