### ISSUE TITLE
Client crash (Journeymap / Xiuzhen accessory mod?)

### ISSUE THREAD

**Issue by suprllh** [Electroblob77/Wizardry#697]
Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Server

Issue details: It may cause a crash conflict with the helmet in the original Xiuzhen accessory mod, because I have tested it on a stand-alone computer and a server. As soon as I put on the original Xiuzhen accessory helmet, it will cause the client to crash. The accessory mod's name is: refiner. If you want to fix this bug, I can provide this mod to you. Thank you

Other mods involved: 新原初修真yvanchuxiuzhen    Integration package：https://pan.baidu.com/s/1A-C3-ng8dVWfEadHbHOiwg   password：6666
![image](https://user-images.githubusercontent.com/87687857/126266156-3bf8dfc7-b11e-4687-a03d-3efdbda755fd.png)

[minecraft-exported-logs-2021-07-20T13-01-07.log](https://github.com/Electroblob77/Wizardry/files/6845749/minecraft-exported-logs-2021-07-20T13-01-07.log)

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by WinDanesz** [comment]
This seems to be a Journeymap issue, didn't see anything related to wizardry in the crash. Reopen the issue if it still persists
