### ISSUE TITLE
The Server Kicks me when someone cast an spell

### ISSUE THREAD

**Issue by ArcamakShinjitsu** [Electroblob77/Wizardry#698]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting. You may also find the [troubleshooting page](https://github.com/Electroblob77/Wizardry/wiki/Troubleshooting) helpful.

Minecraft version: 1.12.2
Wizardry version: 4.3.4
Environment: Server

Issue details: My game lags in a weird way when someone cast an spell, for example, I'm mining and soemone cast a fire spell and it kicks me off the game with the error below.

mods:
SecurityCraft 1.8.21
Avaritia 3.3.0.37
Backpack 3.0.2
Baubles 1.5.2
buildcraft-all-7.99.24.8
Chisel 1.0.2.45
CodeChickenLib 3.2.3.358
conarm 1.2.5.10
CTM 1.0.2.31
CustomNPCs (05Jul20)
Electroblobs Wizardry 4.3.4
FTBLib 5.4.7.2
Furniture 6.3.1
Hwyla 1.8.26-B41
Infinity Item Editor 0.14.2
jei 4.16.1.302
journeymap 5.7.1
llibrary 1.7.20
Mantle 1.3.3.55
MineMenu 1.6.11
MorePlayerModels (05Dec19)
Optifine HD U G5
TConstruct 2.13.0.183
wings 1.1.6

Link to crash report (if applicable): Internal Exception: java.io.IOException: An established connection was aborted by the software in your host machine

I'm playing with other mods, but it cannot be the problem since my other friends are not experiencing problems as me, so is a client error

(Sorry If I didn't explain correctly, I'm bad in english)

**Comment by WinDanesz** [comment]
Could be a lot of things, but I'm sure it will help EB if you send your mod list as you haven't provided much information

**Comment by ArcamakShinjitsu** [comment]
I updated the issue, the mods are where they should be now, I still don't know why it happens, the server itself doesn't lag, actually I noticed that my game also doesn't lag because I can see people changing items in their hands, but Everything stops moving and after 1 or 2 minutes, the game kicks me out with the error said in the issue

**Comment by bluejello42** [comment]
after some testing the issue seems to be with infinity item editor, the copy of minecraft I had running with it  was experiencing severe latency when the copy of minecraft without it cast spells, but the reverse was not true.  

mods used: infinity item editor (infinity-0.14.2.jar) and EBWizardry (ElectroblobsWizardry-4.3.4-MC1.12.2.jar),

**Comment by ArcamakShinjitsu** [comment]
Oh, alright, thanks for helping me solve the problem.
