### ISSUE TITLE
Effects are not visible on players

### ISSUE THREAD

**Issue by EliMisael223** [Electroblob77/Wizardry#700]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting. You may also find the [troubleshooting page](https://github.com/Electroblob77/Wizardry/wiki/Troubleshooting) helpful.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.4 [change as necessary]
Environment: Server [delete as necessary]

Issue details: The error is when I enter the server no player can see the effects of the magic and from the console it does not indicate any error

Other mods involved: Argentina+Food+Mod, Baubles, Biomes You Go, CQR, clumps, CustomNpc, MedievalCraft, Ordinary coins, tombstone, progressive bosses, spartan shield, toroquest, voice chat, VariedCommodities, useful_backpacks, worldprotector, vanillafix

**Comment by FavouriteDragon** [comment]
Can I get more information on this? Is the online mode enabled? Anything else?

**Comment by FavouriteDragon** [comment]
Is your forge version 2855?
