### ISSUE TITLE
Known Spells Resets After Logout - (cracked server)

### ISSUE THREAD

**Issue by GalaxyDragon245** [Electroblob77/Wizardry#707]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting. You may also find the [troubleshooting page](https://github.com/Electroblob77/Wizardry/wiki/Troubleshooting) helpful.

Minecraft version: 1.12.2
Wizardry version: 4.3.4-MC1.12.2
Environment: Offline Server

Issue details: whenever I log out of the server the known spells from spellbooks resets, as if I never learned them... only in an offline server, if I set it online though, the spells remains learned.

Other mods involved: No One

Link to crash report (if applicable): The game doesn't crash

Thanks in advance for any help

**Comment by Since2014** [comment]
Hello, same problem as me

I tested it before and dont know why, the only differences in the problem between you and me is that i have other mods involve

**Comment by WinDanesz** [comment]
Is it a legit or a cracked server?

**Comment by Since2014** [comment]
It is not a legit one, mostly becouse not all of My Friends have the money to pay it

**Comment by WinDanesz** [comment]
Then it can't be fixed
