### ISSUE TITLE
Tilted screen death glitch

### ISSUE THREAD

**Issue by Djarriqeaux** [Electroblob77/Wizardry#711]
![issue](https://user-images.githubusercontent.com/89438141/130553896-94677a00-4438-4d3d-9cfb-3dcfe2a81fcc.png)
I was out exploring and I got hit by a remnant. It gave me this tilted screen and said I had 0 hearts. I've tried healing spells, commands, starving, drowning, burning, and mobs don't attack me either. I can't access chests or shulker boxes, or pick anything up either. I fixed this once by having my friend put my stuff in a chest since I am able to drop items, and completely delete my player data. Downloading, deleting, and uploading the player data did not work either. I am using the CosmicSMP modpack by CrystalCuture if that helps at all. 
![2021-08-23_23 11 51](https://user-images.githubusercontent.com/89438141/130554568-16b4bdf4-2462-4792-90b2-f771f0bfeaba.png)
This is my inventory upon death. hope this helps.

**Comment by WinDanesz** [comment]
This was likely caused by another mod. Reopen this issue if it keeps happening and provide more details (involved mods, logs).
