### ISSUE TITLE
Crash With Improved Mobs Mod

### ISSUE THREAD

**Issue by UberbeastX** [Electroblob77/Wizardry#715]
Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Singleplayer

Issue details: Shot arrows at an ancientwarfare NPC it should have either dodged or got hit but the game just crashed instead and vanilla fix and what I checked said Improved mobs and this mod had something to do with it(I'm not sure sure though)

Other mods involved: Improved Mobs mod 

Link to crash report (if applicable): 
[crash-2021-09-09_20.20.27-server.txt](https://github.com/Electroblob77/Wizardry/files/7140414/crash-2021-09-09_20.20.27-server.txt)

**Comment by WinDanesz** [comment]
This is caused by improvedmobs mod trying to some custom logic into a freshly spawned wizard in a world gen wizard tower. Check the mod's configs how you can blacklist the wizard entity or consult with the dev of improvedmobs.
