### ISSUE TITLE
Help me~About LWJGL2

### ISSUE THREAD

**Issue by AntiThesis1250** [Electroblob77/Wizardry#716]
Six months ago, I started forgemod development because of your Wizardry. But now I still haven't found any tutorials about lwjgl2. lwjgl2 forum doesn't have anyone to respond to me. lwjgl2 wiki can't be opened. I don't know where to start learning lwjgl2. please tell me!
(I can only post here because I couldn't find any other contact information for you.)

**Comment by AntiThesis1250** [comment]
So far I can only learn part of the usage of LWJGL2 through your code. I want to render my obj, json, etc. models.
Help me~ it's really hard without tutorials

**Comment by Derailedzack** [comment]
There are java docs for lwjgl 2

**Comment by Derailedzack** [comment]
http://legacy.lwjgl.org/documentation.php.html Forge comes with a obj loader.

**Comment by Derailedzack** [comment]
I can also provide some help with lwjgl 2
