### ISSUE TITLE
Runestone Pedestals probably should not spawn Wizards when placed in Survival

### ISSUE THREAD

**Issue by anabsolutesloth** [Electroblob77/Wizardry#718]
Minecraft version: 1.12.2
Wizardry version: 4.3.4

Question details:
Currently, when you place a Runestone Pedestal in Survival, it will spawn 3 Wizards of the appropriate Element near the pedestal, this enables fairly easy Wizard farming in the base mod, and probably should not happen.

Example (Recorded in MC Eternal 1.5):
https://user-images.githubusercontent.com/63694982/134286719-77b459c3-b088-4a74-b76b-721a44ccecaa.mp4

I have no idea if this is intended or not.

**Comment by smoothuk** [comment]
This doesn't happen in the base mod.  Must be something in the mod pack causing that to happen.
