### ISSUE TITLE
Error when using the Arcane Workbench with Arcane Essentials' swords

### ISSUE THREAD

**Issue by ghost** [Electroblob77/Wizardry#723]
Minecraft version: 1.12.2
Wizardry version: 4.3.4
Environment: Server

Issue details: There was an error when using the Arcane workbench to install spells on Sword
![image](https://user-images.githubusercontent.com/47876134/135760281-25cddea5-8c87-4b9a-8614-1fb21824e593.png)

Other mods involved: https://github.com/FavouriteDragon/Arcane-Essentials

Link to crash report (if applicable): https://paste.ubuntu.com/p/5PXWD4g3Cw/

**Comment by WinDanesz** [comment]
Wrong issue tracker, report this to the Arcane Essentials issue tracker
