### ISSUE TITLE
Where do I get Astral Diamonds?

### ISSUE THREAD

**Issue by xDavidBH88** [Electroblob77/Wizardry#724]
Hi, I've been wandering for a while and I can't find any astral diamond. Not even in the end cities. Where do I get them and How?
Thanks!

I play in 1.12.2, by the way.

**Comment by WinDanesz** [comment]
Are you using a modpack?

**Comment by xDavidBH88** [comment]
Only Botania, aether, twilight forest, carry on and electroblob's wizardry.

**Comment by ChaselessBoi** [comment]
to get astral diamond you need 9 shards which dropped by monsters and most likely dropped by wizards

**Comment by WinDanesz** [comment]
Shards are added by Ancient Spellcraft, they are not part of the base Electroblob's Wizardry mod. The default source is from loot chests.

**Comment by xDavidBH88** [comment]
Ok, thanks! Is it possible in all the chests or only end cities'?

**Comment by WinDanesz** [comment]
Refer to the `DEFAULT_LOOT_INJECTION_LOCATIONS` setting for the full list
