### ISSUE TITLE
Haggler's Sign not working?

### ISSUE THREAD

**Issue by landrodron** [Electroblob77/Wizardry#727]
I found the Sign recently after looking for a while and i am not sure if it is not working or if i just dont know how its used

patch 1.12.2

**Comment by WinDanesz** [comment]
the haggler's sign only does one thing - when you wear the sign in your baubles inventory (or if you don't have Baubles, you have to put it into your hotbar), it ensures that each time you trade with a wizard, a new trade is unlocked - if and only if the wizard haven't maxed out its trade slots yet.

**Comment by landrodron** [comment]
so from what i am seeing is it used as having it equipped and trading with the wizard to get more trade slots for them to have new ones? i might not be understanding how the item its self is used or the mechanics of trading with the wizards

**Comment by WinDanesz** [comment]
No, Haggler's Sign won't increase the max number of trades. It just ensures that each trade will unlock the next yet to be unlocked trade.
