### ISSUE TITLE
Can't put spell in wand

### ISSUE THREAD

**Issue by Someolpoo** [Electroblob77/Wizardry#730]
Minecraft version: 1.12.2 
Wizardry version: 4.3.4
Environment: Singleplayer

Issue details: i can't put cleave fire to the apprientice wand
Also i bought the cleave fire

Other mods involved: alot

**Comment by anabsolutesloth** [comment]
If you're playing a premade modpack, it's somewhat likely that the Cleave Fire spell was disabled the pack's author.

**Comment by Someolpoo** [comment]
I checked the config and cleave fire was enabled 
Just one thing is that i bought cleave fire from a wizard and its the only spells that doesn't work if i put it in my wand

**Comment by WinDanesz** [comment]
That spell is not from this mod, this issue should be posted to the spell author's issue tracker. Wild guess but it might be an Arcane Essentials spell, possibly a special sword-only spell.

**Comment by WinDanesz** [comment]
I'm going to assume this is the Flame Cleave spell of Arcane Essentials. Discuss with the addon author.
