### ISSUE TITLE
Wizard's not trading in multiplayer

### ISSUE THREAD

**Issue by JacksonpYT** [Electroblob77/Wizardry#734]
On my Minecraft server when the wizards are clicked they do not trade, it works fine in singleplayer.

**Comment by JacksonpYT** [comment]
I have tried reinstalling the mod

**Comment by WinDanesz** [comment]
Do you have any addons?

**Comment by JacksonpYT** [comment]
Yes I have extra spells, Arcane additions and magic seeds for electroblobs wizardry

**Comment by JacksonpYT** [comment]
I removed magic seeds and it's still broken

**Comment by JacksonpYT** [comment]
it's a different mod messing with it and all other trading

**Comment by WinDanesz** [comment]
Which mod?

**Comment by WinDanesz** [comment]
This would be useful information for others in the future

**Comment by eduexile** [comment]
I agree with @JacksonpYT , it's a different mod the one that is messing up all the trades, including with other villagers. I have arrived to that conclusion because the trades from Minecraft Comes Alive mod aren't working either, but it seems that these 2 mods aren't the problem

**Comment by JacksonpYT** [comment]
it was from me removing minecraft comes alive

**Comment by Carphent** [comment]
It seems like I have the same problem too but the server and the clients doesn't have MCA. Is there any other conflicting mod that anyone suggest that I remove?

**Comment by WinDanesz** [comment]
FutureMC had a bug with trading in older versions, if be sure to update if you have it
