### ISSUE TITLE
When creating an addon, what is the minimum forge version?

### ISSUE THREAD

**Issue by RpxdYTX** [Electroblob77/Wizardry#736]
Minecraft version: 1.12.2
Wizardry version: 4.3.4

# Question details
There are some situations that try-and-error might be too late, so the question is what is the minimum and maximum forge version to use when creating an addon? Also, could you add these in the wiki to create an addon? (since it makes easier for other people to notice)

Other mods involved: none

**Comment by WinDanesz** [comment]
The oldest version that should work fine is probably 1.12.2-14.23.5.2847 - TFSpellPack uses this, but I don't recommend using such old versions.
For the latest, you should always aim to use the last stable 1.12.2 forge version, or using the same Forge version Wizardry itself uses should be always a safe bet. Won't give any concrete version there as it's subject to change with versions, so you can always check the build.gradle/gradle.properties files.
