### ISSUE TITLE
Universal spell type cooldown. 

### ISSUE THREAD

**Issue by NoMoreUsernames999** [Electroblob77/Wizardry#737]
Suggestion details: Identical spells bound to a wand should have universal cooldowns. Currently, you can bind 6 "heal" spells to the same wand and then spam them by cycling through the wand as you cast. By the time you get back to the first slot you cast, the cooldown will be reset. Allowing OP constant healing. This be ones a huge issue with trying to balance spells, since if you increase the cooldowns enough to make this not viable, people who only bind one copy of a spell to their wand will be penalized with ridiculously long cooldowns. 
If you have 6 of the same spell, casting it should start a cooldown on all spells of identical name similar to how scroll cooldown works.

**Comment by Tora-B** [comment]
What about the same spell bound to multiple wands? Is that a problem, or do you think it's balanced by the additional space required? How is that different from the spell taking up multiple slots on the wand? There's already a tradeoff, and otherwise there wouldn't be much benefit to binding the same spell multiple times to the same wand.

**Comment by NoMoreUsernames999** [comment]
IMO, binding the same spell to multiple wands is also OP. You basically get the same problem. It's getting to the point where I am considering disabling all healing spells on my server because they are making the players immortal. Using cooldown upgrades should be the only way to cast spells faster. Because it still doesn't allow you to spam the more costly (in cooldown rate) spells. I have ended up with all players going for healing and pvp goes nowhere because nobody can die. 
I think having universal cooldown for spells of the same name works both ways, since people that want their players to be able to spam spells can just lower the cooldowns, and people that don't want their players to spam spells can increase the cooldowns (and it actually have an effect).

**Comment by edgaradr223** [comment]
totally agree with this, i had to disable healing mages in my server because they were immortal and were making knights and assassin teammates immortal, same spell name should share cooldown to avoid this.

**Comment by WinDanesz** [comment]
No promises but I have some vague plans to implement this (global cooldown of spells for each player, regardless of cast souce) as an alternative option alongside the current system

**Comment by WinDanesz** [comment]
136b1cc9 added the config feature to prevent binding the same spell to a wand multiple times. Will be released in v4.3.11
There is also a setting that prevents wand cooldowns from decrementing if the wand is not held by the player
