### ISSUE TITLE
Telekinesis won't bind to Wand (MC Eternal) 

### ISSUE THREAD

**Issue by THAT-ON3-GUY** [Electroblob77/Wizardry#739]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting. You may also find the [troubleshooting page](https://github.com/Electroblob77/Wizardry/wiki/Troubleshooting) helpful.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.4 [change as necessary]
Environment: LAN game

Issue details: I'm playing MC Eternal with a friend and I'm binding spells to my wand, while other spells work fine the telekinesis spell refuses to bind to my wand. 

Other mods involved: Unknown

**Comment by anabsolutesloth** [comment]
Hiya, Dev for MC Eternal here, we disabled Telekinesis and Greater Telekinesis because they can bypass FTB Utilities Claim Protection.
