### ISSUE TITLE
Horse Summon Broke

### ISSUE THREAD

**Issue by litjohn50** [Electroblob77/Wizardry#74]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.1.2 
Environment: Server

Issue details: So once I summoned a spirit horse which died of suffication, when I was going down an incline. From then on it would not let me  summon the spirit horse again. I don't know if its a issue with the spawning. In the gyazo video I am right clicking on the ground (even if you can't see the wand moving) and it does nothing. I can use a different spell as seen and that spell works fine.

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): https://gyazo.com/498f417bcedb3d911c9ab545dac38ff6

**Comment by ProsperCraft** [comment]
I don't know how the logic currently works, but perhaps it could always despawn the previous spirit horse(or any owned by the caster) and spawn a new one?

**Comment by ProsperCraft** [comment]
This is also a problem with the spirit wolf as well.

**Comment by Electroblob77** [comment]
I used to have this issue during development, but I thought I'd fixed it... my guess is that for some reason, suffocation doesn't trigger the bit of code that tells the player they no longer have a spirit horse (and can summon another one). Either that or the server got out of sync, possibly if you logged out.

@ProsperCraft Now that is a neat idea. I think I'd actually prefer that mechanic anyway, and it'll certainly fix the issue. I'll implement that change for the next update.

**Comment by vediis** [comment]
I'm on a 1.7.10 server and can confirm the spirit wolf issue. You can manually fix this by going to your world > playerdata > ForgeCaps > ebwizardry:wizarddata and setting hasSpiritHorse or hasSpiritWolf respectively to 0.

**Comment by Electroblob77** [comment]
The new behaviour suggested above has been implemented in the 4.2.0 release.
