### ISSUE TITLE
Skeleton Legion tears itself apart

### ISSUE THREAD

**Issue by DaedalusGame** [Electroblob77/Wizardry#75]
Minecraft version: 1.12.2
Wizardry version: 4.1.2
Environment: Server

Issue details: 
Summon Skeleton Legion will summon a number of skeletons which will swarm enemies of the player as expected, but since they have bows, their stray arrows will often cause massive infighting, decimating the horde again. This might be related to Rough Mobs since Rough Mobs gives skeletons both, melee weapons and bows, but assuming that Skeleton Legion skeletons usually have bows, this could probably also happen without.

Other mods involved: 
Rough Mobs (?)

**Comment by Electroblob77** [comment]
This isn't *technically* a bug, the behaviour is sort-of intended in that summoned creatures should be able to attack each other. However, you're right that it's a bit weird when a group of minions is summoned in the same spell. I might look into some kind of group AI to get around this, or add a config option to stop minions targeting each other.

**Comment by DaedalusGame** [comment]
There happens to be a team system built-in, tamed mobs and illagers use it already. See `Entity::isOnSameTeam`. Maybe that can help, since it makes them not infight from what I can see.

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release, you may need to disable `minionRevengeTargeting` in the config.
