### ISSUE TITLE
A very verified client crash bug

### ISSUE THREAD

**Issue by fkh233** [Electroblob77/Wizardry#758]
Minecraft version: 1.12.2
Wizardry version: 4.3.4
Environment: server

Issue details: [The client has been crashing, and the query can't find a specific problem to solve.]
Link to crash report (if applicable): [https://mcpaste.io/495ee20aa53231a2]

**Comment by WinDanesz** [comment]
Looks like an incompatibility with Wizardry's spell animation rendering <-> Bountiful Baubles' bauble renderer on the player. For now, you can disable one of these in their respective config and that will probably fix it.

**Comment by fkh233** [comment]
> 

Is there no way to coexist? Both modules are doing very well. I don't want to abandon one of them. Can you provide a way to fix it?

**Comment by WinDanesz** [comment]
I can give it a try, but can't promise it will be compatible.

**Comment by fkh233** [comment]
Then I would like to ask how long it will take to give the results. There are 40 or 50 players in my server now. This situation is very urgent, but the module of witchcraft is really fascinating. I don't want to delete it and give it up.

**Comment by WinDanesz** [comment]
Can't give you any timelines...
But maybe you misunderstood me, you don't have to remove these mods. You just need to disable in Wizardry's config the spell animations OR disable the rendering of baubles in Bountiful's config.

**Comment by fkh233** [comment]
I checked the configuration file of Bountiful Baubles module and found no animation https://mcpaste.io/1979fc77ea3e29fe that can be disabled.
If I disable Wizardry's animation, wouldn't it be hard to release the spell and see nothing?

**Comment by fkh233** [comment]
Is this the option? No spell animation.

    # Whether to use custom animations for players casting spells. Disable this option if it conflicts with other mods that add player animations.
    B:spellcastingAnimations=false

**Comment by WinDanesz** [comment]
> Is this the option? No spell animation.
> 
> ```
> # Whether to use custom animations for players casting spells. Disable this option if it conflicts with other mods that add player animations.
> B:spellcastingAnimations=false
> ```

Yes, you need to set that to `false`

**Comment by WinDanesz** [comment]
I assume this solved your issue, reopen otherwise.
