### ISSUE TITLE
Spell casting crashes the game but not server (Turkish lang settings)

### ISSUE THREAD

**Issue by Oguzhan22345** [Electroblob77/Wizardry#759]
Minecraft version: 1.12.2  
Wizardry version: 4.3.4 
Environment: Singleplayer/Server

Issue details: Spell casting works fine on singleplayer but when ı cast spell  on my forge server,my minecraft crashes but server works.

Other mods involved: Twiligt forest

Link to crash report (if applicable):
[crash-2022-01-15_19.28.42-client.txt](https://github.com/Electroblob77/Wizardry/files/7875471/crash-2022-01-15_19.28.42-client.txt)

**Comment by WinDanesz** [comment]
The client's language is set to Turkish. That is known to mess up packets and EbWiz (and by the way not just EbWiz, I've seen this with other mods too), might be because of the special characters it has. Solution is to change the client lang to e.g. English.

**Comment by Oguzhan22345** [comment]
> The client's language is set to Turkish. That is known to mess up packets and EbWiz (and by the way not just EbWiz, I've seen this with other mods too), might be because of the special characters it has. Solution is to change the client lang to e.g. English.

**Comment by Oguzhan22345** [comment]
> The client's language is set to Turkish. That is known to mess up packets and EbWiz (and by the way not just EbWiz, I've seen this with other mods too), might be because of the special characters it has. Solution is to change the client lang to e.g. English.

Not solve the problem.I changed client lang to english (usa) but still crashes my client.

[crash-2022-01-16_12.21.04-client.txt](https://github.com/Electroblob77/Wizardry/files/7876729/crash-2022-01-16_12.21.04-client.txt)

**Comment by WinDanesz** [comment]
1) Did you restart the game after changing the language?
2) What is the localisation language of the server and the OS language where the server is running?

**Comment by Oguzhan22345** [comment]
> 1. Did you restart the game after changing the language?
> 2. What is the localisation language of the server and the OS language where the server is running?

1-Yes restarted the game after changing lang.
2-I dont know what is the localisation language of server.My OS language is Turkish.Dont understand meaning of "where server is running?"you mean server file location ?

**Comment by WinDanesz** [comment]
Check your server and client logs to see if you notice error messages regarding the loading of spells
> 2-I dont know what is the localisation language of server.My OS language is Turkish.Dont understand meaning of "where server is running?"you mean server file location ?

Yes, I meant the OS language where the server is running

**Comment by WinDanesz** [comment]
Another idea, try to start your server by adding these JVM arguments (alongside whatever you currently had):
`-Duser.language=en -Duser.country=US`
Try the same with your minecraft client. I still have a feeling that this issue relates to the Turkish locale. 
This article describes how to do the above for your client: https://support.exaroton.com/hc/en-us/articles/360019857658-ID-mismatch-between-world-and-game
The issue there is different but the root cause and the solution is probably the same.

**Comment by fynnthemage** [comment]
I am having this exact same crash report. However, I am playing in the US with my OS and my Minecraft client both set to English, and so is the LAN server I'm playing on. The person hosting the world can cast any spell they want, but the person who connects can only cast about half of the spells without crashing. The JVM arguments for -Duser.language=en and -Duser.country=US are already there.

**Comment by Oguzhan22345** [comment]
> Another idea, try to start your server by adding these JVM arguments (alongside whatever you currently had): `-Duser.language=en -Duser.country=US` Try the same with your minecraft client. I still have a feeling that this issue relates to the Turkish locale. This article describes how to do the above for your client: https://support.exaroton.com/hc/en-us/articles/360019857658-ID-mismatch-between-world-and-game The issue there is different but the root cause and the solution is probably the same.

Problem solved thank you.İt also fixed my workbench that not binding spells and same about thaumcraft problem that salis mundus not convert crafting table  thank you again.
