### ISSUE TITLE
Server crashes when using magic that has to much particles

### ISSUE THREAD

**Issue by chegaheitor** [Electroblob77/Wizardry#760]
Minecraft version: 1.12.2
Wizardry version: 4.3.4
Environment: Server

Issue details: Hi, first i wanna say sorry for my english, i'm brazilian
Second, i installed the mod and some addons in my server, and when i use a magic that has a lot of particles the server crashes, it happens to when 2 or more wizard cast spells

i just wanna know, the problem is on my server memory or has something on the mod? 

Other mods involved: Arcane Essentials, Seed For Wizardy, Zettai Grimoires, Ancient Spellcraft, GLS Craftable Wizardy Items, Wyzardy Tales and Zettai Magi
[crash-2022-01-15_19.36.21-server.txt](https://github.com/Electroblob77/Wizardry/files/7876060/crash-2022-01-15_19.36.21-server.txt)
c

**Comment by WinDanesz** [comment]
This is caused by the Wizardry Tales addon. Report it to that mod's issue tracker.
