### ISSUE TITLE
Evil Wizard crash

### ISSUE THREAD

**Issue by OMGEA006** [Electroblob77/Wizardry#765]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting. You may also find the [troubleshooting page](https://github.com/Electroblob77/Wizardry/wiki/Troubleshooting) helpful.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.4 [change as necessary]
Environment: /Server [delete as necessary]

Issue details: When ever i try to activate the evil wizard trap and i attack one of them the server crashes if i join it will crash agian unless i kill the mob with a command 

Other mods involved: [TF spellpack]
                                    Ancient spellcraft
                                   Extra spells pack
                                    Wizard tales
Link to crash report https://pastebin.pl/view/a035db5c

**Comment by WinDanesz** [comment]
Crash with Zetta's addon, please close this ticket and open for the addon author's issue tracker.
