### ISSUE TITLE
Group Heal isn't working on multiplayer servers

### ISSUE THREAD

**Issue by fandomaniac** [Electroblob77/Wizardry#77]
Group Heal isn't working on multiplayer servers. Had it loaded up on a Master Healer Wand and when activating during a battle with myself and other players missing hearts, it did nothing. Not even an animation.

Minecraft version: 1.12.2 
Forge version: 14.23.4.2759
Wizardry version: 4.1.2
Environment: SMP hosted server

**Comment by Electroblob77** [comment]
Did you make sure the other players were your allies? Either way, it should still heal you. I'll look into it, thanks for reporting.

**Comment by fandomaniac** [comment]
Sorry, I added everyone as an ally and now it's working.
