### ISSUE TITLE
Using Smoke Bomb spell crashes client

### ISSUE THREAD

**Issue by EmyLightsaber** [Electroblob77/Wizardry#771]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting. You may also find the [troubleshooting page](https://github.com/Electroblob77/Wizardry/wiki/Troubleshooting) helpful.

Minecraft version: 1.12.2 Forge version 14.23.5.2860
Wizardry version: 4.3.5
Environment: Server

Issue details: Used the Smoke Bomb Spell, noticed it was a Grey color instead of red as the spell was being cast, it crashed the client, expected to see a smoke bomb smoke cover.

[crash-2022-02-08_23.12.32-client.txt](https://github.com/Electroblob77/Wizardry/files/8029653/crash-2022-02-08_23.12.32-client.txt)

**Comment by EmyLightsaber** [comment]
![2022-02-08_23 20 09](https://user-images.githubusercontent.com/85321634/153126838-aabf5417-d743-4cd5-ab73-872e36cdae2e.png)

**Comment by EmyLightsaber** [comment]
Attempting to fix by deleting config on both server/client side first.
Edit:
deleting config failed.

**Comment by WinDanesz** [comment]
The server also has v4.3.5?
How could deleting a config folder fail? You didn't stop the server while deleting?

**Comment by EmyLightsaber** [comment]
I stopped the server before deleting, and afterwards started it back up with new configs.

**Comment by WinDanesz** [comment]
Okay, what about the other question?

**Comment by EmyLightsaber** [comment]
yes, both server and client are using v4.3.5

**Comment by WinDanesz** [comment]
Ok, it's definitely something about the spell data syncing. You can't do much from your side, apart from testing to see if you get this problem with only Wizardry installed. I'll need to try to replicate the issue

**Comment by Guakachola** [comment]
I don't know if this helps, but this is also happening on my multiplayer server. Every player when casting a spell with zero mana has their client crash. I tried using the same spells in single-player, but they seem to be working fine there. It might be worth mentioning that the spell does cast even when the game crashes.

**Comment by WinDanesz** [comment]
Fixed in v4.3.6

Note if you are using the Ancient Spellcraft addon - be sure to check the file changelog on CurseForge for an additional step to stop the crash.
