### ISSUE TITLE
Various Novice Spells use 0 mana.

### ISSUE THREAD

**Issue by EmyLightsaber** [Electroblob77/Wizardry#772]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting. You may also find the [troubleshooting page](https://github.com/Electroblob77/Wizardry/wiki/Troubleshooting) helpful.

Minecraft version: 1.12.2 Forge version 14.23.5.2860
Wizardry version: 4.3.5
Environment: Server

Issue details: Noticed various novice spells, including Smoke Bomb, Frizz, Mind Trick, Muffle, Leap, and Ward all use 0 mana, and I suspect they crash the client when used.

**Comment by EmyLightsaber** [comment]
Similar to previous bug, trying to fix by deleting server/client config first.
Edit:
After deleting config with server stopped, the new config failed. Additionally, various unknown Advanced and Apprentice spells changed to novice level, but are still unknowable/nonassignable on a Novice Level Wand.

**Comment by WinDanesz** [comment]
Refer to #771

**Comment by WinDanesz** [comment]
Fixed in v4.3.6

Note if you are using the Ancient Spellcraft addon - be sure to check the file changelog on CurseForge for an additional step to stop the crash.
