### ISSUE TITLE
Crash to desktop (only on multiplayer)

### ISSUE THREAD

**Issue by Arachnotron1** [Electroblob77/Wizardry#773]
As the title suggests, during multiplayer, the game crashes whenever any item is used. The wands with spells bound to them, the scrolls, all of it.

This only happens on multiplayer however, it works perfectly fine in single player, and this has worked on multiplayer before.

https://paste.ee/p/OfUYC

that is the crash report i get, thank you for reading

**Comment by MagmaSlime123** [comment]
Please use Pastebin. Not a secure connection.

**Comment by Linext23** [comment]
I'm having the same issue actually, here's my pastebin
https://pastebin.com/EmEKYxXK

**Comment by MagmaSlime123** [comment]
Works, thanks.

Anyway, did you disable/enable any Spells/Artifacts?

**Comment by Linext23** [comment]
Nope, i haven't touched the configs of the mod other than to look and see what there was in it, everything was kept default.

**Comment by MagmaSlime123** [comment]
Nvm then. @WinDanesz ^

**Comment by WinDanesz** [comment]
Fixed in v4.3.6

Note if you are using the Ancient Spellcraft addon - be sure to check the file changelog on CurseForge for an additional step to stop the crash.
