### ISSUE TITLE
[China uses a scroll and then the game crashes]

### ISSUE THREAD

**Issue by Lonelyxiya** [Electroblob77/Wizardry#774]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting. You may also find the [troubleshooting page](https://github.com/Electroblob77/Wizardry/wiki/Troubleshooting) helpful.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.5 [change as necessary]
Environment: Server

Issue details: [Certain Chinese players were playing the server, using the scrolls and then crashing. The name of the scroll is Magic Shield.Sorry, I'm just a Chinese modpack maker and I'm too unaware of crash report submissions.
]

Other mods involved: [only list mods that are relevant to the problem]
[latest.log](https://github.com/Electroblob77/Wizardry/files/8045373/latest.log)
![R)N{Y4)44U03BU1EPBVM2CH](https://user-images.githubusercontent.com/83713575/153523548-3d8f4da6-d759-4ecd-8ba2-f53a773ecdda.png)

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by MagmaSlime123** [comment]
Please fill in the issue template.

**Comment by WinDanesz** [comment]
Fixed in v4.3.6

Note if you are using the Ancient Spellcraft addon - be sure to check the file changelog on CurseForge for an additional step to stop the crash.
