### ISSUE TITLE
Crash on MP when using certain Spells

### ISSUE THREAD

**Issue by BackdadSchuh** [Electroblob77/Wizardry#776]
Minecraft version: 1.12.2
Wizardry version: 4.3.5 
Environment: Server

Issue details: On my Minecraft Server, whenever I use the Smoke Bomb Scroll, the Earthquake or the Mind Trick Spell, my game crashes not the Server, it does not crash in Singleplayer

Link to crash report (if applicable): https://pastebin.com/1D5xFZm8

**Comment by Greief** [comment]
Yes, this happens with most sorcery spells. I have had this problem with conjure block and muffle. But it only happens on servers.

**Comment by Drakarrys** [comment]
> Yes, this happens with most sorcery spells. I have had this problem with conjure block and muffle. But it only happens on servers.

Same issue here, conjure block, smoke bomb, mind trick, crash the game only

**Comment by WinDanesz** [comment]
Revert to v4.3.4 until the issue is fixed in the next release.

**Comment by Greief** [comment]
yes I have

**Comment by WinDanesz** [comment]
Then you must have changed something else too. Did you update any spell packs recently?

**Comment by Greief** [comment]
no i did revert to v4.3.4 and it fixed it
