### ISSUE TITLE
Master Spells show as Novice Spells

### ISSUE THREAD

**Issue by Greief** [Electroblob77/Wizardry#777]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting. You may also find the [troubleshooting page](https://github.com/Electroblob77/Wizardry/wiki/Troubleshooting) helpful.

Minecraft version: 1.12.2
Wizardry version: 4.3.5 
Environment: Server

Issue details: When looking for spells in the creative menu, I found the Summon Iron golem spell listed as a novice spell. When playing on singleplayer, the master spell book is there, making 2 spell books of master spells. However on a server, the master books are seemingly deleted, and replaced by those novice spell books.  This doesn't affect the game, as it doesn't let you bind the novice spells that are supposed to be master. 
If you can look into it, I would really appreciate it. Thanks!

**Comment by WinDanesz** [comment]
Known issue of 4.3.5, revert to v4.3.4 till a fix is released
