### ISSUE TITLE
When I use ward spell, it crashes

### ISSUE THREAD

**Issue by RedDragon204** [Electroblob77/Wizardry#779]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting. You may also find the [troubleshooting page](https://github.com/Electroblob77/Wizardry/wiki/Troubleshooting) helpful.

Minecraft version: 1.12.2   
Wizardry version: 4.3.5 
Its a multiplayer server

Issue details: 
I tried using the ward spell and, it crashed me back to the main launcher.

Other mods involved: [only list mods that are relevant to the problem]
Im not sure what could be causing this.

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]
https://pastebin.com/5yewQwGU

Sorry for the inconvenience,
Hunter

**Comment by WinDanesz** [comment]
Known issue of 4.3.5, revert to v4.3.4 till a fix is released

**Comment by WinDanesz** [comment]
Fixed in v4.3.6

Note if you are using the Ancient Spellcraft addon - be sure to check the file changelog on CurseForge for an additional step to stop the crash.
