### ISSUE TITLE
Game crashes every time i use a spell

### ISSUE THREAD

**Issue by Matthew1230410** [Electroblob77/Wizardry#780]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting. You may also find the [troubleshooting page](https://github.com/Electroblob77/Wizardry/wiki/Troubleshooting) helpful.

Minecraft version: 1.12.2
Wizardry version: 4.3.5 
Environment: Server 

Issue details: every time i use a spell (expect Magic missile and summon zombie) the game crashes and the mod is based on magic and spells and we cant use any thing 

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable):
[crash-2022-02-19_19.24.13-client.txt](https://github.com/Electroblob77/Wizardry/files/8102759/crash-2022-02-19_19.24.13-client.txt)

**Comment by WinDanesz** [comment]
Known issue of 4.3.5, revert to v4.3.4 till a fix is released
