### ISSUE TITLE
Spell Hud is invisible except for text.

### ISSUE THREAD

**Issue by Kingmiami** [Electroblob77/Wizardry#784]
Minecraft version: 1.12.2
Wizardry version: 4.3.5
Environment: Singleplayer

Issue details: When having a wand equipped, the spell hud is gone. I've installed multiple mods over a long period before I noticed this bug, so I'm not sure what causes it. I have my full list of mods on me, so I'll include it in a pastebin if necessary.

![ebwizhud](https://user-images.githubusercontent.com/49174731/155777142-947800af-a25b-4265-9939-88a6a54a9f6e.png)

This happens with and without shaders.

**Comment by WinDanesz** [comment]
Please try to replicate this issue with just Wizardry and let me know if it still occurs.
Be sure to double-check the client config that can disable/enable the spell HUD too.

**Comment by Kingmiami** [comment]
@WinDanesz So sorry for not responding, I don't check github often. I did some testing, and it appears that EB's wizardry is incompatible with the [RPG HUD mod](https://www.curseforge.com/minecraft/mc-mods/rpg-hud), at least for the UI. Unfortunate that I have to remove the mod now, hopefully there will be a fix for this in future versions.

**Comment by MagmaSlime123** [comment]
RPG HUD doesn't support/update older versions if I remember, so your stuck with the issue.
