### ISSUE TITLE
What purpose does the Lectern item provide?

### ISSUE THREAD

**Issue by Link5261** [Electroblob77/Wizardry#788]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting. √

Minecraft version: 1.12.2   
Wizardry version: 4.3.4

Question details: I have no clue what the Lectern item is supposed to do. I crafted one to get the achievement, but upon placing it down, there's just an interface for spells that is completely devoid of entries, along with a search/filter area near the top of the interface. I cannot "use" spell books, neither unknown nor known, on the lectern. It doesn't seem to gather info from spell books in my inventory either, and I cannot find information online regarding use of this item, neither here in this git nor on various wikis that cover the mod's contents. So, in short, **how does one use the lectern item?**

Other mods involved: none.

EDIT: Nevermind - I re-read the guide book included in the mod and deduced that it will only search nearby bookshelves from the mod for spell books.

**Comment by WinDanesz** [comment]
The lectern integrates with nearby EbWiz (spell) bookshelves, giving you an unified GUI where all nearby books are displayed if the books are in the bookshelf. Same goes for the arcane workbench, it integrates with the bookshelves for easier usage.
