### ISSUE TITLE
Bug with a ray spell

### ISSUE THREAD

**Issue by Spexx368** [Electroblob77/Wizardry#789]
Minecraft version: 1.12.2  
Wizardry version: 4.3.6-4.3.4
Environment: Singleplayer/LAN game/Server

Issue details: It looks like a "Ray spell" from Electroblobs Wizardry is trying to access a piece of code that doesn't exist is there any way to fix this?

[crash-2022-03-15_21.47.35-client.txt](https://github.com/Electroblob77/Wizardry/files/8258583/crash-2022-03-15_21.47.35-client.txt)

**Comment by WinDanesz** [comment]
Addon issue, arcane essentials
