### ISSUE TITLE
1.7.10 Duplicate enchantment ID:100

### ISSUE THREAD

**Issue by ZacharyAlan137** [Electroblob77/Wizardry#790]
I tried to load up a modpack I've created however when it finally loaded it said that it crashed due to the duplication of the enchantment  Magic Resist. How do I go about fixing this
[crash-2022-03-17_12.49.35-client.txt](https://github.com/Electroblob77/Wizardry/files/8288758/crash-2022-03-17_12.49.35-client.txt)
?

**Comment by WinDanesz** [comment]
Sorry, but 1.7.10 is no longer supported. The issue is a generic modded minecraft problem, you can find plenty of workarounds online
