### ISSUE TITLE
forfeit event still griefs

### ISSUE THREAD

**Issue by janthomile** [Electroblob77/Wizardry#791]
Minecraft version: 1.12.2
Wizardry version: 4.3.6 [change as necessary]
Environment: Singleplayer/LAN Game

Issue details: 
The earth-element "the ground collapses beneath you!" forfeit event still griefs in protected claims, despite most others respecting them.

Other mods involved:
FTBLib, FTBUtils

**Comment by WinDanesz** [comment]
Is this true for the Earthquake spell too? Because I see the same claim checks in both mods

**Comment by WinDanesz** [comment]
Closing as inactive
