### ISSUE TITLE
Remove Curse for other people

### ISSUE THREAD

**Issue by PotassiumMan** [Electroblob77/Wizardry#792]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft versions: 1.12.2 (Mod ver. 4.3.6)

Suggestion details: You should be able to remove curses off allies with the Remove Curse spell.

Other mods involved: (not sure if this matters for this but... (these are the mods im playing with)) ancient spellcraft, Wizardry Tales, Wizardry Fate, AiImprovements, Antique Atlas, Baubles, Bountiful Baubles, Comforts, CraftTweaker2, EpicFightMod, Forgelin, FutureMC, Gravestone, Morpheus, Optifine(1.12.2 HD U G5), ShoulderSurfing, Spartan Shields, Spartan Weaponry, TravelersBackpack, Waystones, electroblob's wizardry (obviously)

Should I list all the mods next time, or just the main mod and the addons next time? Also, sorry if you can. I tried testing it on my server and also Googled it online but I couldn't find anything

**Comment by WinDanesz** [comment]
I see you have Ancient Spellcraft, with that addon you have methods to cast spells on behalf of others, check the metamagic spells and Channel Effect. The suggestion itself feels like something more fitting for addons anyways, as most EB spells that are beneficial are AoE or self-cast.
