### ISSUE TITLE
Comply with conventional commits.

### ISSUE THREAD

**Issue by ghost** [Electroblob77/Wizardry#793]
[Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by WinDanesz** [comment]
That was a concise suggestion, but I thank you for it regardless. I see some good benefits with using a commit-msg convention - especially for changelog generation, I'll try to stick to it. 
If you have any suggestions for enforcing this on the git server-side (github.com), I'd be curious about it. Workflow runs on push are a bit too late to enforce the commit msg standard.
