### ISSUE TITLE
support 1.16.5,1.18.2and more

### ISSUE THREAD

**Issue by XxttCrystal** [Electroblob77/Wizardry#798]
I want to know when it will be updated to minecraft 1.16.5or1.18.2 version
My friend told me it will be updated but need time :D
I have expected it for so many month
Like IC² ,It is alive and it has been updated to 1.18.2
EIO has been updated(but I still have it) ,too.
I hope Wizardry mod will be updated soon.

(I'm a Chinese , I'm weak in English , pardon me. ;P)

**Comment by WinDanesz** [comment]
Sorry, no ETA (=Estimated Time of Arrival)

**Comment by MagmaSlime123** [comment]
Please see the FAQ on the Discord.
