### ISSUE TITLE
Make Arcane Workbenches available for use by multiple players like the vanilla crafting table.

### ISSUE THREAD

**Issue by janthomile** [Electroblob77/Wizardry#799]
Suggestion details: In a multiplayer server and for adventure maps it would be useful if multiple people could use the same altar without interacting with each others' items. This would be like the difference between the vanilla crafting table, whereby each use of the workbench is like a single instance, without an inventory stored in the block.

**Comment by WinDanesz** [comment]
Sorry, but this won't happen. The same could be requested for e.g. vanilla furnaces, it's how the feature works. Use multiple workbenches if you want to share them
