### ISSUE TITLE
Client Crashing when connecting to server

### ISSUE THREAD

**Issue by AzureDoom** [Electroblob77/Wizardry#80]
Minecraft version: 1.12.2
Wizardry version: 4.1.2  
Environment: Singleplayer/Server

Issue details: Holding Wand with no spells and pressing b or n and logging out then trying to relogging back in

Link to crash report: https://gist.github.com/AzureZhen/ab4192ac81d2bb3758aae29b9d30f517

**Comment by Electroblob77** [comment]
Ok, I can see what's going on there, I just need an extra safety check. Thanks for reporting.

**Comment by Electroblob77** [comment]
Didn't even notice that this is a duplicate of #90. Although this issue was first, since all the discussion is there now I'll close this one.
