### ISSUE TITLE
Equipping armor crashes my game

### ISSUE THREAD

**Issue by maxoupidou** [Electroblob77/Wizardry#801]
Minecraft version: 1.12.2
Wizardry version: 4.3.6
Environment: Singleplayer and Server

Issue details: equipping armor crashes my game

Other mods involved: The armor I want to equip was created by myself through Mcreator. The name of the mod is TESTMOD

help me ='(

Link to crash report
[crash-2022-04-15_00.22.28-client.txt](https://github.com/Electroblob77/Wizardry/files/8492569/crash-2022-04-15_00.22.28-client.txt)

**Comment by WinDanesz** [comment]
Looks like you are either 
A) not using that MCreator armor feature correctly or
B) MCreator armor is not compatible with Wizardry

Either way, I don't recommend using that tool to generate mods, it won't teach you how to develop mods, and it can have plenty of issues like this where you won't be able to figure it out.
