### ISSUE TITLE
[Bug] Networking error on connecting

### ISSUE THREAD

**Issue by xIGBClutchIx** [Electroblob77/Wizardry#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Connecting to server and getting "A fatal error has occurred, this connection is terminated"

### Expected behaviour

To be able to join the server.

### Steps to reproduce

1. Join Server

### Crashlog

https://gist.github.com/xIGBClutchIx/37985521308076b625465aaf4aa0bef2

### Environment (Singleplayer/Server, etc.)

LAN game/Server

### Mod version

4.3.6

### Minecraft version

1.12.2

### Forge version

1.12.2 - 14.23.5.2860

### Other mods

https://gist.github.com/xIGBClutchIx/d8a024ba150e166b45110bd06f908ffa

**Comment by WinDanesz** [comment]
Are you sure the client is using the same configs and mod versions? A mismatch in configs or mod versions can cause this.

**Comment by xIGBClutchIx** [comment]
> Are you sure the client is using the same configs and mod versions? A mismatch in configs or mod versions can cause this. 

Yeah I thought that too but I downloaded all the files from the server exactly and made a new MultiMC instance.

**Comment by WinDanesz** [comment]
Fixed by 3155aa681
Use v4.3.7
