### ISSUE TITLE
I want to reprint it to the Chinese version of minecraft

### ISSUE THREAD

**Issue by cubewhy** [Electroblob77/Wizardry#809]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Observed behaviour

I applied for my friend because my friend can't use GitHub

He will not use this mod for profit. He just wants to help you promote this mod. If he sends it to Netease, more players will know this mod. Please allow him to reprint it.

### Expected behaviour

Move to Minecraft of Chinese Version

### Steps to reproduce

1. None.

### Environment (Singleplayer/Server, etc.)

Not sure

### Mod version

lastest

### Minecraft version

all_versions

### Forge version

none

**Comment by WinDanesz** [comment]
Is curseforge.com not available from China?

**Comment by cubewhy** [comment]
In China, curseforge is really not easy to access. Most minecraft players in China use minecraft represented by Netease. Although this launcher is free, they can't add their own mod. They can only buy mod in the built-in mall. My friend said he wanted to play this mod (on the Chinese version of minecraft). Let me come to you and get the reprint right of this mod.

**Comment by cubewhy** [comment]
The Chinese version of minecraft module can not be uploaded by ordinary people. It needs to meet special requirements, and I meet this requirement, so my friend asked me to ask you for the reprint right of this mod and let me upload this mod.

**Comment by WinDanesz** [comment]
Sorry for the late reply. I simply don't have the authority to allow you to do this. Only the mod owner (Electroblob) can decide if he allows you. He is inactive nowadays, so it will take a long time till you can get a response from him, sorry.
I'd suggest to keep this ticket open.
