### ISSUE TITLE
issues with armour from thaumic wonders and aether continuations

### ISSUE THREAD

**Issue by DoctorMage** [Electroblob77/Wizardry#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

equipping this void fotress armour from thaumic wonders or valkyrie armour /agillity boots from aether will cause the game to constatly up ram usage

https://streamable.com/47actc
https://streamable.com/vcoinc

With vm java visual vm
https://streamable.com/q8n5d2

aether one is much less obvious but is possible just takes it's time

### Expected behaviour

Game runs fine ram stays at normal amounts and within set by java/launcher

### Steps to reproduce

1. Install thaumic wonders or aether
2. go into game and equip armour void fortress armour  from thaumic wonders  or agillity boots from aether (currently tested
3. game will keep up how much ram is being used until out of memory crash

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

ElectroblobsWizardry-4.3.7-MC1.12.2

### Minecraft version

1.12.2

### Forge version

1.12.2 - 14.23.5.2859

### Other mods

thaumicwonders-1.8.2
Thaumcraft-1.12.2-6.1.BETA26
Aether Continuation v1.3.0
aether-1.12.2-v1.5.3.2

**Comment by DoctorMage** [comment]
Apologies thaumic wonders is unrelated https://github.com/daedalus4096/ThaumicWonders/issues/53

**Comment by Invadermonky** [comment]
This issue also exists with Aetherium Ashen Armor - [https://www.curseforge.com/minecraft/mc-mods/aetherium-ashen-armor](url)

Changing B:spellcastingAnimations to false stops the freezing from occurring.

**Comment by DoctorMage** [comment]
agility boots is also it's own issue apolgies
