### ISSUE TITLE
[Bug] Some scrolls are still on cooldown in Creative mode

### ISSUE THREAD

**Issue by SfortzaPhantom** [Electroblob77/Wizardry#813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

In fact, even though in EBWizardry 4.3.5 a fix for spells cooldown in Creative mode was presented, there are still some packs where spells are triggering cooldown on spells.

For example: Chargeable Strike (from Extra Spells), Winds of Winter (from Mo'Spells) are acting like there is no 4.3.5 fix and they send another scrolls on cooldown.

### Expected behaviour

All the scrolls should not have cooldown, those as well.

### Steps to reproduce

1. Install Extra Spells, Mowzie's Mobs and Mo'Spells
2. Join the server
3. Cast Chargeable Strike or Winds of Winter
4. Enjoy your cool-down!

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

4.3.7

### Minecraft version

1.12.2

### Forge version

1.12.2 - 14.23.5.2860

### Other mods

[ExtraSpells-1.12.2-1.2.0.jar](https://www.curseforge.com/minecraft/mc-mods/extra-spells-electroblobs-wizardry/files/3091628)
[MoSpells-1.12.2-1.0.3.jar](https://www.curseforge.com/minecraft/mc-mods/mo-spells/files/3736077)
[Mowzie's Mobs-1.5.8.jar](https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs/files/3048685)

**Comment by WinDanesz** [comment]
This must be some custom logic by those spell packs, Wizardryby itself only puts its ItemScroll on cooldown outside of creative mode
