### ISSUE TITLE
Wand disappears in offhand after death. 

### ISSUE THREAD

**Issue by expertincringe** [Electroblob77/Wizardry#817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

So basically when I used a scroll all my stuff went on the ground picked it up but one thing was missing my wand and this isnt the first time which was when I died.

### Expected behaviour

Obviously I wanted all my stuff back especially my wand since there was multiple spells bond to it.

### Steps to reproduce

1.Create a new game

2.Put a wand in your offhand

3.Force drop all of your stuff

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.0.0

### Minecraft version

1.12.2

### Forge version

1.12.2 14.23.5.2860

### Other mods

Roguelike Adventures and Dungeons

**Comment by WinDanesz** [comment]
There is no 1.0.0 version of this mod. My suspect is that RAD is doing something, consult with the pack makers, unless you can replicate this with just wizardry.
