### ISSUE TITLE
the nbt of the entities that are summoned

### ISSUE THREAD

**Issue by 8426753951** [Electroblob77/Wizardry#822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

I found that the zombies(ebwizardry:zombie_minion of course) which are summoned by the spells have the nbt casterUUIDLeast and  casterUUIDMost ,I think the two decide who the entities are summoned will help to fight and hope to summon them by commands,but I don't know how the UUID is made.
I am sorry for my English , I think the question shouldn't be a bug but I can't find other links to ask, it's hard to log in(discord).

### Expected behaviour

summon entities by commands like spells

### Steps to reproduce

/summon ebwizardry:zombie_minion {......casterUUIDLeast: ,HurtTime:0s,casterUUIDMost: }

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

4.3.7

### Minecraft version

1.12.2

### Forge version

1.12.2 - 14.23.5.2859

### Other mods

CraftTweaker2 4.1.20.648
ContentTweaker 4.10.0

**Comment by 8426753951** [comment]
I may make some other mistakes because I havn't use github before.

**Comment by WinDanesz** [comment]
This converter might help https://skylinerw.com/uuid/index.php?convert=dechex&uuidleast=1&uuidmost=1
