### ISSUE TITLE
[Bug] 1.7.10 Server crash

### ISSUE THREAD

**Issue by felipeleite5w** [Electroblob77/Wizardry#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Minecraft version: 1.7.10
Wizardry version: Electroblob's+Wizardry+-+1.1.5+-+MC+1.7.10.jar
Environment: Multiplayer

Issue details: server crash suddenly

Link to crash report (if applicable): https://gist.github.com/felipeleite5w/aae62b2d518249de7a7210675d4ac7c8

### Expected behaviour

not crash

### Steps to reproduce

Join the server and crash

### Crashlog

a

### Environment (Singleplayer/Server, etc.)

LAN game/Server

### Mod version

latest for 1.7.10

### Minecraft version

1.7.10

### Forge version

1.7.10 latest

**Comment by WinDanesz** [comment]
1.7.10 isn't supported anymore. Try tweaking Forge's settings, there is one to remove erroring entities from the world.
