### ISSUE TITLE
[Bug] Disconnect you lose all learned/discovered spells

### ISSUE THREAD

**Issue by eldediamante** [Electroblob77/Wizardry#828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

When discovering ALL the spells and disconnecting from the server, when I log back in it tells me that I don't have any

### Expected behaviour

When leaving the server save my spells so I don't have to learn them all again

### Steps to reproduce

1. Join server (Magma)
2. Use the /discoverspell command
3. leave the server
4. Join server (Magma)
5. try to cast a spell
6. Discover the spell again

### Environment (Singleplayer/Server, etc.)

LAN game/Server

### Mod version

4.3.8

### Minecraft version

1.12.2

### Forge version

1.12.2 14.23.5.2860

### Other mods

SecurityCraft
DeconTable
Baubles
Bettercaves
BetterDiving
BetterMineshaftForge
blockcraftery
bookshelf
bookworm
Buildcraft-all
carryon
cfm
chamaleon
Chisel
chiselandbits
comforts
CosmeticArmorReworked
Costumes
CreativeCore
CustomNPCs
Decocraft
ElectroblobsWizardy
ElevatorMod
emoticons
Erebus
extrautils2
fencejumper
heroicarmory
hwyla
jei
journeymap
library
Locks
luckyblocks
malisiscore
malisisdoors
mclib
ModularVoiceChat
moon-core
MoreSwordsLegacy
mowziesmobs
mysticallib
NetherPortalFix
NomadicTents
obfuscate
OnlinePicFrame
OpenBlocks
OpenModsLib
ordinarycoins
Pirates
PlayerRevive
Portable-Lighting-Mod
prefab
PTRLib
railcraft
RandomThings
reap
roost
rustic
ScalingHealth
SilentLib
Sit
soggytransportation
StorageDrawers
structurize
StupidThings
tombstone
torchmaster
Trapcraft
TreeChopper
u-team-core
useful-backpacks
VariedCommodities
vehicle
WaterStrainer
Waystones

**Comment by eldediamante** [comment]
In case you also need to use these plugins:
EssentialsX
EssentialsXChat
EssentialsXProtect
EssentialsXSpwan
Invsee
Jail
LuckPerms
LuckTab
Multiverse-Core
Multiverse-Portals
NickHider
PlayerTimeLimit
ProtocolLib
SkinRestorer
Sleep-most
StaffChat
SuperVanish
TrollBoss
Worldedit
Worldguard

**Comment by WinDanesz** [comment]
Is the server in "offline" mode?

**Comment by eldediamante** [comment]
I have tried both ways, both offline and online, and it gives me the same problem, but yes, the server is offline

**Comment by WinDanesz** [comment]
Cracked servers (=offline mode on) are not supported. Your issue is typically occuring in cracked servers only.

**Comment by eldediamante** [comment]
But I did the test by putting the server "online" and it didn't work either, I always have to leave it "online" for it to work, right?

**Comment by WinDanesz** [comment]
Yes, it must be always online, and you need a non cracked MC account to connect.

**Comment by eldediamante** [comment]
Ok I'll try it again then, thanks
