### ISSUE TITLE
A tiny tweak

### ISSUE THREAD

**Issue by EmperorPlebb** [Electroblob77/Wizardry#83]
Minecraft version: 1.12.2
Wizardry version: 4.1.2
Environment: Singleplayer

Issue details: I was messing around with the awesomely modeled mage hats, until I noticed that they seem to clip with the upper hat texture of a player's skin.

Other mods involved: No other mods to change a player's appearance were present.

Link to crash report: No crash reported, a simple cosmetic issue. Here are some screenshots below.
No mage hat, skin hat body part enabled.
![2018-11-03_13 51 09](https://user-images.githubusercontent.com/44732806/47956254-9fca4f80-df6f-11e8-92fb-20beec6e5bde.png)
No mage hat, skin hat body part disabled.
![2018-11-03_13 51 14](https://user-images.githubusercontent.com/44732806/47956255-9fca4f80-df6f-11e8-9b35-e7355e06061d.png)
Mage hat, skin hat body part enabled.
![2018-11-03_13 51 23](https://user-images.githubusercontent.com/44732806/47956256-9fca4f80-df6f-11e8-8cbb-bac8c9cbb2cb.png)
Mage hat, skin hat body part disabled.
![2018-11-03_13 51 31](https://user-images.githubusercontent.com/44732806/47956257-9fca4f80-df6f-11e8-90f1-7f9f0de981ce.png)
Hope you can see what I mean so you can fix it whenever you get the chance!

**Comment by Electroblob77** [comment]
Someone mentioned this on curseforge ([here](https://minecraft.curseforge.com/projects/electroblobs-wizardry?comment=510)) as well, as I said there it's something I've just never got round to fixing, but now it's logged here it won't get forgotten. Thanks!

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
