### ISSUE TITLE
[Bug] Can't discover spells when using them 

### ISSUE THREAD

**Issue by Pen1ds** [Electroblob77/Wizardry#830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Whenever I try to use certain undiscovered spells that i have equipped on my wand, I can use the spell but it just gives me a chat message and will create a bomb or teleport me randomly. I have left the server I was in, tried restarting Minecraft, and spammed the spell. I didn't find any other errors except this.

### Expected behaviour

I expected the spell to discover like normal, after casting it multiple times it still doesn't discover it.

### Steps to reproduce

1. Equip the spell on wand (I have a apprentice wand and am using what appears to be a Apprentice Fire spell due to it spawning either blazes, setting me on fire, launching a fireball, or spawning a firebomb)
2. Go out and begin holding the spell button to use it
3. wait a few seconds and get chat message like "A firebomb spawns above you" or "The wand catches fire in your hand"
4. Repeat with the only different result being a different event

### Environment (Singleplayer/Server, etc.)

LAN game/Server

### Mod version

4.3.8

### Minecraft version

1.12.2 

### Forge version

1.12.2-14.23.5.2860

### Other mods

1. Ancient Warfare 2 
2. Baubles
3. Callable Horses
4. ChickenLib
5. Electroblob's Wizardry
6. Ice and Fire:Dragons
7. Just Enough Items (JEI)
8. LLibrary
9. Matchlock Guns
10. Spartan and Fire
11. Spartan Shields
12. Spartan Weaponry
13. Waystones
14. Wooltostring
(This is my first bug report im sorry if this is an error on my part)

**Comment by WinDanesz** [comment]
You were probably missing the conditions to cast those spells, e.g. Pocket Furnace needs a smeltable item
