### ISSUE TITLE
The Infamous Wizard Book crash returns

### ISSUE THREAD

**Issue by 88880** [Electroblob77/Wizardry#84]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.1.2 [change as necessary]  
Environment: Singleplayer [delete as necessary]

Issue details: Unfortunately, the game crashes upon the wizard book being used after I change the key to "Next Spell", similarly to #45. The mod version is latest, but it still happens. Is there anything we can do? Thank you, electroblob

Other mods involved: Roguelike Adventure modpack

Link to crash report (if applicable): https://pastebin.com/VN8CVzP2

**Comment by Electroblob77** [comment]
What did you change the next spell key to? The crash report doesn't look the same as in #45, but I could be wrong.

**Comment by 88880** [comment]
I changed it to "\". I tried a couple more like "insert" and etc. but I think it didn't work

**Comment by Silivek** [comment]
I was using a novice wand and made my next key the comma key and it made my game crash

**Comment by Electroblob77** [comment]
This may be fixed by the handbook rewrite in Wizardry 4.2. If not, please reopen this issue.
