### ISSUE TITLE
Add a config option to allow spell cooldowns to continue when you are not holding it

### ISSUE THREAD

**Issue by LynxGrimbane** [Electroblob77/Wizardry#846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

I was told on the discord to create a reminder when asking about this. 

### Expected behaviour

A config option to allow this would be great!

### Steps to reproduce

-

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

4.3.9

### Minecraft version

1.12.2

### Forge version

1.12.2 - 14.23.5.2860

**Comment by WinDanesz** [comment]
fixed by 73811c3a6b39170b1ee4013c53072d7a846d0952
