### ISSUE TITLE
[Bug] I'm crashing everytime I go in my solo world help 

### ISSUE THREAD

**Issue by Cripplingdepressi0n** [Electroblob77/Wizardry#847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

I just equipped a battle dagger or mage dagger whatever it's called and then I crashed.

### Expected behaviour

?

### Steps to reproduce

1. in server
2. had full battlemage armour
3. equipped my mage dagger or whatever
4. crash
5. cant get back in

### Crashlog

https://gist.github.com/Cripplingdepressi0n/877df3b7bb6e8052fd4e297dfc254094

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

R.A.D

### Minecraft version

1.12

### Forge version

curseforge?

**Comment by WinDanesz** [comment]
Outdated addon (Ancient Spellcraft) issue. Update to the latest version

**Comment by Cripplingdepressi0n** [comment]
Hi sorry mistake my minecraft version is 1.12 which is the same as the mod
