### ISSUE TITLE
Curse of Soulbinding not working properly

### ISSUE THREAD

**Issue by dragongod100** [Electroblob77/Wizardry#85]
Minecraft version: 1.7.10
Wizardry version: 1.1.5  
Environment: Server 

Issue details: Upon casting the spell: curse of soulbinding, it seemed to work properly at first. The target to damage equivalent to myself. Once the player died and respawned, he continued to die from damage I took. after I used /kill none of the targets appear to take the damage nor do they die. 

Other mods involved: AnimationAPI by thehippomaster21
1.7.10-2.9m
 AppleMilkTea by RazzleberryFox
1.7.10-0.48.3
 Armourer's Workshop by RiskyKen
1.7.10-1.0.0
 Astikoor by MennoMax
1.7.10-0.28.2
 Automagy by Tuhljin
1.7.10-2.0.1
 Backpacks by Eydamos
1.7.10-1.0.8.3
 Battlegear 2 - Bullseye by nerd_boy
1.7.10-1.2.2final
 Baublelicious by DenBukki
1.7.10-1.0.1.10p
 Baubles by Azanor
1.7.10-0.8.1
 Better Builders Wands by Portablejim
1.7.10-2.0.17
 Better Foliage by Octarine Noise
1.7.10-1.11.5
 BiblioCraft by Nuchaz
1.7.10-1.5
 BiblioWoods Natura by Nuchaz
1.7.10-6.16
 bspkrsCore by bspkrs
3.3.6-1.7.10
 Carpenter's Blocks by Mineshopper
1.7.10-1.3.4.19
 Chicken Chunks by Chicken Bones
2.9.5.11
 Chisel by Automatic_Maiden
1.7.10-1.0.7.47_138
 CodeChickenCore by Chicken Bones
1.7.10-3.1.4-329
 CoFHCore by Team CoFH
1.7.10-1.4.0-11
 CookieCore by Ephys
1.7.10-1.1.3
 Craft Heraldry by Vazkii
1.7.10-3.2.3
 Damage Indicators by rich1051414
1.7.10-1.0
 Description Tags by BluSunrize
1.7.10-59.0.3
 Dimensional Anchors by Immibis
1.7.10-1.1.5
 Electroblob's Wizardry by electroblob
1.7.10-0.2.0.36_beta
 Ender Core by CrazyPants
1.7.10-1.4.7.38
 Ender Storage by Chicken Bones
1.7.10-1.4.6
 ExtraTic by JeanGlassmaker
1.7.10-1.4.0
 FairyLights by pau101
1.7.10-1.2.0.345
 Forge Multipart by Chicken Bones
1.7.10-1.4.6.1355
 ForgeEssentials Client by lucas1998
1.7.10-1.7.0
 Garden Stuff by jaquardo
1.7.10-1.0.1-20
 GuideAPI by TehNut
1.7.10-1.1.3-21
 Hardcore Wither by thor12022
1.7.10-59.1.4
 Immibis Core by Immibis
1.7.10-59.0.0
 Immibis' Autofood by Immibis
1.7.10-1.5.9.156
 Inventory Tweaks by Kobata
1.7.10-6.0.62.742
 Iron Chests by cpw
1.7.10-0.0.8
 It's The Little Things by Zlepper
1.7.10-1.2.0.8
 Item Blacklist by DoubleDoorDevelopment
1.7.10-1.2.1
 IVToolkit by Ivorius
1.7.10-1.2.2
 Jabba by ProfMobius
1.7.10-5.1.4p2
 JourneyMap by techbrew
1.7.10-04
 LiteLoader by Mumfrey
1.7.10-34.3
 Lord of The Rings by Tangient LLC
2.24.2
 LoTRCircles Configs by PlowmanPlow
1.7.10-0.3.2b
 Mantle by mDiyo
1.7.10-3.0.10b
 Mine Tweaker by Stan Hebben
1.7.10_10.13.4.1614
 Minecraft Forge by The Forge Team
1.7.10-0.2.7
 MinePainter by Zombie Killer
1.7.10-0.9.6
 ModTweaker by jaredlll08
1.7.10-2.2.0.1-126
 Natura by mDiyo
1.7.10-1.12.14.40
 NEI Addons by bdew
1.7.10-1.1.2
 NEI Integration by Tonius
1.7.10-1.0.0
 NEI Lotr by The Ranger Malvegil
1.7.10-1.7a
 NEI Thaumcraft Plugin by DjGiannuzz
1.7.10-1.0.5.120
 Not Enough Items by Chicken Bones
1.7.10-3.0.0.18
 ObsidiPlates by Myrathi
1.7.10-1.6
 Open Blocks by LUA Maniac
1.7.10-0.10
 OpenModsLib by LUA Maniac
1.7.10_HD_U_D6
 Optifine by sp614x
1.7.10-0.1.2
 Platforms by ShetiPhian
1.7.10-1.10.1
 ProjectE by skinkillerj
1.7.10-3.5.0
 ReAuth by TechnicianLP
1.7.10-1.6.2
 Redstone Paste by FyberOptic
1.7.10-1.1.28
 Refined Relocation by Dynious
1.7.10-1.0c
 RikMuldsCore by rikmuld
1.7.10-1.1.1
 SafeZone by Melonslise
1.7.10-3.0.0
 ShetiPhianCore by ShetiPhian
1.7.10-1.07.2
 Signpost by Gollorum
1.7.10-1.27
 Status Effect HUD by bspkrs
1.7.10-1.10.9
 Storage Drawers by jaquandro
1.7.10-4.2.3.5
 Thaumcraft by Azanor
1.7.10-2.1g
 The Camping Mod by rikmuld
1.7.10-1.2.6-118
 Thermal Foundation by TeamCoFH
1.7.10-0.2.15.tweak
 Tinker's Mechworks by Glassmaker
1.7.10-1.1.2-20
 Tinker's Steelworks by Ephys
1.7.10-1.8.8b991
 Tinkers' Construct by Boni
1.7.10-1.7.10.2
 Trade Booth by aeroc
1.7.10-1.1.2.16
 Translocator by Chicken Bones
1.7.10-2.0.4
 TreeCapitator by bspkrs
1.7.10-59.0.4
 TubeStuff by Immibis
1.7.10-0.2
 Tumbleweed by konwboj
1.5.10-1.7.10
 Waila by ProfMobius
1.7.x-1.1.6
 Waila Harvestability by Squeek502
1.7.10-0.2.0-25
 Waila Plugins by tterrag1098

**Comment by Electroblob77** [comment]
Ok, sounds weird. This is in 1.7.10 so there may well be bugs lying around, I haven't touched that version in quite a while. I might look into it at some point, thanks for reporting.

**Comment by Electroblob77** [comment]
Closing this because 1.7.10 is no longer supported.

**Comment by MrVityaTrash** [comment]
Any Known fixes?
