### ISSUE TITLE
[Bug] Crash when launching the game. 1.12.2.

### ISSUE THREAD

**Issue by Froud17** [Electroblob77/Wizardry#852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

The game crashes when i open it with this mod. 

### Expected behaviour

The game should open just fine like it did last time.

### Steps to reproduce

1. Launch the game.
2. Crash.

### Crashlog

https://gist.github.com/Froud17/42809d36a58583cd5a87e2f0c5b9e41d

### Environment (Singleplayer/Server, etc.)

Not sure

### Mod version

4.3.9

### Minecraft version

1.12.2

### Forge version

1.12.2 - 14.23.5.2860

**Comment by Teal-Wolf-25** [comment]
Can you attach the file located at C:\Users\Froud\AppData\Roaming\.minecraft\crash-reports\crash-2023-05-23_15.33.05-client.txt instead of what you attached?

**Comment by Froud17** [comment]
Yeah! Here it is https://gist.github.com/Froud17/824fc0f6a1a11f69a8fc02f436237a4b

**Comment by Teal-Wolf-25** [comment]
I see it is caused by it not being to load the guide book but I'll have to do some testing to figure out more

**Comment by Froud17** [comment]
I'll wait patiently for an answer, thank you!

**Comment by Teal-Wolf-25** [comment]
I can't figure it out personally but you can wait for others here or go to the official Discord server for support. https://discord.gg/gMxCs65tQA

**Comment by WinDanesz** [comment]
Join the discord and use the pinned .cfg there that disables loading of the manual book

**Comment by Froud17** [comment]
Just tried with the .cfg and now the game opens but crashes again in the loading screen.

**Comment by Froud17** [comment]
I'm sorry, i've made a mistake. It works just fine now. Thank you very much!
