### ISSUE TITLE
[Bug] Amulet of Anchoring / Telekinesis change is broken

### ISSUE THREAD

**Issue by brisingraerowing** [Electroblob77/Wizardry#866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

From Nils on discord, players can only be disarmed when they have the amulet.

[Offending Line](https://github.com/Electroblob77/Wizardry/blob/1.12.2/src/main/java/electroblob/wizardry/spell/Telekinesis.java#L40)

There needs to be a `!` on the check.

### Expected behaviour

Disarms work without the amulet.

### Steps to reproduce

1. Use latest EBW with at least 2 players
2. Try to disarm a player with and without the amulet
3. Observe inverted effects

### Environment (Singleplayer/Server, etc.)

LAN game/Server

### Mod version

4.3.13

### Minecraft version

1.12.2

### Forge version

Unknown

**Comment by WinDanesz** [comment]
Fixed by f9cf1b3
