### ISSUE TITLE
SMP Server crash when casting "Summon Skeleton Legion" [Version: 4.1.2 - MC 1.12.2]

### ISSUE THREAD

**Issue by fandomaniac** [Electroblob77/Wizardry#89]
Getting a server crash when casting "Summon Skeleton Legion" on a SMP server. Crash log link below.

Mod Version: Electroblob's Wizardry - 4.1.2 - MC 1.12.2
Forge Version: Forge-1.12.2 - 14.23.5.2769

Pastebin link: https://pastebin.com/uGVwXFyL

**Comment by Electroblob77** [comment]
Okay, looks like wizardry and dungeon tactics are triggering each other's events in an infinite loop, leading to a StackOverflowError. Unfortunately DT isn't (as far as I can tell) open source, so I can't see the exact code involved, but I can see from the crash report that DT is attacking an entity from its own LivingHurtEvent. Without some kind of check against looping, this is a recipe for StackOverflowErrors. In fact, I had a similar issue before involving curse of soulbinding and other retaliatory effects. Do you happen to know what the skeleton legion was attacking at the time?

I expect the most likely explanation is that both wizardry and dungeon tactics have their own protection against looping, but those two systems don't interact with each other so they can still cause problems when put together. I may be able to implement some kind of detection of excessive calls to this particular part of wizardry's code and avoid the loop that way.

**Comment by Electroblob77** [comment]
Just noticed this appears to be similar to #72, which is handy because loot slash conquer has a github repo to look through for possible causes.

**Comment by fandomaniac** [comment]
The crash is still happening with the latest version (4.1.4 - MC 1.12.2). This time with the Silverfish Swarm spell.

Crash Report:
https://pastebin.com/cGK3hmYc

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release with the addition of `DamageSafetyChecker`.
