### ISSUE TITLE
Increase configuration options for modpack customisation and other customisation options.

### ISSUE THREAD

**Issue by Needmoremods** [Electroblob77/Wizardry#92]
Minecraft version: 1.10.2 [change as necessary]  
Wizardry version: Electroblob's+Wizardry+-+2.1.2+-+MC+1.10.2 [change as necessary]  
Environment: Singleplayer

Issue details: Just a few possible suggestions. 

**Config:**

- Ice age and freezing spells are instant kill for most mobs, quite difficult to balance these spells when you have boss battles where you can instantly kill them. Possibly freeze whilst DoT until broken out manually or after a certain amount of time option?

- Is it in any way possible to increase damage modifiers above 20? The same for heal modifiers/addition of heal modifiers (potency did not seem to increase my healing amount).

- Configurable mana levels in different wands, or maybe through storage upgrade value multipliers or something.

- Ability to configure damage of spectral/fire etc weapons, durability and decay in the config? As well as spells that increase your armor or resistance?

- Configurable armor, durability and mana values for wizard armor?

**Other**
- Increase radius of certain spells such as sigils, forcefields, blizzard with an increased mana cost or somehow upgradeable? 

- Possibly upgradeable wizard armor similar to wands for each type.

- Now for something I don't think would ever happen, but one can wish. Compatibility with Ars Magica 2 spells?

**Comment by Electroblob77** [comment]
Thanks for the suggestions!

Far from instantly killing mobs, ice age and ice statue do not deal any damage whatsoever, they simply freeze the target for a certain period of time. I am aware that this sometimes disrupts boss mechanics so in future boss mobs will probably be immune to these spells.

Yes, you can change the castCommandMultiplierLimit in the config file. More on that [here](https://github.com/Electroblob77/Wizardry/wiki/Commands#cast).

Customisation and configurability in general is something I'm working on. In particular, a lot of people have requested being able to adjust individual spell attributes, so these will be defined in JSON files allowing them to be changed with a resource pack.

Blast upgrades increase the radius of quite a few spells, including blizzard. I'm extending this to more spells for the next update.

I'm reluctant to add four tiers of armour simply because it would generate a lot of items, but I do want to expand what can be done with wizard armour.

It would be quite nice and potentially feasible to allow AM2 spells to be cast with wizardry wands, but AM2 isn't in 1.12 yet and it would be a low priority in any case.

**Comment by Needmoremods** [comment]
Appreciate the feedback. 

> Far from instantly killing mobs, ice age and ice statue do not deal any damage whatsoever, they simply freeze the target for a certain period of time

Ah I should be more specific. It seems that vanilla mobs and most modded mobs such as those from Lycanite mobs do not die and work as intended. I've tested and isolated it to mobs created with the  custom NPC mod where they are instantly killed. As it is isolated to this mod unlikely to be on your end I think. I have notified Noppes to see if it can be fixed.

>Yes, you can change the castCommandMultiplierLimit in the config file. More on that here.

Right, but is that only for commands or also for wand casted spells? I can't seem to put the modifier for that above 20. 255 makes sense for the castCommandMultiplierLimit though. What modifier affects summoned creatures damage? Also a suggestion that maybe health could be modifiable with damage for them. 

>I'm reluctant to add four tiers of armour simply because it would generate a lot of items, but I do want to expand what can be done with wizard armour.

Understood, clutter indeed. 

> It would be quite nice and potentially feasible to allow AM2 spells to be cast with wizardry wands, but AM2 isn't in 1.12 yet and it would be a low priority in any case.

Only but a wish away, unfortunately AM2 development seems stagnated among the various bugs it still has, maybe one day :').

**Comment by Electroblob77** [comment]
Right, fair enough about custom NPCs. Feel free to post an issue here anyway, it's good to keep track of things.

The modifier limit is only for commands, yes. The wand ones are fixed anyway though, not sure how you could be changing that at all. Summoned creatures are currently not affected by damage modifiers. However, this will be changing! I need to decide whether to make them deal more damage, have more health, or a bit of both, but one of those will happen.

**Comment by Needmoremods** [comment]
> The modifier limit is only for commands, yes. The wand ones are fixed anyway though, not sure how you could be changing that at all.

I have been changing the player attribute via the following config option:

```
Global damage scaling factor for the damage dealt by players casting spells, relative to 1.
    D:playerDamageScaling=20.0
```

Where I am unable to increase the scaling above 20. 

I am hitting something like 500 damage (250 hearts I think) with lightning disc each cast when maxed out in potency etc. Thus I assumed that such damage would be attributed to the modded attribute, however if I remember correctly, it did increase the damage I have dealt.

> I need to decide whether to make them deal more damage, have more health, or a bit of both, but one of those will happen

I guess maximal customisation would be something like, change a multiplier for health or damage to scale accordingly to however one would want.

Though I have to say, one of the best magic mods I've ever played on Minecraft. Clean and smooth. Well done to you.

**Comment by Electroblob77** [comment]
Oh, you're scaling it with that config option, I see. That's a limit set in the code, you have to set a min and a max so 20 must be what I chose at the time. That config option was intended as a quick way to adjust balance for different sizes of modpack, pvp or whatever, so I figured 20 was more than enough. I can easily change it if people want.

And thanks!

**Comment by Electroblob77** [comment]
The limit has been increased to `Integer.MAX_VALUE` (2^31-1) in the 4.2.0 release.
