### ISSUE TITLE
Arcane Workbench GUI does not dim the background

### ISSUE THREAD

**Issue by Vazkii** [Electroblob77/Wizardry#96]
Minecraft version: 1.12.2
Wizardry version: 4.1.2

The Arcane Workbench, Handbook, and potentially other GUIs in the mod do not dim the background. You can see the difference by opening the Workbench followed by any other vanilla GUI.

**Comment by Electroblob77** [comment]
Thanks for this, I noticed it in my dev branch recently and fixed it in there so it'll be rolled out in the next update.
