### ISSUE TITLE
Weird Bug? or i did something wrong?

### ISSUE THREAD

**Issue by Toff33** [Electroblob77/Wizardry#97]
I tried to figure out how to add the magic missile spell to my wand and i clicked my mouse button 5 which i rebound for next spell and it kicked me out of the game and wouldn't let me rejoin after multiple times of retying and it gave me this link --> https://paste.dimdev.org/loyutalete.mccrash

**Comment by Electroblob77** [comment]
Duplicate of #90, see that issue for the answer.
