### ISSUE TITLE
Incompatible books with SmoothFont

### ISSUE THREAD

**Issue by tyler489** [Electroblob77/Wizardry#99]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.1.2
Environment: Singleplayer/LAN game/Server 

Issue details: 
when looking at a magic book (in this case magic missel) with the mod Smooth Font (https://minecraft.curseforge.com/projects/smooth-font) the game crashes with this crash report 
https://pastebin.com/ickhXKGr
Other mods involved: Smooth Font

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]
https://pastebin.com/ickhXKGr

https://minecraft.curseforge.com/projects/smooth-font/issues/7

**Comment by Electroblob77** [comment]
bre2el seems to have identified the source of the problem. The only unusual thing wizardry does with font is use what I call a mixed font renderer, which allows normal text and SGA characters to be rendered inline with each other. Based on what was said in the other issue thread, I'm guessing that Smooth Font has loaded before wizardry, so the mixed font renderer wasn't initialised in time. bre2el has posted a jar with a possible fix on the Smooth Font issue thread, try that out and see if it works.

**Comment by Electroblob77** [comment]
Based on comments on the SmoothFont issue tracker (https://minecraft.curseforge.com/projects/smooth-font/issues/7) I'm assuming this is fixed. Please reopen if the issue persists.
